### ISSUE TITLE
Python package: Loosen version requirements for maturin

### ISSUE THREAD

**Issue by gyscos** [delta-io/delta-rs#1004]
# Description

The current python package requires an exact maturin version (currently 0.14.2): 

https://github.com/delta-io/delta-rs/blob/c1f5a7e9497fceeea4d5b20c9eaf6ebe109f1b65/python/pyproject.toml#L1-L2

Would you consider loosening it, for example to what is suggested in maturin's Readme?
```toml
[build-system]
requires = ["maturin>=0.14,<0.15"]
```

**Use Case**

This would let us build the python package with the latest maturin version (currently 0.14.5) rather than requiring an older version.
In my case it is to package the deltalake python package for archlinux.

The current workaround is to build the package in a virtualenv, but it's generally discouraged when a "direct" build is possible.

Thanks!

**Comment by wjones127** [comment]
That restriction seems good to me, especially if maturin suggests it. 👍 

Would you be wiling to submit a PR?
