### ISSUE TITLE
Time travel within retention period not possible after `vacuum()` operation

### ISSUE THREAD

**Issue by bossenti** [delta-io/delta-rs#1013]
# Environment

**Delta-rs version**: `0.6.4`

**Binding**:  Python

**Environment**:
- **Cloud provider**: AWS (EMR)
- **OS**: Ubuntu

***
# Bug

**What happened**:
I applied a vacuum operation with a retention period of 720 hours to an existing delta table.
At first glance, the operation was successful. Using `history()`, I still get the transaction log for the last 30 days.
However, when I try time travel to a previous version than the existing but within the retention period with `delta_table.load_version(previous_version)` the following error appears:
```
PyDeltaTableError: Failed to apply transaction log: End of transaction log
```

**What you expected to happen**:
I expect to be able to access versions of the delta table within the retention period after a vacuum operation.

**How to reproduce it**:
see descriptions

**More details**:
I have also checked the delta log manually and with the `delta.io` library.
Both show the very same versions returned by `history()`.
When I try to retrieve an older version directly from Spark via `spark.read.format("delta").option("versionAsOf", 149).load("<path-to-table>")`, I get the following error (concordantly to error above):
```
AnalysisException: Cannot time travel Delta table to version 149. Available versions: [150, 150].
```

Available versions via `DeltaTable.forPath(spark, path).history()`:

|version|timestamp          |
|--------|----------------
|150    |2022-12-11 01:33:15|
|149    |2022-12-11 01:32:08|
|148    |2022-12-01 01:37:18|
|147    |2022-12-01 01:36:36|
|146    |2022-11-24 01:31:44|
|145    |2022-11-17 01:33:16|
|144    |2022-11-15 01:35:31|
|143    |2022-11-14 01:37:33|
|142    |2022-11-13 01:30:53|
|141    |2022-11-12 01:40:11|

**Comment by houqp** [comment]
interesting, @bossenti is it possible for you to share the vacuumed table here as an attachment?

**Comment by bossenti** [comment]
@houqp I need to clarify this
Probably not since it is internal company data, but I'll have a look what I can provide you with

**Comment by bossenti** [comment]
Would a full transaction log already be helpful for you?

**Comment by houqp** [comment]
yeah, just the log itself should be enough. If you can also reproduce this with dummy data, that would be great too.

**Comment by bossenti** [comment]
Alright, I'll provide the log beginning next week probably.
I can also try to build a reproduction with dummy data but this will probably take some time

**Comment by houqp** [comment]
interesting, the log directory you provided doesn't contain a checkpoint file, which makes it invalid. Was it intentionally ignored? or was it incorrectly deleted by the vacuum command?

**Comment by bossenti** [comment]
Ah my bad, I just missed to include it in the `zip` file.
Here it is
[00000000000000000150.checkpoint.parquet.zip](https://github.com/delta-io/delta-rs/files/10342820/00000000000000000150.checkpoint.parquet.zip)

**Comment by houqp** [comment]
@bossenti did you post-process/reformatted these JSON log files? Each action in the json file should all be stored in a single line, but the files you uploaded have actions prettified into multiple lines like below:


```
18:47:24 ❯ cat _delta_log/00000000000000000145.json
{
  "remove": {
    "path": "year=2022/month=11/day=10/part-00000-c3e43875-297d-461e-88aa-665d9729a155.c000.snappy.parquet",
    "deletionTimestamp": 1668648795549,
    "dataChange": true,
    "extendedFileMetadata": true,
    "partitionValues": {
      "year": "2022",
      "month": "11",
      "day": "10"
    },
    "size": 254889
  }
}
```

**Comment by houqp** [comment]
As for the specific error you were getting, it is because your log folder only contains the checkpoint for version 150. If you travel back to any versions prior to that, it will throw an error because earlier checkpoints are already deleted.

This is assuming you uploaded all the checkpoint files in your comment at https://github.com/delta-io/delta-rs/issues/1013#issuecomment-1370676543. Could you confirm that @bossenti ?

**Comment by houqp** [comment]
The vaccum command is not supposed to change any file inside the _delta_log folder, so I am surprised it is causing data corruption for you. However, table checkpoint operations will delete older log files and checkpoints. @bossenti what system did you use to write to the delta table?

**Comment by bossenti** [comment]
> As for the specific error you were getting, it is because your log folder only contains the checkpoint for version 150. If you travel back to any versions prior to that, it will throw an error because earlier checkpoints are already deleted.
> 
> This is assuming you uploaded all the checkpoint files in your comment at [#1013 (comment)](https://github.com/delta-io/delta-rs/issues/1013#issuecomment-1370676543). Could you confirm that @bossenti ?

Yes, I uploaded all the checkpoint files that existed at that time.

**Comment by bossenti** [comment]
> The vaccum command is not supposed to change any file inside the _delta_log folder, so I am surprised it is causing data corruption for you. However, table checkpoint operations will delete older log files and checkpoints. @bossenti what system did you use to write to the delta table?

We run our PySpark jobs on AWS EMR clusters with EMR version `6.8` (this includes Spark in version `3.3.0`).
For vacuuming and compressing our delta tables we use `deltalake` in version `0.70.0`, at the time of reporting the issue this was version `0.64.0`.

Do you need more information?
I'm happy to provide them

**Comment by bossenti** [comment]
> @bossenti did you post-process/reformatted these JSON log files? Each action in the json file should all be stored in a single line, but the files you uploaded have actions prettified into multiple lines like below:
> 
> ```
> 18:47:24 ❯ cat _delta_log/00000000000000000145.json
> {
>   "remove": {
>     "path": "year=2022/month=11/day=10/part-00000-c3e43875-297d-461e-88aa-665d9729a155.c000.snappy.parquet",
>     "deletionTimestamp": 1668648795549,
>     "dataChange": true,
>     "extendedFileMetadata": true,
>     "partitionValues": {
>       "year": "2022",
>       "month": "11",
>       "day": "10"
>     },
>     "size": 254889
>   }
> }
> ```
> 
> This makes the commit logs invalid.

Yes, first I removed the `stats` section from the files.
That probably led to the different formatting.
I'm sorry if that caused any confusion.
I can confirm that in their original version they contain all the information in one line.

**Comment by bossenti** [comment]
> > The vaccum command is not supposed to change any file inside the _delta_log folder, so I am surprised it is causing data corruption for you. However, table checkpoint operations will delete older log files and checkpoints. @bossenti what system did you use to write to the delta table?
> 
> We run our PySpark jobs on AWS EMR clusters with EMR version `6.8` (this includes Spark in version `3.3.0`). For vacuuming and compressing our delta tables we use `deltalake` in version `0.70.0`, at the time of reporting the issue this was version `0.64.0`.
> 
> Do you need more information? I'm happy to provide them

I was just looking through some of our delta logs and noticed that we only have checkpoint files for every tenth log version (e.g. `150`, `160`, etc.) and an additional file called `_last_checkpoint` that was created at the same time as the last checkpoint, but has a different file size. Maybe this information is helpful for you @houqp

**Comment by houqp** [comment]
one checkpoint created every 10 commits is expected behavior.

The reason you are not able to time travel to older versions is because your log dir only contains the checkpoint for version 150. In order to time travel back to version 149, we need the checkpoint for version 140.

Since vacuum operation doesn't touch checkpoints and commits, you are sure it's the vacuum command that's deleting the checkpoint files? It would be helpful if you can provide a delta table log dir before the vacuum run so we can run the vacuum run ourselves to see if we can reproduce the issue from our end.

**Comment by bossenti** [comment]
> Since vacuum operation doesn't touch checkpoints and commits, you are sure it's the vacuum command that's deleting the checkpoint files?

We do not touch the delta log manually and delta tables are only touched by vacuuming and compaction besides writing/adding data to the tables. So it is currently the only explanation we have in mind
But I can activate bucket versioning for the tables affected so that we can confirm this assumption.

**Comment by bossenti** [comment]
> Since vacuum operation doesn't touch checkpoints and commits, you are sure it's the vacuum command that's deleting the checkpoint files? It would be helpful if you can provide a delta table log dir before the vacuum run so we can run the vacuum run ourselves to see if we can reproduce the issue from our end.

Yes, that should be possible, I'll provide you with one.

**Comment by houqp** [comment]
@bossenti did you also use the deltalake python library to create checkpoints? If so, this would explain why checkpoints are deleted incorrectly.

**Comment by bossenti** [comment]
No. We only write to the delta tables with (Py)Spark `3.3.0` and Delta Lake `2.1.0`

**Comment by bossenti** [comment]
@houqp Enabling bucket versioning shows that the problem is not related to the vacuum command.
Therefore, I am closing this issue and we will investigate it further.
Sorry for the trouble and huge thank you for your support so far 🙏🏼
