### ISSUE TITLE
DeltaStorageHandler is not serializable

### ISSUE THREAD

**Issue by chitralverma** [delta-io/delta-rs#1015]
# Environment

**Delta-rs version**: latest

**Binding**: 
Python

**Environment**:
- **Cloud provider**: all
- **OS**: mac ventura, m1
- **Other**:

***
# Bug

**What happened**:
I am trying to add delta connector to [Polars](https://github.com/pola-rs/polars), but which doing a lazy scan polars tries to serialize function and objects, see [here](https://github.com/pola-rs/polars/blob/master/py-polars/polars/internals/anonymous_scan.py#L81). This line breaks with the below exception as `DeltaFileSystemHandler` is not serializable I suppose,
```
TypeError: cannot pickle 'builtins.DeltaFileSystemHandler' object
```

It will be great if this could be serializable, otherwise on Polars side we will have to rely on `fsspec` or `pyarrow.fs`, bypassing the `DeltaStorageHandler` implementation altogether.

**What you expected to happen**:
Exception should not occur.

**How to reproduce it**:
You can use the following minimal code to reproduce this.

```
import deltalake
from deltalake.fs import DeltaStorageHandler
dsh = DeltaStorageHandler("./delta-table")

import pickle
pickle.dumps(dsh)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot pickle 'builtins.DeltaFileSystemHandler' object

```

**More details**:

**Comment by roeap** [comment]
Hi @chitralverma - had a quick look into this it seems this is not natively supported by pyo3 modules. That being said, there are some pointers in an [issue](https://github.com/PyO3/pyo3/issues/100) that I can explore to make this work.

Really looking forward to a polars integration - thanks! 👍

**Comment by chitralverma** [comment]
> Hi @chitralverma - had a quick look into this it seems this is not natively supported by pyo3 modules. That being said, there are some pointers in an[ #pyo3/100](https://github.com/PyO3/pyo3/issues/100#issue-284724409) that I can explore to make this work.
> 
> Really looking forward to a polars integration - thanks! 👍 

Thanks a lot
