### ISSUE TITLE
Cannot create Delta Lake table from DataFusion data frame with timestamp field with timezone

### ISSUE THREAD

**Issue by andrei-ionescu** [delta-io/delta-rs#1019]
# Environment

**0.5.0**:

**Binding**: 
None. Rust.

**Environment**:
- **Cloud provider**: N/A
- **OS**: MacOS Ventura
- **Other**: N/A

***
# Bug

**What happened**:

When trying to create a Delta Lake table based on an Arrow Schema that contains a field of type timestamp with timezone the following error occurs:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SchemaError("Invalid data type for Delta Lake: Timestamp(Microsecond, Some(\"UTC\"))")', src/main.rs:220:86
```

**What you expected to happen**:

Being able to create a Delta Lake table with a timezone timestamp type.

**How to reproduce it**:

1. Create an Arrow Schema `arrow_schema` with a field of timestamp type with UTC timezone.
2. Do the following:

```
let delta_schema = deltalake::Schema::try_from(Arc::new(arrow_schema)).unwrap();
```

**More details**:

The issue seems to be found in the converter from `ArrowDataType` into `SchemaDataType` found here: https://github.com/delta-io/delta-rs/blob/main/rust/src/delta_arrow.rs#L218.

There is no case when the Arrow Data Type is `ArrowDataType::Timestamp(TimeUnit::Microsecond, Some(tz))`.

It seems that the Delta Lake format does NOT support timestamp with timezone — it needs to be transformed to UTC first: 

>Notes
>
>Timestamps with local timezone are internally normalized and persisted in UTC. Whenever the value or a portion of it is extracted the local session timezone is applied.

Quote from https://docs.databricks.com/sql/language-manual/data-types/timestamp-type.html

**Possible fixes**:

1. **Easy fix for UTC timestamp types** — include the timestamp type having the **UTC** timezone into the current pattern and transform it into the `timestamp` primitive. This will fix the exact problem described above, specific to UTC.
4. **Permanent fix** — transform the timezoned timestamp into UTC time but this requires extensive changes into other areas.

**Comment by ion-elgreco** [comment]
@rtyler this issue has already been resolved, can you close it?
