### ISSUE TITLE
Support for LargeUtf8 column type

### ISSUE THREAD

**Issue by chitralverma** [delta-io/delta-rs#1024]
# Environment

**Delta-rs version**: latest

**Binding**: 
Python

**Environment**:
- **Cloud provider**: all
- **OS**: mac ventura, m1
- **Other**:

***
# Bug

**What happened**:
While writing a delta table to a location from a PyArrow table, the writer breaks with the following error,
```
deltalake.PyDeltaTableError: Schema error: Invalid data type for Delta Lake: LargeUtf8
```

Not sure if this is write only issue or also a read issue.

**What you expected to happen**:
PyArrow types like `LargeUtf8`, `LargeString` should be supported.

**How to reproduce it**:
You can use the following minimal code to reproduce this.

```
import pyarrow as pa
from deltalake.writer import write_deltalake

# Create a pyarrow table with LargeString column 'name'
pylist = [{'name': 'Joey', 'age': 14}, {'name': 'Ivan', 'age': 32}]
schema = pa.schema([pa.field('name', pa.large_string()), pa.field('age', pa.int64())])
t = pa.Table.from_pylist(pylist, schema=schema)

write_deltalake("/tmp/test-delta", data=t)
```

**More details**:

**Comment by houqp** [comment]
Deltalake itself doesn't distinguish between large and regular string/byte bytes: https://github.com/delta-io/delta/blob/master/PROTOCOL.md#primitive-types. I think we can just represent them using the primitive `string` and `binary` types.
