### ISSUE TITLE
Add color to PR labels

### ISSUE THREAD

**Issue by iajoiner** [delta-io/delta-rs#1038]
# Description
Currently the auto generated PR labels almost all have the same color. Using different colors for different labels can improve readability.

**Related Issue(s)**
https://github.com/delta-io/delta-rs/issues/1026

**Comment by wjones127** [comment]
Could we also align them to the existing labels? I realized we added `delta-rs-crate` when we already had `bindings/rust` for example. Similar with `python` and `bindings/python`.

**Comment by iajoiner** [comment]
@wjones127 Sure! I also wonder whether we should retroactively label old PRs and generate a better historical CHANGELOG.

**Comment by iajoiner** [comment]
@wjones127 @roeap On it..
