### ISSUE TITLE
CDC action not supported

### ISSUE THREAD

**Issue by Fazzani** [delta-io/delta-rs#1039]
# Environment

**Delta-rs version**:
0.6.4
**Binding**: 

**Environment**:
- **Cloud provider**: Azure
- **OS**: Windows
- **Other**:

***
# Bug

**What happened**:

```
 self._table = RawDeltaTable(
deltalake.PyDeltaTableError: Invalid JSON in log record: unknown variant `cdc`, expected one of `metaData`, `add`, `remove`, `txn`, `protocol`, `commitInfo` at line 1 column 6
```

**What you expected to happen**:

**How to reproduce it**:

Reading deltaTable with CDC enabled

**More details**:

**Comment by wjones127** [comment]
Thanks for the report. This should be fixed in #959.

**Comment by rtyler** [comment]
@wjones127 I believe there's a second bug here in that a `min_reader_version` is not being respected here. I'm digging around in Slack to see what reader version [the CDC protocol change](https://github.com/delta-io/delta/commit/29a45af0614be0dfde959ae88fd3ed3d1a7f6b75) should require :thinking:

**Comment by wjones127** [comment]
@rtyler That should have been fixed with https://github.com/delta-io/delta-rs/pull/932. Although not sure either what version the CDC actions are part of.

**Comment by rtyler** [comment]
As far as I can tell we have this support now
