### ISSUE TITLE
Add convertToDelta command

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#1041]
The `convertToDelta` command is a good way to attract users because it makes Delta an easy switch.  See [this blog post](https://delta.io/blog/2022-09-23-convert-parquet-to-delta/) for details.

The command adds a `_delta_log` directory to an existing Parquet data lake.  It doesn't change any of the underlying data files - it's an in-place operation.

Would be a nice addition to this library 💪

**Comment by iajoiner** [comment]
I will do this one.

**Comment by MrPowers** [comment]
Awesome @iajoiner.  I'll make sure to write a blog post when this gets merged in.  Lots of folks will find this functionality useful.

**Comment by iajoiner** [comment]
Sorry for the delay for I just recovered from COVID. I will do the release first and then this one.

**Comment by MrPowers** [comment]
@iajoiner - are you still planning on grabbing this one?

**Comment by rtyler** [comment]
Huh, I just saw this ticket. I actually [built this the other week](https://github.com/buoyant-data/oxbow) which can be run as a CLI or Lambda function :shrug:
