### ISSUE TITLE
Python blob auth does not accept AZURE_CLIENT_SECRET

### ISSUE THREAD

**Issue by Hanspagh** [delta-io/delta-rs#1062]
# Environment

**Delta-rs version**: 0.6.4

**Binding**: python

**Environment**:
- **Cloud provider**:
- **OS**: iOS
- **Other**:

***
# Bug 

**What happened**:

Using storage_options key when reading a delta table, it does not accept the var AZURE_CLIENT_SECRET

**What you expected to happen**: It works

**How to reproduce it**:

**More details**: This seems to be fixed on main, but not in current release 0.6.4,  would it be possible to do a release

**Comment by roeap** [comment]
this will be fixed in the upcoming release #1098

**Comment by roeap** [comment]
validated that this works, feel free to re-open if the issue persists.
