### ISSUE TITLE
Support Statistics in PyArrow

### ISSUE THREAD

**Issue by aersam** [delta-io/delta-rs#1070]
# Description

**Use Case**

I'd like to use polars to read delta files, using the statistics from delta log. I asked for support there, but seems to be something that should be implemented in this repo

If I understand correctly, it should be possible to tell pyarrow some statistics about the columns (https://arrow.apache.org/docs/python/generated/pyarrow.parquet.Statistics.html), which should be done using delta log in our case

**Related Issue(s)**

https://github.com/pola-rs/polars/issues/6260

**Comment by roeap** [comment]
Hi @aersam  - indeed we do use the file statistics when creating pyarrow Datasets. Here is how it is done internally.

https://github.com/delta-io/delta-rs/blob/8e0b8cbcb397ba040fba743049134262390fcc5d/python/deltalake/table.py#L360-L371

the `dataset_partitions` method reads the log and does the required processing. Does that already help? And if not, yould you elaborate a bit what you would need for an integration to work?

**Comment by aersam** [comment]
oh, that looks good. Found no docu and assumed it's not implemented, my error :) I would reopen it if there is something missing.

thanks a lot and continue your great work :)
