### ISSUE TITLE
Paths in add actions aren't always percent-decoded

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#1079]
# Environment

**Delta-rs version**:

**Binding**: 

**Environment**:
- **Cloud provider**:
- **OS**:
- **Other**:

***
# Bug

Our methods `get_files_by_partition()` and `get_files_iter()` take the raw paths, without decoding the percent-encoded characters. I wonder if we can do that decoding when deserializing the JSON actions? Also we should see whether this is necessary for Parquet checkpoints.

**Comment by houqp** [comment]
I would expect paths to be encoded in the checkpoints as well. If paths are always URL encoded when stored in the object store, it might be more efficient to only work with url encoded paths in the core at runtime and url encode get_files_by_partition's arguments instead.

**Comment by wjones127** [comment]
> it might be more efficient to only work with url encoded paths in the core at runtime and url encode get_files_by_partition's arguments instead.

Yeah I think the funny thing is we will decode them, pass them to the object store implementation, who will then encode them again for their HTTP requests.

The one annoying thing about doing this within `get_files_by_partitions` is that now we have to handle a parsing error in that function (if it's not valid percent-encoded). It would be nice for that function to remain infallible.

**Comment by kuksag** [comment]
Is there any way I can help resolve this issue? It may be related to the problem I recently encountered where reading and writing to delta tables didn't work due to percent-encoded characters in the path

**Comment by tmrlvi** [comment]
Why not use `object_store::path::Path::parse.` instead of `object_store::path:Path::from`?

When I look at the JSON written by the official pyspark library, the paths, at least in the add actions, are already encoded, and using `Path::from` farther encodes the encoded url. (And in the python implementation, `Path::from` is called twices, so it is double encoded)

From the [docs](https://docs.rs/object_store/latest/object_store/path/struct.Path.html#encode):

>  A string containing potentially illegal path segments can be encoded to a [Path](https://docs.rs/object_store/latest/object_store/path/struct.Path.html) using [Path::from](https://docs.rs/object_store/latest/object_store/path/struct.Path.html#method.from) or [Path::from_iter](https://docs.rs/object_store/latest/object_store/path/struct.Path.html#method.from_iter).

Replacing all the `Path::from()` with `Path::parse().unwrap()` in `rust/src/table_state.rs` and in `python/src/filesystem.rs` seems to solve this issue, but:

1. I am not sure it does not introduce other issues
2. I am not sure how to handle errors gracefully in file_paths_iter (instead of unwrapping and crashing)
3. I did not test writing at all

**Comment by wjones127** [comment]
Hmm I'm still struggling to understand what the correct behavior should be.

With PySpark, if I write a table with data (partitioned on first 3 columns):

```python
[('/%20%f', date(1970, 1, 1), b'hello', 6),]
```

Then on disk I see the path encoded once:

```
│  ├── letter=%2F%2520%25f
│  │  └── date=1970-01-01
│  │     └── data=hello
│  │        └── part-00000-a29a3f63-5a26-4127-aeff-e6d27c077917.c000.snappy.parquet
```

But in the transaction log I see the path encoded twice:

```
{"add":{"path":"letter=%252F%252520%2525f/date=1970-01-01/data=hello/part-00000-a29a3f63-5a26-4127-aeff-e6d27c077917.c000.snappy.parquet","partitionValues":{"letter":"/%20%f",...
```

Do you see the same thing? Perhaps we should be percent decoding the paths in the log?

**Comment by wjones127** [comment]
Okay I think I have a solution: https://github.com/delta-io/delta-rs/pull/1613

**Comment by tmrlvi** [comment]
> Do you see the same thing? Perhaps we should be percent decoding the paths in the log?

Yes. I think partitioning in Spark assume URL encoding (reading the directory as a parquet dataframe reads the partition correctly), and it seems that in the delta log, there is another escaping (I have no idea why).

I'm not familiar with the official spec to say what is correct though :sweat: (It could be also a mistake in the original implementation)

**Comment by tmrlvi** [comment]
> Okay I think I have a solution: #1613

Basically, this leaves the path as is in the logs, right?

**Comment by wjones127** [comment]
> Basically, this leaves the path as is in the logs, right?

Well the logs have them percent encoded, so they are decoded once to match what's on disk. But elsewhere we avoid accidentally re-encoding them.
