### ISSUE TITLE
Unable to authenticate with DefaultAzureCredential

### ISSUE THREAD

**Issue by mpicard** [delta-io/delta-rs#1096]
# Environment

**Delta-rs version**:  deltalake = "0.6.4"

**Binding**: Python

**Environment**: macOS
- **Cloud provider**: Azure
- **OS**: Linux
- **Other**:

***
# Bug

**What happened**: TypeError: argument 'storage_options': 'bool' object cannot be converted to 'PyString'

**What you expected to happen**: I expect write_deltalake to use the azure.identity.DefaultAzureCredential to authenticate in this scenario, just like pyarrow would.

**How to reproduce it**:

- TypeError: argument 'storage_options': 'bool' object cannot be converted to 'PyString':
```python
        write_deltalake(
            f"az://container/delta/test",
            df,
            storage_options={"account_name": account_name, "anon": False},
        )
```

- deltalake.PyDeltaTableError: Generic DeltaTable error: Failed to find valid credential.:
```python
        write_deltalake(
            f"az://container/delta/test",
            df,
            storage_options={"account_name": account_name, "anon": "False"},
        )
```

**More details**:

There are several packages that manage to do this, I would expect delta to work similarly:
- https://pypi.org/project/adlfs/
- https://arrow.apache.org/docs/python/generated/pyarrow.fs.FSSpecHandler.html

**Comment by cesar-vermeulen** [comment]
Curious to follow this - did you manage to get this work somehow in the meanwhile?

**Comment by roeap** [comment]
the Azure credentials are actually not supported at all :) - the the configuration that gets passed into them should however seeem familiar, when configuring storage for deltalake. 

[Here](https://docs.rs/object_store/0.8.0/object_store/azure/enum.AzureConfigKey.html#variants) you can find the supported storage options for azure.

**Comment by roeap** [comment]
closing this as we need to work with the auth mechanics that are offered by object_Store right now.
