### ISSUE TITLE
parquet2 feature flag fails to parse checkpoint

### ISSUE THREAD

**Issue by mpetri** [delta-io/delta-rs#1116]
# Environment

**Delta-rs version**: rust 0.6 from crates.io

**Binding**:  rust 0.6 from crates.io

**Environment**:
- **Cloud provider**: aws/s3
- **OS**:
- **Other**:

***
# Bug

**What happened**: Trying to load a deltalake with the `parquet2` feature fails. succeeds with `parquet` feature

**What you expected to happen**: load should work with both `parquet` and `parquet2` feature flags

**How to reproduce it**:

**More details**: Error message:

```
Error: Invalid action record found in log: Failed to parse parquet checkpoint: Invalid action: unsupported page encoding type for primitive column: Plain

Caused by:
    0: Failed to parse parquet checkpoint: Invalid action: unsupported page encoding type for primitive column: Plain
    1: Invalid action: unsupported page encoding type for primitive column: Plain
```

**Comment by houqp** [comment]
@mpetri do you mind attaching the table checkpoint here to help reproduce the error?

**Comment by rtyler** [comment]
We removed parquet2 :fire:
