### ISSUE TITLE
Panic while attempting to authenticate with Azure Bearer token

### ISSUE THREAD

**Issue by Rob-DL** [delta-io/delta-rs#1117]
I'm trying to access a delta lake that's on an Azure Blob store. For security reasons the only authentication method I can use is the bearer token. I'm trying to read the table using the following python code.

```
dt = DeltaTable(
    "az://mycontainer/path_to_table",
    storage_options={
        "AZURE_STORAGE_ACCOUNT_NAME": "account-name",
        "ACCOUNT_NAME": "account-name",
        "BEARER_TOKEN": "eyJ0eXA...",
    },
)
```

But when I run this I'm greeted with the following panic from the underlaying rust code:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidByte(132, 46)', C:\Users\robdl\.cargo\registry\src\github.com-1ecc6299db9ec823\object_store-0.5.3\src\azure\credential.rs:156:48
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "C:\Users\rolaat\test\deltars.py", line 16, in <module>
    dt = DeltaTable(
  File "C:\Users\rolaat\.venv\tmpvenv\lib\site-packages\deltalake\table.py", line 121, in __init__
    self._table = RawDeltaTable(
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: InvalidByte(132, 46)
```

The problem seems to be with that the token isn't valid base64, which is technically true as these Azure generated tokens aren't padded correctly. But even after correcting for this I keep getting the same error. I generated several tokens trough the azure cli using the command below, but they all result in the same error.

`az account get-access-token --resource https://myproject.blob.core.windows`

From [this discussion](https://github.com/delta-io/delta-rs/discussions/1113) I understand that this is a bug as it tries to use the token as an access key to create a signature, which is not the intended usage.

**Comment by roeap** [comment]
We have a PR open in object-store that will fix this issue - apache/arrow-rs#3698.

The name may be misleading, but the fix is included :). We do have to wait for the next object store release but, there are no other changes required in deltalake for this to take effect.

**Comment by roeap** [comment]
@stephen-bowser - the release process for the next version of the object store crate has actually already started. So the release should go public in the the next few days.

I plan on triggering another python release shortly after to include these fixes.

**Comment by Rob-DL** [comment]
It's working now.
