### ISSUE TITLE
Implement Z-order sorting option in Optimize operation

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#1127]
# Description

Would like to be able to z-order tables. We probably need to implement a z-order sorting function in apache/arrow-rs first.

**Use Case**

**Related Issue(s)**

Probably should prioritize #1125 first.

**Comment by MrPowers** [comment]
It'd be great if someone could grab this.  Z ORDERing provides a "killer feature" functionality to end users.  I think this functionality will get us a lot of users.

**Comment by wjones127** [comment]
Design doc for Z-order is here: https://docs.google.com/document/d/1TYFxAUvhtYqQ6IHAZXjliVuitA5D1u793PMnzsH_3vs/edit#heading=h.q7ah6pca24ul

Note that DataFusion has a spilling sort node, which can sort arbitrarily large inputs: https://github.com/apache/arrow-datafusion/issues/1568. We should try to reuse that if possible.

However, we should still get optimize working in basic cases first.

**Comment by MrPowers** [comment]
Here's the suggested interface for Z ORDER: `delta_table.optimize.z_order(["col1", "col2"])`.

Z Ordering allows users to fully enjoy the power of data skipping.

Even a naive implementation that simply sorts the data would be really useful for the data community.  We could release a naive algorithm to start and then swap in a more fancy implementation later.

Even an implementation that simply sorts on one column would be a huge win right now.

**Comment by wjones127** [comment]
TODO:

* [ ] Implement z-order sort key function
* [ ] Register function as a [scalar UDF](https://docs.rs/datafusion/latest/datafusion/physical_plan/udf/struct.ScalarUDF.html)
* [ ] Implement sorting query that sorts the data by the z-order sort key, then drops the key

## z-order sort key function

1. Map each column to a one or more 4-byte (32-bit) value. Variable width columns can map to a configurable number of int32s; for example strings we'll use the first 4 x N bytes of the string.
2. Interleave the bits of the mapped values into a single binary array. That array is the z-order sort key.
