### ISSUE TITLE
Compiler failure on clean build of rust code

### ISSUE THREAD

**Issue by guyrt** [delta-io/delta-rs#1132]
# Environment

**Delta-rs version**:   main branch head

**Binding**: n/a

**Environment**:   
- **Cloud provider**: N/S
- **OS**:  Windows and WSL (tried both)
- **Other**:   clean rustup install so latest everything.    rust 1.67.0

***
# Bug

**What happened**:

running `cargo test ` results in compile error

**What you expected to happen**:

**How to reproduce it**:

Hopefully this reoccurs for anyone starting from a totally clean environment. 

**More details**:

Here's my output:

       Compiling memoffset v0.7.1
         Compiling aws-smithy-client v0.52.0
         Compiling reqwest v0.11.14
      error[E0252]: the name `tls` is defined multiple times
        --> C:\Users\riguy\.cargo\registry\src\github.com-1ecc6299db9ec823\rusoto_core-0.48.0\src\lib.rs:25:5
         |
      23 | use hyper_rustls as tls;
         |     ------------------- previous import of the module `tls` here
      24 | #[cfg(feature = "native-tls")]
      25 | use hyper_tls as tls;
         |     ^^^^^^^^^^^^^^^^ `tls` reimported here
         |
         = note: `tls` must be defined only once in the type namespace of this module
      help: you can use `as` to change the binding name of the import
         |
      25 | use hyper_tls as other_tls;
         |     ~~~~~~~~~~~~~~~~~~~~~~
      
      error[E0599]: no function or associated item named `new` found for struct `hyper_rustls::HttpsConnector` in the current scope
         --> C:\Users\riguy\.cargo\registry\src\github.com-1ecc6299db9ec823\rusoto_core-0.48.0\src\request.rs:224:41
          |
      224 |         let connector = HttpsConnector::new();
          |                                         ^^^ function or associated item not found in `hyper_rustls::HttpsConnector<_>`
      
      error[E0599]: no function or associated item named `new` found for struct `hyper_rustls::HttpsConnector` in the current scope
         --> C:\Users\riguy\.cargo\registry\src\github.com-1ecc6299db9ec823\rusoto_core-0.48.0\src\request.rs:244:41
          |
      244 |         let connector = HttpsConnector::new();
          |                                         ^^^ function or associated item not found in `hyper_rustls::HttpsConnector<_>`
      
      Some errors have detailed explanations: E0252, E0599.
      For more information about an error, try `rustc --explain E0252`.
      error: could not compile `rusoto_core` due to 3 previous errors
      warning: build failed, waiting for other jobs to finish...

**Comment by wjones127** [comment]
Sorry this is a known issue. I'm working on resolving it in #1097, but for now I'd suggest only building one crate at a time, instead of the whole workspace.

**Comment by guyrt** [comment]
ok - i'm closing as dupe then.
