### ISSUE TITLE
Adopt ruff for python linting in CI/CD

### ISSUE THREAD

**Issue by roeap** [delta-io/delta-rs#1149]
# Description

As proud members of the Rust community, as well as advocates of rust backed python, I thought we could adopt [ruff](https://pypi.org/project/ruff/) as our main python linter in CI/CD.

Its not a huge pain right now, but the change is also quite minimal in terms of effort, and I personally made great experiences with it several projects.

As a bonus we could add delta-rs to the list of adopters alongside many other great projects like, pydantic, polars, pandas and many more...

**Use Case**

**Related Issue(s)**

**Comment by houqp** [comment]
Yeah, I have been thinking of adding switching to ruff as well!

**Comment by fvaleye** [comment]
Good idea 👍

**Comment by marijncv** [comment]
For reference, I created a [PR](https://github.com/charliermarsh/ruff/pull/3133) on the ruff repository to add delta-rs to the list of users
