### ISSUE TITLE
failed to open remote tables with name containing space character

### ISSUE THREAD

**Issue by roeap** [delta-io/delta-rs#1156]
# Environment

**Delta-rs version**:

**Binding**: 

**Environment**:
- **Cloud provider**:
- **OS**:
- **Other**:

***
# Bug

as discussed in https://github.com/delta-io/delta-rs/issues/600#issuecomment-1406180752, we seem to have trouble opening delta tables in remote stores, if the table name contains a space character (or any character that will be URL encoded?).

**What you expected to happen**:

**How to reproduce it**:

**More details**:

**Comment by rtyler** [comment]
@roeap I believe this should be addressed now right? Or does this also relate to #1245?

**Comment by bkazour** [comment]
Hello,
It seems this issue still exists, am I correct?

**Comment by TakreemAkhter** [comment]
seems so. My delta table partitions has a '#' and I get a fileNotFound exception with the character getting converting to '%2523'. Anyway I can handle it in my code?

**Comment by rtyler** [comment]
@TakreemAkhter would you be able to test the latest `HEAD` of main? We made a number of changes that should improve this and I've seen other reproducible bugs resolved by the refactor

**Comment by ion-elgreco** [comment]
I believe this also got resolved with this fix https://github.com/delta-io/delta-rs/pull/2705
