### ISSUE TITLE
vacuum do nothing on Azure storage

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#1174]
# Environment

**Delta-rs version**: 0.7

**Binding**:  Python

**Environment**:
- **Cloud provider**: Azure
- **OS**: Windows 10
- **Other**:

***
# Bug

I created a delta table in Azure using this code
`write_deltalake(table_or_uri='az://delta', data=result, mode="overwrite", storage_options=storage_options)`

see delta history 

```
[{'delta-rs': '0.6.0', 'timestamp': 1677194435965},
 {'clientVersion': 'delta-rs.0.6.0',
  'operation': 'delta-rs.Write',
  'operationParameters': {'mode': 'Overwrite', 'partitionBy': '[]'},
  'timestamp': 1677194457447},
 {'clientVersion': 'delta-rs.0.6.0',
  'operation': 'delta-rs.Write',
  'operationParameters': {'mode': 'Overwrite', 'partitionBy': '[]'},
  'timestamp': 1677195075181},
 {'clientVersion': 'delta-rs.0.6.0',
  'operation': 'delta-rs.Write',
  'operationParameters': {'mode': 'Overwrite', 'partitionBy': '[]'},
  'timestamp': 1677196133144},
 {'clientVersion': 'delta-rs.0.6.0',
  'operation': 'delta-rs.Write',
  'operationParameters': {'mode': 'Overwrite', 'partitionBy': '[]'},
  'timestamp': 1677196136085},
 {'clientVersion': 'delta-rs.0.6.0',
  'operation': 'delta-rs.Write',
  'operationParameters': {'mode': 'Overwrite', 'partitionBy': '[]'},
  'timestamp': 1677196163370},
 {'clientVersion': 'delta-rs.0.6.0',
  'operation': 'delta-rs.Write',
  'operationParameters': {'mode': 'Overwrite', 'partitionBy': '[]'},
  'timestamp': 1677196165748}]

```
now when I run 
`dt.vacuum(dry_run=False)`

nothing happen the parquet files are not deleted ?

**Comment by wjones127** [comment]
What do you get when you run `dt.vacuum(dry_run=True)`? And are you files older than the `retention_hours` specified? It defaults to 1 week, so if none of the files are 1 week old they won't be deleted unless you pass a shorter window.

**Comment by djouallah** [comment]
Thanks, did not know about retention hours, when I try this
`dt.vacuum(retention_hours=1,dry_run=True)`
i get this error
PyDeltaTableError: Generic error: Invalid retention period, minimum retention for vacuum is configured to be greater than 168 hours, got 1 hours
