### ISSUE TITLE
Add number of monthly downloads badge to the README

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#1190]
Here's a project I have with a number of monthly PyPi downloads:

<img width="484" alt="Screen Shot 2023-02-28 at 1 33 55 PM" src="https://user-images.githubusercontent.com/2722395/221947209-8de66d1c-aa51-40e5-a404-b0e2c02ecf39.png">

Can we add this badge to the delta-rs README?  Let me know and I'll be happy to make a PR.

We have 457,000 downloads in the last month, which seems impressive.

**Comment by houqp** [comment]
that sounds good, i think our number actually decreased, we used to have something like 1M monthly download :P

**Comment by wjones127** [comment]
Yeah weird it dropped off recently https://pypistats.org/packages/deltalake

**Comment by cmackenzie1** [comment]
Resolved by 3d0ec0298a546a1a6d3c2e21bbea1ddad8dc1f7b?
