### ISSUE TITLE
Datafusion scan fails on dictionary column

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#1194]
# Environment

**Delta-rs version**:

**Binding**: 

**Environment**:
- **Cloud provider**:
- **OS**:
- **Other**:

***
# Bug

**What happened**:

Reported in https://github.com/delta-io/delta-rs/pull/1187#issue-1601421482

scanning `delta-0.8.0-partitioned` results in:

```
External(Execution("Failed to map column projection for field year. Incompatible data types Dictionary(UInt16, Utf8) and Utf8"))
```

**What you expected to happen**:

**How to reproduce it**:

**More details**:

**Comment by rtyler** [comment]
@wjones127 does this still fail after the recent upgrades to datafusion and arrow?

**Comment by ion-elgreco** [comment]
Closing it as stale, and I believe this is resolved
