### ISSUE TITLE
Add version to deltalake python package

### ISSUE THREAD

**Issue by chitralverma** [delta-io/delta-rs#1227]
# Description
Small task of adding a `__version__` to the init.py of deltalake python package.

Example of how `pyarrow` does it is available [here](https://github.com/apache/arrow/blob/main/python/pyarrow/__init__.py#L43).
This is a low priority easy additional and I am happy to raise a PR for this.

**Use Case**

 This will allow users to,
```
import deltalake as dl
print(dl.__version__)
'0.8.1'
```

**Related Issue(s)**

**Comment by houqp** [comment]
please feel free to send us a PR
