### ISSUE TITLE
Support configuring parquet compression

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#1235]
# Description

We should probably make this configurable at the table level, if there's some standard for that.

Note: need to change the filename format:

https://github.com/delta-io/delta-rs/blob/8b854694d7eca2ef563601aac03f167fb7f0449c/rust/src/writer/utils.rs#L96-L97

Also, should we consider using zstd by default? It produces smaller files than snappy, but is faster than gzip (the Iceberg default). It was one of the better ones it my tests of Parquet compression, and I've seen suggested in several other venues for Parquet tables.

**Use Case**

**Related Issue(s)**

**Comment by spebern** [comment]
It would also be a good idea to support compression levels. `zstd`'s decompression speed does not suffer that much from higher levels, but achieves higher compression ratios (https://gregoryszorc.com/blog/2017/03/07/better-compression-with-zstandard/).

When download is a bottleneck and compression speed is not tuning the level can be useful.
