### ISSUE TITLE
Rust: Load Delta Table on with selected partitions

### ISSUE THREAD

**Issue by everestas** [delta-io/delta-rs#1237]
# Description

As far as I know, currently you can only get files uris by providing partition, however there is no way of loading data by partitions.

**Use Case**

Load data by partition to reduce the size of data to read.

**Related Issue(s)**

**Comment by kvedes** [comment]
You can load a specific partition, however it seems that it doesn't work for nested partitions. 
For python you do it like this (not sure how to do it for rust, but python uses Rust underneath so it should be possible):

```python
dt = DeltaTable(...)

table = dt.to_pandas(
    partitions=[("col0, "=", "myvalue)],
    columns=[
        "col0",
        "col1"
    ],
)
```

**Comment by alexwilcoxson-rel** [comment]
I have encountered this with the Rust API as well using DataFusion. The load operation uses the DataFusion DeltaTable scan as well.

The scan could be changed to use delta table's `get_active_add_actions_by_partitions` given the partition filters could be provided to the scan, either via pushdown filters or potentially a field on DeltaTable set when building it initially.

**Comment by ion-elgreco** [comment]
DeltaScanBuilder should prune partitions and files properly before that ParquetExec is crated in rust, so this shouldn't be an issue anymore
