### ISSUE TITLE
avoid loading checkpoints created for older versions

### ISSUE THREAD

**Issue by houqp** [delta-io/delta-rs#125]
Follow up from https://github.com/delta-io/delta-rs/pull/124.

Since transaction version commit and checkpointing are not transactional, newer transaction versions can become visible to readers before a checkpoint is created. When we are reloading table from source, we could also compare current in memory table version with the version from a new latest checkpoint, if current in memory version is already ahead, then we can skip the checkpoint restoration.

**Comment by dispanser** [comment]
I have some concerns with the general strategy of always using a check point when it exists. In my day job, one particular streaming sink has checkpoints of size 500MB, whereas each individual commit is about 30kb of json data. In such a case, loading a few dozen json files can be a lot quicker, especially when the i/o backend requests them in a concurrent / non-blocking fashion.

A minimum implementation might give the choice to the user, exposing the information (newest available checkpoint, current version, estimated checkpoint size) or something along these lines.

**Comment by houqp** [comment]
@dispanser good call, I filed #128 to track this.
