### ISSUE TITLE
Add optimization to only list log files starting at a certain name

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#1252]
# Description

When listing the `_delta_log` directory, we should be able to say "start listing at 000...0010000.json` to only get log files after the 10000th (skipping a lot of calls) if that's all we need.

**Use Case**

**Related Issue(s)**

**Comment by rtyler** [comment]
Good idea!

**Comment by wjones127** [comment]
Heard from Scott that this was recently implemented in the Spark impl. Definitely seems like low-hanging fruit.

**Comment by ognis1205** [comment]
Would you mind if I worked on this? While I would love to tackle some of the "aged" good first issues, I haven't been able to determine which ones are still active and require assistance. Therefore, I would like to begin by addressing a low-hanging fruit before diving into more extensive contributions.

**Comment by wjones127** [comment]
Feel free to! I'm not 100% sure this optimization actually applies to our codebase yet. It looks like instead of listing, we just look for the N+1 log file until we get a 404 error back:

https://github.com/delta-io/delta-rs/blob/8a4b2b849a7a1e3deb0e68e50d78e31eea771206/rust/src/delta.rs#L792-L793

But I think there's at least one function that could benefit now: https://github.com/delta-io/delta-rs/blob/8a4b2b849a7a1e3deb0e68e50d78e31eea771206/rust/src/delta.rs#L657

**Comment by ognis1205** [comment]
@wjones127 
Thanks as always, Will!
I will look into the implementation and file a PR!

**Comment by ognis1205** [comment]
FYI:
I still have not gotten started on this. There is another task on delta-rs.
Please forgive my lateness. I will start from this week.

**Comment by roeap** [comment]
@ognis1205 - no worries at all. I do believe that for this optimization to really take effect, it needs to be added in the object_store crate rather then here, otherwise we would be getting the full payload in any case.

After a quick scan, it seems S3 supports this, although I haven't seen any explicit mention of ordering in the response, there is a "start-after" header that can be passed to list. I guess If there is a concept of "after" there should be a concept of ordering as well :).

For Azure I unfortunately have not found an equivalent parameter.

**Comment by ognis1205** [comment]
@roeap 
Thank you for understanding and sharing your helpful comments! It really helps me!

**Comment by ognis1205** [comment]
- Add `list_with_offset`

https://github.com/delta-io/delta-rs/blob/930d16e583fbd784f5f3d4bb8bcd753e2d6488a6/rust/src/storage/mod.rs#L201

- Try to use `list_with_offset` instead

https://github.com/delta-io/delta-rs/blob/8a4b2b849a7a1e3deb0e68e50d78e31eea771206/rust/src/delta.rs#LL858C1-L858C1

- Try to use `list_with_offset` instead

https://github.com/delta-io/delta-rs/blob/8a4b2b849a7a1e3deb0e68e50d78e31eea771206/rust/src/delta.rs#L670

**Comment by ognis1205** [comment]
I think I found a bug relating to this issue:
https://github.com/delta-io/delta-rs/issues/1403

**Comment by ognis1205** [comment]
@wjones127 @roeap 

Hi folks,

Sorry for being late; I have been a bit busy lately. Regarding the issue, after reviewing the current implementation of `delta-rs` and `object_store`, I noticed something:

- The `ObjectStore::list` and `ObjectStore::list_with_offset` methods return `ObjectMeta`, which does not provide any access to a file system. In other words, we have to call the `ObjectStore::get` method to search for each commit file until we receive a 404 error.

- As for the `find_latest_checkpoint_for_version` method, the specified `version` number is used to query all commit logs **before** it. Therefore, I believe the proposed optimization cannot be applied here.

Instead, while reviewing the current implementation, I guess I found a bug relating to `incremental_update`. I will work on it if would not mind.

**Comment by wjones127** [comment]
We don't use `ObjectStore::list_with_offset` yet, but I think we will need it to support reading multipart checkpoint files. https://github.com/delta-io/delta/pull/946

**Comment by ognis1205** [comment]
@wjones127 
I understand. Please allow me make it clear again:

 - Add `list_with_offset` delegating method to `DeltaObjectStore`
 - No optimization added
 - Regarding the issue what I suspect a bug, I will make another PR + reproducing code

Would you mind if I proceed this way?

**Comment by wjones127** [comment]
Yes, that sounds good

**Comment by ognis1205** [comment]
@wjones127 
I filed an PR:
https://github.com/delta-io/delta-rs/pull/1410
