### ISSUE TITLE
Data is replicated when overwriting data concurrently

### ISSUE THREAD

**Issue by sfilimonov-exos** [delta-io/delta-rs#1254]
# Environment

**Delta-rs version**: 0.8.1

**Environment**:
- **Cloud provider**: s3 or locally
- **OS**: Ubuntu 20.04

***
# Bug

**What happened**: Data is replicated in the Delta Table when writing to the table with `write_deltalake(..., mode="overwrite")`

**What you expected to happen**: Data is not replicated, there are no extra duplications in the data.

**How to reproduce it**:
```
import threading
from shutil import rmtree

import pandas as pd
from deltalake import DeltaTable, write_deltalake

path = "demo"

rmtree("demo", ignore_errors=True)

df = pd.DataFrame(data=[('one', 1), ('two', 2)], columns=["name", "val"])

write_deltalake(path, data=df, mode="append")

assert len(DeltaTable(path).to_pandas()) == 2, len(DeltaTable(path).to_pandas())


def overwrite(delta_table: DeltaTable):
    table = delta_table.to_pyarrow_table()  # appears like redundant file is being read here
    write_deltalake(delta_table, table, mode="overwrite")


def comp():
    for _ in range(5):
        overwrite(DeltaTable(path))


for i in range(5):
    overwrite(DeltaTable(path))

assert len(DeltaTable(path).to_pandas()) == 2, len(DeltaTable(path).to_pandas())  # Sequential - ok

t1 = threading.Thread(target=comp)
t2 = threading.Thread(target=comp)
t1.start()
t2.start()
t1.join()
t2.join()

res = DeltaTable(path).to_pandas()

assert len(res) == 4, len(res)  # Concurrent - fails

```

**More details**:

The same happens when writing to S3 having enabled locking through dynamo (`AWS_S3_LOCKING_PROVIDER = "dynamodb"` in envs).

**Comment by roeap** [comment]
Yeah, I think will was correct, this is a commit issue. op 1 and 2 read version 0 of the table. You can see that both contain identical remove actions. op 3 must have read version 1 of the table, where 1 commit already happed, this it only removes the file from 1, but not the file from 2.

So we are left with 2 active files, from op 2 and 3. As will pointed out, we are about to merge a PR that will enable us to support the optimistic commit protocol and resolve situations like this.

**Comment by wjones127** [comment]
#632 will not fix this for Python, but in a follow-up PR we will get the Python bindings using the new conflict checker.
