### ISSUE TITLE
Azure SAS tokens not working in 0.8.0

### ISSUE THREAD

**Issue by damiondoesthings** [delta-io/delta-rs#1255]
# Environment

**Delta-rs version**: 0.8.0

**Binding**: Python

**Environment**:
- **Cloud provider**: Azure
- **OS**: Ubuntu
- **Other**:

***
# Bug

**What happened**: SAS tokens are seamingly not appended to the request url when specified as storage options. The same thing works in version 0.7.0

**What you expected to happen**: Requests are authenticated with an SAS token

**How to reproduce it**:
Run this snippet with version 0.8.0
```python
dt = DeltaTable(
f"az://{<container>}",
storage_options= { 
"AZURE_STORAGE_ACCOUNT_NAME": <storageaccount>,
"SAS_TOKEN": <sas>
}
)
```

This will lead to an Azure authorization error. The error shows a request url without SAS.
The same code works fine in 0.7.0

**More details**:

I have a theory on why this may not show up in tests.
I believe the `arrow-rs` storage emulator always uses a hardcoded account key, so using a SAS or not makes no difference for the test:
https://github.com/apache/arrow-rs/blob/e5a1676950ab5c04b0a74953ec5418da67cedb45/object_store/src/azure/mod.rs#L919

I am not very familiar with that package though, so this may be wrong.

**Comment by rtyler** [comment]
@damiondoesthings I'm really not sure how to reproduce this, do you have a test case handy using the a localstack type of Azure replica service? I don't have any blob storage in Azure handy to explore this further

**Comment by damiondoesthings** [comment]
Hey @rtyler, thanks for the response. I tried again with my Azure setup and I can't reproduce the issue anymore on 0.8.1. So I will assume it is fixed. Maybe it was just a fluke :) Will close the issue. Thanks a lot!
