### ISSUE TITLE
Duplicate files after update

### ISSUE THREAD

**Issue by dispanser** [delta-io/delta-rs#127]
Hi,

After playing with the `update()` function for #124 I noticed that the number of files in one of my test runs was off.

I was able to reproduce the behavior in my [branch](https://github.com/delta-io/delta-rs/compare/main...dispanser:duplicate-files-after-update). The test loads version 0 of a data set, and then updates to the newest version. The expected outcome is that `get_files()` produces the same set of files as when directly loading the newest version. However, the file that was already in version 0 appears twice in the list.

`update()` is the only call site to `restore_checkpoint` that does not start empty, and I believe it should start from an empty state when loading a checkpoint, as checkpoints are typically self-contained. Instead, it applies the actions read from the checkpoint to the previously stored state.

I may be misunderstanding how checkpoints are supposed to work, but the provided dataset has been produced by a very simple spark function (delta 0.8.0), and I guess that defines a compatibility baseline.

**Comment by houqp** [comment]
Yes, checkpoints should only be restored on an empty table because it contains all historical commits. To be extra safe, I think we should just clear table state within `restore_checkpoint`.

**Comment by dispanser** [comment]
looking at `struct DeltaTable`, would it be sufficient to clean:
- `tombstones`
- `files`
- `commit_infos`

The following fields should contain an entry in the checkpoint so they are always overwritten when loading a checkpoint:
- `current_metadata`
- `min_reader_version`
- `min_writer_version`
- `last_check_point` (overwritten directly by `update`)

I'm a bit unsure about `app_transaction_version`, though. I guess I'll consult the spec first.

**Comment by houqp** [comment]
`app_transaction_version` needs to be cleared as well since it's also populated from transaction actions.

Perhaps to make the code easier to maintain, we can create a new `DeltaTableState` struct to host all these in memory states and store it as a single field in `DeltaTable`. Then upon checkpoint restore, we can just reassign this field with `DeltaTableState::default()`.

**Comment by houqp** [comment]
@dispanser should we assign this issue to you? If not, I can pick it up, just wanted to make sure someone is working on this ;)

**Comment by dispanser** [comment]
I'd love to. If you can wait til weekend, that is ;)

**Comment by houqp** [comment]
alright, issue assigned to you :)
