### ISSUE TITLE
Add decimal primitive type to document

### ISSUE THREAD

**Issue by ognis1205** [delta-io/delta-rs#1280]
# Description

According to this [PR](https://github.com/delta-io/delta-sharing/pull/288), I think that the [official document](https://docs.rs/deltalake/latest/deltalake/schema/enum.SchemaDataType.html) should describe the `decimal` primitive type as well.

**Comment by ognis1205** [comment]
If you don't mind, I think I can handle it and make a PR.

**Comment by roeap** [comment]
we are always happy to review and accept PRs - so any contribution highly welcome!
