### ISSUE TITLE
`datafusion` feature ineffective in 0.9.0

### ISSUE THREAD

**Issue by iajoiner** [delta-io/delta-rs#1304]
# Environment

**Delta-rs version**:
0.9.0 / main
**Binding**: 
Rust
**Environment**:
- **Cloud provider**:
- **OS**: Ubuntu 22.04 / AMD64
- **Other**:

***
# Bug
When upgrading from 0.8 to 0.9 we can no longer use a `DeltaTable` as `datafusion::datasource::TableProvider`.

**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**More details**:

**Comment by cmackenzie1** [comment]
I ran into this as well. To fix, you can do the following:

```rs
use deltalake::datafusion::datasource::provider_as_source;

let table = detalake::open_table("./hello");
let provider = provider_as_source(table)
```

**Comment by roeap** [comment]
Not sure I completely follow on what the regression here is. I think we use traverse the scan from `TableProvider` quite regularly in the test, and they still run.

We could consider also implementing `TableSource` for `DeltaTable`, which should be quite straight forward, as the table provider trait is a superset of the table source trait - at least I think it is.

My first guess would be that the datafusion APis somehow changed - last time we skipped a version or two. To find out more some context would be great. @iajoiner - could you provide an example with failing code?

**Comment by rtyler** [comment]
Is this perhaps a bug in our documentation rather than code? Either way, I would love to clear this up :)

**Comment by iajoiner** [comment]
@roeap @rtyler Sorry for my delayed reply. This turns out to be an issue caused by datafusion version disparity. If anything we need to emphasize that arrow and DF versions need to be compatible with the ones used by delta-rs and that ideally we should use delta-re-exported versions of arrow and DF.
