### ISSUE TITLE
Python write_deltalake in Minio

### ISSUE THREAD

**Issue by nortontsilva** [delta-io/delta-rs#1309]
I'm using S3 library to record data from a dataframe in a Minio bucket. For that I'm using the write_datalake and in storage_options i'm sending following paramiters:

storage_options = {
    "aws_access_key_id": MINIO_USER,
    "aws_secret_access_key": MINIO_KEY,
    "endpoint_url": MINIO_ENDPOINT,
    "use_ssl": "true",
    "verify": "false",
    "AWS_REGION": 'us-east-1',
    "signature_version": "s3v4"
}

But there's  an error response, lie this :
deltalake.PyDeltaTableError: 
Failed to load checkpoint: Failed to read checkpoint content: Generic S3 error: Error performing get request stage/file.delta/_delta_log/_last_checkpoint: response error "request error", after 0 retries: error sending request for url (https://srv.domine.com.br:32000/bucketname/stage/file.delta/_delta_log/_last_checkpoint): error trying to connect: The message received was unexpected or badly formatted. (os error -2146893018).

Reading is ok using Boto3 library, with following paramiters:
s3 = boto3.resource('s3',
    endpoint_url=MINIO_ENDPOINT,
    aws_access_key_id=MINIO_USER,
    aws_secret_access_key=MINIO_KEY,
    use_ssl=True,
    verify=False,
    region_name='us-east-1',
    config=boto3.session.Config(signature_version='s3v4')
    )

I tried testing this recording into a different server without the HTTPS certificate,  with following paramiters:
    "aws_access_key_id": MINIO_USER,
    "aws_secret_access_key": MINIO_KEY,
    "endpoint_url": MINIO_ENDPOINT,
    "AWS_REGION": 'us-east-1'}

It works!
The issue is when sending the data to a https server.

What should I do?

**Comment by roeap** [comment]
Hi, for your code it seems to be an ssl issue. The verify=false option is likely not getting passed down to the object store, as client options are treated separately. We should look into allowing this kind of configuration.

That said, for production workloads my official stance would obviously be to look into the root bund o.a. to be able to verify certificates 😀

**Comment by nortontsilva** [comment]
Ok! got it! tks!
