### ISSUE TITLE
feat(python): add filters argument to DeltaTable.to_pandas() for filter pushdown

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#1316]
Reading Delta tables into pandas DataFrames could be more intuitive.

Here's the current syntax:

```python
import pyarrow.dataset as ds

dt = DeltaTable(f"{pathlib.Path.home()}/data/delta/G1_1e8_1e2_0_0")
dataset = dt.to_pyarrow_dataset()
condition = ds.field("id1") == "id016"
df = dataset.to_table(filter=condition, columns=["id1", "id2", "v1"]).to_pandas()
```

Could we provide an interface that's more similar to `pandas.read_parquet`?  Something like this:

```
import deltalake

dt = DeltaTable(f"{pathlib.Path.home()}/data/delta/G1_1e8_1e2_0_0")
df = dt.filters([("id1", "==", "id016")]).to_pandas()
```

The list of tuples of how predicates are passed in `pandas.read_parquet`.

I'm open to other interfaces too.  I think something that hides `pyarrow.dataset`, is less code, and is familiar with existing pandas syntax would be good.

**Comment by wjones127** [comment]
Have you tried `DeltaTable.to_pandas()`? I think that's exactly what you are looking for. https://delta-io.github.io/delta-rs/python/api_reference.html#deltalake.table.DeltaTable.to_pandas

**Comment by MrPowers** [comment]
@wjones127 - Here's the signature for that function `to_pandas(partitions=None, columns=None, filesystem=None)`.

I don't see any `filters` argument for metadata-based file skipping.  Let me know if I am missing something!

**Comment by wjones127** [comment]
I see. We can extend that method to pass down filters in the dataset.

**Comment by MrPowers** [comment]
Great!  Can we expose the filters to use this syntax `[("id1", "==", "id016")]` instead of this `ds.field("id1") == "id016"`?

**Comment by MrPowers** [comment]
We may even want to combine the `partitions` and `filters` functionality.  That's what pandas and pyarrow do from what I understand.  [See here](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetDataset.html).

**Comment by wjones127** [comment]
Yes, I think we'll deprecate `partitions` in favor of `filters`, but leave both in for now. And we can use `DNF` filters if you want. Or maybe can can accept either?

**Comment by ognis1205** [comment]
Hi, guys. I apologize for interrupting your argument. Although it may take me some time to fully grasp the structure of delta-rs, I would like to work on this issue. Would it be possible to assign me to this issue?

**Comment by wjones127** [comment]
We would gladly accept a PR for this. 😄 

Note there is a function called `filters_to_expression` that can handle converting the DNF filter format into PyArrow expressions. ([code](https://github.com/apache/arrow/blob/b9cc5df8a4f7c7fe09f40ba92a74981dee5e536a/python/pyarrow/parquet/core.py#LL155C5-L155C26)).

**Comment by ognis1205** [comment]
Thank you @wjones127 @MrPowers!

Once there's a consensus on the implementation, please feel free to assign me to this issue, and I will follow the discussion here as well. Also, I will check the source code that you linked.

**Comment by MrPowers** [comment]
@ognis1205 - I think there is a consensus on the next steps and you can get started.

See [here](https://arrow.apache.org/docs/python/generated/pyarrow.parquet.ParquetDataset.html) for more information on the DNF filter format that Will is referring to.

Here's the [existing to_pandas method signature](https://delta-io.github.io/delta-rs/python/api_reference.html#deltalake.table.DeltaTable.to_pandas): `to_pandas(partitions=None, columns=None, filesystem=None)`

You can submit a PR that will update the method signature to this: `to_pandas(partitions=None, columns=None, filesystem=None, filters=None)`

Let me know if you'd like any additional clarification!

**Comment by ognis1205** [comment]
Thanks again @MrPowers @wjones127 !!

**Comment by ognis1205** [comment]
@wjones127 @MrPowers 

Hi, everyone! I have a question.
While making a PR for this issue, I encountered the following error:

     https://github.com/delta-io/delta-rs/actions/runs/4926020116/jobs/8800992032?pr=1349#step:8:18

So, I am considering implementing a fallback function for `pyarrow.parquet.core.filters_to_expression` that is compatible with PyArrow 7.0.0. However, I came across this comment on another PR:

     https://github.com/delta-io/delta-rs/pull/1315#issuecomment-1532453405

Should I still implement the fallback function if the Python `deltalake` package will soon drop support for Python 3.7?
Would it be okay to implement a stub function that does nothing instead?

**Comment by ognis1205** [comment]
I checked the PyArrow API doc. Only PyArrow >= 10.0.0 supports `pyarrow.parquet.core.filters_to_expression`.
So I think I should implement the fallback function in either case.

**Comment by wjones127** [comment]
Yes, we will drop support for Python 3.7, but we are keeping support (for now) for PyArrow 7.

**Comment by ognis1205** [comment]
@MrPowers @wjones127 
FYI:
I created [a PR for this issue](https://github.com/delta-io/delta-rs/pull/1349).

**Comment by FrankPortman** [comment]
Sorry for bumping an ancient ticket - maybe the docs online are outdated, but my understanding is this route supports `OR` clauses indirectly (or maybe that was the intent, either way it appears to support `OR`), while `partition_filters` still doesn't. Further the more flexible `filters` don't extend into `files` or `file_uris` methods. E.G. this ticket: https://github.com/delta-io/delta-rs/issues/1923

Is my understanding of the current limitations correct? I'm interested in helping contribute either code or documentation updates.
