### ISSUE TITLE
Add filters argument to DeltaTable.file_uris() and DeltaTable.files()

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#1329]
# Description

**Use Case**

`DeltaTable.file_uris()` and `DeltaTable.files()` only take `partition_filters` as an argument.  It'd be nice if they accepted a `filters` argument that could be used for file skipping as well.

**Related Issue(s)**

`DeltaTable.to_pandas()` needs a `filters` argument as well, so [this issue](https://github.com/delta-io/delta-rs/issues/1316) is related.

**Comment by wjones127** [comment]
Currently, this can be accomplished through `Dataset.get_fragments()`:

```python
import pyarrow as pa
import pyarrow.dataset as ds
from deltalake import DeltaTable, write_deltalake

sample_data = pa.table({
    'part': pa.array(['a', 'a', 'b', 'b', 'c', 'c']),
    'x': pa.array([1, 1, 2, 2, 3, 3])
})

write_deltalake('sample_data', sample_data, partition_by=['part'])

dt = DeltaTable('sample_data')
dt.file_uris(partition_filters=[('part', '>', 'a')])
# ['/Users/willjones/Documents/notebooks/sample_data/part=c/0-acc806b2-a96d-47cc-ac80-7607abca0a66-0.parquet',
# '/Users/willjones/Documents/notebooks/sample_data/part=b/0-acc806b2-a96d-47cc-ac80-7607abca0a66-0.parquet']

# With Dataset.get_fragments
filter = (ds.field('part') > 'a') & (ds.field('x') < 3)
fragments = dt.to_pyarrow_dataset().get_fragments(filter=filter)
list(fragment.path for fragment in fragments)
# ['part=b/0-acc806b2-a96d-47cc-ac80-7607abca0a66-0.parquet']
```

I'm reluctant to make this more convenient, since reading a Delta Table straight from the files is a low-level API. If doing this become common practice for end users, it will make adoption of deletion vectors (another important optimization!) more difficult.

**Comment by MrPowers** [comment]
Yea, I agree, if there is a work-around, then we shouldn't add a new API.  Thanks for showing me the right way @wjones127.
