### ISSUE TITLE
Handle commitInfo action

### ISSUE THREAD

**Issue by xianwill** [delta-io/delta-rs#133]
This is likely a low priority issue, but is mentioned in the [TODO list](https://github.com/delta-io/delta-rs/blob/8efd96a7202dc7eebdc435dba86dbc51d67854f9/TODO#L1) and is an aspect of the delta log protocol that is not yet implemented in delta-rs. As described in the protocol doc, [commit provenance information](https://github.com/delta-io/delta/blob/331c2af50dc3a2746f72f58cb896a5459caebff1/PROTOCOL.md#commit-provenance-information), may be included in delta logs within a `commitInfo` action so delta-rs should be able to read and write these.

The [reference implementation](https://github.com/delta-io/delta/blob/331c2af50dc3a2746f72f58cb896a5459caebff1/src/main/scala/org/apache/spark/sql/delta/OptimisticTransaction.scala#L426) creates this action and prepends it to the others before writing the log entry.

A [TODO exists in DeltaTransaction](https://github.com/delta-io/delta-rs/blob/715be9a497ec63b9bcd7dbdae7eba58f15e62049/rust/src/delta.rs#L799) where we should be able to do something similar.

**Comment by rtyler** [comment]
Closing the dupe I just created in #152 

This would be great to expose to the `DeltaTransaction` writer code such that a caller can supply their own `serde_json::Value`  (map) of JSON that can be addied into the transaction log.

The use-case I have in mind for this is to enable improved auditability of transactions, for example [kafka-delta-ingest](https://github.com/delta-io/kafka-delta-ingest) could add a map such as:

```json
{
  "commitInfo": {
    "kafka-delta-ingest": {
      "version" : "0.2.3",
      "delta-rs-version": "0.1.3",
      "topic": "originating-kafka-topic",
      "partition": 1
    }
  }
}
```

**Comment by nfx** [comment]
Implementing that in #265, @rtyler please link the PR also to this issue.

**Comment by nfx** [comment]
@rtyler what you're mentioning about kafka ingest is called "userMetadata" and it is a string. We can't get a struct there.

**Comment by houqp** [comment]
@nfx based on https://github.com/delta-io/delta/blob/master/PROTOCOL.md#commit-provenance-information, commit info action is supposed to be schemaless and can store arbitrary json object right?

**Comment by nfx** [comment]
@houqp we'd need to check to what extent is it arbitrary, as delta history technically returns commit infos.

**Comment by rtyler** [comment]
We do have the commit info action supported now, clearing this out
