### ISSUE TITLE
Extending concurrent writers support on S3

### ISSUE THREAD

**Issue by nkarpov** [delta-io/delta-rs#1333]
# Description

I'd like to suggest that we refactor the log related execution paths to more easily support alternate storage backend implementations.

The motivation for this is that today users can only use lock semantics (LockClient) to provide mutual exclusion at commit time. While it's straight forward to provide an alternate LockClient (like one backed by something other than DynamoDB), it's not straight forward to provide a completely different approach.

Adding a LogStore trait that encapsulates write/read/list for the delta log specifically will allow developers to more easily add alternate log implementations. It will also help clean up some of the current leak of concerns between commit/transaction.

I've tried to do some diligence and draft a straw-man proposal of the changes required in this doc, ~~https://docs.google.com/document/d/1Ge3Ddd3rwm0SJITBsGHVO2eCGEpmsducya-h5psCiT4~~
https://docs.google.com/document/d/1feXyfuW1XByxgfLbzf3wFYuF1uYf2O9f0SYFQDwh9MY

I'm new to Rust specifically, so would really appreciate any and all comments before I start on a PR, especially if I've suggested a non-rust type approach to this problem...

@roeap @rtyler @houqp @wjones127

**Comment by wjones127** [comment]
IIUC, you want a layer between the transaction logic and the object store, as a trait called `LogStore`. I think this makes sense, but probably has a lot of refactoring implications:

 * This means we use `LogStore` for logs and then a raw `ObjectStore` for data files. Do users now have to pass both? Or maybe by default to some generic `LogStore` that wraps the provided `ObjectStore`?
 * We currently have `ObjectStore` prefixed at the table root. Maybe this is a good opportunity to somehow open up support for absolute paths?
 * Do `S3StorageBackend` and `FileStorageBackend` just become a `LogStore` then?

**Comment by roeap** [comment]
> We currently have ObjectStore prefixed at the table root. Maybe this is a good opportunity to somehow open up support for absolute paths?

I agree, this would be a good opportunity to set us on this path, and also more clearly separating concerns by moving some of the lower level log handling logic off `DeltaTable`.

To support absolute paths for the data files we may need a dedicated abstraction as well, since object_stores `Path` assumes to be always relative the the stores root and in the most general sense, files may be distributed across buckets etc ...

All in all I do believe though that this can be a significant improvement to our codebase... while also being a significant effort.

**Comment by nkarpov** [comment]
> This means we use LogStore for logs and then a raw ObjectStore for data files. Do users now have to pass both? Or maybe by default to some generic LogStore that wraps the provided ObjectStore?

> Do S3StorageBackend and FileStorageBackend just become a LogStore then?

S3StorageBackend and FileStorageBackend already wrap their respective Object Stores so yeah I think they are good candidates for where implement these new log specific methods. Users should continue to only have to specify "one thing", so, for example, to support an alternate log store for S3, you'd have to implement a, `OtherS3StorageBackend`, and a flag for the config to swap between it and the existing one. I'm not sure it's ideal, but, it provides the appropriate (full) isolation between two different backends, and, realistically, there aren't that many of these different implementations...

> We currently have ObjectStore prefixed at the table root. Maybe this is a good opportunity to somehow open up support for absolute paths?

> To support absolute paths for the data files we may need a dedicated abstraction as well, since object_stores Path assumes to be always relative the the stores root and in the most general sense, files may be distributed across buckets etc

I actually haven't taken a look at this yet, will do...

**Comment by ognis1205** [comment]
Hi everyone,

I followed the discussion above and made a recap of the proposal of @nkarpov. I'm reading the source code of the delta Rust crate for my learning purpose so the document also helped me a lot to grasp the structure of the crate as well. It really helped me a lot!

Here is the recap and my additional proposal for the refactoring. There are still further considerations, e.g., how to choose a preferred backend when creating a Delta Table instance, but I think it will help the further discussion.

https://docs.google.com/document/d/1O39-WrcZbrifQOyWoRVs_uIo53Flo2_zSZznh0ULmrY/edit?usp=sharing

**Comment by ognis1205** [comment]
(Potentially) related issues:
 - https://github.com/delta-io/delta-rs/issues/865

**Comment by ognis1205** [comment]
@nkarpov 
After reviewing my additional proposal, I noticed something.
If I understand you correctly, I think I have to update my proposal.
Besides that, I guess, we might not make a consensus.
I will update my and/or create a new document until the first online chat.

**Comment by nkarpov** [comment]
Just adding this as an FYI to whomever might pass through this issue. There's a WIP PR on the delta-go side that uses essentially the pattern proposed in this thread to add support for the conditional write approach 

https://github.com/rivian/delta-go/pull/25

**Comment by rtyler** [comment]
I am going to close this, we now have an S3DynamoDbLogStore in `main` and the groundwork has been laid to provide alternative locking implementations whether as pluggable `ObjectStore` impls or as `LogStore` impls
