### ISSUE TITLE
docs(python): show data catalog options in Python API reference

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#1347]
# Description

This enum doesn't show anything, which isn't very helpful.

https://delta-io.github.io/delta-rs/python/api_reference.html?highlight=datacatalog#deltalake.data_catalog.DataCatalog

**Use Case**

**Related Issue(s)**

**Comment by omkar-foss** [comment]
Hey @wjones127, I've checked this issue and raised [this PR](https://github.com/delta-io/delta-rs/pull/1532) to show the available options from the `Enum` with links to their respective catalogs' documentation. Please let me know if anything else needs to be added. Thanks.
