### ISSUE TITLE
Implement rename_obj (atomic rename) API in storage backend

### ISSUE THREAD

**Issue by xianwill** [delta-io/delta-rs#135]
As discussed in https://github.com/delta-io/delta-rs/discussions/89, for multi-writer support, the S3 storage backend requires an atomic rename operation that uses a distributed lock lease to ensure that log files are not overwritten by other writers. 

Ultimately, the high-level logic of a `DeltaTransaction` commit should abstract over storage backends and look like:

```
* write temp file
* optimistic commit loop:
  * atomic rename
  * if version already exists
    * do conflict resolution if update, update temp file
  * increase version
```

Usage of the distributed lock should use a two-phase-commit and a compare-and-swap (i.e. conditional write) approach to guard the file write. The two-phase-commit is necessary so other writers can detect a stale transaction, determine state and continue or repair the previous transaction state. The compare-and-swap is required so a writer that has acquired the lock can fail in case it paused without knowing and exceeded the lock lease timeout. 

Further discussion about the implementation (including a proposal for a DynamoDb schema that represents a lock) should continue in  https://github.com/delta-io/delta-rs/discussions/89 before this issue is taken on.

**Comment by houqp** [comment]
As a side note for implementation, it looks like we need two types of consistency guarantees where:

1. for creating the temp object, we need put if not exists
2. for renaming the temp object, we need rename if not exists
