### ISSUE TITLE
minWriterVersion is set to 1

### ISSUE THREAD

**Issue by davidvesp** [delta-io/delta-rs#1352]
# Environment

**Delta-rs version**: 0.9-python

**Binding**: 

**Environment**:
- **Cloud provider**: Azure (ADLS V2)
- **OS**: Windows 10
- **Other**:

***
# Bug

**What happened**: Create a new table in delta format on ADLS V2. When we check properties of the table with the command:
DESCRIBE DETAIL '<table_location>'
We see that minReaderVersion=1 and minWriterVersion=1

**What you expected to happen**: 
We see that minReaderVersion=1 and **minWriterVersion=2**

**How to reproduce it**:
 write_deltalake(destination_delta, data = merged_table, mode='overwrite', overwrite_schema=True, storage_options=storage_options, configuration=delta_configuration)
delta_configuration = {
    "delta.autoOptimize.autoCompact": "false",
    "delta.autoOptimize.optimizeWrite": "true",
    "delta.logRetentionDuration": "7 days"
}

**More details**:

**Comment by wjones127** [comment]
Is there a reason you expect your table to have `minWriterVersion` 2? Are you using column invariants? Or have you set `delta.appendOnly`? I think we just don't increase the `minWriterVersion` unless you are actually using a feature that requires it.

**Comment by davidvesp** [comment]
The only reason is that I want to avoid writers with previous versions being able to write into the table. 
I added the delta.appendOnly:
delta_configuration = {
    "delta.autoOptimize.autoCompact": "false",
    "delta.autoOptimize.optimizeWrite": "true",
    "delta.logRetentionDuration": "7 days",
    "delta.appendOnly": "true"
}
And make a new ingestion to a table, but I still see minWriterVersion=1.
