### ISSUE TITLE
add partition filter to optimize 

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#1354]
it will be nice to have an option to optimize only specific partition,  for example optimize only yesterday data and keep today data as it is.

**Comment by wjones127** [comment]
Have you checked out the API docs for this function? https://delta-io.github.io/delta-rs/python/api_reference.html#deltalake.table.DeltaTable.optimize

We do support this. We actually have a blog post we are publishing soon on how to use this. :)

**Comment by djouallah** [comment]
sorry missed that

**Comment by djouallah** [comment]
@wjones127 I get un error with this

dt.optimize(partition_filters='2023-05-12')

TypeError: argument 'partition_filters': Can't extract `str` to `Vec`

what's the right way to do it ?

**Comment by wjones127** [comment]
Sorry it's not clear from the parameter description, but it should be a DNF filter, just like the `partition_filters` in the other functions. So if you have a partition column "date", you can optimize only that date with

```python
dt.optimize(partition_filters=[('date', '=', '2023-05-12')])
```

You can also pass inequalities and multiple conditions:

```python
dt.optimize(partition_filters=[('date', '>=', '2023-05-12'), ('x', '=', '2')])
```
