### ISSUE TITLE
Support merge (upsert) in Python

### ISSUE THREAD

**Issue by hongbo-miao** [delta-io/delta-rs#1357]
# Description

**Use Case**

I have dataframe with a few columns `timestamp`, `current`, `voltage`, `temperature`.
I hope `timestamp` to be unique, like a primary key.

Currently below code will keep appending if I run same code on same dataframe.

```py
write_deltalake("s3a://my-bucket/my-delta-tables/motor", df, mode="append")
```

It would be great to support merge (upsert) like this https://docs.databricks.com/delta/merge.html
Thanks! 😃

**Related Issue(s)**

Originally asked at https://github.com/delta-io/delta-rs/discussions/1355

**Comment by mohitbansal-gep** [comment]
Hi Team , any updates, of when can this be made available in python

**Comment by ion-elgreco** [comment]
@wjones127 can you assign this to me? Would like to give this a try next few weekends :)

**Comment by pfwnicks** [comment]
any updates on this? This would be an amazing feature to have out of the box for python. Any open issues blocking this still?

**Comment by ion-elgreco** [comment]
> any updates on this? This would be an amazing feature to have out of the box for python. Any open issues blocking this still?

I started last week, I'm still getting the hang of rust so it will probably take a couple weeks

**Comment by ion-elgreco** [comment]
> any updates on this? This would be an amazing feature to have out of the box for python. Any open issues blocking this still?

I'm working on it but I expect it will take a couple weeks. I only have time to work on it in weekends

**Comment by mohitbansal-gep** [comment]
When this will be released to pypi?

**Comment by ion-elgreco** [comment]
> When this will be released to pypi?

Somewhere this week

**Comment by pfwnicks** [comment]
awesome job @ion-elgreco! Thanks for cranking this out!

**Comment by ion-elgreco** [comment]
> @ion-elgreco Thanks for enabling this!
> Does this feature also enable schema merge? Something similar to this: https://docs.databricks.com/en/delta/update-schema.html#merge-schema-evolution

No only Merge operation.

**Comment by mohitbansal-gep** [comment]
Is the usage updated in Docs?

**Comment by ion-elgreco** [comment]
@mohitbansal-gep nope not yet. The API has examples for each command and you can find some more clear examples in the blog I wrote: https://delta.io/blog/2023-10-22-delta-rs-python-v0.12.0/
