### ISSUE TITLE
dataChange incorrect in get_add_actions

### ISSUE THREAD

**Issue by quartox** [delta-io/delta-rs#1379]
# Environment

**Delta-rs version**: 0.8.1

**Binding**: Python

**Environment**:
- **Cloud provider**: AWS
- **OS**: Ubuntu
- **Other**:

***
# Bug

**What happened**: 
Attempting to find data change True records yields inconsistent results. 

```
df = delta_table.get_add_actions().to_pandas()
df[df["data_change"] == True]
```

When I first read the table only the 9 most recent actions showed data change True. After a new commit to the table only the most recent action showed data change True and the previous 9 actions now showed False.

Confirmed from reading the commit logs that data change was True for all of those actions.

**What you expected to happen**:

Data change to match commit logs.

**How to reproduce it**:

Read the delta table add actions, make a new commit to the delta table with data change True and read the add actions again.

**More details**:

**Comment by ion-elgreco** [comment]
@quartox can you share a reproducible example? Or is this outdated by now

**Comment by quartox** [comment]
I haven't tested this recently. Given there are no other reports of this problem it is probably safe to close.

**Comment by ion-elgreco** [comment]
@quartox thanks for the update!
