### ISSUE TITLE
Need partitions changes (add/drop) on existing tables

### ISSUE THREAD

**Issue by itsluqiang** [delta-io/delta-rs#1387]
# Description
Hi, it seems we only be able to set partitions when creating a new table. Can we have feature of modifying existing table's partitions?
Or delta-rs already have it but I didn't find it in document. 

Thanks!

**Comment by ion-elgreco** [comment]
@itsluqiang this is now possible with: https://delta-io.github.io/delta-rs/python/api_reference.html#deltalake.table.DeltaTable.delete to drop

And you can write a new partition ofcourse with `write_deltalake(partition_by='column')`
