### ISSUE TITLE
Windows paths: spaces are parsed to %20 (reading delta table)

### ISSUE THREAD

**Issue by ABChristian** [delta-io/delta-rs#1391]
# Environment

**Delta-rs version**:
Python deltalake 0.9.0

**Environment**:
- **OS**: Windows 10 64bit
- **Python**: 3.11.3

***
# Bug

**What happened**:
Reading a delta table inside a folder which contains spaces thorws an error.
A new folder containing "%20" instead of spaces is created.

This folder/delta table was written using deltalake, and created in the expected location.

**What you expected to happen**:
The table should be created and read in the same folder.

**How to reproduce it**:
`import deltalake as dl

dl.write_deltalake(table_or_uri="./deltalake/data",data=DATAFRAME, mode="append")
data = dl.DeltaTable(table_uri="./deltalake/data")
print(data.to_pandas())`

**More details**:
  File "(...)\Lib\site-packages\deltalake\table.py", line 442, in to_pandas
    return self.to_pyarrow_table(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "(...)\Lib\site-packages\deltalake\table.py", line 426, in to_pyarrow_table
    ).to_table(columns=columns)
      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow\_dataset.pyx", line 546, in pyarrow._dataset.Dataset.to_table
  File "pyarrow\_dataset.pyx", line 3449, in pyarrow._dataset.Scanner.to_table
  File "pyarrow\error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\_fs.pyx", line 1551, in pyarrow._fs._cb_open_input_file
  File "(...)\Lib\site-packages\deltalake\fs.py", line 22, in open_input_file
    return pa.PythonFile(DeltaFileSystemHandler.open_input_file(self, path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
deltalake.PyDeltaTableError: Object at location C:\Folders\Prefix%20-%20Suffix\deltalake\data\0-8162c431-b69c-4931-8618-75de0202cbc6-0.parquet not found: (...) (os error 2)

**Comment by djouallah** [comment]
same issue here

**Comment by Phil-T1** [comment]
Using 0.10.2, I'm having this same issue where Windows paths cannot be decoded due to their spaceyness.

Writing only succeeds where paths which have no space characters. :(

**Comment by JvdH-NL** [comment]
Using 0.16.4 I am having same issue. Running Python code from a path that contains spaces gives me 'object at location <FILL PATH WITH SPACES that have been replaced with %20 .... parquet file> not found ....
I have some sample data, using code, fails on last statement. And path is on corporate OneDrive containing spaces.
delta_table_path = 'deltaTable/'
dt = DeltaTable(delta_table_path)
# Read Data from Delta table
dt.to_pandas()

**Comment by JvdH-NL** [comment]
Quickstart on Homepage results in error in reading (writing part goes ok), same issue as my previous post.

**Comment by ion-elgreco** [comment]
Is this still an issue with 0.22.3?

**Comment by ABChristian** [comment]
It's working!
Tested using deltalake 0.22.3, Python 3.12.8

**Comment by nealsullivan** [comment]
I am seeing this (again?) using Windows 11, deltalake 0.24.0 and Python 3.12.

If it helps at all - I've got my project in a OneDrive folderpath which has "OneDrive - <OrgName>" as the default name.  

Here's an example from VS Code: 

![Image](https://github.com/user-attachments/assets/654fb8b9-b5d1-4f99-a200-58c0334df749)

**Comment by ABChristian** [comment]
I just re-did the test, and it's working as expected for writing and reading.
What does your complete test look like?

the only thing i saw is, that it's creating an empty folder with %20 instead of spaces, but it seemingly does not interfere with reading/writing or checking.

**Comment by nealsullivan** [comment]
Maybe it's this empty-path-with %20's that's the issue?  with polars i get a FileNotFoundError that points to the %20's location.  Which would make sense if the data is actually written to the non-%20's location.  I'm sorry if this is an id10t / picnic issue... 

![Image](https://github.com/user-attachments/assets/44ad95aa-d81a-46ec-815a-24133f64e0f9)

I came here after digging around the polars read_delta implementation and seeing how it all points back to file_uri's being parsed from delta-rs.

**Comment by ion-elgreco** [comment]
@nealsullivan problem is in polars parquet reader, you should create issue there

**Comment by ABChristian** [comment]
I think the creation of the %20-folder is done by delta-rs, but the failing read seems to be a polars issue.

I opened an issue for that already:
https://github.com/pola-rs/polars/issues/20944

**Comment by nealsullivan** [comment]
Thanks for pointing me to the polars issue, @ABChristian.  I'm going to track that.  

Using the pyarrow options has also been an issue for me where I get a 'Repetition level historgram size mismatch' if and unless the WriterProperties have default_column_perperties setting statistics_enabled to 'NONE'... but that's a whole different/unrelated issue. [https://github.com/apache/arrow/issues/45283](https://github.com/apache/arrow/issues/45283)
