### ISSUE TITLE
Rust writer in operations makes a lot of data copies

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#1394]
# Environment

We keep the Parquet file being written as a `Vec<u8>`. The `write_batch` method seems to clone the vec each time it is called, and the batch size for many operations is quite small, defaulting at 1024 rows. 

https://github.com/delta-io/delta-rs/blob/930d16e583fbd784f5f3d4bb8bcd753e2d6488a6/rust/src/operations/writer.rs#L326-L343

@roeap Do you remember why we do this? I'm wondering whether we can just rip out this error handling, or if we actually do some sort of retry with this.

**Comment by roeap** [comment]
I do remember wondering the same thing (hence the TODO 😆). This just go carried over from previous implementations and I think originated somewhere in kafaka-delta ingest. I guess back then the write API exposed was much lower level - i.e. user would have to use the writer structs directly.

In our codebase here I think we are not retrying anything. Also did a quick dive into what errors we may actually see there, and I think we either have an IO issue (where we do retry in object store) or somehow malformed data (did not go too deep into the parquet crate). So my vote would be for ripping it out.

**Comment by wjones127** [comment]
Okay. I'm going to refactor that module now.

**Comment by roeap** [comment]
I just opened #1396, which may be relevant in that context, as it also affects the write path.
