### ISSUE TITLE
np.inf values not properly handled when reading deltalake

### ISSUE THREAD

**Issue by noselasd** [delta-io/delta-rs#1411]
# Environment

**Delta-rs version**:
0.9.0 

(Or whichever is bundled with the python 0.9.0 package, latest at pypi.org at this time)

**Binding**: 
Python

**Environment**:
- **OS**:
Linux

***
# Bug
Dataframes containing numpy infinite (np.inf) values doesn't seem to be handled properly.

This small example fails when reading back the deltatable.
```
import pandas as pd
import deltalake
import numpy as np

data = {
        "day": ['2021.01.02', '2021.01.02','2021.01.04'],
        "hour": [1,2,10],
        "data": [1.1,2.2,np.inf]
      }
df = pd.DataFrame(data)
deltalake.write_deltalake('/tmp/test_deltalake', df, partition_by=['day', 'hour'])
new_df = deltalake.DeltaTable('/tmp/test_deltalake').to_pandas()
```

`deltalake.DeltaTable('/tmp/test_deltalake').to_pandas()` results in 
```


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.virtualenvs/pandas/lib/python3.11/site-packages/deltalake/table.py", line 442, in to_pandas
    return self.to_pyarrow_table(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.virtualenvs/pandas/lib/python3.11/site-packages/deltalake/table.py", line 424, in to_pyarrow_table
    return self.to_pyarrow_dataset(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.virtualenvs/pandas/lib/python3.11/site-packages/deltalake/table.py", line 392, in to_pyarrow_dataset
    for file, part_expression in self._table.dataset_partitions(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
deltalake.PyDeltaTableError: Invalid JSON in file stats: expected value at line 1 column 89
```

The `/tmp/test_deltalake/_delta_log/00000000000000000000.json` file looks like this:
```

{"protocol":{"minReaderVersion":1,"minWriterVersion":1}}
{"metaData":{"id":"5dad15c5-ccc2-401d-8105-be2fb8d681ed","name":null,"description":null,"format":{"provider":"parquet","options":{}},"schemaString":"{\"type\":\"struct\",\"fields\":[{\"name\":\"day\",\"type\":\"string\",\"nullable\":true,\"metadata\":{}},{\"name\":\"hour\",\"type\":\"long\",\"nullable\":true,\"metadata\":{}},{\"name\":\"data\",\"type\":\"double\",\"nullable\":true,\"metadata\":{}}]}","partitionColumns":["day","hour"],"createdTime":1685452194506,"configuration":{}}}
{"add":{"path":"day=2021.01.02/hour=2/0-45a1ddd8-e6c5-4f09-bfa6-479668a5f37e-0.parquet","size":2158,"partitionValues":{"day":"2021.01.02","hour":"2"},"modificationTime":1685452194499,"dataChange":true,"stats":"{\"numRecords\": 1, \"minValues\": {\"data\": 2.2}, \"maxValues\": {\"data\": 2.2}, \"nullCount\": {\"data\": 0}}","tags":null}}
{"add":{"path":"day=2021.01.04/hour=10/0-45a1ddd8-e6c5-4f09-bfa6-479668a5f37e-0.parquet","size":2158,"partitionValues":{"day":"2021.01.04","hour":"10"},"modificationTime":1685452194501,"dataChange":true,"stats":"{\"numRecords\": 1, \"minValues\": {\"data\": 1.7976931348623157e+308}, \"maxValues\": {\"data\": Infinity}, \"nullCount\": {\"data\": 0}}","tags":null}}
{"add":{"path":"day=2021.01.02/hour=1/0-45a1ddd8-e6c5-4f09-bfa6-479668a5f37e-0.parquet","size":2158,"partitionValues":{"hour":"1","day":"2021.01.02"},"modificationTime":1685452194503,"dataChange":true,"stats":"{\"numRecords\": 1, \"minValues\": {\"data\": 1.1}, \"maxValues\": {\"data\": 1.1}, \"nullCount\": {\"data\": 0}}","tags":null}}
{"commitInfo":{"timestamp":1685452194506,"operation":"CREATE TABLE","operationParameters":{"mode":"ErrorIfExists","metadata":"{\"configuration\":{},\"created_time\":1685452194506,\"description\":null,\"format\":{\"options\":{},\"provider\":\"parquet\"},\"id\":\"5dad15c5-ccc2-401d-8105-be2fb8d681ed\",\"name\":null,\"partition_columns\":[\"day\",\"hour\"],\"schema\":{\"fields\":[{\"metadata\":{},\"name\":\"day\",\"nullable\":true,\"type\":\"string\"},{\"metadata\":{},\"name\":\"hour\",\"nullable\":true,\"type\":\"long\"},{\"metadata\":{},\"name\":\"data\",\"nullable\":true,\"type\":\"double\"}],\"type\":\"struct\"}}","protocol":"{\"minReaderVersion\":1,\"minWriterVersion\":1}","location":"file:///tmp/test_deltalake"},"clientVersion":"delta-rs.0.10.0"}}

```

**Comment by cnogradi** [comment]
Just ran into this issue as well. Would love to see it fixed.

**Comment by kangshung** [comment]
I have the same issue. Pandas treats and writes `np.Inf` values as Double type into Parquet, whereas deltalake does not.
Numpy docs: https://numpy.org/doc/stable/reference/constants.html

Could we get it implemented soon? Probably similar issues happen to other constants as well. @ion-elgreco

**Comment by wjones127** [comment]
Infinity is a valid float, but it’s not a valid JSON value. We can simply not write the stat if the value if positive or negative infinity.

**Comment by noselasd** [comment]
> Infinity is a valid float, but it’s not a valid JSON value. We can simply not write the stat if the value if positive or negative infinity.

Today it is written to the json, resulting in an invalid json file in delta_log. and the deltatable is more or less broken.  When the value is read back when the deltatable is opened later on, opening the deltatable ,unsurprisingly due to invalid json, fails.

Is it possible to detect this on the write path and fail there ? It's somewhat fragile to be able to write a dataframe and break the whole delta table.

**Comment by wjones127** [comment]
> Is it possible to detect this on the write path and fail there ?

We don't need to fail, just need to omit the statistics if they are +/- Infinity. That would avoid the error in reading. And it's semantically the same, since no min/max means no lower/upper bound, which is kind of the same as saying the lower/upper bound are negative/positive infinity, right?

**Comment by cnogradi** [comment]
In order to get around this issue a few months ago, we implemented this:

import deltalake.writer as writer
old_get_file_stats_from_metadata = writer.get_file_stats_from_metadata

def new_get_file_stats_from_metadata(metadata: Any, ) -> Dict[str, Union[int, Dict[str, Any]]]:
    stats = old_get_file_stats_from_metadata(metadata)
    # replace all instances of inf with 0
    stats['maxValues']={ key: (value if value != float('inf') else 0) for key, value in stats['maxValues'].items()}
    return stats

# Monkey patch the broken code which writes a inf type which cannot be read back
writer.get_file_stats_from_metadata = new_get_file_stats_from_metadata

**Comment by wjones127** [comment]
> # replace all instances of inf with 0
> stats['maxValues']={ key: (value if value != float('inf') else 0) for key, value in 
 stats['maxValues'].items()}

Do you not have positive numbers in your data? 🤔  I wouldn't recommend blindly inserting zeros into the max value statistics.

**Comment by cnogradi** [comment]
> > # replace all instances of inf with 0
> > stats['maxValues']={ key: (value if value != float('inf') else 0) for key, value in
> > stats['maxValues'].items()}
> 
> Do you not have positive numbers in your data? 🤔 I wouldn't recommend blindly inserting zeros into the max value statistics.

For my purposes, this works. (simply reading and writing using the python API).  But I am curious what the stats are used for that might be affected?  I am honestly ignorant here.

**Comment by wjones127** [comment]
> But I am curious what the stats are used for that might be affected? I am honestly ignorant here.

Statistics are used in "data skipping". If you have a file where the max for column `x` is 0, and you are scanning with the filter `x > 1`, then we will skip that file. So the danger in having incorrect statistics is your query results can be missing rows if you are passing a filter.
