### ISSUE TITLE
Support delete operation in Python

### ISSUE THREAD

**Issue by Matthieusalor** [delta-io/delta-rs#1417]
# Description
The delete operation has been implemented in rust (#832) . It would be nice to support it as well in python. 
Unless I'm mistaken I haven't seen any work on that yet. 

I'd be happy to start working on the feature, as it would be my first contribution I'd probably need support along the way.

**Use Case**

**Related Issue(s)**

**Comment by roeap** [comment]
We are always happy to provide guidance and support along the way! So feel free to go ahead!

**Comment by Matthieusalor** [comment]
Thanks. To open up the discussion with anyone interested: 
I started working on it, I would have loved to use pyarrow expressions as the predicate, however these python objects seems to be just empty shells preventing us to extract anything out of them outside of the c code. 
The way I approached it to start with is I wrote a function with the following signature:
```rust
 fn py_dnf_to_expr(dnf: Vec<Vec<(&str, &str, &PyAny)>>) -> datafusion_expr::Expr{
 ```
 Which in the process transform the &PyAny to a datafusion_common::scalar::ScalarValue. 
 The goal then will be to use the generated expression and pass it directly to the DeleteBuilder.

**Comment by Matthieusalor** [comment]
I have drafted a working version for the feature for which I've had to remove `abi3` and `abi3-py37` from the pyo3 features (https://github.com/delta-io/delta-rs/blob/main/python/Cargo.toml#L39). The reason is https://github.com/PyO3/pyo3/blob/65312b43b215ee215a018ba657880bdb0c5dcba5/src/types/mod.rs#L11 where `PyDate`, `PyDateTime` ... are configured with `#[cfg(not(Py_LIMITED_API))]` meaning they do not get imported when the abi3 features are enabled. A typical use case would be to use the following predicate 
```python
delta_table.delete(
    [("value_date", "<", date(2023, 1,1))]
)
```
Where the date object would be catch as a PyDate in the underlying rust library which is the reason why I need to get them imported. 
Maybe I'm missing something here and would appreciate if anyone can advise.

- Is it safe to remove these features ? 
- Would someone know a workaround ?

**Comment by wjones127** [comment]
> Is it safe to remove these features ?

No, if we remove these features we need to change how we package Python wheels. Right now we just create one wheel per platform at the minimum Python version. The limited API guarantees that all subsequent versions will be ABI-compatible. If we disabled the limited API, then we need to instead build a wheel for every Python version. Not sure if we want to do that at this time.

As a workaround, are you able to use the date types as normal Python types in Rust? For example, with date you just need to access the year, month, and day attributes, extract them at integers, and then you can parse them into a date in Rust (or whatever target structure you are working towards). If you upload a draft PR I can take a look at the code and make suggestions.

**Comment by guilhem-dvr** [comment]
Hi @Matthieusalor, are you still working on this feature or would you be willing to push your draft?

I'd be happy to work on it, but since you said you did most of the work I'd rather ask before starting working on it.
