### ISSUE TITLE
Slack Invite Link No Longer Valid

### ISSUE THREAD

**Issue by adam133** [delta-io/delta-rs#1425]
Hopefully a quick fix - the Slack invite in the readme is no longer valid - 
https://github.com/delta-io/delta-rs/blob/75a6e94928cc87ca23919e1acb8e050ae987eba5/README.adoc?plain=1#L82

**Comment by roeap** [comment]
cc @dennyglee @MrPowers

**Comment by dennyglee** [comment]
Thanks - let me work on that now.  In the interim, please use https://go.delta.io/slack.  Thanks!

**Comment by dennyglee** [comment]
Just created #1426  - @roeap any chance you can review?

**Comment by dennyglee** [comment]
Thanks @adam133 - #1426 has been merged so will close this issue.  Feel free to re-open if this is incorrect.  Thanks!
