### ISSUE TITLE
to_pyarrow_table() should use full schema provided by delta table

### ISSUE THREAD

**Issue by lucienfregosi** [delta-io/delta-rs#144]
Hi 

First of all thanks for your work on delta RS this package is super useful for our work and our team led by @fvaleye 👍 

We have an issue using the function `to_pyarrow_table()`

`DeltaTable(table_path).to_pyarrow_table()` returns the dataset but with an incomplete schema, we miss one column which is definitely in one ouf our parquet files.

Using `DeltaTable(table_path).schema()` we got the complete schema including the missing column.

Thanks in advance

**Comment by houqp** [comment]
How are you getting the schema using `DeltaTable(table_path).to_pyarrow_table()`? Are you using the builtin pyarrow schema method? If so, it infers the schema from parquet data, which is not guaranteed to be the same as the schema defined for the delta table through the transaction log. Could you double check those parquet files to see if that particular column exists and contains valid data?

**Comment by lucienfregosi** [comment]
I'm getting the schema with simply printing the pyarrow table `print(DeltaTable(table_path).to_pyarrow_table())`
This print displays the schema (without the new column)

I have double-checked with downloading my parquet file in S3 and inspecting it with parquet tools and the missing column is definitely there and the data seems valid.

**Comment by houqp** [comment]
that's interesting, @lucienfregosi could you try loading that single parquet file with pyarrow and print the loaded pyarrow table to see if that particular column shows up in the output?

**Comment by lucienfregosi** [comment]
I tried in 2 distinct way to load the single parquet files
`pandas.read_parquet('<file_path>.parquet', engine='pyarrow')`
`pyarrow.parquet.ParquetFile("<file_path>.parquet")`

And I always retrieve the missing column when I print the data with pyarrow !

**Comment by houqp** [comment]
So perhaps this is a bug in pyarrow dataset module, which is what we used in our python binding: https://github.com/delta-io/delta-rs/blob/main/python/deltalake/table.py#L42.

Can you give the following a try to verify it?

```python
d = pyarrow.dataset.dataset(['<file_path>.parquet'], format="parquet")
print(d.to_table())
```

**Comment by lucienfregosi** [comment]
Same result I got the column with pyarrow dataset as expected 

Just to give as context as I can 
We have multiple files in S3 like
- year=2021/month=3/day=2/parquet1.parquet
- year=2021/month=3/day=3/parquet2.parquet
- year=2021/month=3/day=4/parquet3.parquet
- year=2021/month=3/day=5/parquet4.parquet => the new columns is here parquet4.parquet

And then read the delta table for retrieve the data
`dataset = DeltaTable(table_path).to_pyarrow_table()`
`print(dataset)` => the new columns does not show up

**Comment by houqp** [comment]
Perhaps the dataset module only uses the first parquet file from the list to infer the schema. Could you give the following code a try?

```python
d = pyarrow.dataset.dataset([
    "year=2021/month=3/day=2/parquet1.parquet",
    "year=2021/month=3/day=5/parquet4.parquet",
], format="parquet")
print(d.to_table())
```

**Comment by lucienfregosi** [comment]
Indeed 
When this code snippet I don't have the column.
It seems that the dataset module only uses the first parquet for inferring the schema

**Comment by lucienfregosi** [comment]
And with this code 
`d = ds.dataset([
    "parquet4.parquet",
    "parque1.parquet",
], format="parquet")
print(d.schema)`

it shows the missing column as pyarrow seems to use the first parquet for the schema

**Comment by houqp** [comment]
Nice, worth filing an upstream bug issue for this I think.

I think for delta table specifically, we can do better here. Since we now have the delta table schema method (thanks to @fvaleye ), we can manually override the schema using the one defined in the delta table when creating the pyarrow dataset instead of letting pyarrow doing the schema inference.

**Comment by houqp** [comment]
@lucienfregosi looks like pyarrow's dataset constructor does take the schema argument: https://arrow.apache.org/docs/python/generated/pyarrow.dataset.dataset.html#pyarrow.dataset.dataset. Could you try passing in the delta table schema into the constructor within the `to_pyarrow_table` method when constructing the dataset?
