### ISSUE TITLE
fix(python): make sure we always write microsecond precision timestamps

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#1467]
# Description

Right now I think we are be accident. But PyArrow will change default to nanoseconds so we should specify this.

See: https://github.com/apache/arrow/issues/35746

**Use Case**

**Related Issue(s)**

**Comment by anjakefala** [comment]
The goal is to get https://github.com/apache/arrow/issues/35746 merged in by 13.0.0!

**Comment by ion-elgreco** [comment]
@wjones127 I can give this a go, should be straightforward and similar to the delta_arrow_schema_from_pandas logic, right?

**Comment by ion-elgreco** [comment]
@wjones127 I was thinking this could work: https://github.com/delta-io/delta-rs/compare/main...ion-elgreco:delta-rs:fix/cast-timestamp-always-to-us-precision

But after checking the PyArrow docs and testing what a RecordBatchReader does, it apparently doesn't cast the schema when you pass a different one. It will throw an error that the schema that is passed is not the same as the one that was expected, so it only works on pa.Table.. 

Do you have any idea how you can cast/read a recordBatch to a new schema?

Also, one thing that won't be caught are all the fields or structs that contain nested date-times with different precision. This may possibly be the case for the method where the precision is fixed for pd.DataFrame.
