### ISSUE TITLE
Add support for more authentication schemas for Azure

### ISSUE THREAD

**Issue by boufleur** [delta-io/delta-rs#149]
Currently the only way to authenticate against Azure is by providing accountname and/or key/sas token. For ADLS Gen2 with ACL enabled data lakes, we need also to authenticate by supplying service principals (Azure AD).
A good way of working would be to set env variables as follow:
* AZURE_STORAGE_AUTH_TYPE
* AZURE_STORAGE_SPN_CLIENT_ID
* AZURE_STORAGE_SPN_TENANT_ID
* AZURE_STORAGE_SPN_CLIENT_SECRET

**Comment by mattc-eostar** [comment]
Could be a good idea to allow authentication through environment variables OR a filesystem object

https://arrow.apache.org/docs/python/filesystems.html#using-fsspec-compatible-filesystems
```python
# creating an fsspec-based filesystem object for Google Cloud Storage (could be S3 or Azure Blob/DL)
import gcsfs
fs = gcsfs.GCSFileSystem(project='my-google-project')

# using this to read a partitioned dataset
import pyarrow.dataset as ds
ds.dataset("data/", filesystem=fs)
```

FSSPEC for Azure: https://github.com/dask/adlfs
```python
fs = adlfs.AzureBlobFileSystem(
  account_name = storage_account_name,
  account_key = storage_account_access_key
)
```
Notes from Readme
```
The filesystem can be instantiated with a variety of credentials, including:
    account_name
    account_key
    sas_token
    connection_string
    or Azure ServicePrincipal credentials (tenant_id, client_id, client_secret)

The following enviornmental variables can also be set and picked up for authentication:
    "AZURE_STORAGE_CONNECTION_STRING"
    "AZURE_STORAGE_ACCOUNT_NAME"
    "AZURE_STORAGE_ACCOUNT_KEY"
    "AZURE_STORAGE_SAS_TOKEN"
    "AZURE_STORAGE_CLIENT_SECRET"
    "AZURE_STORAGE_CLIENT_ID"
    "AZURE_STORAGE_TENANT_ID"
```

**Comment by GBBBAS** [comment]
It would be great to also provide Service Principal authentication with certificates. Secrets are not always an accepted method for  authenticating Service Principals in certain organisations and technologies

**Comment by drahnreb** [comment]
The filesystem object method proposed by @mattc-eostar should be the preferred method.
This is a common practice and would enable @GBBBAS remark.

Maybe the [unofficial Rust SDK](https://github.com/Azure/azure-sdk-for-rust/blob/master/sdk/identity/examples/client_credentials_flow_blob.rs) could be implemented and made available for python etc.?

**Comment by nfx** [comment]
I might eventually look at it. There's also Azure CLI authentication, that is missing here in the list and Managed Service Identity (equivalent of EC2 Instance Profiles).
