### ISSUE TITLE
Expose Update & Delete operations from Rust into Python

### ISSUE THREAD

**Issue by ion-elgreco** [delta-io/delta-rs#1505]
# Description
Since the Update, Delete operations have been developed in Rust, would be nice to expose them also in Python.

**Comment by loleek** [comment]
Delete python binding may in progress. https://github.com/delta-io/delta-rs/issues/1417
I can file the Update part.

**Comment by ion-elgreco** [comment]
@loleek are you still planning to do the Update part? Otherwise, I can pick it up.

**Comment by loleek** [comment]
@ion-elgreco No, I'm too busy to work on this.  Pick it up, thanks.
