### ISSUE TITLE
get_add_actions() MAX is not showing complete value

### ISSUE THREAD

**Issue by Merlyn661992** [delta-io/delta-rs#1534]
# Environment

**Delta-rs version**: 0.10.0

**Binding**: 

**Environment**:
- **Cloud provider**:
- **OS**:
- **Other**:

***
# Bug

**What happened**:
get_add_actions() MAX is not showing complete value
**What you expected to happen**:
MAX to show complete max value for the column but it limits to only max 30-40 characters
**How to reproduce it**:
item = dt.get_add_actions().to_pydict()['max']
        for k in item:
                print(['columnName'])
**More details**:
each of this rows contains atleast 5000 characters but its restricted to only 30-40 characters, hence not able to find max length of column using get_add_actions
![image](https://github.com/delta-io/delta-rs/assets/139494566/e2123dd1-d129-4dcf-adba-4330b31da77b)

**Comment by wjones127** [comment]
Hello. String statistics are truncated intentionally. You should not use these statistics to find the max. If you read the [Delta Protocol](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#per-file-statistics) on statistics, you'll notice there is a [footnote](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#user-content-fn-1-31370884e12ee2d85da4c03815e4e644):

> String columns are cut off at a fixed prefix length.
