### ISSUE TITLE
Adding version number to .history()

### ISSUE THREAD

**Issue by jakubkovac** [delta-io/delta-rs#1561]
# It would be helpful to have version number alongside each entry in the .history() method

**Use Case**
similarly to delta.DeltaTable.forPath(...).history() that returns a sparkDataFrame with version number, it would be useful to have this directly in the history method.

Currently I'm using the spark history to detect the specific version number corresponding to a datetime, since version is the only argument with polars.read_delta.

If I understood delta correctly, history might not have the complete history of versions, because of retention period - but available history is probably coming from the logs in the _delta_log folder right?

Is there a better way to get version numbers and their corresponding timestamp through deltalake library?

**Comment by Hanspagh** [comment]
I am facing the same issue

**Comment by ion-elgreco** [comment]
Looks pretty straightforward, I could look into it soon.
