### ISSUE TITLE
Path to reader version 3, writer version 7 transaction log protocol support

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#1568]
# Description

Delta Lake transitioned to [table features](https://delta.io/blog/2023-07-27-delta-lake-table-features/) and now has a better upgrade path for connectors.

delta-rs can upgrade to protocol version 3,7 (skipping the intermediate protocol versions) and then cherry pick the table features that will be supported.

Adding table feature support may also make it safer when reading Delta tables with delta-rs.  Does delta-rs gracefully error out when reading a table with table features that are enabled that delta-rs does not currently support?

The purpose of this issue is to organize the remaining work that's needed to get protocol version 3,7 support.  Seems like delta-rs is close.

**Comment by wjones127** [comment]
> Does delta-rs gracefully error out when reading a table with table features that are enabled that delta-rs does not currently support?

This should happen right now, so if anyone is getting incorrect data back from delta-rs, we should consider that a bug.

**Comment by MrPowers** [comment]
Once [this](https://github.com/delta-io/delta-rs/pull/1807) is merged, we should have full support for append only tables.

**Comment by roeap** [comment]
> does that mean the rust writer automatically checks it?

This check is done in the `commit` function, since we are also committing actions to the protocol via that function it should cover all code paths...

**Comment by hntd187** [comment]
Okay so I have to check the write paths are respected for invariants and fix that if necessary to ensure we have invariant support throughout. Then once that is done I'll start implementing check constraints.

**Comment by MrPowers** [comment]
@hntd187 - can we claim reader version 3, writer version 7 transaction log protocol support now?

**Comment by hntd187** [comment]
I believe what I signed up to do is done and dusted, so barring any other support we need to support it, I believe so.
