### ISSUE TITLE
Unable to `cargo update` using git tag or rev on Rust 1.70

### ISSUE THREAD

**Issue by cmackenzie1** [delta-io/delta-rs#1580]
# Environment

**Delta-rs version**: 0.14

**Binding**: rust

**Environment**:
- **Cloud provider**:
- **OS**:
- **Other**:

***
# Bug

**What happened**:

`cargo update` fails to find `deltalake` when using `git` to specify cargo dependency. 

**What you expected to happen**:

`cargo update` to succeed

**How to reproduce it**:

```toml
# Cargo.toml
[dependencies]
deltalake = { git = "https://github.com/delta-io/delta-rs.git", tag = "rust-v0.14.0", features = [
    "s3",
    "parquet",
    "arrow",
    "datafusion",
] }
```

```bash
$ rustup install 1.70.0
$ cargo +1.70.0 update
    Updating crates.io index
    Updating git repository `https://github.com/delta-io/delta-rs.git`
error: no matching package named `deltalake` found
location searched: https://github.com/delta-io/delta-rs.git?tag=rust-v0.14.0
```

```bash
$ rustup install 1.71.0
$ cargo +1.71.0 update
    Updating crates.io index
    Updating git repository `https://github.com/delta-io/delta-rs.git`
```

**More details**:

Using `crates.io` format `deltalake = { version = "0.14.0" }` works fine. 

Could potentially be related to #1572 ? There were some cargo workspace related changes in `cargo`, https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-171-2023-07-13

**Comment by cmackenzie1** [comment]
Fails for `1.69.0` as well.

```bash
$ rustup install 1.69.0
$ cargo +1.69.0 update
    Updating crates.io index
remote: Enumerating objects: 160156, done.
remote: Counting objects: 100% (19115/19115), done.
remote: Compressing objects: 100% (398/398), done.
remote: Total 160156 (delta 18721), reused 19075 (delta 18694), pack-reused 141041
Receiving objects: 100% (160156/160156), 104.91 MiB | 4.62 MiB/s, done.
Resolving deltas: 100% (116010/116010), completed with 2288 local objects.
From https://github.com/rust-lang/crates.io-index
 + c840c3f7c3...59bdc2e853            -> origin/HEAD  (forced update)
    Updating git repository `https://github.com/delta-io/delta-rs.git`
error: no matching package named `deltalake` found
location searched: https://github.com/delta-io/delta-rs.git?tag=rust-v0.14.0
```

**Comment by cmackenzie1** [comment]
Works OK for rust `1.70` and git tag `rust-v0.13.0`. Looks more and more likely its due to the workspace changes :(

**Comment by rtyler** [comment]
Does this fail in the same way when you use a branch rather than the tag reference?

**Comment by cmackenzie1** [comment]
Yeah, I tried pointing it at my fork but got the same result. It seems any git style pointer fails rust<=1.70 for v0.14

**Comment by rtyler** [comment]
According to one of the fine folks over the in the `cargo` project, this is more likely to be the addition of the `line-tables-only` option, which I'm hopeful we can make apply only on newer Cargo versions

**Comment by rtyler** [comment]
Going to close t his out, it's kinda annoying but we should encourage people to use newer cargoes since the upstream issue (in cargo somewhere) is not likely going to be fixed soon
