### ISSUE TITLE
Z Order can't find column with a capitalised character

### ISSUE THREAD

**Issue by mrfuxi** [delta-io/delta-rs#1586]
# Environment

**Delta-rs version**: 0.10.1

**Binding**: `python`

**Environment**:
- **Cloud provider**: `local`
- **OS**: `Linux Fedora fc38`
- **Other**: `Python 3.8`, `pyarrow==12.0.1`, `arrow==1.2.3`

***
# Bug

**What happened**:
Running z order on table that has columns containing cap case causes exception

Error
```
Traceback (most recent call last):
  File "./case.py", line 16, in <module>
    main()
  File "./case.py", line 12, in main
    dt.optimize.z_order(columns=["col_a"])
  File "/.../python3.8/site-packages/deltalake/table.py", line 694, in z_order
    metrics = self.table._table.z_order_optimize(
_internal.DeltaError: Generic DeltaTable error: Schema error: No field named col_b. Valid fields are "?table?".col_a, "?table?"."col_B", __zorder_key.
```

**What you expected to happen**:
Z order to finish the work

**How to reproduce it**:
```python
from deltalake import write_deltalake, DeltaTable
import pandas as pd


def main():
    path = "./test_caps"

    df = pd.DataFrame({"col_a": [1, 2, 3], "col_B": ["a", "b", "c"]})
    write_deltalake(path, df, mode="overwrite")

    dt = DeltaTable(path)
    dt.optimize.z_order(columns=["col_a"])


if __name__ == "__main__":
    main()
```

**More details**:

**Comment by wjones127** [comment]
I suspect this boils down to DataFusion not being case sensitive. Will need more investigation though.

**Comment by watfordkcf** [comment]
Are columns being quoted somehow? I know I've had issues with quoted columns being case sensitive in datafusion.

**Comment by Trebla2010** [comment]
I'm having issues with z_order as well.
dt.schema()
Schema([Field(FieldA, PrimitiveType("string"), nullable=True), Field(FieldB, PrimitiveType("string"), nullable=True), Field(Value, PrimitiveType("decimal(12,4)"), nullable=True), Field(Date, PrimitiveType("date"), nullable=True))

---------------------------------------------------------------------------
DeltaError                                Traceback (most recent call last)
Cell In[144], line 1
----> 1 dt.optimize.z_order(["Date"])
DeltaError: Generic DeltaTable error: Schema error: No field named date. Valid fields are "?table?"."FieldA", "?table?"."FieldB", "?table?"."Value", "?table?"."Date".

**Comment by sachin-snt** [comment]
@wjones127 We are also seeing the same issue but will Updating the delta table

**Comment by shumaev99** [comment]
> @wjones127 We are also seeing the same issue but while Updating the delta table

Same here.

**Comment by djouallah** [comment]
same here :(
