### ISSUE TITLE
Delta-rs Write with Ray DataSet 

### ISSUE THREAD

**Issue by raviranak** [delta-io/delta-rs#1593]
# Description
Currently delta-rs write takes pyarrow.Table, BatchRecord and pandas . ray dataset is a distributed dataset with underlying record is ObjectRef of pa.Table 

**Use Case**
Ability to Write from ray dataset directly to delta lake 

I have added my changes in fork repo 
https://github.com/raviranak/delta-rs

**Comment by raviranak** [comment]
I would like to raise PR for this , please let me know how to be the contributor for this repo

**Comment by roeap** [comment]
Hi @raviranak - we would be happy to review a PR, since you seem to have a working solution already :)

**Comment by raviranak** [comment]
Hi @roeap , PR link https://github.com/delta-io/delta-rs/pull/1679

**Comment by MrPowers** [comment]
Do you think this should go in the deltaray project? https://github.com/delta-incubator/deltaray

**Comment by ion-elgreco** [comment]
This should live upstream indeed
