### ISSUE TITLE
Remove rusoto in favor of the official AWS SDK for Rust

### ISSUE THREAD

**Issue by rtyler** [delta-io/delta-rs#1601]
# Description

[Rusoto has been in maintenance mode](https://github.com/rusoto/rusoto#maintenance-status) for the last 2.5 years. In the mean time the official [AWS SDK for Rust is in developer preview](https://aws.amazon.com/sdk-for-rust/) and I would guess that they'll call it "GA" at re:invent this year.

Either way developer preview is better than "not really maintained".

This issue is to track the migration away from rusoto.

**Use Case**

**Related Issue(s)**

**Comment by tustvold** [comment]
FWIW object_store now exposes a request authoriser, if you wanted to keep dependencies down, and aren't using an extensive number of APIs - https://docs.rs/object_store/latest/object_store/aws/struct.AwsAuthorizer.html
