### ISSUE TITLE
Standardize Databricks environment variable names

### ISSUE THREAD

**Issue by MigQ2** [delta-io/delta-rs#1627]
# Description

In the [documentation](https://delta-io.github.io/delta-rs/python/usage.html#loading-a-delta-table) I can see that in order to authenticate to Databricks Unity Catalog I need to use environment variables `DATABRICKS_WORKSPACE_URL` and `DATABRICKS_ACCESS_TOKEN`

However, Databricks has worked recently to standardize the environment variables that hold this information with different names, they use `DATABRICKS_HOST` and `DATABRICKS_TOKEN` as stated in [section 2.e. of this documentation](https://learn.microsoft.com/en-us/azure/databricks/dev-tools/databricks-connect-ref#--step-2-configure-connection-properties)

It would be great to Unify environment variable names that `deltalake` used with the ones Databricks uses so that users don't have to maintain 2 different sets of environment variables

**Comment by rtyler** [comment]
This is a good idea, I've tagged it as a good first issue in case somebody wants to grab it, otherwise I think I'll knock it out next week ahead of the next crate release

**Comment by nfx** [comment]
@rtyler implementer of Unified Auth for Databricks Connect (and other SDKs for Databricks) here =) there's more than DATABRICKS_HOST and DATABRICKS_TOKEN environment variables, we have a full set of SDK OAuth compliance behaviors to verify. We have plans to get compliant auth experience for Rust by releasing something in Databricks Labs, no timeline promises for that yet. 

I'd suggest moving this issue to v0.18 milestone and I'll see if we can accelerate the release of that thing in Labs :)

**Comment by rtyler** [comment]
@nfx I'll gladly assign this to you :laughing:  Let me know how I can help!

**Comment by rtyler** [comment]
@nfx I am thinking of queueing up a 0.16 later this week(end) or early next week. Do you think you'd have a chance to fix up some env variables before then? If not I can take this issue back and plonk some changes into a pull request
