### ISSUE TITLE
Support minio and other S3 API compatible services

### ISSUE THREAD

**Issue by houqp** [delta-io/delta-rs#163]
# Description

To support S3 compatible services like minio, we need to provide a way for users to specify custom endpoint url through environment variables or other means.

https://docs.rs/rusoto_core/0.46.0/rusoto_core/enum.Region.html#aws-compatible-services has the example on how this can be done by setting a custom region object when initiating the S3 client.

https://github.com/delta-io/delta-rs/blob/main/rust/src/storage/s3.rs#L146 is where we create the region object in delta-rs, so we just need to change the code to detect the endpoint url override there.

**Comment by kesavkolla** [comment]
Can we get a new Python release with this fix?

**Comment by fvaleye** [comment]
Hello @kesavkolla,

The new release of the Python bindings `0.4.5` will include this fix!
