### ISSUE TITLE
performance regression in 0.10.2

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#1632]
# Environment

0.10.2

Python

**Environment**:
Cloudflare R2

***
# Bug

sorry the bug report is not very helpful, but I notice when I updated to the latest 10.2, the performance has degraded considerably, I am using Google Cloud functions to write to Cloudflare R2, I had to go back to 10.1

![image](https://github.com/delta-io/delta-rs/assets/12554469/aa859398-f947-4ad3-b888-7b4b31f7a28d)

**Comment by djouallah** [comment]
same with writing to Azure, using Fabric notebook, the resource usage just increased significantly ?
![image](https://github.com/delta-io/delta-rs/assets/12554469/2019f20a-ac6e-4bda-8a1c-41cab0ba3831)

**Comment by rtyler** [comment]
Do you happen to have an example of some write code you can share? There are a few reasons I can imagine this changing.

What would also be helpful would be the pyarrow version being used (and/or pandas version)

**Comment by djouallah** [comment]
here is the code, I am not sure how to get the pandas version, I just run this code in google cloud functions

https://github.com/djouallah/aemo_tracker/blob/main/writedelta.py

**Comment by ion-elgreco** [comment]
@djouallah can you check against v0.13 if you still see performance issues?
