### ISSUE TITLE
Slack community invite link has expired

### ISSUE THREAD

**Issue by BnMcG** [delta-io/delta-rs#1636]
# Bug

**What happened**: Slack invite link on the delta-rs README and delta.io website (https://go.delta.io/slack -> https://delta-users.slack.com/join/shared_invite/zt-21t89s35s-08fmjWsmhUOcCaUdS0MN5Q#/shared-invite/) has expired, it's not possible to join the Slack group.

**What you expected to happen**: To be able to register on Slack

**How to reproduce it**: Click the link 🙂 

**More details**: N/A

**Comment by wjones127** [comment]
https://join.slack.com/t/delta-users/shared_invite/zt-23h0xwez7-wDTm43ZVEW2ZcbKn6Bc8Fg
