### ISSUE TITLE
Make table protocol version / table features easily accessible

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#1657]
# Description

There is a `deltalake.table.ProtocolVersion` interface [here](https://delta-io.github.io/delta-rs/python/api_reference.html?highlight=protocol#deltalake.table.ProtocolVersions), but I don't fully understand it.  I guess this is for changing the protocol versions of a table?

Is there a way to fetch the reader_version & writer_version for a table?

Is there a way to fetch all the table features that are enabled for a table?

**Comment by wjones127** [comment]
That's the return value of the `DeltaTable.protocol()` method. 

https://github.com/delta-io/delta-rs/blob/7d2bb27b4edee838fec70f43008a76c70e9b00d4/python/deltalake/table.py#L413

For some reason this method isn't documented.

**Comment by wjones127** [comment]
Oh it's probably just because it doesn't have a docstring. Anyone want to make a PR to add one?

**Comment by MrPowers** [comment]
@wjones127 - getting this documented would be awesome!

What do you think about another `table_features` method that returns the table features that are enabled for a table?  If the `protocol()` method returns 3,7, then the user still won't know what table features are enabled.

**Comment by wjones127** [comment]
> What do you think about another table_features method that returns the table features that are enabled for a table? If the protocol() method returns 3,7, then the user still won't know what table features are enabled.

Perhaps this could be another field on `ProtocolVersions`, since it is part of the versioning info? Something like:

```python
class ProtocolVersions(NamedTuple):
    min_reader_version: int
    min_writer_version: int
    table_features: List[str]
```

**Comment by ion-elgreco** [comment]
> > What do you think about another table_features method that returns the table features that are enabled for a table? If the protocol() method returns 3,7, then the user still won't know what table features are enabled.
> 
> Perhaps this could be another field on `ProtocolVersions`, since it is part of the versioning info? Something like:
> 
> ```python
> class ProtocolVersions(NamedTuple):
>     min_reader_version: int
>     min_writer_version: int
>     table_features: List[str]
> ```

Currently we can access them I saw, with dt.metadata().configuration

**Comment by Jan-Schweizer** [comment]
I'd like to try myself on this issue.
The task is to extend the `pub struct Protocol` [here](https://github.com/delta-io/delta-rs/blob/3c34b9e4cfaabcadef18dbd40c741b3e8ff18977/rust/src/protocol/mod.rs#L636) like so:

```Rust
pub struct Protocol {
    pub min_reader_version: i32,
    pub min_writer_version: i32,
    pub reader_features: Option<Vec<String>>,
    pub writer_features: Option<Vec<String>>,
}
``` 

Also, the [DeltaTableState](https://github.com/delta-io/delta-rs/blob/3c34b9e4cfaabcadef18dbd40c741b3e8ff18977/rust/src/table/state.rs#L29) should be extended with `reader_features: Option<Vec<String>>,` and `writer_features: Option<Vec<String>>,`.

Is this understanding correct?
