### ISSUE TITLE
Add `set_table_properties` to DeltaTable class 

### ISSUE THREAD

**Issue by ion-elgreco** [delta-io/delta-rs#1663]
# Description

**Use Case**
Currently it's not possible to alter the table_properties after a write (or TableConfig as it's referred to in code.) So now you need Spark-delta to alter these properties.

**Comment by MrPowers** [comment]
@ion-elgreco - can you provide more details on the specific table properties that you're referring to here?

**Comment by ion-elgreco** [comment]
> @ion-elgreco - can you provide more details on the specific table properties that you're referring to here?

These ones:
https://books.japila.pl/delta-lake-internals/DeltaConfigs/#table-properties
And  https://docs.delta.io/table-properties.html

**Comment by srsharathreddy-92** [comment]
it would be great if we can change logRetentionDuration property after first write.

**Comment by pedrosalgadowork** [comment]
Any update on this, so we can also change it from python?

**Comment by dtheodor** [comment]
Does this issue cover adding support for DDL statements in general, such as [CREATE TABLE](https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-create-table-using.html) and [ALTER TABLE ...](https://docs.databricks.com/en/sql/language-manual/sql-ref-syntax-ddl-alter-table.html)? Currently only possible with spark.
