### ISSUE TITLE
Writing with large arrow types (e.g. large_utf8), writes wrong partition encoding

### ISSUE THREAD

**Issue by ion-elgreco** [delta-io/delta-rs#1669]
# Environment

**Delta-rs version**:
0.11.0
0.10.2
0.10.1

**Binding**: 
python

**Environment**:
- **Cloud provider**: Azure
- **OS**: WSL/Ubuntu
- **Other**:

***
# Bug

**What happened**:
When you write arrow table with large_utf8 the written partition encoding is incorrect.
![image](https://github.com/delta-io/delta-rs/assets/15728914/32eae1de-8f2f-4edc-a3d0-be595fcf47e6)

**What you expected to happen**:
Write the correct string encoding just like it does with small utf8 type.
![image](https://github.com/delta-io/delta-rs/assets/15728914/aeeac975-0c6f-4a49-986a-20155e912672)

**How to reproduce it**:
```python
import polars as pl
import pyarrow as pa
from deltalake import write_deltalake
from polars.io.delta import _convert_pa_schema_to_delta

df = pl.DataFrame({
    "foo": ["A","B","C"],
    "bar": ["1","2","3"]
})
arrow_data = df.to_arrow()

small_schema = _convert_pa_schema_to_delta(arrow_data.schema)
arrow_data_small = arrow_data.cast(small_schema)

write_deltalake('TEMP_large_utf8', arrow_data, partition_by=['foo'])
write_deltalake('TEMP_utf8', arrow_data_small, partition_by=['foo'])

```

**More details**:

**Comment by ion-elgreco** [comment]
@roeap Do you perhaps know the root cause of this particular issue, since you've recently worked on this?

**Comment by wjones127** [comment]
@ion-elgreco what version of PyArrow are you using here?

**Comment by ion-elgreco** [comment]
@wjones127 PyArrow v11.0.0

**Comment by ion-elgreco** [comment]
Ah I see in pyarrow v12.0.0 it's working.. this is going to be a fun discussion with our platform team.

**Comment by wjones127** [comment]
Yeah this is due to a bug that was fixed upstream: https://github.com/apache/arrow/pull/34549

**Comment by wjones127** [comment]
@ion-elgreco there might actually be a patch we can make to work around this for older versions of PyArrow: https://github.com/apache/arrow/issues/34546#issuecomment-1466587443

**Comment by ion-elgreco** [comment]
> @ion-elgreco there might actually be a patch we can make to work around this for older versions of PyArrow: [apache/arrow#34546 (comment)](https://github.com/apache/arrow/issues/34546#issuecomment-1466587443)

That would be really helpful because some internal libraries that are used to access our datalake our locked to pyarrow 11 since the dependencies are on some AzureML packages that are limited to pyarrow 11.
