### ISSUE TITLE
Document configuration of dynamodb lock

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#1674]
# Description

We should document what needs to be set for the dynamodb lock.

We should also note that this locking mechanism isn't compatible with any other one, including the Spark one.

Note: the upstream crate also could use better docs: https://github.com/delta-incubator/dynamodb-lock-rs/issues/2

**Use Case**

**Related Issue(s)**

**Comment by wjones127** [comment]
See: https://github.com/delta-io/kafka-delta-ingest#writing-to-s3

**Comment by brayanjuls** [comment]
Hey! can I work on this issue?

**Comment by MrPowers** [comment]
Sure thing @brayanjuls, just assigned this to you.
