### ISSUE TITLE
Documentation for .history says results should be in reverse chronological order, but results are returned in chronological order

### ISSUE THREAD

**Issue by Hanspagh** [delta-io/delta-rs#1680]
# Environment
MacOS

**Delta-rs version**:
delta-rs.0.15.0

**Binding**: 
Python

***
# Bug
History is returned in chronological order while documentation says the opposite 

**What happened**:

**What you expected to happen**:

**How to reproduce it**:
df = pd.DataFrame({"x": [1, 2, 3, 4]})

write_deltalake("table.delta", df, mode="append")
write_deltalake("table.delta", df, mode="append")
write_deltalake("table.delta", df, mode="append")
write_deltalake("table.delta", df, mode="append")

**More details**:
DeltaTable("table.delta").history()

```
[{'timestamp': 1695978312893,
  'operation': 'CREATE TABLE',
  'operationParameters': {'metadata': '{"configuration":{},"created_time":1695978312893,"description":null,"format":{"options":{},"provider":"parquet"},"id":"9adb7a7d-e4b6-4f1a-b325-c60f45685bd9","name":null,"partition_columns":[],"schema":{"fields":[{"metadata":{},"name":"x","nullable":true,"type":"long"}],"type":"struct"}}',
   'mode': 'ErrorIfExists',
   'protocol': '{"minReaderVersion":1,"minWriterVersion":1}',
   'location': 'file:///Users/hans.pagh/Code/pippi/pippi-base/sovs.delta'},
  'clientVersion': 'delta-rs.0.15.0'},
 {'timestamp': 1695978319475,
  'operation': 'WRITE',
  'operationParameters': {'mode': 'Append', 'partitionBy': '[]'},
  'clientVersion': 'delta-rs.0.15.0'},
 {'timestamp': 1695978899613,
  'operation': 'WRITE',
  'operationParameters': {'mode': 'Append', 'partitionBy': '[]'},
  'clientVersion': 'delta-rs.0.15.0'}]
```

**Comment by rtyler** [comment]
Would you be up for updating the documentation @Hanspagh ? :smile:

**Comment by Hanspagh** [comment]
Sure, I would say for alignment with the Deltaspark package, we should change the logic to actually return the events in chronological order, would that be okay as well?

**Comment by r3stl355** [comment]
I agree with @Hanspagh, Delta returns history in reverse chronological order so to be consistent delta-rs should do the same, it needs to be an implementation change, not a documentation change
