### ISSUE TITLE
Support `arrow` format as an alternative to parquet

### ISSUE THREAD

**Issue by universalmind303** [delta-io/delta-rs#1691]
# Description
the [protocol specification](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#format-specification) seems to indicate that alternative formats are supported. Spark seems to support alternative formats in some capacity. 

It would be great to support the [IPC file format](https://arrow.apache.org/docs/format/Columnar.html#ipc-file-format)`arrow` in addition to parquet.

**Use Case**
Many newer engines are “Arrow-native” or “Arrow-compatible”. Enabling the arrow format as an option would allow these engines to use delta without first having to convert to a supported file format (`parquet`).

It would also naturally lend itself as a backend to an ADBC connector 

**Related Issue(s)**
#954

**Comment by wjones127** [comment]
> seems to indicate that alternative formats are supported

They are supported in theory, but in practice the format is pretty tightly coupled to Parquet for the time being. I'm not aware of any support in Spark implementation for other formats for data files. Have you seen any?

> It would be great to support the [IPC file format](https://arrow.apache.org/docs/format/Columnar.html#ipc-file-format)arrow in addition to parquet.

The IPC file format lacks a lot of features Parquet has that make it useful in table formats. For example, Parquet files contain statistics about the row groups and pages within it. IPC file format doesn't have any stats.

I'm not aware of anyone using Arrow IPC files as data lake storage: all the Arrow maintainers I work with use Parquet. And a significant amount of effort has gone into writing optimized readers and writers for Parquet in the Arrow ecosystem. See, for example: https://arrow.apache.org/blog/2022/12/26/querying-parquet-with-millisecond-latency/

Overall, I think the Arrow community is more interested in squeezing out more performance from Parquet than making Arrow IPC files a viable alternative.
