### ISSUE TITLE
CI fails: `test_restore_by_datetime`

### ISSUE THREAD

**Issue by ion-elgreco** [delta-io/delta-rs#1715]
In the ubuntu-latest test run the CI fails https://github.com/delta-io/delta-rs/actions/runs/6466271544/job/17578081398?pr=1694.

```
---- test_restore_by_datetime stdout ----
Error: GenericError { source: TooLargeRestoreVersion(3, 3) }


failures:
    test_restore_by_datetime
```

**Comment by r3stl355** [comment]
I'll look into this

**Comment by r3stl355** [comment]
I'm getting this in Docker: ```
error: failed to build archive: No such file or directory

error: could not compile `deltalake` (lib) due to previous error

Caused by:
  process didn't exit successfully: `/root/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin/rustc --crate-name deltalake --edition=2021 rust/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=130 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="arrow"' --cfg 'feature="arrow-array"' --cfg 'feature="arrow-buffer"' --cfg 'feature="arrow-cast"' --cfg 'feature="arrow-ord"' --cfg 'feature="arrow-row"' --cfg 'feature="arrow-schema"' --cfg 'feature="arrow-select"' --cfg 'feature="azure"' --cfg 'feature="dashmap"' --cfg 'feature="datafusion"' --cfg 'feature="datafusion-common"' --cfg 'feature="datafusion-expr"' --cfg 'feature="datafusion-physical-expr"' --cfg 'feature="datafusion-proto"' --cfg 'feature="datafusion-sql"' --cfg 'feature="default"' --cfg 'feature="dynamodb_lock"' --cfg 'feature="gcs"' --cfg 'feature="glue"' --cfg 'feature="hyper"' --cfg 'feature="parquet"' --cfg 'feature="python"' --cfg 'feature="reqwest"' --cfg 'feature="rusoto_core"' --cfg 'feature="rusoto_credential"' --cfg 'feature="rusoto_dynamodb"' --cfg 'feature="rusoto_glue"' --cfg 'feature="rusoto_sts"' --cfg 'feature="s3"' --cfg 'feature="sqlparser"' --cfg 'feature="tracing"' --cfg 'feature="unity-experimental"' -C metadata=0ffb9acc915687a9 -C extra-filename=-0ffb9acc915687a9 --out-dir /usr/src/delta-rs/target/debug/deps -C incremental=/usr/src/delta-rs/target/debug/incremental -L dependency=/usr/src/delta-rs/target/debug/deps --extern arrow=/usr/src/delta-rs/target/debug/deps/libarrow-64399041442f89ec.rmeta --extern arrow_array=/usr/src/delta-rs/target/debug/deps/libarrow_array-8b27be4b3063ea6b.rmeta --extern arrow_buffer=/usr/src/delta-rs/target/debug/deps/libarrow_buffer-9ff38575d8d2cd63.rmeta --extern arrow_cast=/usr/src/delta-rs/target/debug/deps/libarrow_cast-e3c0139c395c2344.rmeta --extern arrow_ord=/usr/src/delta-rs/target/debug/deps/libarrow_ord-b684abd05bf6bbb8.rmeta --extern arrow_row=/usr/src/delta-rs/target/debug/deps/libarrow_row-4f94bd7bb4ed095a.rmeta --extern arrow_schema=/usr/src/delta-rs/target/debug/deps/libarrow_schema-98ba6abed5fc5340.rmeta --extern arrow_select=/usr/src/delta-rs/target/debug/deps/libarrow_select-df827b8c8423502e.rmeta --extern async_trait=/usr/src/delta-rs/target/debug/deps/libasync_trait-c3c52840d6d4d47d.so --extern bytes=/usr/src/delta-rs/target/debug/deps/libbytes-e54e4f0b515dfd0c.rmeta --extern cfg_if=/usr/src/delta-rs/target/debug/deps/libcfg_if-6caf6cd55fa899f6.rmeta --extern chrono=/usr/src/delta-rs/target/debug/deps/libchrono-4c1aed73faedf0fd.rmeta --extern dashmap=/usr/src/delta-rs/target/debug/deps/libdashmap-011ed47290eca84c.rmeta --extern datafusion=/usr/src/delta-rs/target/debug/deps/libdatafusion-2f85d092107a377e.rmeta --extern datafusion_common=/usr/src/delta-rs/target/debug/deps/libdatafusion_common-57d77b3835e8dfc8.rmeta --extern datafusion_expr=/usr/src/delta-rs/target/debug/deps/libdatafusion_expr-37414d1883824b53.rmeta --extern datafusion_physical_expr=/usr/src/delta-rs/target/debug/deps/libdatafusion_physical_expr-eaffa10b5e9ea015.rmeta --extern datafusion_proto=/usr/src/delta-rs/target/debug/deps/libdatafusion_proto-fbd7b16af6ac55a7.rmeta --extern datafusion_sql=/usr/src/delta-rs/target/debug/deps/libdatafusion_sql-b24cc6a31d648aae.rmeta --extern dynamodb_lock=/usr/src/delta-rs/target/debug/deps/libdynamodb_lock-ecd1c4e32d3c2ace.rmeta --extern errno=/usr/src/delta-rs/target/debug/deps/liberrno-259d2d4016b3e4a0.rmeta --extern futures=/usr/src/delta-rs/target/debug/deps/libfutures-bade62ded1754706.rmeta --extern hyper=/usr/src/delta-rs/target/debug/deps/libhyper-cf951a82454260f9.rmeta --extern itertools=/usr/src/delta-rs/target/debug/deps/libitertools-6cb6d9042f06cb85.rmeta --extern lazy_static=/usr/src/delta-rs/target/debug/deps/liblazy_static-a1c7da82b1419d90.rmeta --extern libc=/usr/src/delta-rs/target/debug/deps/liblibc-bfd076d8aee8e048.rmeta --extern log=/usr/src/delta-rs/target/debug/deps/liblog-87d2a4c630402711.rmeta --extern num_bigint=/usr/src/delta-rs/target/debug/deps/libnum_bigint-3333589f0d4fc209.rmeta --extern num_traits=/usr/src/delta-rs/target/debug/deps/libnum_traits-1d0ff7635bced255.rmeta --extern num_cpus=/usr/src/delta-rs/target/debug/deps/libnum_cpus-0dd30c60a394a5af.rmeta --extern object_store=/usr/src/delta-rs/target/debug/deps/libobject_store-9549e421603f4196.rmeta --extern once_cell=/usr/src/delta-rs/target/debug/deps/libonce_cell-958b48ed93849f01.rmeta --extern parking_lot=/usr/src/delta-rs/target/debug/deps/libparking_lot-862505407b098ec8.rmeta --extern parquet=/usr/src/delta-rs/target/debug/deps/libparquet-c936e4ce372ea2a1.rmeta --extern percent_encoding=/usr/src/delta-rs/target/debug/deps/libpercent_encoding-59066ed36aae8783.rmeta --extern rand=/usr/src/delta-rs/target/debug/deps/librand-33c59a840f7b2fdd.rmeta --extern regex=/usr/src/delta-rs/target/debug/deps/libregex-686f32ec0640f83c.rmeta --extern reqwest=/usr/src/delta-rs/target/debug/deps/libreqwest-80a88b3ba58b494b.rmeta --extern rusoto_core=/usr/src/delta-rs/target/debug/deps/librusoto_core-cbcde88a9b0ac301.rmeta --extern rusoto_credential=/usr/src/delta-rs/target/debug/deps/librusoto_credential-7a23f933bb610553.rmeta --extern rusoto_dynamodb=/usr/src/delta-rs/target/debug/deps/librusoto_dynamodb-49d7f8e6801db625.rmeta --extern rusoto_glue=/usr/src/delta-rs/target/debug/deps/librusoto_glue-910e8608c5b6871f.rmeta --extern rusoto_sts=/usr/src/delta-rs/target/debug/deps/librusoto_sts-6b5c0df30049fd3e.rmeta --extern serde=/usr/src/delta-rs/target/debug/deps/libserde-804f91ceb04ccf05.rmeta --extern serde_json=/usr/src/delta-rs/target/debug/deps/libserde_json-87d82c6f1a9d7230.rmeta --extern sqlparser=/usr/src/delta-rs/target/debug/deps/libsqlparser-013d2fdf3592db84.rmeta --extern thiserror=/usr/src/delta-rs/target/debug/deps/libthiserror-73f10d15eb8bfd99.rmeta --extern tokio=/usr/src/delta-rs/target/debug/deps/libtokio-44d7ceeb3dc019fd.rmeta --extern tracing=/usr/src/delta-rs/target/debug/deps/libtracing-479ffc7dfce0b309.rmeta --extern url=/usr/src/delta-rs/target/debug/deps/liburl-9a24581d538b3a94.rmeta --extern uuid=/usr/src/delta-rs/target/debug/deps/libuuid-1672c1d9dd6a24e2.rmeta -C debuginfo=line-tables-only -L native=/usr/src/delta-rs/target/debug/build/bzip2-sys-e04b866dcbe38b76/out/lib -L native=/usr/src/delta-rs/target/debug/build/lzma-sys-3c27bc8149590d75/out -L native=/usr/src/delta-rs/target/debug/build/zstd-sys-5ec7f13281680799/out -L native=/usr/src/delta-rs/target/debug/build/ring-c7708933db432194/out -L native=/usr/src/delta-rs/target/debug/build/openssl-sys-4c3065486219f608/out/openssl-build/install/lib -L native=/usr/src/delta-rs/target/debug/build/lz4-sys-32208a8413f44c99/out -L native=/usr/src/delta-rs/target/debug/build/blake3-acce6656ff1edd1e/out` (exit status: 1)
```

**Comment by r3stl355** [comment]
I am trying to reproduce this but getting different type of failures. Here is my setup:
1. Using Ubuntu 23.04 Docker image on my laptop
2. Installing a Rust toolchain using a script which claims to be a match to what's used by GitHub actions (this script: https://github.com/catthehacker/docker_images/blob/master/linux/ubuntu/scripts/rust.sh). Validating I see it's running the same cargo as the failing CI script on GitHub (1.73.0)
3. I am not using any Rust cache. CI seems to be using `swatinum/rust-cache@2` but I don't know how to install that in Docker (yet). Could this be causing issues?
4. Git clone delta-rs from main
5. Running various builds from CI using `cargo clippy ***` works
6. This is where it gets weird - I cannot explain this but looks like it's failing to - running `cargo test` for the first 2-3 times fails with some error like this 
```  
= note: collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
error: aborting due to previous error

Couldn't compile the test.
---- crates/deltalake-core/src/delta_datafusion/mod.rs - delta_datafusion (line 5) stdout ----
error: linking with `cc` failed: exit status: 1``` 
but every time I run that command it seem to be compiling more and more modules and eventually (after 3-4 runs) it actually runs the tests
7. At this point I start getting test failures but looks like they are docstring errors:
```
failures:
    crates/deltalake-core/src/lib.rs - (line 16)
    crates/deltalake-core/src/lib.rs - (line 7)
 .... etc
```
I don't get what is it complaining about and why it is using `create/` prefix here. This is what in `lib.rs: line 7`
```
//! ```rust
//! async {
//!   let table = deltalake::open_table("./tests/data/simple_table").await.unwrap();
//!   let files = table.get_files();
//! };
//! ```
```
this looks a valid code to me. There are similar docs in line 16 and 28 in the same file - it is complaining about 7 and 16 but not 28

I'll keep on digging but any ideas on what I'm doing wrong/missing would be helpful, thanks

**Comment by r3stl355** [comment]
OK, I'm nearly there (a question about the need to make multiple builds before the tests start running still remains but I'll worry about that later)

Looks like `cargo test` on Ubuntu doesn't like "```" in docs and in few places complains about "```rust" docs. 
Adding `ignore` for now seem to resolve the issue so I'll submit a PR with those changes shortly. 

There is no such problem on MacOS though.

**Comment by r3stl355** [comment]
A follow up - I was unable to re-create the issue using an Ubuntu 22.04 ec2 instance - all tests run fine. I guess this issue could be closed unless it's still happening

**Comment by ion-elgreco** [comment]
@r3stl355 it only occurred once then. Closing it then, thanks for looking into it!
