### ISSUE TITLE
Improve write throughput through a finer-grained lock.

### ISSUE THREAD

**Issue by syedashrafulla** [delta-io/delta-rs#1716]
# Description

delta-rs uses a Rust-based AWS DynamoDB lock client that [has a partition key but no sort key](https://docs.rs/dynamodb_lock/0.4.3/src/dynamodb_lock/lib.rs.html#485-505). As a result, the lock forces a commit happening shortly after an in-progress commit to [sleep for a refresh period before retrying](https://docs.rs/dynamodb_lock/0.4.3/src/dynamodb_lock/lib.rs.html#389).

delta-standalone uses its own Java-based AWS DynamoDB lock that has [the same partition key but the commit name as the sort key](https://github.com/delta-io/delta/blob/v3.0.0rc2/storage-s3-dynamodb/src/main/java/io/delta/storage/S3DynamoDBLogStore.java#L236-L237), with the `fileName` set to the commit [here](https://github.com/delta-io/delta/blob/v3.0.0rc2/connectors/standalone/src/main/scala/io/delta/standalone/internal/OptimisticTransactionImpl.scala#L374). As a result, the commit happening shortly after an in-progress commit can immediately reserve the next commit and move on with committing the next commit. delta-standalone ensures commits are in-order by checking the delta log for the previous commit's existence in the log.

The consequence of adding the commit file name as a sort key is that concurrent writers do not have to wait for the `refresh_period` to determine their next commit. The commit happening shortly after reads the log and then locks its ownership of the next commit. In return for the cost of adding the commit file name as a sort key, the commits themselves are scheduled more frequently than the refresh period.

I think this is a worthwhile tradeoff and a feature to introduce to delta-rs.

**Use Case**

Concurrent writes from multiple writers using delta-rs.

**Related Issue(s)**

https://github.com/delta-io/delta-rs/issues/1674 for documenting how the lock works
https://github.com/delta-io/delta-rs/issues/1333 for a separation-of-concerns refactor of the lock
https://github.com/delta-io/delta-rs/issues/1251 for documentation that the current lock is incompatible with the Apache Spark or Databricks locks, which I believe is less necessary when the commit-file-name-as-sort-key is introduced.

**Comment by rtyler** [comment]
@dispanser has been [doing some work](https://github.com/delta-io/delta-rs/pulls?q=is%3Apr+author%3Adispanser+is%3Aclosed) to move us to a consistent implementation with the Delta/Spark library's `S3DynamoDbLogStore` implementation. 

I will close this issue once we remove the older dynamodb lock from delta-rs.

**Comment by rtyler** [comment]
0.17 has been released which removes the older lock and moves us to the S3DynamoDbLogStore, see #2173 for more details in the changelog
