### ISSUE TITLE
Remove a Partition

### ISSUE THREAD

**Issue by bouillon** [delta-io/delta-rs#1717]
It seems there is no way to remove a partition?

In docs I see a documented way to overwrite a partition https://delta-io.github.io/delta-rs/python/usage.html#overwriting-a-partition but not how to remove it or make it empty. Of course, I can create a dummy DataFrame but it will still be one row in my partition. Is there some workarounds for the moment? Is the future planned?

[**Related Issue(s)**
](https://github.com/delta-io/delta-rs/issues/1387)

**Comment by wjones127** [comment]
In the next release we'll add `delete()`, so that will let you remove a partition. https://github.com/delta-io/delta-rs/pull/1687

**Comment by bouillon** [comment]
Perfect, thanks

**Comment by ion-elgreco** [comment]
@wjones127 we can close this one now 😄
