### ISSUE TITLE
Support convert_to_delta for parquet2

### ISSUE THREAD

**Issue by junjunjd** [delta-io/delta-rs#1723]
# Description

Support `convert_to_delta` for `parquet2`. Currently  [the `convert_to_delta` function](https://github.com/delta-io/delta-rs/pull/1686) is only implemented for `parquet`.

**Related Issue(s)**
https://github.com/delta-io/delta-rs/issues/1041, https://github.com/delta-io/delta-rs/issues/1682, https://github.com/delta-io/delta-rs/pull/1686

**Comment by ion-elgreco** [comment]
I don't think we should take another dependency for this, parquet-rs is already sufficient enough
