### ISSUE TITLE
VACUUM doesn't create a commit in transaction log

### ISSUE THREAD

**Issue by ion-elgreco** [delta-io/delta-rs#1726]
When you vacuum a table with delta-rs, it  doesn't create a commit in the delta transaction log, stating the VACUUM operation.

**Comment by wjones127** [comment]
Does it do that in Spark? I wouldn't expect it to create a transaction.

**Comment by ion-elgreco** [comment]
@wjones127 apparently they do since this PR: https://github.com/delta-io/delta/pull/1552

**Comment by ion-elgreco** [comment]
@wjones127 I checked my tables written with databricks, and they all have the VACUUM START/END commits

![image](https://github.com/delta-io/delta-rs/assets/15728914/d95ebf87-0030-4d71-a362-56675eecc2cc)
