### ISSUE TITLE
Rust version can not read delta table in local Minio since version 0.13.0

### ISSUE THREAD

**Issue by leehuwuj** [delta-io/delta-rs#1729]
# Environment

**Delta-rs version**: 0.13.0, 0.14.0, 0.15.0, 0.16.0

**Binding**: 

**Environment**:
- **Cloud provider**: AWS
- **OS**: Mac OS 14.0
- **Other**:

***
# Bug

**What happened**: 
Try load table from S3 with AWS provider and MinIO local but got timeout error. I tested ok with version 0.12.0 but got error since 0.13.0 to 0.16.0.

**What you expected to happen**:

**How to reproduce it**:
```rust
use deltalake::{DeltaTableError, open_table, DeltaTable};

async fn main() -> Result<(), DeltaTableError> {
    let table_uri = "s3://test-bucket/dataset";
    let table = open_table(table_uri).await?;
}
```
```shell
> cargo run

Error: ObjectStore { source: Generic { store: "S3", source: Error { retries: 2, message: "request error", source: Some(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Ipv4(xxx.xxx.xxx.xxx)), port: None, path: "/latest/api/token", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 60, kind: TimedOut, message: "Operation timed out" })) }), status: None } } }
```

**More details**:

**Comment by cmackenzie1** [comment]
@leehuwuj how are the S3 credentials being provided here? Are you setting environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` or relying on some other part of the credential resolution chain?

**Comment by roeap** [comment]
We moved a lot of the environment parsing logic etc to the underlying object store crate, as @cmackenzie1 points out this seems to be a credential issue. The message suggests that object store tries to query an EC2 metadata endpoint, which is the default if no other credential is found.

My suggestion would be to always pass the intended credentials via the `open_table_with_options` function.

**Comment by leehuwuj** [comment]
Thank guys, as above comments, i retried successfully with MinIO by providing explicitly the credentials in `storage_options`.
For S3 providers, the moment i raised this ticket, i tried authenticate transparently through AWS SSO chain. I have not tested by providing the storage_options explicitly but i think the issue can be resolved just like the MinIO.

For anyone who are facing the same issue, please set the storage_options explicitly via `open_table_with_options` or through `DeltaTableBuilder`, if you are using MinIO without ssl please set the `allow_http` to "true".
