### ISSUE TITLE
Compiling latest rust code fails

### ISSUE THREAD

**Issue by michaelbrichko** [delta-io/delta-rs#1732]
Windows\Latest git repository code. "cargo build" fails from root folder and from rust folder.

Compiling from rust folder:
PS C:\delta-rs\rust> cargo build
error: failed to parse manifest at `C:\delta-rs\rust\Cargo.toml`

Caused by:
  error inheriting `arrow` from workspace root manifest's `workspace.dependencies.arrow`

Caused by:
  failed to parse manifest at `C:\delta-rs\Cargo.toml`

Caused by:
  expected a boolean or an integer
  in `profile.test.debug`

Compiling from root folder:
PS C:\delta-rs> cargo build
error: failed to parse manifest at `C:\delta-rs\Cargo.toml`

Caused by:
  expected a boolean or an integer
  in `profile.test.debug`

Thank you!

**Comment by wjones127** [comment]
How old is your cargo installation? IIRC we require fairly new versions to be able to build.

**Comment by michaelbrichko** [comment]
> How old is your cargo installation? IIRC we require fairly new versions to be able to build.
PS C:\delta-rs> cargo version
cargo 1.70.0 (ec8a8a0ca 2023-04-25)

PS C:\delta-rs> rustc --version
rustc 1.70.0 (90c541806 2023-05-31)
PS C:\delta-rs>

**Comment by michaelbrichko** [comment]
version 1.73 solves the issue. Thank you!
