### ISSUE TITLE
optimize operation fails with EmptySegment on shallow cloned table

### ISSUE THREAD

**Issue by rtyler** [delta-io/delta-rs#1748]
# Environment

**Delta-rs version**: any 

**Binding**: rust

**Environment**:
- **Cloud provider**: any
- **OS**: any
- **Other**:

***
# Bug

**What happened**:

One of the novel characteristics of a Delta table created by `SHALLOW CLONE` is that it creates a new prefix in the object store, with just a `_delta_log/` prefix, and then the transactions in that new cloned table will have transactions that point to the original table's objects.

For operations which do a coercion of `Add` to `ObjectMeta` structs which carry an `object_store::path::Path` that cannot have a full URL inside it.

The sample shallow clone I created was basically just:   `CREATE TABLE rtyler.shallow_test_downstream SHALLOW CLONE rtyler.shallow_test_upstream`

```
---- test_read_shallow_clone_table stdout ----
Error: GenericError { source: EmptySegment { path: "s3://bucket/databases/rtyler.db/shallow_test_upstream/part-00000-5662e269-99f5-4066-963d-603a3126f7ba.c000.snappy.parquet" } }
```

**What you expected to happen**:

I would expect my shallow clone table to be "optimized", or no-opped. 

**How to reproduce it**:

```rust
#[tokio::test]
async fn test_read_shallow_clone_table() -> DeltaResult<()> {
    let path = "./tests/data/shallow_test_downstream";
    let table = deltalake::open_table(&path).await?;
    use deltalake::DeltaOps;
    let ops = DeltaOps::try_from_uri("file:///home/tyler/source/github/delta-io/delta-rs/rust/tests/data/shallow_test_downstream").await.unwrap();
    ops.optimize().await?;
    assert!(false);
    Ok(())
}
```

**More details**:

**Comment by ion-elgreco** [comment]
Issue is already reported here about absolute paths support https://github.com/delta-io/delta-rs/issues/865, will close this as duplicate
