### ISSUE TITLE
Add high-level checking for append-only tables

### ISSUE THREAD

**Issue by junjunjd** [delta-io/delta-rs#1759]
# Description
Add high-level checking to delete, merge and update operations to return error immediately when the Delta table is append-only. 
**Use Case**
https://github.com/delta-io/delta-rs/pull/1747 adds low-level checking for append-only. This issue will add a high-level checking and thus closes #352.

**Related Issue(s)**
#352

**Comment by MrPowers** [comment]
@junjunjd - is this done?  Can we close this issue?

**Comment by junjunjd** [comment]
> @junjunjd - is this done? Can we close this issue?

@MrPowers The low-level checking is added to `commit` function. We still need to add some high-level checking so that operations can return an error immediately before calling the `commit` function. I'll take at look at this once my [convert_to_delta](https://github.com/delta-io/delta-rs/pull/1686) MR is reviewed/merged.

**Comment by roeap** [comment]
#1807 adds some checks for protocol compatibility before we start the heavy lifting. To check append only, we theoretically need to see the generated actions on a table. We could try and guess what might get generated - e.g. in a merge we suspect updates - but might end up rejecting operations that may have worked. then there are more obvious ones - like delete - that we could prohibit.

Do you have some specific thoughts on where we could introduce some pre-write checks?

**Comment by junjunjd** [comment]
@roeap The `ProtocolChecker ` looks great. I added a `check_append_only` method to be used for high-level checking in delete, update and write with `Overwrite` save mode.

You are right that for a merge, we won't be able to know if there is data change until the actions are generated. Any high-level checking would need to be added to the `execute` method when a Remove with data change is generated.

While going over the operation, I also noticed that remove and filesystem check will always be rejected if the table is append-only and `files_to_remove` is not empty. I think it makes sense to make these two operations bypass the low-level checking, otherwise append-only tables will not be able to restore or perform filesystem check. What do you think?
