### ISSUE TITLE
Support writes to mounted local path with blobfuse

### ISSUE THREAD

**Issue by RobinLin666** [delta-io/delta-rs#1765]
# Description

**Use Case**
Re-open an issue for tracking https://github.com/delta-io/delta-rs/issues/1418#issuecomment-1769921086. Thank you.

```python
import pandas as pd
from deltalake.writer import write_deltalake

df = pd.DataFrame(
    {
        "a": [1, 2, 3, 4, 5],
        "fruits": ["banana", "orange", "mango", "apple", "banana"],
    }
)

write_deltalake('/lakehouse/default/Files/fruits', df,mode='overwrite')
```
<img width="816" alt="image" src="https://github.com/delta-io/delta-rs/assets/128118209/56da2a0b-2414-4a6a-86ae-57f3762d60a0">

**Related Issue(s)**
https://github.com/delta-io/delta-rs/issues/1418#issuecomment-1769847878
https://github.com/GlareDB/glaredb/issues/1809

**Comment by scsmithr** [comment]
For what it's worth, I was testing with this change to object store: https://github.com/GlareDB/arrow-rs/pull/2/files

The first diff chunk explicitly drops the file so that the metadata gets flushed to blobstore before the rename.

The second chunk I'm not sure is necessary. I was just trying out explicitly syncing the file, but I don't recall it actually fixing the issue.

**Comment by RobinLin666** [comment]
Thanks @scsmithr, I tried to mitigate the issue from blobfuse side.

for #1 rename issue can be mitigated. I upload the tmp file before renaming.

for #2 you said blobfuse doesn't support hard linking, `copy_if_not_exists` will fail. I don't quite understand how this aspect is affected and whether it is the cause of the error I encountered above. `OSError: Generic DeltaLocalObjectStore error: Function not implemented (os error 38)`  If possible, please let me know where it need a hard link and we can think about any workarounds available.

I saw the same error when writing to DBFS, perhaps it's one of the reasons?
https://github.com/delta-io/delta-rs/issues/987
