### ISSUE TITLE
Expose cleanup_metadata or create_checkpoint_from_table_uri_and_cleanup to the Python API

### ISSUE THREAD

**Issue by alisheykhi** [delta-io/delta-rs#1768]
# Description
When utilizing the `table.create_checkpoint()` method in Python, direct access to the `cleanup_metadata()` function is currently unavailable. This limitation results in an increased number of log entries. In Spark, this feature is integrated as a step at the end of the method (as evident in the [Spark implementation](https://github.com/delta-io/delta/blob/8639c411890a5c77386f04e2282fcf4caa401eff/spark/src/main/scala/org/apache/spark/sql/delta/Checkpoints.scala#L303)). However, it's conspicuously absent from the Python API.

In the Rust implementation (as seen in the [Rust implementation](https://github.com/delta-io/delta-rs/blob/a67140c6b13a6f820f4879f31eb927d140327746/rust/src/protocol/checkpoints.rs#L92C14-L92C58)), there's a `cleanup_metadata` and also `create_checkpoint_from_table_uri_and_cleanup` method, but it's not called at the end of the `create_checkpoint` process.

There is another [Pull Request (PR)](https://github.com/delta-io/delta-rs/pull/1728) that addresses the creation of a checkpoint both before and after the vacuum operation. However, the absence of the `cleanup_metadata` method during the checkpoint creation process results in the metadata directory remaining uncleared.

**Use Case**
Cleaning up the Metadata Directory After Checkpoint Creation or Optimization

**Related Issue(s)**
#1728

**Comment by mattslack-db** [comment]
I agree that the `cleanup_metadata` method should be made available in Python, as it can be useful to reduce the file listing time as the number of files in _delta_log grows. However I would definitely not add it to the `create_checkpoint` function. You _generally_ want to keep the metadata, so you have the ability to roll back to a previous version.

**Comment by r3stl355** [comment]
take

**Comment by alisheykhi** [comment]
thanks @r3stl355 , for more details and discussion on the root cause of the issue, please refer to [this discussion thread](https://github.com/delta-io/delta-rs/discussions/1760).
