### ISSUE TITLE
expose use_dictionary=False when writing Delta Table and running optimize

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#1772]
is there a way when running delta optimize to turn off RLE_Encoding, the Engine I use to query those delta tables does not support it yet

**Comment by wjones127** [comment]
> the Engine

What engine are you using that does support this?

**Comment by djouallah** [comment]
There is a big with PowerBI if it read a parquet with rle encoding:(

**Comment by Alaburda** [comment]
@djouallah have you found a solution to this?

**Comment by djouallah** [comment]
> @djouallah have you found a solution to this?

just don't run metadata checkpoint till PowerBI fix the issue

**Comment by djouallah** [comment]
one year later, someone fix it from the community :  https://github.com/delta-io/delta-rs/pull/3214
