### ISSUE TITLE
[RFC] Use arrow for checkpoint reading and state handling

### ISSUE THREAD

**Issue by roeap** [delta-io/delta-rs#1776]
# Description

With the switch to updated schema / types in #1756 we also got quite some code to read checkpoints and more generally handle the table state as arrow record batches. In the past we tried several times to switch to arrow-based state.

I believe now is a good time, as we did a lot of the required work in kernel already. In this context I would also question the value of further maintaining a parquet2 variant of the checkpoint parsing or rather an arrow2 equivalent. IIRC, polars is currently vendoring large parts of the arrow2 codebase and as they are currently the main maintainers, there is likely little maintenance going forward.

AS there is a zero-copy interop between arrow and arrow2, I think we can just remove that support from our codebase, which would lead to - i be lieve - significantly reduced complexity.

**Use Case**

**Related Issue(s)**

**Comment by ion-elgreco** [comment]
Polars also cloned pieces of arrow2 into Polars since the main maintainer of arrow2 pulled back. It's called polars-arrow now. So any activity on that arrow will probably also likely only happen into polars-arrow, unless folks back port stuff to arrow2.

**Comment by houqp** [comment]
I agree with deleting the parquet2 support code to keep things simple given the fork. That said, I recommend taking the columnar based parsing approach in the current parquet2 implement for the new arrow-rs based state implementation for better performance.

**Comment by roeap** [comment]
>  I recommend taking the columnar based parsing approach

Fully agree. My thinking was to start with loading most of the state in a first pass, and then moving to something I recently learned is called `PnM-Query` - i.e. trying our best to get the protocol and metadata as efficiently as possible. i.e. scanning all commit files and then selectively getting the data from the checkpoint if not present in any commit json file. and loadig file actions only when needed ...
