### ISSUE TITLE
errors when using pyarrow dataset as a source

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#1779]
pyarrow dataset is not a supported source for delta-rs but I noticed it works fine and it does generate the files but at then end i get an error that py.dataset is not iterable.

the reason I amusing dataset and not table is to avoid OOM

**Comment by stefnba** [comment]
Same for me. 

It works fine the first time but as soon as the table exists the error you mentioned is thrown.

**Comment by ion-elgreco** [comment]
Can you specify when you were passing a pyarrow dataset as a source?

**Comment by djouallah** [comment]
here is the code

import pyarrow.dataset as ds
from deltalake.writer import write_deltalake
```
from trident_token_library_wrapper import PyTridentTokenLibrary
aadToken = PyTridentTokenLibrary.get_access_token("storage")

for tbl in ['nation','region','customer','supplier','orders','part','lineitem','partsupp'] :
     print(tbl)
     write_deltalake(f"abfss://Rust@onelake.dfs.fabric.microsoft.com/TPCH_DuckDB100.Lakehouse/Tables/{tbl}",\
     ds.dataset(f'/lakehouse/default/Files/{sf}/{tbl}',format="parquet")\
     ,mode='overwrite',overwrite_schema=True\
     ,max_rows_per_file =250000000,min_rows_per_group=8000000,max_rows_per_group=16000000\
     ,storage_options={"bearer_token": aadToken, "use_fabric_endpoint": "true"})
```

**Comment by ion-elgreco** [comment]
The only inputs that are accepted are these:

data (Union[[pandas.core.frame.DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame), [pyarrow.lib.Table](https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table), [pyarrow.lib.RecordBatch](https://arrow.apache.org/docs/python/generated/pyarrow.RecordBatch.html#pyarrow.RecordBatch), Iterable[[pyarrow.lib.RecordBatch](https://arrow.apache.org/docs/python/generated/pyarrow.RecordBatch.html#pyarrow.RecordBatch)], [pyarrow.lib.RecordBatchReader](https://arrow.apache.org/docs/python/generated/pyarrow.RecordBatchReader.html#pyarrow.RecordBatchReader)]) – Data to write. If passing iterable, the schema must also be given. 

So you will need to add` .to_table()` after the` ds.dataset(f'')`

**Comment by djouallah** [comment]
yes, I am doing .to_table() but what I notice, it does works and write the files even without it, I much prefer not to use to_table as it consume a lot of memory

**Comment by stefnba** [comment]
I recommend using `. to_batches()` which returns an iterator of RecordBatch. 

`.to_table()` reads all the selected data from the dataset into memory and by doing so defeats all the purpose of a pyarrow dataset.

**Comment by djouallah** [comment]
@stefnba do you have please a full example using to_batch() i could not make it to works ?

**Comment by ion-elgreco** [comment]
Hmm I think I get it now, looking at the code in our python writer, [pyarrow.dataset.Dataset sup](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.write_dataset.html) does support writing datasets.

**Comment by stefnba** [comment]
In your code sample just add `.to_batches()`, then it should work.

More info, see [here](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.Dataset.html#pyarrow.dataset.Dataset.to_batches)

```
ds.dataset(f'/lakehouse/default/Files/{sf}/{tbl}',format="parquet").to_batches()
```

**Comment by djouallah** [comment]
thanks @stefnba now it ask about the schema :)

**Comment by ion-elgreco** [comment]
I am working on a quick fix it's actually really small fix.

**Comment by stefnba** [comment]
> Hmm I think I get it now, looking at the code in our python writer, [pyarrow.dataset.Dataset](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.write_dataset.html) does support writing datasets.

Yes it does. That's why it also works when no table exists yet since in `write_deltalake()`, `if table is not None` is skipped and the data is directly written with `ds.write_dataset()`. 

```python
if table is not None:
        # We don't currently provide a way to set invariants
        # (and maybe never will), so only enforce if already exist.
        invariants = table.schema().invariants
        checker = _DeltaDataChecker(invariants)

        def check_data_is_aligned_with_partition_filtering(
            batch: pa.RecordBatch,
        ) -> None:
            if table is None:
                return
            existed_partitions: FrozenSet[
                FrozenSet[Tuple[str, Optional[str]]]
            ] = table._table.get_active_partitions()
            allowed_partitions: FrozenSet[
                FrozenSet[Tuple[str, Optional[str]]]
            ] = table._table.get_active_partitions(partition_filters)
            partition_values = pa.RecordBatch.from_arrays(
                [
                    batch.column(column_name)
                    for column_name in table.metadata().partition_columns
                ],
                table.metadata().partition_columns,
            )
            partition_values = batch_distinct(partition_values)
            for i in range(partition_values.num_rows):
                # Map will maintain order of partition_columns
                partition_map = {
                    column_name: encode_partition_value(
                        batch.column(column_name)[i].as_py()
                    )
                    for column_name in table.metadata().partition_columns
                }
                partition = frozenset(partition_map.items())
                if (
                    partition not in allowed_partitions
                    and partition in existed_partitions
                ):
                    partition_repr = " ".join(
                        f"{key}={value}" for key, value in partition_map.items()
                    )
                    raise ValueError(
                        f"Data should be aligned with partitioning. "
                        f"Data contained values for partition {partition_repr}"
                    )

        def validate_batch(batch: pa.RecordBatch) -> pa.RecordBatch:
            checker.check_batch(batch)

            if mode == "overwrite" and partition_filters:
                check_data_is_aligned_with_partition_filtering(batch)

            return batch

        if isinstance(data, RecordBatchReader):
            batch_iter = data
        elif isinstance(data, pa.RecordBatch):
            batch_iter = [data]
        elif isinstance(data, pa.Table):
            batch_iter = data.to_batches()
        else:
            batch_iter = data

        data = RecordBatchReader.from_batches(
            schema, (validate_batch(batch) for batch in batch_iter)
        )

    ds.write_dataset(
        data,
        base_dir="/",
        basename_template=f"{current_version + 1}-{uuid.uuid4()}-{{i}}.parquet",
        format="parquet",
        partitioning=partitioning,
        # It will not accept a schema if using a RBR
        schema=schema if not isinstance(data, RecordBatchReader) else None,
        file_visitor=visitor,
        existing_data_behavior="overwrite_or_ignore",
        file_options=file_options,
        max_open_files=max_open_files,
        max_rows_per_file=max_rows_per_file,
        min_rows_per_group=min_rows_per_group,
        max_rows_per_group=max_rows_per_group,
        filesystem=filesystem,
        max_partitions=max_partitions,
    )
```


Here is the error message:
```
320     else:
    321         batch_iter = data
    323     data = RecordBatchReader.from_batches(
--> 324         schema, (validate_batch(batch) for batch in batch_iter)
    325     )
    327 ds.write_dataset(
    328     data,
    329     base_dir="[/](https://file+.vscode-resource.vscode-cdn.net/)",
   (...)
    343     max_partitions=max_partitions,
    344 )
    346 if table is None:

TypeError: 'pyarrow._dataset.FileSystemDataset' object is not iterable
```

**Comment by stefnba** [comment]
> thanks @stefnba now it ask about the schema :)

When you use an iterable in `write_deltalake()` you need to provide a schema. Notice the `schema=dataset.schema` and `dataset.to_batches()`.

```python
from trident_token_library_wrapper import PyTridentTokenLibrary

aadToken = PyTridentTokenLibrary.get_access_token("storage")

for tbl in ["nation", "region", "customer", "supplier", "orders", "part", "lineitem", "partsupp"]:
    print(tbl)

    dataset = ds.dataset(f"/lakehouse/default/Files/{sf}/{tbl}", format="parquet")

    write_deltalake(
        f"abfss://Rust@onelake.dfs.fabric.microsoft.com/TPCH_DuckDB100.Lakehouse/Tables/{tbl}",
        data=dataset.to_batches(),
        mode="overwrite",
        schema= dataset.schema,
        overwrite_schema=True,
        max_rows_per_file=250000000,
        min_rows_per_group=8000000,
        max_rows_per_group=16000000,
        storage_options={"bearer_token": aadToken, "use_fabric_endpoint": "true"},
    )
```

**Comment by ion-elgreco** [comment]
https://github.com/delta-io/delta-rs/pull/1780

**Comment by djouallah** [comment]
@ion-elgreco @stefnba a question, Delta-s can read delta table from onelale using Storage option, do you know if this works can be ported upstream to pyarrow dataset, I have a case where I want to read some parquet files from another url ?

**Comment by ion-elgreco** [comment]
> @ion-elgreco @stefnba a question, Delta-s can read delta table from onelale using Storage option, do you know if this works can be ported upstream to pyarrow dataset, I have a case where I want to read some parquet files from another url ?

I don't get the question, fsspec doesn't support one lake? If they don't you need to create an issue there and at adlfs repo
