### ISSUE TITLE
Auto assign GitHub issues with a "take" message

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#1791]
Some repos are setup so users can type "take" and an issue is auto-assigned to them.

See [this pandas issue](https://github.com/pandas-dev/pandas/issues/52238) for example.

This could be a nice addition to this project.

**Comment by rtyler** [comment]
As far as I can tell this only works for people already in the GitHub organization. You cannot assign people outside the organization to an issue

**Comment by MrPowers** [comment]
@rtyler - I don't think you can assign people outside an organization till they comment on the issue.  I was thinking that if they comment "take" and then the GitHub Action callback runs, then perhaps that person can be assigned.  Thoughts?

**Comment by MrPowers** [comment]
Here's [the code](https://github.com/pandas-dev/pandas/blob/9465449b09668c7fe6081e5ec4f96d5e4287d082/.github/workflows/comment-commands.yml#L14).

Someone who understands this better than me can better assess.
