### ISSUE TITLE
No Official Help

### ISSUE THREAD

**Issue by ISimion** [delta-io/delta-rs#1849]
# Description

Asking for help here since any other official way does not work. If I try to access the [official documentation link ](https://delta-io.github.io/delta-rs/ ) from pypi.org, I get `404`. 

If I try to address a question on the [official Slack](https://delta-users.slack.com/ssb/redirect), it asks for my e-mail and afterward awaits a six-character code from my e-mail. Still, I am only getting an e-mail from Slack stating that no account was found with my e-mail, so, I can't access the Slack community.

**Use Case**

When searching for help.

**Related Issue(s)**

None.

**Comment by wjones127** [comment]
Hi @ISimion, sorry you've had trouble finding help.

The current docs are here: https://delta-io.github.io/delta-rs/python/
We are currently working to move to a new docs site, which is where I think the broken link comes from.

Here is a invite link to the Slack as well: https://join.slack.com/t/delta-users/shared_invite/zt-26v5bopyu-RMRrHczIc80lQgANLZwwCQ

**Comment by ISimion** [comment]
Thank you so much.
