### ISSUE TITLE
When will upgrade object_store to 0.8?

### ISSUE THREAD

**Issue by RobinLin666** [delta-io/delta-rs#1858]
# Description

**Use Case**

There are a lot of features and bug fixes in object_store 0.8, when it will upgrade?

**Related Issue(s)**

**Comment by rtyler** [comment]
We're more or less beholden to our transitive dependencies like  [datafusion](https://crates.io/crates/datafusion/32.0.0/dependencies) upgrading unfortunately.

I'm hoping to see a datafusion 33 in the next week or two

**Comment by RobinLin666** [comment]
> We're more or less beholden to our transitive dependencies like [datafusion](https://crates.io/crates/datafusion/32.0.0/dependencies) upgrading unfortunately.
> 
> I'm hoping to see a datafusion 33 in the next week or two

Hi @rtyler, I saw the [datafusion](https://crates.io/crates/datafusion/33.0.0/dependencies) 33 is ready, but it still use 0.7 object_store, it means that delta-rs can only use 0.7 version of object_store? :-(

**Comment by ion-elgreco** [comment]
@rtyler :)
