### ISSUE TITLE
Add a Rust-backed engine for write_deltalake

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#1861]
# Description

Right now we've built on top of the PyArrow writers. This requires a lot of complex code that is essentially duplicating logic in Rust. The main motivation for writing it was that the Rust implementation wasn't ready, so it was faster to build on top of PyArrow. That might not be true anymore.

We can update the signature of `write_deltalake()` to take an `engine` parameter (sort of like how Pandas [read_parquet](https://pandas.pydata.org/docs/reference/api/pandas.read_parquet.html) has this parameter), which would let users choose to use the pyarrow engine or the Rust engine for now. Eventually we can switch the default and deprecate the pyarrow implementation.

We should be on the lookout for issues that block this. First, we need to make sure the same unit tests pass with the new writer. So we should parametrize all tests by the engine.

Second, we should be on the lookout for performance issues. We have a set of benchmarks here: https://github.com/delta-io/delta-rs/blob/56a97289201dc05ca2a1a94953b82efdc6bb3b5f/python/tests/test_benchmark.py#L28, which we can add to. One known issue (that might have been solved) is: https://github.com/delta-io/delta-rs/issues/1225

**Use Case**

**Related Issue(s)**

**Comment by roeap** [comment]
we should use this opportunity to also consolidate our writer implementations. right now we have one in `/writer` as well as `/operations/writer`. The one in operations being the newer one. Originally it was meant to have two implementations only for a short while, but this has been the case for many months now 😆.

The `/writer` one was mainly kept around to keep supporting the kafka-delta-ingest use case to also be able to writer json data.

**Comment by ion-elgreco** [comment]
@roeap I am mainly exposing operations/write to Python, not writer

**Comment by roeap** [comment]
I'll re-open this to keep track until we have a more full-featured rust writer?

**Comment by ion-elgreco** [comment]
@roeap yeah good one!
