### ISSUE TITLE
Fix docs deployment

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#1867]
# Description

https://github.com/delta-io/delta-rs/actions/runs/6880582444/job/18715123279

Likely a matter of which credentials the job is running under.

**Use Case**

**Related Issue(s)**

**Comment by r3stl355** [comment]
I need to do some experiments with this.

@wjones127 do you have write access to `gh-pages` branch? (I presume you do). 

The failing action is https://github.com/JamesIves/github-pages-deploy-action, responsible for deploying the build results to a `gh-pages` branch. According to the action's docs, `you must ... provide Read and Write Permissions to the provided GITHUB_TOKEN` but I am not sure which GITHUB_TOKEN was used when the action was triggered manually. 
Previous deployment scripts used `github.GITHUB_TOKEN` to do the same.

The action has a `token` property which I can try setting to `github.GITHUB_TOKEN` but I am not sure it will make any difference as it seems to be a default value.

The other alternative is to add `permissions: contents: write` to the action - that should work but will result in a longer script as I'd have create a separate step for deployment.

Lastly, during the release process docs release is run as a dispatched/async job so even if it fails, the main release should not be effected.

**Comment by r3stl355** [comment]
take
