### ISSUE TITLE
Organize docs with single lefthand sidebar

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#1873]
Can we please add a single lefthand navigation to the docs?  Something like this:

```
Home
Installation
Usage
  Overview
  Loading a Delta Table
  Examining a Delta Table
  Querying a Delta Table
  Managing a Delta Table
  Writing Delta Tables
API Reference
```

**Comment by r3stl355** [comment]
This can be done but it will also change how the rest of the pages look, e.g top navigation menus. This is all driven by the `theme`. Currect version is using `material` which is popular at the moment. We can choose a style and make our own modifications but we need to choose the overall desired design before making changes to sections.

**Comment by MrPowers** [comment]
I am moving the installation guide to the Usage section that will fix this issue: https://github.com/delta-io/delta-rs/pull/1875
