### ISSUE TITLE
Implementing CHECK constraints 

### ISSUE THREAD

**Issue by hntd187** [delta-io/delta-rs#1881]
# Description

As part of 3,7 support, implement check constraints on tables. #1568 @MrPowers could you please assign me this so others know

**Use Case**

**Related Issue(s)**
#1568

**Comment by ion-elgreco** [comment]
@hntd187 you can write 'take'

**Comment by hntd187** [comment]
take

**Comment by MrPowers** [comment]
@r3stl355 - I love "take".  Thank you!!
