### ISSUE TITLE
Add documentation on how to build and run documentation locally

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#1893]
# Description

The documentation can be run locally when the right packages are installed and commands are run.

Here's my understanding of the steps:

```
cd python
make develop
cd ..
mkdocs serve
```

We should document these steps, perhaps in the [CONTRIBUTING.md](https://github.com/delta-io/delta-rs/blob/main/CONTRIBUTING.md) file?

**Comment by r3stl355** [comment]
you also need to install the docs requirements first time you run it, here is the full script
```
(cd python; make develop)
pip install -r docs/requirements.txt
mkdocs serve
```

**Comment by r3stl355** [comment]
take
