### ISSUE TITLE
docs: Delta Lake + Polars integration

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#1906]
# Description

Add a docs page for the Delta Lake + Polars integration

**Comment by MrPowers** [comment]
@ion-elgreco - would you like to grab this one?

**Comment by ion-elgreco** [comment]
@MrPowers Sure! I'll write one after I've done some upstream changes in polars wrt MERGE

**Comment by MrPowers** [comment]
@ion-elgreco - awesome, sounds great.  jfyi, these integration pages are designed to be updated as interfaces evolve.  So we can write one now that explains `read_delta` and `scan_delta` and then update it with the merge section later.  No rush of course, just adding this detail!

**Comment by ion-elgreco** [comment]
@MrPowers makes sense, those sections I could already do, let me look at that next week :)

**Comment by MrPowers** [comment]
This was added: https://delta-io.github.io/delta-rs/integrations/delta-lake-polars/

@ion-elgreco - would you like me to keep this one open or should we close it for now?
