### ISSUE TITLE
Rethink the load_version and load_with_datetime interfaces

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#1910]
# Description

There are currently a few different interfaces for time traveling:

Option 1:

```python
DeltaTable("some_path", version=1)
```

Option 2:

```python
dt = DeltaTable("some_path")
dt.load_version(1)
```

Option 3:

```python
dt = DeltaTable("some_path")
dt.load_with_datetime("2018-01-26T18:30:09Z")
```

We should consider providing a single interface:

```python
dt = DeltaTable("some_path").time_travel(version=1)
dt = DeltaTable("some_path").time_travel(version_as_of="2018-01-26T18:30:09Z")
```

I don't think methods like these should be limited to only taking string arguments: `load_with_datetime(datetime_string: str)`

Users should be able to pass in Python date and datetime objects as well.

**Comment by ion-elgreco** [comment]
Good one, we can perhaps consolidate the load_version and load_with_datetime into a single function:

`DeltaTable.load_to(version: int | datetime)`
