### ISSUE TITLE
Python Bug: "No type alias for floatingpoint"

### ISSUE THREAD

**Issue by mattc-eostar** [delta-io/delta-rs#192]
#Environment

**Delta-rs version**: 0.4.5

**Binding**: python

**Environment**:
- **Cloud provider**: Azure
- **OS**: MacOS (Intel)
- **Other**:

***
#Bug

**What happened**: Attempted to load a delta table written by Spark on Azure Databricks. The file is written successfully and the parquet file can be listed through DeltaTable.files() in this binding. When trying to convert to a pyarrow dataset, it says there is no alias for floatingpoint datatype. The file has a couple hundred columns so not sure yet which column it is, but I would imagine it should be able to map this datatype just like any other data type.

**What you expected to happen**: I expected a PyArrow dataset to be created so I can call to_table with some filters to grab the necessary data. I'm not sure how a validly created Delta table would have trouble being read by this library. It does not seem like a complex datatype to map or cast during conversion.

**How to reproduce it**:
```python
from deltalake import DeltaTable

dt = DeltaTable(f'abfss://{container_name}@{storage_options["account_name"]}.dfs.core.windows.net/datasets/{datasets["customers"]}')
dt.to_pyarrow_dataset()
```

**More details**:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/anaconda3/envs/main/lib/python3.6/site-packages/pyarrow/types.pxi in pyarrow.lib.type_for_alias()

KeyError: 'floatingpoint'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-206-e63261d47564> in <module>
----> 1 dt.to_pyarrow_dataset()
~/anaconda3/envs/main/lib/python3.6/site-packages/deltalake/table.py in to_pyarrow_dataset(self)

~/anaconda3/envs/main/lib/python3.6/site-packages/deltalake/table.py in pyarrow_schema(self)

~/anaconda3/envs/main/lib/python3.6/site-packages/deltalake/schema.py in pyarrow_schema_from_json(json_data)

~/anaconda3/envs/main/lib/python3.6/site-packages/deltalake/schema.py in <listcomp>(.0)

~/anaconda3/envs/main/lib/python3.6/site-packages/deltalake/schema.py in pyarrow_field_from_dict(field)

~/anaconda3/envs/main/lib/python3.6/site-packages/deltalake/schema.py in pyarrow_datatype_from_dict(json_dict)

~/anaconda3/envs/main/lib/python3.6/site-packages/pyarrow/types.pxi in pyarrow.lib.type_for_alias()

ValueError: No type alias for floatingpoint
```

**Comment by houqp** [comment]
Interesting, @fvaleye I am guessing this is coming from https://github.com/delta-io/delta-rs/blob/main/python/deltalake/schema.py#L256?

**Comment by houqp** [comment]
yep, looks like we need to match the float column types using `name = floatingpoint` and `precision` key instead: https://github.com/apache/arrow/blob/master/rust/arrow/src/datatypes/datatype.rs#L363-L365.

**Comment by mattc-eostar** [comment]
This a list of unique datatypes in the DeltaTable schema before converting to PyArrow:
```
{'DataType(binary)',
 'DataType(boolean)',
 'DataType(decimal(38,18))',
 'DataType(double)',
 'DataType(integer)',
 'DataType(short)',
 'DataType(string)',
 'DataType(timestamp)'}
```
Is it the decimal datatype?

**Comment by houqp** [comment]
@mattc-eostar it's mostly coming from the double type, based on delta spec, this is defined as float64, in other words, floatingpoint with double precision: https://github.com/delta-io/delta/blob/master/PROTOCOL.md#primitive-types.

This should be a fairly straight forward fix in `pyarrow_datatype_from_dict` :)

**Comment by houqp** [comment]
here are all the type aliases in pyarrow: https://github.com/apache/arrow/blob/master/python/pyarrow/types.pxi#L2567

**Comment by fvaleye** [comment]
Thanks for detecting this @mattc-eostar 👍, we missed the `floatingpoint` data type in pyarrow
