### ISSUE TITLE
Python v0.14 wheel files not up to date

### ISSUE THREAD

**Issue by GraemeBrownTL** [delta-io/delta-rs#1945]
Windows 10
Rust 0.14

**Binding**: Sorry, not sure what this means 

Cloud Platform: Azure Synapse

I have upgraded to v0.14 via "pip install...", however deltalake.__version__ still shows 0.13.

I expected to see deltalake.__version__ = 0.14

I suspect that the pypi wheel file is not correctly updated.

I have compared my local copy of table.py under .../my_env/site-packages/deltalake... with table.py in the .tar.gz file at https://pypi.org/project/deltalake/#modal-close, and they are different. Similarly, I compared the code in table.py from the (unzipped) .whl file available at the same page, with the source code in the .gz file, and they are different. The .whl file matches my local .../site-packages/... file, so I believe that the 'pip upgrade' worked.

**Comment by ion-elgreco** [comment]
I do see the deltalake. Did you run pip install --upgrade deltalake?

![image](https://github.com/delta-io/delta-rs/assets/15728914/2e8b9d05-9b08-4fa8-9cc0-64f9091b1785)

**Comment by GraemeBrownTL** [comment]
Yes, I did run that.

![image](https://github.com/delta-io/delta-rs/assets/76975934/3b31dd80-784e-498b-9a82-247e51032947)

![image](https://github.com/delta-io/delta-rs/assets/76975934/dcefebba-0c8c-49f6-bac4-cd24b0e0ecff)

**Comment by ion-elgreco** [comment]
![image](https://github.com/delta-io/delta-rs/assets/15728914/deb38098-9509-4e68-9838-cc98defab4c4)

**Comment by GraemeBrownTL** [comment]
It is working now. Not sure what changed!
