### ISSUE TITLE
Unable to merge uppercase column names

### ISSUE THREAD

**Issue by gdubya** [delta-io/delta-rs#1960]
# Environment
**Delta-rs version**:
python = "^3.11"
deltalake = "^0.13.0"
pandas = "^2.1.3"

**Environment**:
- **OS**: Ubuntu

***
# Bug

**What happened**:
`_internal.DeltaError: Generic DeltaTable error: Schema error: No field named source.y. Valid fields are source.x, source."Y", source.__delta_rs_source, target.x, target."Y", target.__delta_rs_target.
`

**What you expected to happen**:
Successful merge.

**How to reproduce it**:
```
    from deltalake import DeltaTable, write_deltalake
    import pyarrow as pa
    data = pa.table({"x": [1, 2, 3], "Y": [4, 5, 6]})
    write_deltalake(tmp_path, data)
    dt = DeltaTable(tmp_path)
    new_data = pa.table({"x": [1], "Y": [7]})
    (
        dt.merge(
            source=new_data,
            predicate="target.x = source.x",
            source_alias="source",
            target_alias="target")
        .when_matched_update_all()
        .execute()
    )

```
**More details**:
Note that the delta table was originally created with an uppercase `Y` column. This was intentional.

**Comment by ion-elgreco** [comment]
This is already tracked here: https://github.com/delta-io/delta-rs/issues/1797

And a fix is on its way:

**Comment by ion-elgreco** [comment]
@gdubya btw, i suggest upgrading to 0.14.0 it's way faster (the case bug is still there though in that release)

**Comment by gdubya** [comment]
Ah, sorry. I did a quick search but didn't see that one. Thanks!

**Comment by ion-elgreco** [comment]
@gdubya no worries! Hopefully soon in a small 0.14.1 release we can release the fix
