### ISSUE TITLE
Constraint expr not formatted during commit action

### ISSUE THREAD

**Issue by ion-elgreco** [delta-io/delta-rs#1971]
Currently when you write a constraint expr, the expr is not formatted on write, so you could end up with these expressions in the log: 

`'delta.constraints.value_gt_5': 'foo         >0',`

Maybe it's good if we format them before writing.

**Comment by Blajda** [comment]
take

**Comment by scarman-db** [comment]
Okay so this is why there were bits that confused me when I looked at the check constraint impl today. :-D thanks @Blajda appreciate the help here
