### ISSUE TITLE
Use commitinfo timestamp instead of file medata timestamp to get version

### ISSUE THREAD

**Issue by ion-elgreco** [delta-io/delta-rs#1972]
Currently we look at the file metadata last modified instead of the timestamp from the transaction log itself: 
```rust

   pub(crate) async fn get_version_timestamp(
        &mut self,
        version: i64,
    ) -> Result<i64, DeltaTableError> {
        match self.version_timestamp.get(&version) {
            Some(ts) => Ok(*ts),
            None => {
                let meta = self
                    .object_store()
                    .head(&commit_uri_from_version(version))
                    .await?;
                let ts = meta.last_modified.timestamp_millis();
                // also cache timestamp for version
                self.version_timestamp.insert(version, ts);
                
                Ok(ts)
            }
        }
```
We should take the timestamp from the transaction log instead.

**Comment by rtyler** [comment]
I don't believe we can safely do this. The [protocol states](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#commit-provenance-information)

> Implementations are free to store any valid JSON-formatted data via the commitInfo action.

The fact that conventionally the Delta/Spark and Delta/Rust writers are placing a `timestamp` field in the `commitInfo` JSON is not guaranteed by the protocol definition. 

Unfortunately, I don't think we can do this without violating the protocol. 

I am curious what the use-case is here? Are you trying to avoid a HEAD call to storage, or is there a scenario where the last modified on the object is substantially different from the timestamp optionally recorded in `commitInfo`?

**Comment by ion-elgreco** [comment]
@rtyler ah I did not know that, I thought timestamp was part of the protocol definition. I just thought it was odd to not use the timestamp since it is in the transaction log.

Also, there is some flakiness in the test `restore_by_datetime` and it occurs exclusively on MacOS, so I thought maybe MacOS writes the modified date at a slightly different point in time compared to the rest.
