### ISSUE TITLE
store userMetadata on write operations

### ISSUE THREAD

**Issue by resulyrt93** [delta-io/delta-rs#1990]
# Description
With spark deltalake we can store userMetadata with write operations, thus we can access them in delta history. It can be an arbitrary json data. Is there a way to store it with delta-rs python binding? Doc [link](https://books.japila.pl/delta-lake-internals/delta/options/#usermetadata)

**Use Case**
In our case, we want to store user data with write operation to match transaction with user.

**Related Issue(s)**
https://github.com/delta-io/delta-rs/issues/133

**Comment by ion-elgreco** [comment]
Should be trivial to expose, I can take a look at it after new years eve

**Comment by r3stl355** [comment]
Can `userMetadata` be added to `app_metadata` before being passed to `commit` (unless it is already the same thing and just needs to be exposed to Python)? Adding a new parameter to `commit` would touch many operations. 
I am working on https://github.com/delta-io/delta-rs/issues/1957 so can also look into this after I'm done there

**Comment by cekicbaris** [comment]
+ 
this is exactly what we need.

**Comment by ion-elgreco** [comment]
@r3stl355 it's the same thing, see my PR: https://github.com/delta-io/delta-rs/pull/1994

![image](https://github.com/delta-io/delta-rs/assets/15728914/a3701544-0663-4c51-899a-736945ed97a0)

**Comment by r3stl355** [comment]
cool, so this doesn't touch Rust at all, nice
