### ISSUE TITLE
Conda version 0.15.0 is missing files

### ISSUE THREAD

**Issue by echai58** [delta-io/delta-rs#2021]
# Environment

**Delta-rs version**: 0.15.0

**Binding**: python

- **OS**: linux

***
# Bug

**What happened**: if you conda install deltalake 0.15.0, you are unable to use the package because the code is missing in the package source files.

**How to reproduce it**: download deltalake 0.15.0 via conda, and `from deltalake import DeltaTable` will fail. If you look at the deltalake directory in the conda environment, you will see all the files are missing.

0.15.0 installs fine via pip, so would like it to work via conda as well.

**Comment by ion-elgreco** [comment]
@echai58 we don't maintain those conda-forge channels, you can create an issue here: https://github.com/conda-forge/deltalake-feedstock/issues

**Comment by echai58** [comment]
> @echai58 we don't maintain those conda-forge channels, you can create an issue here: https://github.com/conda-forge/deltalake-feedstock/issues
> 
> I also installed it through conda-forge with no issue, maybe try rebuilding your env.

Are you on linux? what python version?

**Comment by ion-elgreco** [comment]
@echai58 I tried it on Windows since I had conda there
