### ISSUE TITLE
Hash for StructField should consider more than the name

### ISSUE THREAD

**Issue by rtyler** [delta-io/delta-rs#2045]
Two StructFields with the same name but different data_types are considered to hash equivalently, which I think is incorrect.

I'm working around this for now, but filing for @roeap and I to discuss later

**Comment by roeap** [comment]
Agreed, in fact, `name`, `data_type` and `nullability` should match for a field to be considered equivalent.

**Comment by sonhmai** [comment]
take

**Comment by sonhmai** [comment]
@rtyler: I added PR to fix this.
