### ISSUE TITLE
API to return full table history

### ISSUE THREAD

**Issue by houqp** [delta-io/delta-rs#205]
# Description

**Use Case**

See https://docs.delta.io/0.8.0/delta-utility.html#retrieve-delta-table-history

**Comment by nfx** [comment]
i'll look into it

**Comment by Smurphy000** [comment]
@nfx Are you still working this? I noticed the PR that is up when I was looking for a way to get table history but it has been a few months.

**Comment by xuky76** [comment]
@houqp I think this might be able to be closed out 

# Related issue

- closed in PR #428 

# Documentation
[Docs](https://docs.rs/deltalake/latest/deltalake/delta/struct.DeltaTable.html#method.history)
