### ISSUE TITLE
Error while writing Pandas DataFrame to Delta Lake (S3)

### ISSUE THREAD

**Issue by vinamrgrover** [delta-io/delta-rs#2051]
# `write_deltalake` isn't working as expected

I encountered an error while calling `write_deltalake` method:

```ValueError : you must provide schema if data is iterable```

Even though it worked perfectly with a PyArrow Table, it didn't work for Pandas DataFrame. 

**How to reproduce it**:
```
# To reproduce it, just try to write a Pandas DataFrame to an S3 Bucket

write_deltalake(
    <your_s3_url>,
    data = df,
    storage_options = storage_options,
    overwrite_schema = True,
    mode = 'overwrite'
)
```

**Comment by ion-elgreco** [comment]
@vinamrgrover please provide the deltalake version you're using

**Comment by vinamrgrover** [comment]
Version : `0.15.0`

I already shared a reproducible example above

**Comment by ion-elgreco** [comment]
@vinamrgrover a reproducible example should also include a sample dataframe

**Comment by ion-elgreco** [comment]
You are likely passing something that is not a pandas dataframe, I can write a pandas dataframe with write_deltalake.

```python
import pandas as pd
from deltalake import write_deltalake
df = pd.DataFrame({'foo':['test']})
write_deltalake('test_table_PATH', data=df, mode='overwrite', overwrite_schema=True)
```

**Comment by vinamrgrover** [comment]
Please don't mark it as completed, I better know I have passed Pandas DataFrame in `write_deltalake` method. I think the issue is with the `_has_pandas` variable within `writer.py` module. Try executing this in a new virtual environment

**Comment by topagarwal** [comment]
I am also having similar issue. I read data from deltaWriter, converted to pandas dataframe, filtered some data and then writing it back to a different S3 location. When writing it gives me ValueError, schema of Data and Table does not match. I verified by printing schema of both, they are same. Not sure why its not letting me write.

**Comment by ion-elgreco** [comment]
> I am also having similar issue. I read data from deltaWriter, converted to pandas dataframe, filtered some data and then writing it back to a different S3 location. When writing it gives me ValueError, schema of Data and Table does not match. I verified by printing schema of both, they are same. Not sure why its not letting me write.

Which version are you using? Also create an MRE so we can reproduce it

**Comment by topagarwal** [comment]
I'm using Delta lake v 0.17.0
Here are the steps i did:
1. Read in the DeltaTable from existing S3 location. dt = DeltaTable("s3://mylocation/")
2. Converted it to pyarrow table. arrow_table = dt.to_pyarrow_table()
3. Filtered the arrow table and selected specific columns of interest
4. Converted arrow table to pandas data frame. df = arrow_table.to_pandas()
5. Writing panda dataframe back to existing new delta table. Table is empty at this point.
6.  write_deltalake("s3://test_sample_process/", df, mode="append"). also tried it with schema_mode="overwrite"

To trouble shoot it I looked into deltalake/writer.py file. The Exception is thrown form ln 351. It is trying to sort the data schema and table schema and then match them. It is using pyarrow engine.

The output of matching is 
```

Table is expecting schema

ki_record_name: string
kt_config: string
kt_parameters: string
m_updated_at: timestamp[us, tz=UTC] not null
  -- field metadata --
  comment: '"The time this record was updated"'
m_updated_by: string not null
  -- field metadata --
  comment: '"The process that updated this record"'
namespace: string
work_center: string not null and 

Data is of schema 

ki_record_name: string
kt_config: string
kt_parameters: string
m_updated_at: timestamp[us, tz=UTC]
m_updated_by: string
namespace: string
work_center: string
```

I couldn't isolate the difference in 2 schemas other than table schema as comment and not null defined. The field names and data types are same for both. Wondering what I am missing here.
