### ISSUE TITLE
Potential memory leak on write

### ISSUE THREAD

**Issue by sebastianfuchsprivate** [delta-io/delta-rs#2068]
# Environment

**Delta-rs version**:
0.15.1

**Binding**: 
python

**Environment**:
- **Cloud provider**: Azure
- **OS**: Linux

***
# Bug

**What happened**:
We're running a python websockets subscriber which puts data into a local queue. Every 2-3 seconds a seperate thread is fired to take the content from the queue and appends it back to deltalake storage using dl.write_deltalake(). The queue is flushed afterward.
After about 15K cycles we're seeing an memory usage increase from initially ~1 GB to ~1.5 GB which permanently grows.

**What you expected to happen**:
Mem usage staying constant.

**How to reproduce it**:
Do permanent payload cylced appending writes to a deltalake.

**More details**:
Assuming the mem leak happens somewhere in write_deltalake(), When using the thread monitoring I do see a lot of "tokio-runtime" & "jemalloc_bg" threads.

**Comment by wjones127** [comment]
Hi @sebastianfuchsprivate. Data written with `write_deltalake()` is always at some point goes through PyArrow. From experience, often memory leak reports boil down to folks not understanding how memory pools like Jemalloc work. When objects are deleted, memory pools will hold onto the memory for several minutes in case the program has a new allocation it needs it for.

You can disable memory pools in PyArrow by setting the environment variable `export ARROW_DEFAULT_MEMORY_POOL=system`. **Could you try that and check your memory usage again?**

**Comment by sebastianfuchsprivate** [comment]
@wjones127 - thank you for the hint, just restarted the python program witrh the env var set.
Current mem usage  (RES) at 953.872, will watch it in the next few days.

**Comment by sebastianfuchsprivate** [comment]
@wjones127 - ran it now for several days: it behaves much better on mem consumption although it's not completly gone. After ~35K cycles we're now at min 1.3 GB usage - so I assume something is still eating up mem. I'll try to keep it running to see if this is increasing permanently.

**Comment by ion-elgreco** [comment]
@sebastianfuchsprivate can we close this one?

**Comment by sebastianfuchsprivate** [comment]
using ARROW_DEFAULT_MEMORY_POOL=system minimized the memory consumption increase significantly.
