### ISSUE TITLE
Refactor commit interface to be a Builder

### ISSUE THREAD

**Issue by Blajda** [delta-io/delta-rs#2131]
# Description
Currently  [commit](https://github.com/delta-io/delta-rs/blob/0f6790fd90be869990f55379514339eb09280ba3/crates/deltalake-core/src/operations/transaction/mod.rs#L174-L180) is not a builder which results in a brittle interface whenever new commit options are added. Refactor to be a builder so code changes are isolated to the module and don't require updates in all operations. 

Operation should be updated to delegate to this builder but must keep some members like `log_store` and `operation` private.

**Related Issue(s)**
#2130 - Implementing Txn identifiers would require adding a new parameter to the current function and break various call sites.

**Comment by hntd187** [comment]
take
