### ISSUE TITLE
Unable to retrieve custom metadata from tables in rust

### ISSUE THREAD

**Issue by universalmind303** [delta-io/delta-rs#2153]
# Environment

**Delta-rs version**:

**Binding**: 

**Environment**:
- **Cloud provider**:
- **OS**:
- **Other**:

***
# Bug

**What happened**:
AFAIK, there is no programmatic access to custom metadata written.
```rs
use std::sync::Arc;
use deltalake::{
    kernel::DataType as DeltaDataType,
    kernel::PrimitiveType,
    logstore::default_logstore, operations::create::CreateBuilder, protocol::SaveMode, storage::object_store::local::LocalFileSystem
};

use serde_json::json;
use url::Url;
#[tokio::main]
async fn main() {
    let path = tempfile::tempdir().unwrap();
    let path = path.into_path();
    
    let file_store = LocalFileSystem::new_with_prefix(path.clone()).unwrap();
    let log_store = default_logstore(
        Arc::new(file_store),
        &Url::from_file_path(path.clone()).unwrap(),
        &Default::default(),
    );

    let tbl = CreateBuilder::new()
        .with_log_store(log_store.clone())
        .with_save_mode(SaveMode::Overwrite)
        .with_metadata(vec![("my_custom_metadata".to_string(), json!({"key": "value"}))])
        .with_table_name("test")
        .with_column(
            "id",
            DeltaDataType::Primitive(PrimitiveType::Integer),
            true,
            None,
        );
    let tbl = tbl.await.unwrap();
    // how to get the metadata out of `tbl`?
}
```

How to get the metadata out of `tbl`?
`DeltaTable.config` does not have the app_metadata
`DeltaTable.state.unwrap()` does not have the app_metadata
`DeltaTable::metadata()` does not have the app_metadata

**What you expected to happen**:
Some way to retrieve the metadata
**How to reproduce it**:
See above
**More details**:
I can manually inspect the json file & it is getting written, but I have no way to retrieve it after it's been written.

**Comment by abhiaagarwal** [comment]
take

**Comment by abhiaagarwal** [comment]
After a bit of research, I think what you're looking for is `DeltaTable::history()`? It returns a `Vec<CommitInfo>`, which has the underlying metadata associated.

**Comment by ion-elgreco** [comment]
As @abhiaagarwal mentioned you need to fetch the commitInfo from history, also app metadata afaik is not preserved after checkpointing
