### ISSUE TITLE
Bug/Question:  arrow's`FixedSizeList` is not roundtrippable

### ISSUE THREAD

**Issue by universalmind303** [delta-io/delta-rs#2162]
# Bug

**What happened**:

Currently if you try to write an arrow `FixedSizeList` using delta, the original type is converted to a list. I'm wondering if this is a bug or intentional. Are there any suggested workarounds for working with arrow `FixedSizeList` without losing the fixed size? 

**What you expected to happen**:
I'd expect being able to roundtrip arrow's `FixedSizeList` to/from delta without losing the original type. 

**How to reproduce it**:

**More details**:

**Comment by ion-elgreco** [comment]
Intentional, the delta primitive types doesn't have a fixedsizedlist/array, only list
