### ISSUE TITLE
cleanup_metadata can potentially delete most recent checkpoint, corrupting table

### ISSUE THREAD

**Issue by cmackenzie1** [delta-io/delta-rs#2174]
# Environment

**Delta-rs version**: v0.16 (havent' tried latest version yet)

**Binding**: rust

***
# Bug

**What happened**:
The most recent checkpoint file was deleted during regularly scheduled vacuum/cleanup, corrupting the table. I ran into this issue but haven't had time to look into it. Filing this so it doesn't get forgotten :)

**What you expected to happen**:
Most recent checkpoint should never be deleted. 

**How to reproduce it**:
1. Create table and checkpoint it
2. Set log retention period to 1s
3. Wait 1s and then run `cleanup_metadata`
4. Most recent checkpoint is deleted. 

**More details**:

**Comment by ion-elgreco** [comment]
@cmackenzie1 recently there was a bufix for cleanup_metadata, can you try 0.17 or use the latest python version?

**Comment by cmackenzie1** [comment]
@ion-elgreco yeah, looks like it was fixed in https://github.com/delta-io/delta-rs/commit/25040b8858c7c2cbd2e9a6fba6132452b708a699!
