### ISSUE TITLE
Unsigned numbers seem to be getting mapped to Signed counterparts

### ISSUE THREAD

**Issue by dnsco** [delta-io/delta-rs#2175]
# Environment

**Delta-rs version**:
0.17 (and 0.16.5)

**Binding**: 

**Environment**:
- **Cloud provider**:
- **OS**: Linux

- **Other**:

***
# Bug

**What happened**:
I have a macro that generates an arrow schema for a struct the meat of it is:
```
let result = match ty_str {
        ...,
        "u8" => parse_str::<Type>("::deltalake::arrow::datatypes::DataType::UInt8"),
        "u16" => parse_str::<Type>("::deltalake::arrow::datatypes::DataType::UInt16"),
        "u32" => parse_str::<Type>("::deltalake::arrow::datatypes::DataType::UInt32"),
    };
```

this was working fine when I was making parquet files, but now that I have deltalake-rs, the fields seem to be getting coerced into Int8s.

This seems to be working fine for the first batch, but failing on successive batches, it seems like maybe if all the uints will fit in int space it will work.

one example error is: 

`Failed to convert into Arrow schema: Json error: whilst decoding field 'minValues': whilst decoding field 'output_enable': failed to parse 170 as Int8`

where output_enable is a u8 field on our side, the relevant section of the first schemaString is: `{\"name\":\"output_enable\",\"type\":\"byte\",\"nullable\":false,\"metadata\":{}}`.

**What you expected to happen**:

**How to reproduce it**:

**More details**:

**Comment by ion-elgreco** [comment]
Unsigned integers are not valid primitive types in deltalake, in the python binding we try to cast to integer

**Comment by dnsco** [comment]
going down the rabbit hole: I found that there apparently is some schema conversion that happens in python and I gess not rust https://github.com/delta-io/delta-rs/blob/1dba7e5a2d39b42a58abd83f0805524c59ceda1c/python/deltalake/schema.py#L19

Apparently every column in deltalake has to be signed because java :'( https://github.com/delta-io/delta/blob/master/PROTOCOL.md#primitive-types

**Comment by dnsco** [comment]
So I guess to use this library from rust requires your arrow schema be delta-compatible :'(

**Comment by dnsco** [comment]
It also seems likely that the number 170 pyarrow u8 recordbatch would cause errors in python.

**Comment by ion-elgreco** [comment]
> It also seems likely that the number 170 pyarrow u8 recordbatch would cause errors in python.

It will, the cast from uint to int is tried if it doesn't fit, you simply need to explicitly cast
