### ISSUE TITLE
Add error message for parition_by check

### ISSUE THREAD

**Issue by braaannigan** [delta-io/delta-rs#2177]
Great work on this project!

I triggered the assertion error below. However, as there is no string message after the assertion I get no indication of what went wrong from logging

**Delta-rs version**:
0.15.1

**Environment**:
MacOS

***
# Bug

**What happened**:
I hit this assertion check in write_deltalake:
```python
assert partition_by == table.metadata().partition_columns
```

**What you expected to happen**:
Produce a string to explain what the error is (and preferably how it might be avoided)

**Comment by ion-elgreco** [comment]
@braaannigan if you want you can open a small PR for it? :) A helpful error message is more than welcome
