### ISSUE TITLE
Error when parsing delete expressions

### ISSUE THREAD

**Issue by mortnstak** [delta-io/delta-rs#2187]
# Environment

**Delta-rs version**:0.15.3

**Binding**: python

**Environment**:
- **Cloud provider**: Azure
- **OS**: Windows 11
- **Other**:

***
# Bug

**What happened**: When executing delete operation on a column of type int32, I get
`ValueError: Invalid comparison operation: Int32 <= Int64`

**What you expected to happen**:
I would expect the function to be able parse the integer to a Int32

**How to reproduce it**:

```
from deltalake import DeltaTable, write_deltalake
fromdeltalake.exceptions import DeltaError, DeltaProtocolError, TableNotFoundError, CommitFailedError
import pyarrow as pa
try:
    table_uri = "testdelete"
    ids = pa.array([1,2,3,4], pa.int32())
    names = ["id"]
    data = pa.Table.from_arrays([ids], names = names)
    write_deltalake(table_uri, data, mode='overwrite')
    dt = DeltaTable(table_uri)
    dt.delete("id = 1")
except DeltaError as e:
    print(e)
```

**More details**: Also - need to be able to parse timestamp expressions in delete statements. For instance expressions on the form
`table.delete(f"timestamp < '2024-1-1'")`. This currently generates the following error: 
`ValueError: Invalid comparison operation: Timestamp(Microsecond, None) < Utf8`

Current workaround is to use merge statements.

**Comment by ion-elgreco** [comment]
This is actually related to this one: https://github.com/delta-io/delta-rs/issues/1921, so will close this one as duplicate

**Comment by gprashmi** [comment]
@mortnstak How did you resolve this issue? I have the same issue with table.delete(predicate) for timestamp 
ValueError: Invalid comparison operation: Timestamp(Microsecond, None) < Utf8
