### ISSUE TITLE
slack invite

### ISSUE THREAD

**Issue by rm-vg** [delta-io/delta-rs#219]
# slack access

Hi, the slack link in the readme (<https://join.slack.com/t/delta-users/shared_invite/enQtODQ5ODM5OTAxMjAwLWY4NGI5ZmQ3Y2JmMjZjYjc1MDkwNTA5YTQ4MzhjOWY1MmVjNTM2OGZhNTExNmM5MzQ0YzEzZjIwMjc0OGI0OGM>) redirects to a sign-in page that doesn't allow me to log in with my slack account (I have one, using work email). 
It seems to be for people with a @databricks email account only. (see screenshot)
Is there a different location for public access or could the slack channel be made public somehow by providing the invite link ? 
This is not to actively collaborate, more to follow development to possibly use the library later. 
Thanks! 

**Related Issue(s)**
![image](https://user-images.githubusercontent.com/81195686/116445578-56180280-a856-11eb-91e9-6c06c8b286dd.png)

**Comment by rtyler** [comment]
@rm-vg try [this link](https://dbricks.co/delta-users-slack) from delta.io, if that works, I'll update the readme

**Comment by rm-vg** [comment]
Hi, thanks for the quick response. 
That link works for me :-)
