### ISSUE TITLE
`TableNotFoundError` on `DeltaTable.create(...)`

### ISSUE THREAD

**Issue by rspears74** [delta-io/delta-rs#2195]
# Environment

**Delta-rs version**: 0.15.1

**Binding**:  Python

**Environment**:
- **Cloud provider**: AWS
- **OS**: MacOS
- **Other**: Running in Github Action

***
# Bug

**What happened**:
I am calling `DeltaTable.create` with an S3 path. I get a `TableNotFoundError`.

**What you expected to happen**:
I expect a table to be created at the path I'm specifying.

**How to reproduce it**:
Use `DeltaTable.create(...)` (maybe with an S3 path?)

**More details**:

**Comment by ion-elgreco** [comment]
It would help if you can provide more details, what is the exact code you're running. Something that we can reproduce as well

**Comment by LoicRaillon** [comment]
I'm facing the same issue, which is reproducible with the API doc example
```python
import pyarrow as pa

from deltalake import DeltaTable

dt = DeltaTable.create(
    table_uri="my_local_table",
    schema=pa.schema(
        [pa.field("foo", pa.string()), pa.field("bar", pa.string())]
    ),
    mode="error",
    partition_by="bar",
)
```

**Comment by ion-elgreco** [comment]
@rspears74 the reason it throws a tableNotFoundError is because at the end of creation it's trying to read the table after creation.

I also use S3 but I don't run into this issue so perhaps it's some permission issue?

**Comment by rspears74** [comment]
@ion-elgreco See this comment https://github.com/delta-io/delta-rs/issues/2195#issuecomment-1955192136

**Comment by ion-elgreco** [comment]
@rspears74 have you tried it against the latest version also?

**Comment by rspears74** [comment]
@ion-elgreco I have not, I'm no longer working with delta-rs (this was over a month ago, and the most recent version at the time was `0.15.1`). I don't have time to investigate further right now, but I expect you could potentially reproduce my issue by trying to create a table in an S3 folder that doesn't yet exist - following the example in [this comment in the other issue I opened](https://github.com/delta-io/delta-rs/issues/2197#issuecomment-1955190011). I've worked around these issues for the time being.
