### ISSUE TITLE
Investigate possibility of WASM target

### ISSUE THREAD

**Issue by rtyler** [delta-io/delta-rs#22]
Discussion with @nevi-me brought up an interesting idea, there may be a way to compile delta.rs to a wasm (Web Assembly) target and access a Delta table directly from within the browser.

This isn't something I'm personally going to have time to tinker with, but it would be a _really_ interesting experiment to see how far we can push this library.

**Comment by nevi-me** [comment]
I'll play around with this in the December break; I've been wanting to write a few blog posts about using Rust for data eng; this could make for a good tutorial :)

**Comment by Smurphy000** [comment]
Hey, was any progress made around this idea @nevi-me ? I had a similar thought, then stumbled on this issue, so I was hoping to see if there was any info. Thanks
