### ISSUE TITLE
Unable to merge column names starting from numbers

### ISSUE THREAD

**Issue by t1g0rz** [delta-io/delta-rs#2230]
# Environment

**Delta-rs version**:
deltalake==0.15.3
python 3.11

**Binding**: 
python

**Environment**:
- **Cloud provider**:  Local
- **OS**:  MacOS
- **Other**:

***
# Bug

**What happened**:
Delta tables with column names starting from numbers are created without problems until you try to merge data.

```
DeltaError: Generic DeltaTable error: Schema error: No field named s. Valid fields are s.time, s."1inch", __delta_rs_source, t.time, t."1inch", t.__delta_rs_path, __delta_rs_target.
```
**What you expected to happen**:
Just merge data into the table, or tell me that it's impossible. But merging through Spark works just fine.

**How to reproduce it**:
```python
from deltalake import DeltaTable
import pandas as pd
import pyarrow as pa

DeltaTable.create(
    table_uri="/tmp/test_3",
    schema=pa.schema([
        pa.field("time", pa.timestamp("us"), nullable=False),
        pa.field("1inch", pa.float64(), nullable=False),
    ]),
    mode="overwrite"
)

dl3 = DeltaTable("/tmp/test_3")

print(dl3.to_pandas().columns)   # Index(['time', '1inch'], dtype='object')

dl3.merge(
    pd.DataFrame({
        "time": pd.to_datetime(pd.Series(["2021-01-01 00:00:00"])),
        "1inch": [1.0]
    }),
    predicate="s.time = t.time",
    source_alias='s',
    target_alias='t'
).when_not_matched_insert_all().execute()

```

**More details**:

**Comment by echai58** [comment]
looks to be the same underlying problem as https://github.com/delta-io/delta-rs/issues/2167, you can workaround by 
```
.when_not_matched_insert({
    "time": "s.`time`",
    "1inch": "s.`1inch`"
})
```

**Comment by ion-elgreco** [comment]
I think I can put in a fix to always wrap a column in ``
