### ISSUE TITLE
Partition column comparison is an assertion rather than if block with raise exception

### ISSUE THREAD

**Issue by joe-sharman** [delta-io/delta-rs#2242]
# Environment

**Delta-rs version**:
0.16.0
**Binding**: 
python
**Environment**:
MacOS

***
# Bug

**What happened**:
An assertion is done between partition columns from incoming data and target table. If this fails an AssertionError is raised.
https://github.com/delta-io/delta-rs/blob/15538b9b42ba3d0d20ffd287bb4cc463ff8dfb1d/python/deltalake/writer.py#L340

**What you expected to happen**:
This should be an if block, and raise an exception if the two values aren't the same. `ValueError` would be fine.

**How to reproduce it**:
Try to write a table with the wrong partition columns specified in the incoming data.

**More details**:
This exception should also be changed, maybe something like `FileExistsError`
https://github.com/delta-io/delta-rs/blob/15538b9b42ba3d0d20ffd287bb4cc463ff8dfb1d/python/deltalake/writer.py#L333

Edit:
assert statements are ignored when running in optimise mode, so this could cause issues for a user running in optimised mode

**Comment by ion-elgreco** [comment]
@joe-sharman do you want to make a contribution to address this?

**Comment by joe-sharman** [comment]
I'll put something together :)

**Comment by joe-sharman** [comment]
Hey @ion-elgreco I've had a go making the change. I've tried to follow the commit conventions in the repo and have used built-in exceptions rather than custom as that seems to be the convention here.
