### ISSUE TITLE
Support second and millisecond precision for timestamps

### ISSUE THREAD

**Issue by rebasedming** [delta-io/delta-rs#2273]
# Description

The delta-rs `PrimitiveType` timestamp types only support microsecond precision. While this is sufficient for most use cases, it would be nice to also support second and millisecond precision.

**Use Case**

I would like to use second/millisecond precision timestamps in my DataFusion `DeltaTable`s.

**Related Issue(s)**

**Comment by rebasedming** [comment]
take

**Comment by Blajda** [comment]
@rebasedming the lack of support for different time units is primarily driven by the [Delta Protocol ](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#schema-serialization-format). 
As mentioned in https://github.com/delta-io/delta-rs/issues/2272 these units should be added a the protocol level first.
