### ISSUE TITLE
Accommodate separate set of credentials to access DynamoDB

### ISSUE THREAD

**Issue by MusKaya** [delta-io/delta-rs#2287]
# Description
When using an S3 compatible storage other than AWS S3, one has a set of access and secret key for the storage and another set for the DynamoDB. In this case, we need an option to provide separate credentials for DynamoDB access.

**Use Case**
Concurrent writes to an S3 compatible storage that does not share the credentials as DynamoDB.

**Related Issue(s)**

**Comment by tustvold** [comment]
Which S3 compatible store are you using, most of them shouldn't need DynamoDb as they support conditional writes natively

**Comment by MusKaya** [comment]
> Which S3 compatible store are you using, most of them shouldn't need DynamoDb as they support conditional writes natively

Hi @tustvold, I'm using Linode Object Storage (which [has](https://www.linode.com/community/questions/22749/object-storage-consistency#answer-80347) strong consistency).

**Comment by tustvold** [comment]
So strong consistency is a necessary but insufficient condition here, to not need locking you would need support for conditional writes. I have not been able to ascertain if it supports this.

**Comment by MusKaya** [comment]
I experimented with `AWS_S3_ALLOW_UNSAFE_RENAME='true'` and observed that concurrent writes overwrite the json files and the later one wins the race condition.

We need to provide the DynamoDB credentials to enable concurrent writes and the object storage & DynamoDB require separate pairs of secret & access keys.

Can we consider adding optional parameters (under DeltaTable storage_options) to take DynamoDB credentials in case they differ from S3 credentials?

**Comment by Dobatymo** [comment]
I need this also. I am using AWS S3 and DynamoDB. Both are are accessed using temporary tokens which I get by assuming a role. However S3 and dynamodb are in different regions and the tokens are scoped to the specific region. So I need to pass a separate set of credentials to both of them. I supply the S3 region with `aws_region` and the DynamoDB region indirectly with `aws_endpoint_url_dynamodb`.

Would there be another way to solve this?

**Comment by thomas-chauvet** [comment]
I've opened a PR that should solve this :)
