### ISSUE TITLE
Schema evolution not coercing with Large arrow types

### ISSUE THREAD

**Issue by ion-elgreco** [delta-io/delta-rs#2298]
# Environment

**Delta-rs version**:

**Binding**: 0.16.0

# Bug

**What happened**:
Writing a delta table that has a partition column which is primitive type String and then trying to write with schema_mode="merge" to add new columns results in, when your partition column is in arrow dtype LargeUtf8
```python
SchemaMismatchError: Schema error: Fail to merge schema field 'bar' because the from data_type = LargeUtf8 does not equal Dictionary(UInt16, Utf8)
Schema error: Fail to merge schema field 'bar' because the from data_type = LargeUtf8 does not equal Dictionary(UInt16, Utf8)
```

**Comment by ion-elgreco** [comment]
@aersam fyi :)

**Comment by aersam** [comment]
My boss hit this one and I introduced it - I better fix it ;)
