### ISSUE TITLE
Auth error when running inside VS Code 

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [delta-io/delta-rs#2306]
# Environment

**Delta-rs version**: 0.16.1

**Binding**: python

**Environment**:
- **Cloud provider**:Azure
- **OS**:Windows
- **Other**:

***
# Bug

**What happened**: When my colleage run the following code against a specific storage account **inside VS Code she get the following error** while if she runs it **as a script no error occurs**. It however works for some other storage account. I can run it fine within VS Code and as as script. I suppect something funny is going on with `object_store` and how credentials are cached for `VisualStudioCodeCredential`. 

Code:
```python

from deltalake import DeltaTable
blob_path = "abfss://<container>/<path>" 
storage_account = '<account>'
container = '<container>'
storage_options = {"AZURE_STORAGE_ACCOUNT_NAME": storage_account, "AZURE_CONTAINER_NAME":container, 'use_azure_cli': 'true'}

dt = DeltaTable(blob_path, storage_options=storage_options)
```

Error msg:
```
OSError: Generic MicrosoftAzure error: Client error with status 403 Forbidden: <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:85066fd9-201e-0058-47c6-7a707b000000
Time:2024-03-20T12:57:00.7481649Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request '<redacted>' is not the same as any computed signature. Server used following string to sign: 'GET





Wed, 20 Mar 2024 12:57:00 GMT





x-ms-version:2023-11-03
/<account>/<container>/<path>/_delta_log/_last_checkpoint'.</AuthenticationErrorDetail></Error>
```
**What you expected to happen**:
No error
**How to reproduce it**:
Hard to reproduce as it only is happening for one of us.
**More details**:

**Comment by ion-elgreco** [comment]
Sounds like a misconfiguration of some credentials to me rather than a bug

**Comment by thomasfrederikhoeck** [comment]
@ion-elgreco I tought the same but if we run the code on the **same computer** (but just copied into a python file) and use **same conda env** it doensn't give the issue?

**Comment by thomasfrederikhoeck** [comment]
@ion-elgreco I figured it out (https://github.com/apache/arrow-rs/issues/5534) and it is not a bug in `delta-rs` but maybe more a little confusing behaviour from the Azure Rust SDK. I will close :-)
