### ISSUE TITLE
Extract `add.stats_parsed` with wrong type

### ISSUE THREAD

**Issue by yjshen** [delta-io/delta-rs#2312]
# Bug

During delta log reading, extracting `add.stats_parsed` with the wrong `StringArray` type (on line 82) results in a double `stats_parsed` column in the result batch.

https://github.com/delta-io/delta-rs/blob/eb8c19c404bc53e1e74ddbeb55f182c9e6804b74/crates/core/src/kernel/snapshot/replay.rs#L76-L89

Also, the newly generated `stats_parsed` from `stats` has a different array length than other columns.

```
source: Arrow { source: InvalidArgumentError("Incorrect array length for StructArray field \"stats_parsed\", expected 10 got 14")
```

**What you expected to happen**:
1. extract `add.stats_parsed` with `StructArray` type
2. generated `stats_parsed` should have a same number of rows as other cols.

**How to reproduce it**:

**More details**:

**Comment by ion-elgreco** [comment]
@yjshen can you add some reproducible code?

**Comment by sjohnston** [comment]
I've seen this error when trying to read an old table with 10s of thousands of partitions. I started removing old partitions and vacuum/compact and the error went away. Maybe the schema changed at some point or something wrong with the old data. I'm not sure.
