### ISSUE TITLE
Support bloom filter table indexes

### ISSUE THREAD

**Issue by houqp** [delta-io/delta-rs#232]
# Description

**Use Case**

This could help speed up table scans. This feature is not documented in the official spec yet, see more details in https://docs.databricks.com/delta/optimizations/bloom-filters.html.

**Comment by kesavkolla** [comment]
Any update on this? I would really love to see an ability to do filter on the tables.

**Comment by houqp** [comment]
Databricks still hasn't open-sourced this feature I believe.

**Comment by viirya** [comment]
So this is only doable after Databricks open-souces or at least releases the official spec, right?

**Comment by houqp** [comment]
welp, we can always reverse engineer the format if anyone is interested in doing that :D

**Comment by roeap** [comment]
While trying to fix parquet2 builds in an PR, I realized that parquet2 has at least some support for bloom filters. https://github.com/jorgecarleitao/parquet2/tree/main/src/bloom_filter. 

Just leaving this here for reference 😄.

**Comment by adriangb** [comment]
I believe parquet has support for bloom filters and arrow-rs supports writing them. So I think all that's needed is for delta-rs to enable them on write?

**Comment by rishitesh-snt** [comment]
They are two different types of bloom filters:
1. Parquet bloom filters are at the RowGroup level & skip row groups based on the predicate value(s). Delta should definitely enable writing the bf.
2. Databrick's bloom filter is at the file level. It  skips the data file altogether, which would be a lot more performant for hight cardinality columns.

However, reading the bloom filter file itself is costly. IMO if the bloom filter can be serialized into the delta log files itself, so that file skipping happens at delta scan level.

**Comment by adriangb** [comment]
(1) is a no brainer to enable at least optionally. Is (2) a standard thing, or is it data bricks specific?

**Comment by rishitesh-snt** [comment]
> (1) is a no brainer to enable at least optionally. Is (2) a standard thing, or is it data bricks specific?

2) Its Databricks specific. Not in open source.

**Comment by adriangb** [comment]
Right so not much to be done about that…

I imagine something “custom” could be serialized into metadata, but I don’t see how delta-rs could support that without it being a standard. That said it would be nice if there could be some sort of callback based support for custom features/filters like this.

But support for writing to the files should come first, I believe it should be very straightforward.

**Comment by ion-elgreco** [comment]
I am going to close this one as the bloom filters the discussion is about, is proprietary
