### ISSUE TITLE
Update arrow dependency

### ISSUE THREAD

**Issue by lasantosr** [delta-io/delta-rs#2328]
# Description

Arrow have released version 51, it would be nice to keep delta up to date with arrow.

**Comment by ion-elgreco** [comment]
@lasantosr do you want to open a PR for that?

**Comment by lasantosr** [comment]
@ion-elgreco I'll try!

**Comment by lasantosr** [comment]
We have to wait until datafusion releases a new version, which is about to happen: https://github.com/apache/arrow-datafusion/issues/9682
