### ISSUE TITLE
python package metadata not being uploaded to PyPI

### ISSUE THREAD

**Issue by houqp** [delta-io/delta-rs#234]
# Environment

**Delta-rs version**: all

**Binding**: python

***
# Bug

**What happened**:

The metadata section in https://pypi.org/project/deltalake/ is missing all the python package metadata defined in cargo.toml.

Possibly something to do with matruin packaging or upload.

**What you expected to happen**:

Have supported python version to show up i the metadata section.

**Comment by fvaleye** [comment]
It works better now after upgrading the maturin version!
