### ISSUE TITLE
Create empty table failed on rust engine

### ISSUE THREAD

**Issue by Veiasai** [delta-io/delta-rs#2354]
# Environment
WSL2 Ubuntu
**Delta-rs version**:
python deltalake==0.16.3
**Binding**: 

**Environment**:
- **Cloud provider**:
- **OS**:
- **Other**:

***
# Bug

**What happened**:
write_deltalake with schema provided, and [] as data input, it can work with pyarrow engine. but it failed with rust.
```
                write_deltalake(
                    "./test",
                    [],
                    schema=Schema(fields=fields),
                    )
```
_internal.DeltaError: Generic error: No data source supplied to write command.
**What you expected to happen**:

**How to reproduce it**:

```
from deltalake import write_deltalake, DeltaTable
from deltalake.schema import Schema, Field, PrimitiveType
write_deltalake(
    "./test",
    [],
    schema=Schema(fields=[Field.from_json('''{
            "name": "col",
            "type": "integer",
            "nullable": true,
            "metadata": {}
        }''')]),
        engine="rust"
    )
```

**More details**:

**Comment by ion-elgreco** [comment]
You can create a table using the DeltaTable.create API. https://delta-io.github.io/delta-rs/api/delta_table/#deltalake.DeltaTable.create

**Comment by Veiasai** [comment]
Yea, I found that just now and it worked.

**Comment by ion-elgreco** [comment]
Alright, closing this one then : )
