### ISSUE TITLE
Upgrade to pyo3 0.21.0

### ISSUE THREAD

**Issue by abhiaagarwal** [delta-io/delta-rs#2363]
# Description

pyo3 recently released 0.21.0, which came with some big breaking changes (see: [migration guide](https://pyo3.rs/v0.21.0/migration.html)). This requires rewriting a good chunk of functions, but brings increased performance + memory safety. Also comes with an experimental `async` feature, to expose rust async functions to python async (with no interop required).

**Related Issue(s)**

**Comment by abhiaagarwal** [comment]
take

**Comment by abhiaagarwal** [comment]
this turned out to be way more complicated than I anticipated, as it depends on datafusion updating its pyo3 to 0.21 (tracking apache/arrow-datafusion#9808) and arrow updating (apache/arrow#5566). I patched all the dependencies and successfully compiled, but a bunch of tests related to datafusion are now failing.

https://github.com/abhiaagarwal/delta-rs/commit/785dadadc09e0b9a3ab8150ac7d9ce4f3196c743

**Comment by ion-elgreco** [comment]
@abhiaagarwal let me guess, are you seeing tests failing with?

"Wrong number of children"

**Comment by abhiaagarwal** [comment]
@ion-elgreco exactly right :) how did you know?

**Comment by ion-elgreco** [comment]
@abhiaagarwal magic 🪄 haha

No I also tried bumping it, and @universalmind303 but it all gets that error.

I opened an issue in Datafusion repo this morning, to see if they know what the issue might be

**Comment by abhiaagarwal** [comment]
@ion-elgreco yeah, I have 32 tests failing.

```
failures:
    data_catalog::storage::tests::test_query_table
    delta_datafusion::expr::test::test_expr_sql
    delta_datafusion::tests::delta_scan_case_sensitive
    delta_datafusion::tests::delta_scan_mixed_partition_order
    delta_datafusion::tests::delta_table_provider_with_config
    operations::delete::tests::test_delete_nested
    operations::delete::tests::test_delete_null
    operations::delete::tests::test_delete_on_mixed_columns
    operations::delete::tests::test_delete_on_nonpartition_column
    operations::delete::tests::test_delete_on_partition_column
    operations::merge::tests::test_merge
    operations::merge::tests::test_merge_case_sensitive
    operations::merge::tests::test_merge_delete_matched
    operations::merge::tests::test_merge_delete_not_matched
    operations::merge::tests::test_merge_empty_table
    operations::merge::tests::test_merge_no_alias
    operations::merge::tests::test_merge_partition_filtered
    operations::merge::tests::test_merge_partitions
    operations::merge::tests::test_merge_partitions_skipping
    operations::merge::tests::test_merge_pushdowns
    operations::merge::tests::test_merge_pushdowns_partitioned
    operations::merge::tests::test_merge_str
    operations::merge::tests::test_merge_with_alias_mix
    operations::update::tests::test_update_case_sensitive
    operations::update::tests::test_update_no_predicate
    operations::update::tests::test_update_non_partition
    operations::update::tests::test_update_null
    operations::update::tests::test_update_partitions
    operations::write::tests::test_nested_struct
    operations::write::tests::test_replace_where
    operations::write::tests::test_replace_where_partitioned
    operations::write::tests::test_write_different_types

test result: FAILED. 214 passed; 32 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.76s
```

**Comment by universalmind303** [comment]
@abhiaagarwal @ion-elgreco those are valid errors. Datafusion added some new optimization rules that break a lot of older plans. I am actively working on getting all of the code upgraded to be compatible with this rule. https://github.com/delta-io/delta-rs/pull/2249. Should have this reviewable within the next few days.

**Comment by ion-elgreco** [comment]
@abhiaagarwal you should be able to bump arrow now, just merged @universalmind303's chore PR

**Comment by abhiaagarwal** [comment]
@ion-elgreco arrow is not updated yet, and the branch with the 0.21 pyo3 update is also broken. I'm gonna hold off until things stabilize
