### ISSUE TITLE
Support for Arrow PyCapsule interface

### ISSUE THREAD

**Issue by kylebarron** [delta-io/delta-rs#2376]
# Description

Looking at the code below, the `write_deltalake` function is hard-coded to support only specific pyarrow and pandas objects. 
https://github.com/delta-io/delta-rs/blob/6f81b8034dbef7a0120e354e178f0c859564465e/python/deltalake/writer.py#L283-L306

With the [Arrow PyCapsule interface](https://arrow.apache.org/docs/format/CDataInterface/PyCapsuleInterface.html), you can support any Arrow-based Python input, regardless of the library implementation.

**Use Case**

I'm working on a [Python library for Arrow-backed geospatial operations](https://github.com/geoarrow/geoarrow-rs), and support for the PyCapsule interface would allow interfacing with my or any other Python Arrow library without needing hard-coded support.

**Related Issue(s)**

**Comment by ion-elgreco** [comment]
@kylebarron hey Kyle, are you willing to make this contribution here?

**Comment by kylebarron** [comment]
I put up a short initial PR for the write side to get things moving. I think we may be able to wrap some additional classes to export through the pycapsule interface as well (deferring to `to_pyarrow` under the hood)
