### ISSUE TITLE
ValueError: Partition value cannot be parsed from string.

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [delta-io/delta-rs#2380]
# Environment

**Delta-rs version**:
Main including https://github.com/delta-io/delta-rs/commit/6f81b8034dbef7a0120e354e178f0c859564465e
**Binding**: 
python

**Environment**:
- **Cloud provider**: local
- **OS**: Windows
- **Other**:

***
# Bug

**What happened**:
When I try to create a checkpoint on a table partioned by timestamp I'm hit with a `ValueError. Note that I have build from master including` https://github.com/delta-io/delta-rs/pull/2357:

```python
import pandas as pd
from datetime import datetime
import deltalake as dl

dates = pd.date_range(datetime(2021,1,1,3,4,6,3),datetime(2021,1,3,3,4,6))

df = pd.DataFrame({"time":dates, "a":[i for i in range(len(dates))]})

schema = dl.schema.Schema(fields=[
    dl.schema.Field("time",dl._internal.PrimitiveType.from_json('"timestamp"')),
    dl.schema.Field("a",dl._internal.PrimitiveType.from_json('"integer"'))
    ]
) 

write_deltalake("mytable",df, schema=schema,partition_by="time")
dt = DeltaTable("mytable")
dt.create_checkpoint()
```
which gives:
```
ValueError: Partition value 2021-01-02 03:04:06.000003Z cannot be parsed from string.

```
**What you expected to happen**:
That the checkpoint was created.
**How to reproduce it**:
Run code above

**More details**:

**Comment by thomasfrederikhoeck** [comment]
it appears that the `Z` is missing in the parsing:
https://github.com/delta-io/delta-rs/blob/6f81b8034dbef7a0120e354e178f0c859564465e/crates/core/src/protocol/checkpoints.rs#L444

**Comment by ion-elgreco** [comment]
@thomasfrederikhoeck it shouldn't write the partition values with a Z. Also my PR didn't touch the partition value serialization.

**Comment by thomasfrederikhoeck** [comment]
Yes it appears that pyarrow serialize `timestamp` with `Z` while and `timestampNtz` without.

```python
import pyarrow as pa
import pytz

tz = "UTC"

def get_data(with_tz):
    tzinfo = pytz.timezone(tz) if  with_tz else None
    dates = pd.date_range(
        datetime(2021,1,1,3,4,6,3, tzinfo=tzinfo),
        datetime(2021,1,3,3,4,6, tzinfo=tzinfo)
        )
    return pd.DataFrame({"time":dates, "a":[i for i in range(len(dates))]})

schema = pa.schema(
        [
            ("time", pa.timestamp("us")),
            ("a", pa.int64()),
        ]
    )
dt = DeltaTable.create(
        "mytable_timestampNtz", schema=schema, partition_by=["time"]
    )

write_deltalake("mytable_timestampNtz",get_data(with_tz=False), partition_by="time", mode="append")
print(dt.schema())
schema = pa.schema(
        [
            ("time", pa.timestamp("us",tz)),
            ("a", pa.int64()),
        ]
    )
dt = DeltaTable.create(
        "mytable_timestamp", schema=schema, partition_by=["time"]
    )

write_deltalake("mytable_timestamp",get_data(with_tz=True), partition_by="time", mode="append")
print(dt.schema())

>Schema([Field(time, PrimitiveType("timestampNtz"), nullable=True), Field(a, PrimitiveType("long"), nullable=True)])
>Schema([Field(time, PrimitiveType("timestamp"), nullable=True), Field(a, PrimitiveType("long"), nullable=True)])
```

![image](https://github.com/delta-io/delta-rs/assets/44194839/bf56fc84-bada-4f56-befa-b736f7afdefb)

**Comment by thomasfrederikhoeck** [comment]
@ion-elgreco I wanted to try the rust engine but the problem is that it serialize like this which is invalid on Windows where you can't have colon (`:`) it the folder or file name: `2021-01-01 03:04:06.000003`

**Comment by ion-elgreco** [comment]
@thomasfrederikhoeck can you make a separate issue for that

**Comment by thomasfrederikhoeck** [comment]
Yes, will do :-) @ion-elgreco

**Comment by thomasfrederikhoeck** [comment]
@ion-elgreco Done https://github.com/delta-io/delta-rs/issues/2384 :-)
