### ISSUE TITLE
Allow checkpoint creation when partion column is "timestampNtz "

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [delta-io/delta-rs#2381]
# Description
Right now you can create a table partioned on a column of type timestampNtz. This is all on main.:

```
import pandas as pd
dates = pd.date_range(datetime(2021,1,1,3,4,6,3),datetime(2021,1,3,3,4,6))
df = pd.DataFrame({"time":dates, "a":[i for i in range(len(dates))]})
write_deltalake("mytable",df, partition_by="time")
dt = DeltaTable("mytable")
print(dt.schema())
> Schema([Field(time, PrimitiveType("timestampNtz"), nullable=True), Field(a, PrimitiveType("long"), nullable=True)])

```

However when trying to create a checkpoint I'm hit by

```

dt.create_checkpoint()
> PanicException: not implemented: Primitive type timestampNtz is not supported for partition column values.

```
**Use Case**

**Related Issue(s)**

**Comment by ion-elgreco** [comment]
@thomasfrederikhoeck We just need to add an arm for PrimitiveType::TimestampNtz`

https://github.com/delta-io/delta-rs/blob/6f81b8034dbef7a0120e354e178f0c859564465e/crates/core/src/protocol/checkpoints.rs#L444

I'll see if I can find some time tomorrow

**Comment by thomasfrederikhoeck** [comment]
GIven https://github.com/delta-io/delta-rs/issues/2380 it might also be worth looking at the `Timestamp` arm?

**Comment by thomasfrederikhoeck** [comment]
@ion-elgreco I can grap this one :-)
