### ISSUE TITLE
Use predicates to restrict scan in merge operation

### ISSUE THREAD

**Issue by Tommel71** [delta-io/delta-rs#2411]
# Description

Use predicates in the merge operation to read only parts of the affected partition into memory.

**Use Case**

I only ever write to one partition at a time.
I have a large table and I want to merge 2000 rows (or only one row - the issue remains) using `when_not_matched_insert_all` into it. The merge operation respects partitions, so merging into a new partition is fast. However, it looks like the merge operation currently reads the entire partition into memory, although in my case, the predicate and metadata could be used to restrict the search to only one file in the partition or even just one or very few row groups in parquet when my data is z-ordered. This would greatly speed up the merge operation in my case.

Currently, my query to merge 2000 rows into a partition of 2GB uncompressed parquet files takes 30 seconds, which forces me to internally keep track of whether or not the data has been written which in turn exposes me to data inconsistencies.

**Related Issue(s)**

**Comment by ion-elgreco** [comment]
@Tommel71 with 0.19.1 is it improved? Because it should potentially skip more files now

We still read the full file though if we think it's relevant

**Comment by Tommel71** [comment]
@ion-elgreco Thank you for coming back to this. Good to know that we can use this in the future. For now I have no good way to replicate what I had before because we now implemented the functionality by appending data instead of merging.

I am pretty sure this would now also be a viable approach.
