### ISSUE TITLE
File skipping according to documentation

### ISSUE THREAD

**Issue by t1g0rz** [delta-io/delta-rs#2427]
# Environment

**Delta-rs version**: 0.16.4

**Binding**:  python

# Description

[Here](https://github.com/delta-io/delta-rs/blob/ebbdd69274e8d22055f47aca03bf56f997304cee/docs/delta-lake-best-practices.md?plain=1#L95) documentation says:  
> Ensure the transaction log stores metadata stats for all the columns that benefit from file skipping.

And [here](https://github.com/delta-io/delta-rs/blob/ebbdd69274e8d22055f47aca03bf56f997304cee/docs/delta-lake-best-practices.md?plain=1#L103) guides us to explicitly specify columns for file skipping:  
> It takes some time to compute column statistics when writing files, and it isn’t worth the effort if you cannot use the column for file skipping.
> Suppose you have a table column containing a long string of arbitrary text.  It’s unlikely that this column would ever provide any data-skipping benefits.  So, you can just avoid the overhead of collecting the statistics for this particular column.

I couldn't find a way to exclude some columns from file skipping purposes. In my case, I have quite wide tables (> 200 columns), and out of these, 195 will never be used for file skipping.  
An unintended consequence of including all these columns in statistics calculation is the explosive growth of the delta log size because it writes very long strings of min/max/nulls. This indirectly creates all conditions for issue #2301 and [this from delta slack](https://delta-users.slack.com/archives/C013LCAEB98/p1711921602281259?thread_ts=1711921242.418959&cid=C013LCAEB98).

I found the `delta.dataSkippingNumIndexedCols` setting [here](https://docs.delta.io/latest/table-properties.html)  and I wonder if it's possible to explicitly specify column names. Or should I reorder the table to have skipping columns first and then set delta.dataSkippingNumIndexedCols?

**Comment by ion-elgreco** [comment]
@t1g0rz I checked, but we don't respect it yet 😄 

Buttt I am working on a fix 🕺
