### ISSUE TITLE
chore(deps): update object_store requirement from =0.9 to =0.10

### ISSUE THREAD

**Issue by Silemo** [delta-io/delta-rs#2436]
# Description

The [arrow-rs/object_store](https://github.com/apache/arrow-rs/tree/master/object_store) repository recently (4 days ago) updated the object_store version. You can check out the Change-log [here](https://github.com/apache/arrow-rs/blob/cd3331989d65f6d56830f9ffa758b4c96d10f4be/object_store/CHANGELOG.md).

I imagine this will be taken care of pretty easily, but I wanted to bring up the issue.

**Comment by ion-elgreco** [comment]
@Silemo not really since it introduces breaking changes. So we need to refactor.

**Comment by Silemo** [comment]
Yes, you are right. Sorry for addressing the situation this poorly. I was not sure how to word the issue.

Btw, from the few tests I did we are apparently still prior to release. They are preparing the release but they still need to publish it.

**Comment by ion-elgreco** [comment]
No worries! :) We are first targeting this one: https://github.com/delta-io/delta-rs/pulls

I think @aersam might be interested to refactor to 0.10 object store since it introduces the upload trait

**Comment by Silemo** [comment]
Update: now the version 0.10.0 looks completely released

**Comment by aersam** [comment]
I guess we also have to wait for a release of the arrow crate

**Comment by ion-elgreco** [comment]
Mainly datafusion is paired with object store as far as I know

**Comment by thomasfrederikhoeck** [comment]
#2395 being resolved opens up for this as I see it.

**Comment by ion-elgreco** [comment]
@thomasfrederikhoeck we need to wait for the next datafusion release : )

**Comment by Silemo** [comment]
I imagine that since now Datafusion 38 was released and this issue is on the Rust v0.18 milestone, also the object_store bump will be solved soon
