### ISSUE TITLE
logRetentionDuration don't seems to be respected 

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#2447]
# Environment

**Delta-rs version**:
17.1

**Binding**: 

**Environment**:
Python 

***
# Bug

**What happened**:

 ```
write_deltalake(delta_path, df,configuration = {"logRetentionDuration": "interval 1 day"} ,mode="append",storage_options=storage_options)
dt = DeltaTable(delta_path,storage_options=storage_options)
dt.vacuum(retention_hours=0,dry_run=False,  enforce_retention_duration=False)
dt.create_checkpoint()
dt.cleanup_metadata()

```

don't seems to be working ?

**Comment by ion-elgreco** [comment]
That's correct, it's not yet implemented but it's on my next item on the list to build 😎

**Comment by echai58** [comment]
I think the configuration key should be `delta.logRetentionDuration`.

**Comment by djouallah** [comment]
same issue

**Comment by ion-elgreco** [comment]
> I think the configuration key should be `delta.logRetentionDuration`.

Correct

**Comment by djouallah** [comment]
@ion-elgreco  delta.logRetentionDuration does not work either ?

**Comment by ion-elgreco** [comment]
@djouallah it does work, you provided interval 1 day, so you can't expect the logs to be deleted immediately : P, change it to 1 seconds interval and you can see they get removed

```python
import polars as pl
from deltalake import DeltaTable, write_deltalake

df = pl.DataFrame({"foo": [1]})
delta_path = "test_Table"

write_deltalake(
    delta_path,
    df.to_arrow(),
    configuration={"delta.logRetentionDuration": "interval 1 seconds"},
    mode="overwrite",
)
dt = DeltaTable(delta_path)
dt.vacuum(retention_hours=0, dry_run=False, enforce_retention_duration=False)
dt.create_checkpoint()
dt.cleanup_metadata()
```

**Comment by ion-elgreco** [comment]
@djouallah please share the table configuration in the delta log

**Comment by djouallah** [comment]
`Metadata(id: 62adbf63-1e61-479e-8187-8fd7ef308b5c, name: None, description: None, partition_columns: [], created_time: 1713594980946, configuration: {})`

**Comment by ion-elgreco** [comment]
> `Metadata(id: 62adbf63-1e61-479e-8187-8fd7ef308b5c, name: None, description: None, partition_columns: [], created_time: 1713594980946, configuration: {})`

Yeah, you didn't pass a configuration during creating so it's using the default of 30 days.

**Comment by djouallah** [comment]
ah, I see it has to be in the first time it was created, adding the option later using append or overwrite does not works, thanks !!!
