### ISSUE TITLE
Is there a way to see a query plan?

### ISSUE THREAD

**Issue by geekodour** [delta-io/delta-rs#2481]
# Description
See this blogpost: https://salim-sayed.medium.com/spark-delta-lake-merge-slowness-due-to-skewed-partitions-f212285bd04f
It shows an example of the Physical plan

**Use Case**
I am trying to debug a slow merge while using delta-rs via polars and I am not sure how should I access the query plan. Is it something that's accessible?

**Comment by geekodour** [comment]
Another example: https://kb.databricks.com/delta/delta-merge-into

Think this is more of a pyarrow question?

**Comment by ion-elgreco** [comment]
Not really at the moment. You could modify the delta-rs code to return/dbg the plan.

Are you merging on the full table or a set of partitions?

**Comment by echai58** [comment]
If you set `RUST_LOG=debug` datafusion will print out the full optimized/unoptimized query plans, if that's what you're looking for.
