### ISSUE TITLE
Adopt the delta kernel types

### ISSUE THREAD

**Issue by rtyler** [delta-io/delta-rs#2489]
What feels like long ago, @roeap imported some kernel types manually into the `kernel` module from the early work on delta-kernel-rs. Now `delta_kernel` has been released with a 0.0.1 we can move to adopting those symbols and begin incrementally adopting functionality from the kernel.

This issue is _just_ about the types. I'm not expecting to pull any of the log replay or snapshot code in

**Comment by ion-elgreco** [comment]
I noticed the types were incorrect in kernel for timestamps. Would be good to backport fixes from delta-rs into kernel, otherwise we will have to fix some bugs again ^^

**Comment by rtyler** [comment]
@ion-elgreco we do indeed have some divergence :scream: 

How confident are you in our tests for timestamp support? :smile:

**Comment by nicklan** [comment]
> I noticed the types were incorrect in kernel for timestamps. Would be good to backport fixes from delta-rs into kernel, otherwise we will have to fix some bugs again ^^

We should definitely just fix those in kernel. @ion-elgreco , do you have links to the fixes by any chance? Or just the divergence so I can figure out what needs to change? I can probably figure it out but might be faster if you just point me at it.

Thanks!

**Comment by roeap** [comment]
take

**Comment by roeap** [comment]
started work on this, we do require some updates on kernel first to be able to consume the types, but hoping that this will not be too invasive.
