### ISSUE TITLE
[deltalake_aws] Allow passing AWS_SESSION_TOKEN and other credentials more directly to DynamoDB client.

### ISSUE THREAD

**Issue by adamfaulkner-at** [delta-io/delta-rs#2497]
# Description

My understanding of the code [here](https://github.com/delta-io/delta-rs/blob/81593e919497221a1a08bf8db9d20e8e4a39a8a6/crates/aws/src/storage.rs#L146-L153) is that AWS_SESSION_TOKEN, AWS_SECRET_ACCESS_KEY, and AWS_ACCESS_KEY_ID are assigned to environment variables, and later inferred by the S3 client and the DynamoDB client. It would be nicer if they could be passed directly to these clients without being part of the process's environment.

I think an ideal solution would allow me to configure my own object store and dynamo client, and provide those when registering a table.

**Use Case**

My process is a big monolith with a bunch of stuff in it, completely unrelated to me. Many different identities are used in this process for many different purposes. Environment variables are a single global namespace, so it would be dangerous to plug my credentials in it.

**Related Issue(s)**

**Comment by thomas-chauvet** [comment]
I have a similar issue.

I am using an S3-compatible storage which does not provide locking mechanism. I wanted to use dynamodb on the side of this storage for the locking mechanism but I can't as I need to have the same credentials for dynamodb and s3.

Any idea how to solve this ?

**Comment by thomas-chauvet** [comment]
I've opened a PR that should solve this :)
