### ISSUE TITLE
TypeError: Object of type int64 is not JSON serializable when writing using a Pandas dataframe

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#2501]
can't write to delta using Pandas, I added a reproducible example in this notebook

https://colab.research.google.com/drive/1uPOv8qyj5xW4XfrnkLtZtYIaaQfhupjG#scrollTo=7USg9dd-1ivc

**Comment by ion-elgreco** [comment]
That's a pyarrow pandas compatiblity issue because it fails at `dataframe_to_arrays`. So you should create an issue at PyArrow repo : )

**Comment by djouallah** [comment]
thanks
