### ISSUE TITLE
Incorporate test data that uses tags on the add action

### ISSUE THREAD

**Issue by rtyler** [delta-io/delta-rs#251]
# Description

Right now there are no test datasets in the golden set or our own which use the `tags` field on the add action. It's not really clear to me what kind of data should go into there or how it's used "in real life"

**Use Case**

**Related Issue(s)**

**Comment by ion-elgreco** [comment]
They are now covered in these tables:

crates/test/tests/data/table_with_column_mapping
crates/test/tests/data/table_with_deletion_logs

and these tests (since we read the add actions there):
- test_with_deletion_vector
- async fn test_with_column_mapping() {
