### ISSUE TITLE
Only allow squash merge

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [delta-io/delta-rs#2542]
# Description
Sometimes it appears that some PR are merged in with all the underlying commits which can create some noise on what was changed and it makes reverts harder. I believe squash merge should be enforced - I think this is the common way to go about for a lib like delta-rs.

![image](https://github.com/delta-io/delta-rs/assets/44194839/c9af9a9a-2356-4fb9-a5b2-7088b51c771e)

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

**Use Case**

**Related Issue(s)**

**Comment by ion-elgreco** [comment]
I think the default is squash and merge, but you can still select rebase and merge. Not sure why that sometimes is selected though

**Comment by thomasfrederikhoeck** [comment]
@ion-elgreco I think it is possible to disable all other kinds if you are the repo owner. I think that should be considered since right now commits on master (if not squash) doesn't directly link to PRs.

**Comment by rtyler** [comment]
We recently adopted the merge queue which doesn't support squash merges, or any of the other merge styles apparently.  We've been doing some squashing manually, but I'm going to close t his out since there's not much we can do until github's merge queue is more featureful
