### ISSUE TITLE
Running the basic_operations examples fails with `Error: Transaction { source: WriterFeaturesRequired(TimestampWithoutTimezone) `}

### ISSUE THREAD

**Issue by imor** [delta-io/delta-rs#2552]
# Environment

**Delta-rs version**: main branch

**Binding**: Rust

**Environment**:
- **Cloud provider**:
- **OS**: macOS
- **Other**: local

***
# Bug

**What happened**:

Running basic_operations examples fails with `Error: Transaction { source: WriterFeaturesRequired(TimestampWithoutTimezone) }`

**What you expected to happen**:

Example runs successfully

**How to reproduce it**:

From the `delta-rs/crates/deltalake` folder run `cargo run --features="datafusion" --example basic_operations`

**More details**:
I have tracked the error down to these lines: https://github.com/delta-io/delta-rs/blob/752eef51f6a4f6d52ee8a6f315cec11bb469741a/crates/core/src/operations/transaction/protocol.rs#L121-L123 But I'm not sure how to fix this. If I comment out these lines, the example does work.

**Comment by jhoekx** [comment]
The example was creating an Arrow array with timestamps without time zone. The delta data type was `Timestamp`, which is defined as having a UTC timezone, but it should be `TimestampNtz` to correspond to the data.
