### ISSUE TITLE
Refactor DeltaTable to generic over storage backend trait

### ISSUE THREAD

**Issue by houqp** [delta-io/delta-rs#257]
# Description

**Use Case**

Right now DetalTable references storage backend using dynamic dispatch, this could turn into a potential performance bottleneck because our access to storage backend is now tied to the number of files we process from the delta table.

On top of this, using storage backend as trait object also prevents us from adding generic methods to the storage backend trait.

Instead, we should refactor DeltaTable struct to generic over storage backend trait, then return the table struct as a trait object in the high level `open_table` API.

**Comment by viirya** [comment]
I tried this a little bit for curiosity. I saw a few issues when returning the table struct as a trait object. For example, not all fields are public in DeltaTable struct. We rely on the struct to hide internal stuffs. If we have it as a trait object, we will expose these internals.

**Comment by houqp** [comment]
Yeah, very good point @viirya . I now think it might be better to not use DeltaTable as trait object, at least not for the first version, otherwise it will also restrict us from defining generic methods as well.

**Comment by rtyler** [comment]
No longer needed as far as I can tell
