### ISSUE TITLE
Support HDFS via hdfs-native package

### ISSUE THREAD

**Issue by Kimahriman** [delta-io/delta-rs#2611]
# Description
[hdfs-native](https://github.com/Kimahriman/hdfs-native) is a Rust package I made that implements an HDFS client in pure* Rust. This can be used to add HDFS support to delta-rs without any Java or JVM dependencies.

*Kerberos support uses dynamic loading of `libgssapi_krb5` via `libloading`

**Use Case**
Using delta-rs with HDFS without requiring Java

**Related Issue(s)**

**Comment by santosh-d3vpl3x** [comment]
@Kimahriman is it possible to also add native hdfs support to delta-kernel-rs?

**Comment by ion-elgreco** [comment]
@santosh-d3vpl3x that's something you will have to check with delta-kernel-rs maintainers
