### ISSUE TITLE
Rust writer not encoding correct URL for partitions in delta table

### ISSUE THREAD

**Issue by gprashmi** [delta-io/delta-rs#2634]
# Environment

**Delta-rs version**: 0.17.4

***
# Bug

We write data to delta table using delta-rs with PyArrow engine with DayHour as partition column. However when we run the optimize.compact() on the table, it creates partitions with spaces and does not properly encode the partition urls as shown in the below image i.e; it creates new partitions url with spaces (.zstd.parquet).

![image](https://github.com/delta-io/delta-rs/assets/45960112/97c94b14-661d-4300-b0a5-f8a4bb7476ed)

Can you please let me know how we can run the optimize.compact without having partitions with spaces?

**Comment by gprashmi** [comment]
@g12-al

**Comment by g12-al** [comment]
Confirmed that this also seems to happen in 0.18.0.

This breaks compatibility for our Trino connector to enable visualization on dashboards. Ideally, Trino wouldn't care about spaces (it has a lot of other issues like not being compatible with timezone-aware timestamps).

**Comment by gprashmi** [comment]
@ion-elgreco the issue we see here is with the Pyarrow engine

**Comment by gprashmi** [comment]
@on-elgreco Any update on this issue?

**Comment by ion-elgreco** [comment]
@gprashmi sorry I don't have time to look into it unfortunately

**Comment by gprashmi** [comment]
@ion-elgreco do you have any other suggestions on how this can be handled to have the correct URL encoding with optimizing the table?

**Comment by ion-elgreco** [comment]
I'll take a look at this

**Comment by ion-elgreco** [comment]
@gprashmi @g12-al fix is on it's way in https://github.com/delta-io/delta-rs/pull/2705, will be released in 0.18.3

**Comment by g12-al** [comment]
I'm late to responding, but thank you so much for addressing this @ion-elgreco !

**Comment by gprashmi** [comment]
Thank you very much @ion-elgreco for addressing the issue.
