### ISSUE TITLE
Add context to errors

### ISSUE THREAD

**Issue by nfx** [delta-io/delta-rs#267]
While debugging delta-rs for the first time, i've stumbled upon error messages, that didn't tell much, 

```rust
if self.version == -1 {
  // no snapshot found, no 0 version found.  this is not a delta
  // table, possibly an empty directroy.
  return Err(DeltaTableError::NotATable);
}
```

with corresponding error definition:

```rust
/// Error returned when it is not a DeltaTable.
#[error("Not a Delta table")]
NotATable,
```
e.g. someone would expect the error message to contain a path. e.g. verbose errors are better than concise ones, as we have no java-stacktrace-like blobs of text :)

In scope of this issue, we should add all possible relevant context to error messages and make it a code-review requirement to add new errors only with enough context.

This enhancement would help wider adoption of Delta.

**Comment by houqp** [comment]
We could wrap this enum variant with a free form string :+1:

**Comment by rtyler** [comment]
In #286 I only did a single enum variant, since I wanted to leave others for trying out :smile: 

If nobody submits a pull request for those other variants in the next few days, I'll go ahead and do that to close this issue out :smile_cat:

**Comment by houqp** [comment]
This has already been addressed by Tyler's PR
