### ISSUE TITLE
Function behaving similarly to `SHOW PARTITIONS` in the Python API

### ISSUE THREAD

**Issue by FrankPortman** [delta-io/delta-rs#2671]
# Function behaving similarly to `SHOW PARTITIONS` in the Python API

I am wondering if there is something similar to `SHOW PARTITIONS` from the Spark world of interacting with Delta Tables. This is a metadata-only query that returns back all of the partitions live for a specific Delta Table in a tabular format. Functionality such as `DeltaTable.files_by_partitions` is super helpful for querying but not quite the same thing. [get_active_partitions](https://github.com/delta-io/delta-rs/blob/f432c4f8337c2b0d47958645684e5df336c61522/python/src/lib.rs#L933) is almost what I need but (1) it's not exposed in the public API which makes usage a bit clunky (but certainly nothing life ruining) and (2) the struct it returns is not the most ergonomic.

Any openness to a PR that does this?

**No related issues from what I could tell.**

**Comment by ion-elgreco** [comment]
@FrankPortman feel free to open a PR for this, it's definitely useful as a proper public api

**Comment by FrankPortman** [comment]
@ion-elgreco is your preference to just open up the API so `get_active_partitions` exists on `DeltaTable` in Python? Or are you also open to it or some helper method on `DeltaTable` packaging the results in a more ergonomic format?

For example, right now a call to `table._table.get_active_partitions()` returns something like `frozenset[frozenset[tuple[str, str]]]`, were the inner set contains as many tuples of `pKey, pVal` as there are partition cols in the table. My use case would involve merging those inner tables into some struct or dict, so that a single partition "row" has all the partition cols pivoted out. I don't mind handling that last part in my business logic code, but if this is something you think would be useful, I can add it here as well.

**Comment by ion-elgreco** [comment]
Let's go for something more ergonomic since it's a public api

**Comment by omkar-foss** [comment]
Seems like a nice feature to have! I can pick this up and raise a PR if no one is working on it, let me know.

**Comment by FrankPortman** [comment]
I'd love that - I haven't had a chance to prio yet
