### ISSUE TITLE
DeltaTable.from_data_catalog not working

### ISSUE THREAD

**Issue by flaviokr** [delta-io/delta-rs#2699]
I was following the documentation [here](https://delta-io.github.io/delta-rs/usage/loading-table/), trying to read a table from a catalog:

```
from deltalake import DeltaTable
from deltalake import DataCatalog

database_name = "simple_database"
table_name = "simple_table"
data_catalog = DataCatalog.AWS

dt = DeltaTable.from_data_catalog(data_catalog=data_catalog, database_name=database_name, table_name=table_name)
```

But I am getting the errror: `AttributeError: type object 'deltalake._internal.RawDeltaTable' has no attribute 'get_table_uri_from_data_catalog'`

Is this a bug or is the documentation outdated?

**Comment by ion-elgreco** [comment]
@flaviokr this code is removed on the rust side, but the references in Python were never removed. We might reintroduce it at some point in the future
