### ISSUE TITLE
Enable S3 storage feature by default

### ISSUE THREAD

**Issue by houqp** [delta-io/delta-rs#270]
# Description

**Use Case**

Follow up for https://github.com/delta-io/delta-rs/discussions/208. We have decided to enable s3 storage backend by default and provide a new feature flag to disable s3 storage backend if they desire.

**Comment by xuky76** [comment]
@houqp I imagine there is more to this than flipping the logic of the s3 feature. If you can point me in the right direction I will be happy to help out
