### ISSUE TITLE
Choose which columns to store min/max values for

### ISSUE THREAD

**Issue by kpapadatos** [delta-io/delta-rs#2709]
# Description
It would be useful to be able to choose which columns may be used for file skipping so that min/max values are not stored for unused columns.

**Use Case**
In our use case, we have some large string columns that are never used for file skipping, and keeping min/max values for those results in unnecessarily large delta log files.

**Related Issue(s)**
Delta log files get unnecessarily big.

**Comment by ion-elgreco** [comment]
This is already supported with the configurations "delta.dataSkippingStatsColumns" or "delta.dataSkippingNumIndexedCols"
