### ISSUE TITLE
AWS WebIdentityToken exposure in log files

### ISSUE THREAD

**Issue by wkargul** [delta-io/delta-rs#2719]
https://rustsec.org/advisories/RUSTSEC-2024-0358
      
When using AWS WebIdentityTokens with the `object_store` crate, in the event of
 a failure and automatic retry, the underlying `reqwest` error, including the
full URL with the credentials, potentially in the parameters, is written to the
logs.
```
 object_store v0.9.1
      └── datafusion-proto-common v39.0.0
          └── datafusion-proto v39.0.0
              └── deltalake-core v0.18.1
                  ├── deltalake v0.18.1
                  │   └── raw-service v1.0.4
                  └── deltalake-aws v0.1.2
                      └── deltalake v0.18.1 (*)

**Comment by wkargul** [comment]
Tried `cargo update -p object_store`
and
```
error: There are multiple `object_store` packages in your project, and the specification `object_store` is ambiguous.
Please re-run this command with one of the following specifications:
  object_store@0.9.1
  object_store@0.10.2

**Comment by wkargul** [comment]
Using `deltalake = { version = "0.17.0", features = ["datafusion", "s3"] }` in my Cargo.toml

**Comment by rtyler** [comment]
I'm still unable to reproduce, with a new project and a `cargo add --features datafusion,s3` I am only getting the latest `object_store`

```
plantain% cargo tree | grep -rin "object_store"
    │   │   │   │   ├── in v0.10.1
    │   │   │   │   │   ├── in v0.10.1 (*)
    │   │   │   │   ├── in v0.10.1 (*)
    │   │   │   ├── in v0.10.1 (*)
    │   │   │   │   ├── in v0.10.1 (*)
    │   │   │   ├── in v0.10.1 (*)
    │   │   ├── in v0.10.1 (*)
    │   ├── in v0.10.1 (*)
```

**Comment by wkargul** [comment]
I've removed `target` as well as tried with `cargo clean`

**Comment by wkargul** [comment]
https://crates.io/crates/deltalake-core/0.18.1/dependencies it depends on datafusion-proto v39.0.0 @rtyler

**Comment by rtyler** [comment]
Aha, I see that. That's effectively an error in the datafusion dependency chain which we don't have a way to remedy other than upgrades. our `main` branch has datafusion 40 already in it, and the next Rust crate releases will include it

**Comment by rtyler** [comment]
0.18.2 has the fix here i believe
