### ISSUE TITLE
race condition in s3 rename test

### ISSUE THREAD

**Issue by houqp** [delta-io/delta-rs#275]
# Environment

**Delta-rs version**: main branch

**Binding**: Rust

**Environment**:
- **OS**: MacOS

***
# Bug

**What happened**:

Running s3 rename test locally resulted in the following error:

```
test s3::repair_when_worker_pauses_before_rename_test ... FAILED

failures:

---- s3::repair_when_worker_pauses_before_rename_test stdout ----
REQUEST[w1]: PUT /deltars/repair_test_1/src1
REQUEST[w2]: PUT /deltars/repair_test_1/src2
rename(s3://deltars/repair_test_1/src1, s3://deltars/repair_test_1/dst1) started
rename(s3://deltars/repair_test_1/src2, s3://deltars/repair_test_1/dst2) started
REQUEST[w1]: HEAD /deltars/repair_test_1/dst1
Simulating client unexpected pause.
REQUEST[w2]: HEAD /deltars/repair_test_1/dst1
REQUEST[w2]: PUT /deltars/repair_test_1/dst1
REQUEST[w2]: DELETE /deltars/repair_test_1/src1
REQUEST[w2]: HEAD /deltars/repair_test_1/dst2
REQUEST[w2]: PUT /deltars/repair_test_1/dst2
REQUEST[w2]: DELETE /deltars/repair_test_1/src2
rename(s3://deltars/repair_test_1/src2, s3://deltars/repair_test_1/dst2) finished
Waking up and continue to work
REQUEST[w1]: PUT /deltars/repair_test_1/dst1
rename(s3://deltars/repair_test_1/src1, s3://deltars/repair_test_1/dst1) finished
thread 's3::repair_when_worker_pauses_before_rename_test' panicked at 'assertion failed: `(left == right)`
  left: `"DynamoDb { source: ConditionalCheckFailed }"`,
 right: `"NotFound"`', rust/tests/repair_s3_rename_test.rs:30:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

However, I am not able to reliably reproduce this test error. So feels like a race condition to me.

@mosyp have you ran into this before? Perhaps the w1 resumed before the file was deleted? It doesn't look like an actual bug in the rename design or implementation to me.

**What you expected to happen**:

Test should pass consistently.

**How to reproduce it**:

Haven't found a way to reliably reproduce this yet.

**More details**:

**Comment by roeap** [comment]
was this maybe fixed by these lines? 

https://github.com/delta-io/delta-rs/blob/45a0404287287ead94005740dad90b67922e0ec9/rust/tests/repair_s3_rename_test.rs#L62-L63

as well as similar statements in the test? I.e. do we need to keep this issue open? :)
