### ISSUE TITLE
Read delta table after DELETE operation throws IndexError

### ISSUE THREAD

**Issue by zijie0** [delta-io/delta-rs#276]
# Environment

**Delta-rs version**: python-v0.4.8

**Binding**: Python

**Environment**:
- **Cloud provider**: N/A
- **OS**: Ubuntu 18.04

***
# Bug

**What happened**:

After running DELETE operation on delta table, we read the same table through delta-rs Python binding and got exception: `IndexError: list index out of range`.

**What you expected to happen**:

We should expect same behavior with `delta.tables.DeltaTable` which returns and empty dataframe.

**How to reproduce it**:

Start pyspark shell with command:

```
pyspark --packages io.delta:delta-core_2.12:0.8.0 --conf "spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension" --conf "spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog"
```

Execute the test case:

```
from delta.tables import DeltaTable as SparkDeltaTable
from deltalake import DeltaTable


def test_delete_and_read():
    data_path = 'test_data'
    # generate delta data from Spark
    sdf = spark.createDataFrame([[1]], schema=['c'])
    sdf.write.format('delta').save(data_path)

    # delete delta data
    sdt = SparkDeltaTable.forPath(spark, data_path)
    sdt.delete()

    # load via Spark
    sdf = spark.read.format('delta').load(data_path)
    print(sdf.show())

    # load via delta-rs
    dt = DeltaTable(data_path)
    py_table = dt.to_pyarrow_table()  # throw exception here

```

**More details**:

**Comment by fvaleye** [comment]
Hello @zijie0,

Thank you for submitting this error with all the details!

The read of the Python binding failed when no data files are present in the DeltaTable, illustrated by your `test_case` (after the delete operation). It will be fixed after review here: https://github.com/delta-io/delta-rs/pull/277.
It will be available soon in the next Python release version 😄

**Comment by zijie0** [comment]
Hi @fvaleye ,

Cool! Looking forward to the next release. We will use a local fix for now.

**Comment by fvaleye** [comment]
Hello @zijie0,

The release of the Python binding `0.5.0` includes the fix of the issue.
I close this issue. 

Thanks again!
