### ISSUE TITLE
Missing Linux binary releases and source tarball for Python release v0.19.0

### ISSUE THREAD

**Issue by codesorcery** [delta-io/delta-rs#2777]
# Environment

**Delta-rs version**: 0.19.0

**Binding**: Python

**Environment**:
- **OS**: Linux

***
# Bug

**What happened**:
Only wheels for macOS and Windows are available on PyPI for version 0.19.0 (see https://pypi.org/project/deltalake/0.19.0/#files). Source tarball and Linux wheels are missing. Thus, this release is currently not installable on Linux.

**Comment by ion-elgreco** [comment]
@codesorcery Yup, fix is on it's way, and will re-release it. Some issue with new maturin version
