### ISSUE TITLE
Delta-RS Saved Delta Table not properly ingested into Databricks

### ISSUE THREAD

**Issue by niltecedu** [delta-io/delta-rs#2779]
# Environment

**Delta-rs version**:
0.18.2

**Binding**: 
Not sure

**Environment**:
- **Cloud provider**:
Azure Data Lake Gen2

- **OS**:
Windows 11

- **Other**:

***
# Bug

**What happened**:
Ingesting the delta table stored on the azure data lake, made by the deltalake pakage on azure databricks leads to databricks not picking up the delta tables properly; it loads up all of the parquet files instead of reading it as delta table.

**What you expected to happen**:
Only the latest version of the delta table is ingested

**How to reproduce it**:
Created a pandas dataframe, write to azure multiple times using overwrrite,

**More details**:
Creating a ticket with databricks as well to resolve the issue.

**Comment by ion-elgreco** [comment]
We need more info because this sounds like you are not reading the table correctly with spark

**Comment by niltecedu** [comment]
Heya, reading the table via databricks sql, loading it via deltatable package locally with pandas

![image](https://github.com/user-attachments/assets/404c0480-b423-4037-8428-f82ef5b42b02)


Loading it in databricks sql


![image](https://github.com/user-attachments/assets/4a4d68c7-a4e4-4420-9bbb-58cd5b45732a)


Loading it in databricks sql with distinct

![image](https://github.com/user-attachments/assets/28deb23a-e749-48ad-81d6-8aea4d5ac2d4)


The databricks sql also keeps the older version of the file which different rows

**Comment by niltecedu** [comment]
Nevermind, me being a knobhead. I saved to azure data lake with .parquet in the blobname

Fixing it gives me this for ingestion (I am quite new to databricks)

![image](https://github.com/user-attachments/assets/0ecc70f0-867f-4afb-b616-6bfd4ab39bf4)


Closing this now thanks!
