### ISSUE TITLE
Add aws region parameter on DeltaTable class

### ISSUE THREAD

**Issue by mehd-io** [delta-io/delta-rs#278]
# Description
At the moment, delta-rs is getting the aws region through the environment `AWS_REGION`. There's no other possibility to specify the region when reading a remote table on s3.
**Use Case**
The mechanism makes it difficult to read different delta tables on s3 from different AWS regions through the same process. It would be nice to pass this when creating the DeltaTable. 
If the `AWS_REGION` is not set, we get 
```
Failed to load checkpoint: Failed to read checkpoint content: Failed to read S3 object content: Request ID: None Body: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```

**Comment by mehd-io** [comment]
The log I provided was actually not complete - I just updated it. When I try to reach an `us-east-1` bucket while having `AWS_REGION=eu-west-1` it's throwing that error. I had to manually override the env `AWS_REGION` to the appropriate region to make it works. It's true that in like boto3, you don't actually need to specify the region, not sure what's the current behaviour in rusoto thought...

**Comment by Maks-D** [comment]
@mehd-io Thank you for explanation.

**Comment by houqp** [comment]
Hi @Maks-D :)

@mehd-io, if you are using the rust core directly, we should be able to get it supported with a simple PR. All we have to do is to update the s3 storage constructor method to take an option that can specify region, creds and other s3 backend specific configs: https://github.com/delta-io/delta-rs/blob/d922b311b4ff697f5e0c964ddc7572324d2d3c01/rust/src/storage/s3/mod.rs#L167

Then one can use DeltaTable's `new` method to create a table instance with a specific storage backend config: https://github.com/delta-io/delta-rs/blob/d922b311b4ff697f5e0c964ddc7572324d2d3c01/rust/src/delta.rs#L890-L893

**Comment by mehd-io** [comment]
Thx @houqp for pointing it out! I would happy to have a look :)

**Comment by fvaleye** [comment]
@mehd-io feel free to reach me if you want some help to implement it in the Rust land 😄 and we will see if we can add it into the Python binding as well!
