### ISSUE TITLE
expose target_file_size in python side for WriterProperties

### ISSUE THREAD

**Issue by deanm0000** [delta-io/delta-rs#2810]
# Description
In `optimize.z_order` and `optimize.compact` there is the `target_size` parameter but at an initial write the target size isn't an available parameter

**Use Case**

**Related Issue(s)**

**Comment by ion-elgreco** [comment]
@deanm0000 after the fix you can do this also for first writes:
```python
df.write_delta("test_table", mode='overwrite', delta_write_options={"configuration":{'delta.targetFileSize':str(2*104857600)}})
```

**Comment by ion-elgreco** [comment]
I can also expose target_file_size as well
