### ISSUE TITLE
question: deletionVectors support

### ISSUE THREAD

**Issue by ihor-lazariev** [delta-io/delta-rs#2829]
# Description

When using read_delta on a table with `delta.enableDeletionVectors: true`, it fails with a message shown on a screenshot below

![image](https://github.com/user-attachments/assets/7d73c88b-63f8-4c19-a4a2-845403aedd60)

1. Could this feature be supported? 
2. Could I disable the feature on read action? (I don't have access to the deltalake itself, so I can't manage table properties myself)

deltalake version: 0.19.1

**Comment by ion-elgreco** [comment]
This won't be supported for python with our pyarrow scanner.

You can't disable deletion vectors during reads since that would make it an invalid read

**Comment by kmatt** [comment]
Will deletion vectors be supported with #3733 ?
