### ISSUE TITLE
0.19.2 install error when using poetry, pdm on Ubuntu

### ISSUE THREAD

**Issue by Troubladore** [delta-io/delta-rs#2848]
# Environment

**Delta-rs version**: 0.19.2

**Binding**: 

**Environment**: 
- **Cloud provider**:
- **OS**: Ubuntu 22.04
- **Other**: Python 3.11.9, 3.12.2; Poetry or PDM

***
# Bug

**What happened**: when running command: "poetry add deltalake", I get error:
```Using version ^0.19.2 for deltalake

Updating dependencies
Resolving dependencies... (0.5s)

Package operations: 3 installs, 0 updates, 0 removals

  - Installing numpy (2.1.1)
  - Installing pyarrow (17.0.0)
  - Installing deltalake (0.19.2): Failed

  RuntimeError

  Unable to find installation candidates for deltalake (0.19.2)

  at ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/installation/chooser.py:74 in choose_for
       70│ 
       71│             links.append(link)
       72│ 
       73│         if not links:
    →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
       75│ 
       76│         # Get the best link
       77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
       78│ 

Cannot install deltalake.
```

**What you expected to happen**: deltalake to be added to my venv

**How to reproduce it**: using any working repo, with a local poetry venv based on python 3.12.2 or 3.11.9, and run the "poetry add deltalake" command. Or, with the same repo configured using pdm, run "pdm add deltalake".

**More details**:
Reverting to 0.19.1 works for python 3.12.2 and 3.11.9, for both poetry and pdm

**Comment by ldacey** [comment]
Same with uv in a amd64 Docker container

**Comment by ion-elgreco** [comment]
Python 0.19.2 wheels failed due to issue with openssl https://github.com/openssl/openssl/pull/25367

Unfortunately I don't have time to fix this

**Comment by Troubladore** [comment]
No worries, reverting to prev version is fine. openssl will work itself out eventually - thanks for verifying, and for all your contributions to the project!

**Comment by Troubladore** [comment]
@rtyler  - ty for pushing this fix. Initially I got the same error, but then realized it worked with a straight pip install. Running the commands below to clear the Poetry cache allowed me to upgrade from 19.1 to 19.2 without issue.

```
poetry cache clear --all PyPI
poetry cache clear --all _default_cache
```
