### ISSUE TITLE
writing to blobfuse has stopped working in 0.19.2

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#2860]
# Environment

**Deltalake python 0.19.2**:

**Python**: 

**Environment**:
- **Fabric Onelake**:

this code works fine in 0.18.2

```
import pandas as pd 
from deltalake.writer import write_deltalake
df =pd.DataFrame({'x':[1,2,4]})
write_deltalake("/lakehouse/default/Files/dbo/test",df,mode="append",engine ='rust',storage_options={"allow_unsafe_rename":"true"})
```

but does not work with 0.19.2

OSError: Generic LocalFileSystem error: Unable to rename file: Function not implemented (os error 38)

**Comment by ion-elgreco** [comment]
@djouallah can you try this fix: https://github.com/delta-io/delta-rs/pull/2861

**Comment by djouallah** [comment]
sorry, i don't know how to test it ?

**Comment by ion-elgreco** [comment]
> sorry, i don't know how to test it ?

You will have to build your own wheel with that branch for your platform

**Comment by djouallah** [comment]
hahaha, that will be a task for @RobinLin666  :)
