### ISSUE TITLE
Glue Crawler Error: "Internal Service Exception" when integrating Delta with Glue Catalog

### ISSUE THREAD

**Issue by marcoaanogueira** [delta-io/delta-rs#2937]
# Environment

**Delta-rs version**:0.20.0

**Environment**:
- **Cloud provider**: AWS

***
# Bug

**What happened**:
While attempting to integrate Delta Lake tables with the AWS Glue Catalog, I encountered a generic error:
Crawler Error: Internal Service Exception.
This error occurred during the process of cataloging Delta Lake tables, and I couldn't find much information on how to resolve or troubleshoot this issue.

**What you expected to happen**:
The Glue Crawler should successfully catalog the Delta Lake tables without encountering any errors.

**How to reproduce it**:
1 . Create a Delta Lake table.
2. Set up an AWS Glue Crawler to scan and catalog the table.
3. Run the Crawler.

**More details**:
Error:
<img width="1101" alt="Captura de Tela 2024-10-10 às 14 13 48" src="https://github.com/user-attachments/assets/abf88016-648c-49bb-bd53-2c623540f262">

CloudWatch Error:
<img width="1117" alt="Captura de Tela 2024-10-10 às 14 14 58" src="https://github.com/user-attachments/assets/e77b0f66-c7e3-4bf2-b602-d14372315b05">

**Comment by rtyler** [comment]
Please contact AWS Support for this, delta-rs does do anything with Glue Data Catalog and I cannot provide any advice here.

That said, I have successfully used their crawlers in the past for Delta tables. I don't typically use them because they're bad and expensive though :laughing:

**Comment by marcoaanogueira** [comment]
Thank you very much
