### ISSUE TITLE
Bump arrow to v53 to fix CVE 

### ISSUE THREAD

**Issue by vavsab** [delta-io/delta-rs#2946]
# Description
There is [a vulnerability in lexical-core](https://github.com/advisories/GHSA-2326-pfpj-vx3h/improve).
Arrow lib has fixed it in [53.1.0](https://github.com/apache/arrow-rs/commit/3490639252294215c7ee05990d82b43e2cd097a6#diff-c3edfcf206dee8ed7e0028d5ab9c3e003d4f536f7a95490c00a2feb96b9ca35eR52)
![image](https://github.com/user-attachments/assets/16bc465d-ba0b-46e2-9f7b-1b6e6d1e3ca0)

Could you please bump [arrow lib here](https://github.com/delta-io/delta-rs/blob/66441d10ec54a8afb31f6b46489f15ef3369d8bd/Cargo.toml#L33) to v53?

**Comment by ion-elgreco** [comment]
Latest version has arrow 53
