### ISSUE TITLE
MAP types created in the Deltalake parquet do not follow the default naming convention. 

### ISSUE THREAD

**Issue by clarkr7** [delta-io/delta-rs#2976]
# Environment

**Delta-rs version**:
parquet-rs version 49.0.0 with an arrow schema
 

**Binding**: 

**Environment**:
- **Cloud provider**: Azure
- **OS**: Ubuntu 20.04.6
- **Other**:

***
# Bug

**What happened**: 

Creating Deltalake files usin de;lta-rs, and the underlying parquet files using parquet-rs, are creating MAP types that appesr to deviate from Parquet specification. 

**What you expected to happen**:
[Parquet specification](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#maps) states that the inner fields should be named 'key' and 'value':

```
<map-repetition> group <name> (MAP) {
  repeated group key_value {
    required <key-type> key;
    <value-repetition> <value-type> value;
  }
}
```

However, generated files use "keys" and "values", creating a naming discrepancy. 

```
[
  {
    "keys":"Accept",
     "values":"application/json"
   }, 
   ...
```

**How to reproduce it**:
Sorry, do not have a reproduction. 

**More details**:

**Comment by ion-elgreco** [comment]
Which delta-rs version are you using?

**Comment by ion-elgreco** [comment]
In that case it's already resolved. A couple months ago we updated this upstream in delta-kernel-rs

**Comment by clarkr7** [comment]
Thanks @igor-lobanov-maersk @ion-elgreco, appreciate the updates here.
