### ISSUE TITLE
load_cdf return an empty dataframe when a version is out of range

### ISSUE THREAD

**Issue by pblocz** [delta-io/delta-rs#3035]
# Description

In spark delta table you can enable an option to manage out of range versions or timestamps.  https://docs.delta.io/latest/delta-change-data-feed.html#read-changes-in-streaming-queries
![image](https://github.com/user-attachments/assets/6dcdbadd-e190-48ca-abd3-70a8773afb6e)

Right now the behaviour of load_cdf is inconsistent, if you provide an out of range version you get an error:
![image](https://github.com/user-attachments/assets/88f31339-8063-4920-9f6e-e0a91dacddd6)

But with a timestamp out of range, you get an empty dataset:
![image](https://github.com/user-attachments/assets/4876897a-4bf7-4376-ba92-9962d279a059)

It would be useful for incremental pipelines to have a way to manage this behaviour and make it consistent.

**Comment by ion-elgreco** [comment]
If you know some rust it's probably a simple fix

**Comment by pblocz** [comment]
> If you know some rust it's probably a simple fix

@ion-elgreco I have never used rust and it is been a while since I have done anything that needs to be compiles, but can give it a go
