### ISSUE TITLE
Write operations with without_files lead to data loss due to checkpointing

### ISSUE THREAD

**Issue by JonasDev1** [delta-io/delta-rs#3049]
# Environment

**Delta-rs version**: 21.

**Binding**: Rust

***
# Bug

**What happened**:
I am appending to a delta table that is read with without_files to reduce memory usage. The append process works fine, but during automatic checkpoint creation, older commited files are removed because they are not in the table snapshot and are therefore not part of the checkpoint.

**What you expected to happen**:
Either an error should be displayed or the automatic checkpoint creation should be deactivated

**Comment by ion-elgreco** [comment]
Yeahhh, forgot about that interaction with the code base
