### ISSUE TITLE
Do not include field deletionVector in add action when it is disabled

### ISSUE THREAD

**Issue by Zan-L** [delta-io/delta-rs#3055]
# Description
Snowflake [Delta Diret](https://docs.snowflake.com/en/sql-reference/sql/create-iceberg-table-delta) can't be used on Delta tables produced by delta-rs because it always includes `deletionVector: null` in add actions and Snowflake doesn't support add actions. Removing that field manually from the log files could make it work. But I'm hoping that this field could be dropped for those that have `delta.enableDeletionVectors` set to `false`.

**Use Case**
[Delta Diret](https://docs.snowflake.com/en/sql-reference/sql/create-iceberg-table-delta)

**Related Issue(s)**

**Comment by rtyler** [comment]
Do you have a contact at Snowflake that can participate in this discussion @Zan-L ? The Delta Lake protocol makes this field optional, and it sounds like their reader has a bug or needs to be upgraded

**Comment by Zan-L** [comment]
Thanks for the update! Unfortunately, I don't have any yet. It is a preview feature though so the bug could likely come from them. Feel free to close this issue in that case.
