### ISSUE TITLE
Remove print statement

### ISSUE THREAD

**Issue by tom1919** [delta-io/delta-rs#3070]
The print statement linked below seems unnecessary. Could it be removed?
 
https://github.com/delta-io/delta-rs/blob/main/crates/mount/src/file.rs#L275

https://github.com/delta-io/delta-rs/blob/f49eedb1eeca3fc6adc06076c4cf0a61a6b57912/crates/mount/src/file.rs#L268

**Comment by ion-elgreco** [comment]
@tom1919 can you make a PR for it?
