### ISSUE TITLE
Low level API for creating new delta tables

### ISSUE THREAD

**Issue by Smurphy000** [delta-io/delta-rs#339]
# Description
Adding the ability to create a new Delta table from scratch

**Use Case**
Create a delta table outside of spark

**Comment by Smurphy000** [comment]
I have started some work on this

**Comment by houqp** [comment]
Thanks @Smurphy000 ! I have assigned the issue to you :)

**Comment by Bernolt** [comment]
Hello, I see the issue have been closed, however I don't see the PR. What is the status of this subject?
Br

**Comment by Smurphy000** [comment]
@Bernolt https://github.com/delta-io/delta-rs/pull/342
