### ISSUE TITLE
Duplicate data produced by load_version method

### ISSUE THREAD

**Issue by zijie0** [delta-io/delta-rs#345]
# Environment

**Delta-rs version**: 0.5.1

**Binding**: Python

**Environment**:
- **Cloud provider**: local
- **OS**: CentOS 7.6
- **Other**: Spark 3.0.1

***
# Bug

**What happened**:

When we use `load_version` to get an old version of dataset, the returned data is doubled in rows with duplication.

**What you expected to happen**:

Should get same result with `versionAsOf` option in original Delta.

**How to reproduce it**:

```
spark = pyspark.sql.SparkSession.builder.getOrCreate()
sdf = spark.createDataFrame([['2021-01-01', 1], ['2021-01-02', 3]], schema=['biz_date', 'sales'])
delta_path = 's3a://tmp/test_overwrite'
s3_path = 's3://tmp/test_overwrite'

# write data twice to generate two versions
sdf.write.format("delta").mode("overwrite").option("overwriteSchema", "true").save(delta_path)
sdf.write.format("delta").mode("overwrite").option("overwriteSchema", "true").save(delta_path)

dt = DeltaTable(s3_path)
print(dt.to_pandas().shape)

dt = DeltaTable(s3_path)
dt.load_version(0)
print(dt.to_pandas().shape)
```

The results on my machine is: 

```
In [20]: dt = DeltaTable(s3_path)

In [21]: dt.version()
Out[21]: 3

In [22]: dt.to_pandas().shape
Out[22]: (2, 2)

In [23]: dt = DeltaTable(s3_path)

In [24]: dt.load_version(2)

In [25]: dt.to_pandas().shape
Out[25]: (4, 2)
```

Test with Spark:

```
In [26]: sdf1 = spark.read.format('delta').option("versionAsOf", 3).load(delta_path)

In [27]: sdf1.count()
Out[27]: 2

In [28]: sdf2 = spark.read.format('delta').option("versionAsOf", 2).load(delta_path)

In [29]: sdf2.count()
Out[29]: 2
```

**More details**:

**Comment by houqp** [comment]
thanks @zijie0 for the report, i think this is caused by bugs in the core rust time travel code.

**Comment by zijie0** [comment]
I found a workaround using following code to specify the version:

```
dt = DeltaTable(path, version=version)
```

It returned the same results with Spark.

**Comment by houqp** [comment]
I think most likely this is caused by us not clearing the table state in https://github.com/delta-io/delta-rs/blob/main/rust/src/delta.rs#L698. We do clear table state in `restore_checkpoint`, so this won't happen to tables with more than 10 commits.

@zijie0 are you interested in giving a try to send a PR to fix this bug in the rust core? I think adding `self.state = DeltaTableState::default();` in that branch should be good enough.

**Comment by zijie0** [comment]
@houqp cool! Let me try to get familiar with Rust :)
