### ISSUE TITLE
Read table failed when containing null partition values

### ISSUE THREAD

**Issue by zijie0** [delta-io/delta-rs#348]
# Environment

**Delta-rs version**: 0.5.1

**Binding**: Rust/Python

**Environment**:
- **OS**: CentOS 7.6
- **Other**: Spark 3.0.1 + delta 0.7.0

***
# Bug

**What happened**:

When reading partitioned delta table containing null values, the program throws an exception.

**What you expected to happen**:

Should be able to read table containing null partition values.

**How to reproduce it**:

```
spark = pyspark.sql.SparkSession.builder.getOrCreate()
sdf = spark.createDataFrame([['A', 1], [None, 2]], schema=['k', 'v'])
delta_path = 's3a://tmp/test_partition_with_null'
s3_path = 's3://tmp/test_partition_with_null'

sdf.write.format("delta").mode("overwrite").option("overwriteSchema", "true").save(delta_path)
dt = DeltaTable(s3_path)  # throw PyDeltaTableError!
```

The error message:

```
In [15]: dt = DeltaTable(path)
---------------------------------------------------------------------------
PyDeltaTableError                         Traceback (most recent call last)
<ipython-input-15-2195f07dec1c> in <module>
----> 1 dt = DeltaTable(path)

/home/guandata/.pyenv/versions/3.7.9/lib/python3.7/site-packages/deltalake/table.py in __init__(self, table_uri, version)
     74         :param version: version of the DeltaTable
     75         """
---> 76         self._table = RawDeltaTable(table_uri, version=version)
     77         self._metadata = Metadata(self._table)
     78

PyDeltaTableError: Failed to apply transaction log: Invalid JSON in log record
```

It works fine when using Spark:

```
In [16]: sdf1 = spark.read.format('delta').load('s3a://dolphinscheduler/tmp/test_partition_on_null')

In [17]: sdf1.show()
+----+---+
|   k|  v|
+----+---+
|null|  2|
|   A|  1|
+----+---+
```

**Comment by zijie0** [comment]
I think the problem is that in delta log, there's following line for the null values:

```
{"add":{"path":"k=__HIVE_DEFAULT_PARTITION__/part-00001-8474ac85-360b-4f58-b3ea-23990c71b932.c000.snappy.parquet",
"partitionValues":{"k":null},"size":460,"modificationTime":1627990384000,"dataChange":true}}
```

But in the code here: https://github.com/delta-io/delta-rs/blob/main/rust/src/action.rs#L153
We assume that the partitionValues with type `HashMap<String, String>`, but should be `HashMap<String, Option<String>>`?

**Comment by houqp** [comment]
Good catch @zijie0 , the `HashMap<String, String>` field type is defined based on the type provided in the official delta spec, see https://github.com/delta-io/delta/blob/master/PROTOCOL.md#add-file-and-remove-file and https://github.com/delta-io/delta/blob/master/PROTOCOL.md#partition-value-serialization.

Specifically this quote:

> Partition values are stored as strings, using the following formats. An empty string for any type translates to a null partition value.

So if the reference implementation actually adheres to the spec, it should be writing out empty string for the partition value. I wonder if it's a bug in the 0.7 implementation or a bug in the official deltalake spec. Do you mind sending a question to the deltalake dev list (https://groups.google.com/g/delta-users) for a broader discussion?

**Comment by houqp** [comment]
code to the reference implementation https://github.com/delta-io/delta/blob/eab445a15f478ed2454cf152edb795e9fece91f6/core/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala#L223

**Comment by zijie0** [comment]
@houqp I have posted a question here: https://groups.google.com/g/delta-users/c/ZzzrtNRqRyk

**Comment by houqp** [comment]
@zijie0 thanks for posting the question on the dev list, I think you are right that the field should be declared as `HashMap<String, Option<String>>`. If you send a PR for it, I will be more than happy to merge.

**Comment by zijie0** [comment]
@houqp Ok, I will take a look.
As I am very new to Rust, might need your help on some implementation details :)
