### ISSUE TITLE
Add commitInfo action to low level create table API

### ISSUE THREAD

**Issue by Smurphy000** [delta-io/delta-rs#350]
# Description
The commitInfo for Delta to store additional provenance data should be added to the create table API

# Additional Information
https://github.com/delta-io/delta/blob/master/PROTOCOL.md#commit-provenance-information
https://github.com/delta-io/delta-rs/blob/main/rust/src/action.rs#L755

**Comment by Smurphy000** [comment]
Since commitInfo is stated that implementations are free to store any valid json here, do we have a set of minimum required fields for the delta-rs project that we would want implemented?

**Comment by houqp** [comment]
I think a good approach would be taking a json object passed in by the caller, then add delta-rs version and timestamp on top of it before doing the commit. The more interesting higher level audit info like owner of the commit and operation type will be provided by the caller and should be transparent to delta-rs.

**Comment by Smurphy000** [comment]
@houqp I can work on this now
