### ISSUE TITLE
Honor appendOnly table config in table writes

### ISSUE THREAD

**Issue by houqp** [delta-io/delta-rs#352]
# Environment

**Delta-rs version**: all

**Binding**: all

# Bug

Currently we are not taking `appendOnly` table config into account when performing delta table writes. This config needs to be honored at two levels. In the low level delta transaction commit code path, we need to throw an error if a remove file action is included in a transaction. In the high level delta write API (not available in delta-rs yet), we need to throw an error if user query will result in in place data update.

**Comment by wjones127** [comment]
This we added support for enforcing invariants, this is the only thing left to support writer protocol v2.
