### ISSUE TITLE
public DeltaTable method to access table config

### ISSUE THREAD

**Issue by houqp** [delta-io/delta-rs#353]
# Description

**Use Case**

Looks like there is no public method declared on the `DeltaTable` struct itself to access table config value. Table configurations are currently encapsulated within DeltaTableState.TableMetadata, which is all private fields.

**Comment by Smurphy000** [comment]
Are you saying that a method is needed on `DeltaTable` that can get the current Metadata from its state field and return the configuration HashMap?

**Comment by houqp** [comment]
that's correct

**Comment by Smurphy000** [comment]
I can probably do this unless somebody else wants to

**Comment by houqp** [comment]
Thanks @Smurphy000 , consider yourself assigned :)
