### ISSUE TITLE
setup end to end integration CI test for S3 feature

### ISSUE THREAD

**Issue by houqp** [delta-io/delta-rs#36]
we could leverage projects like localstack and minio to serve test tables through S3 API

**Comment by rtyler** [comment]
With #57 I'm already the point of contact for the Azure storage binding. I can probably just do the same with my neglected AWS account :smile_cat:

**Comment by houqp** [comment]
i was thinking of setting up mino, but if we can get a real public s3 bucket setup, that's even better.
