### ISSUE TITLE
Audit action field optionality

### ISSUE THREAD

**Issue by houqp** [delta-io/delta-rs#372]
# Environment

**Delta-rs version**: all

**Binding**: rust

***
# Bug

**What happened**:

Some of the fields are incorrectly marked as optional in action.rs

**What you expected to happen**:

Make sure optionality annotation matches with what's in delta spec and reference implementation: https://github.com/delta-io/delta/blob/master/core/src/main/scala/org/apache/spark/sql/delta/actions/actions.scala

**How to reproduce it**:

**More details**:

Follow up from https://github.com/delta-io/delta-rs/pull/370

**Comment by mosyp** [comment]
We also has to double check changes and do not copy paste 1-to-1 as this example https://github.com/delta-io/delta-rs/pull/417/files/b33124ce41bf4ce9b210fc67a79c8e8590dc72b4#diff-9fb70b66d3f77e15e99399b95228d124db4bd0d898e1e159bf106ccced488332 shows that we could face some issues
