### ISSUE TITLE
Parameter swap is ignored put_obj in windows fs backend

### ISSUE THREAD

**Issue by mosyp** [delta-io/delta-rs#377]
# Environment

**Delta-rs version**: all

**Binding**:  rust

**Environment**:
- **OS**: windows

***
# Bug

**What happened**:

`swap` parameter is ignored in windows backend `put_obj` function with changes introduced in #376

**Comment by zijie0** [comment]
@mosyp I submitted a PR for this issue.
One remaining problem is that under Linux, if we swap the file, the original file still exists. But in Windows, the original file would be gone.
I'm not sure if we should delete original file in Linux implementation or keep the original file in Windows?

**Comment by mosyp** [comment]
As of now, we only use swap in put_obj where we delete the `tmp` file whatsoever. Taking into account that under windows its done by default without any additional call works for me. Especially since we're not exposing the rename for pub api. However it makes sense to note that platform specific behaviour in func inline docs
