### ISSUE TITLE
Explore behaviour of creating checkpoints with passed table reference

### ISSUE THREAD

**Issue by mosyp** [delta-io/delta-rs#385]
# Description
A follow up issue from https://github.com/delta-io/delta-rs/pull/384/files#r688514360. The create checkpoint call mutates the given table state, thus we have to make it expected to the caller. There's a few possibilities, like keeping an old version, the one that matches given version or bumping to the latest one (what we have now)

**Use Case**
When creating checkpoints with reference to the DeltaTable

**Comment by xianwill** [comment]
IMHO - to abide by "principal of least surprise" the correct behavior would be to store the starting table version and restore up to that point but no farther. So just before the check in https://github.com/delta-io/delta-rs/blob/0a9cc679a4070f7c799ee2fc7d1d898c4d61fbc8/rust/src/checkpoints.rs#L99 (`if table.version != version`), we would do something like:

```
let initial_version = table.version
```

and implement a method analogous to the existing `update_incremental` that accepts a stopping point. We would pass `initial_version` to that method - i.e. `table.update_incremental_to_version(initial_version)`.

That way the user gets their table back in the same state it was in.

**Comment by houqp** [comment]
How about we just make `create_checkpoint_from_table` take an immutable reference of the passed in table and get rid of the version argument?

For applications that only need to checkpoint the current state of a table, that version argument is redundant.

For applications that need to checkpoint a table with a different version, it can just call the `load_version` itself right before the `create_checkpoint_from_table` call. We basically just caller manage the table version change and restore so there will be no surprises. We could still implement `table.update_incremental_to_version(initial_version)` for applications that need to restore table back to a particular state incrementally.

**Comment by mosyp** [comment]
That's true though, so basically we'll be down to the single function e.g.  `create_checkpoint_from_table`. I like the simplicity, I can easily move `load_version` to the kdi
