### ISSUE TITLE
Move version field into `DeltaTableState` struct

### ISSUE THREAD

**Issue by houqp** [delta-io/delta-rs#390]
# Description
`version` is currently a field in `DeltaTable`. It would make more sense to move this into `DeltaTableState` since version maps one to one to state.

**Comment by explicite** [comment]
@houqp I raised draft for this https://github.com/delta-io/delta-rs/pull/553

Still no sure:
1. if we should expose whole state on table
2. Ruby/Python we should move object like state to `DeltaTable...` definitions, or expose only version

Thanks for advice

**Comment by houqp** [comment]
Thanks @explicite for taking on this task! The general rule of thumb for exposing internal fields as public is to consider whether there is a dependency between the field we want to expose with any other field in the struct. In this case, I think version was the only field that correlates to state, so it should be safe to expose the state field after we moved the version field into it. If a field is exposed in the Rust side, I think it's reasonable to expose it to python/ruby as well if you want to do that.
