### ISSUE TITLE
Add mocked GCS provider for tests

### ISSUE THREAD

**Issue by mosyp** [delta-io/delta-rs#397]
# Description
For S3 we have localstack to mock s3/dynamodb usages. But not for others. For GCS quick googling resulted in https://github.com/fsouza/fake-gcs-server. We might give it a try. 

It also would be good to standardise test cases for each backend as well as in CI.

**Comment by roeap** [comment]
We are now using fake-gcs, there are some tests omitted, due to upstream issues, but that is tracked in #780.
