### ISSUE TITLE
DeltaTable likely not handling log_path in a platform-safe manner

### ISSUE THREAD

**Issue by rtyler** [delta-io/delta-rs#40]
Lots of DeltaTable code is doing a primitive "join" (e.g. `format!("{}/{}", log_path, other)`) when creating paths. In the cases where this path is going to be a file system path, this isn't a safe way to create paths.

@houqp I think we're going to have to find some way to handle these path creations better than just munging strings.

**Comment by rtyler** [comment]
OOOOF, I think this is very much related to #39 `find_latest_check_point_for_version` is doing path regular expressions which are in no possible way going to work as expected on Windows :facepalm:

**Comment by houqp** [comment]
yep, apparently the code was not written with windows in mind :P should replace with `std::path::Path`.

**Comment by houqp** [comment]
having a second thought here. when using the azure or s3 backend in windows, do we get unix path or windows path returned from APIs? If it's consistent with native platform path, then we are good, otherwise, we might need to move all the path handling logic into file storage backend instead.

**Comment by sd2k** [comment]
I've just tried running the E2E Azure test on Windows and it passes. The docs also state that the 'path' in the URI should be forward slash delimited: https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-introduction-abfs-uri.

**Comment by houqp** [comment]
Thanks @sd2k for the test! Then it looks like what we need to do is to extend the storage backend trait (https://github.com/apache/arrow/tree/master/rust/parquet) to add methods for path component join and split. Then only use use `std:path::Path` in file storage backend to accommodate for platform specific fs path.

**Comment by houqp** [comment]
as a note for implementer, https://github.com/delta-io/delta-rs/blob/main/rust/src/delta.rs#L497 also needs to be updated to stop using platform specific `Path`.

**Comment by houqp** [comment]
@fvaleye just saw my note in this PR, looks like we missed `get_file_paths` in your refactoring :)

**Comment by fvaleye** [comment]
It seems that I forgot to include this in my PR. Thank you for noticing it, I will submit another PR for refactoring this :)

**Comment by roeap** [comment]
A core feature of `object_store` is to provide a common (and extensively tested) abstraction around paths in an object store across all backends and supported OSs. So I believe this should be properly handled now :).
