### ISSUE TITLE
Move delta-inspect to its own crate

### ISSUE THREAD

**Issue by houqp** [delta-io/delta-rs#402]
# Description

**Use Case**

Currently delta-rs Rust core depends on cli related dependencies like `clap`, which is unnecessary for downstream consumers. We should move delta-inspect code into its own crate within the same workspace like what we did for `aws/delta-checkpoint` so we can move all cli related dependencies to the cli crate and keep delta-rs dependency tree clean.

**Related Issue(s)**

https://github.com/delta-io/delta-rs/issues/401

**Comment by blogle** [comment]
Does `delta-inspect` have any value beyond being an example of how to interact with delta tables through the rust api? Or in other words is there any intent to further develop and add features to it? if not I would suggest just cordoning it off into an `examples` directory similar to what the pyo3 folks do https://github.com/PyO3/pyo3/tree/main/examples.

I think this would solve the goal of removing those dependencies, including from the workspace entirely

**Comment by houqp** [comment]
I do plan to maintain delta-inspect as a simple cli tool that can be used to for debugging purpose similar to parquet-tools. So there is value in moving it into a self-contained crate.
