### ISSUE TITLE
Add additional documentation to setting up python development

### ISSUE THREAD

**Issue by Smurphy000** [delta-io/delta-rs#404]
# Description
Currently trying to setup the dev environment for python using maturin, however, based on the current documentation in the readme and looking for other sources, I can't seem to find a way to easily install the optional dependencies listed in the pyproject.toml file. 

This began after I successfully ran `make develop` but then tried running `make unit-test` where I release pytest was under optional dependencies and no optional dependencies were install with the `make develop` command

**Use Case**
Quickly get the dev environment setup including testing, formatting, and other optional dependencies

**Comment by Smurphy000** [comment]
https://github.com/PyO3/maturin/issues/604

**Comment by Smurphy000** [comment]
From linked issue, I overcame the current concern using `make build` followed by `pip install <path-to-wheel>/example.whl[devel]` or other forms could work. If that is the preferred way for now I could add that to the readme

**Comment by houqp** [comment]
Yes, this is how I setup my local env as well. Thanks for helping with documentation.

**Comment by fvaleye** [comment]
> From linked issue, I overcame the current concern using `make build` followed by `pip install <path-to-wheel>/example.whl[devel]` or other forms could work. If that is the preferred way for now I could add that to the readme

Yes, good idea! The `README.md` needs to be updated to include the optional dependencies for the local environment. You could take a look at the Python build Github workflow file: https://github.com/delta-io/delta-rs/blob/main/.github/workflows/python_build.yml#L58. Thanks for helping!

**Comment by Smurphy000** [comment]
@fvaleye are we good to close this?

**Comment by fvaleye** [comment]
> @fvaleye are we good to close this?

Yes, let me do this for you!
