### ISSUE TITLE
Leverage batch delete in vacuum for Azure Storage

### ISSUE THREAD

**Issue by Dandandan** [delta-io/delta-rs#408]
# Description
Azure supports batching multiple delete operations in a single call. This can speed up vacuum.
We shuld add a new `delete_objs` implementation of StorageBackend for Azure.

**Use Case**

**Related Issue(s)**
https://github.com/delta-io/delta-rs/issues/394

**Comment by akbhuker** [comment]
hey, can I have this issue?
I'm quite new to this so I might need some guidance

**Comment by houqp** [comment]
Issue assigned, thanks @akbhuker for taking up on this!

**Comment by Bernolt** [comment]
Hello,
Any progress here?
if not, I am would be happy to jump in.

**Comment by wjones127** [comment]
Now that we use objectstore, we should implement this upstream: https://github.com/apache/arrow-rs/issues/2615

**Comment by roeap** [comment]
closing this here, as this is now part of upstream object_store.
