### ISSUE TITLE
list_objs is likely going to be problematic with large buckets/directories

### ISSUE THREAD

**Issue by rtyler** [delta-io/delta-rs#41]
The way `find_latest_check_point_for_version` is interacting with `list_objs` in a way that I *think* is going to be inefficient for a large storage bucket (think thousands of objects). 

Right now `list_objs` is returning a stream of items in the bucket/directory and then `find_latest_check_point_for_version` will match against those results.

At least with the S3 `ListObjects` API, the caller can specify a `prefix` to limit the responses to, which may be one way we can prevent `list_objs` from returning too many results just to find the latest checkpoint.

Since I'm brainstorming right now, `list_objs` could just take some `Option<Predicate>` assuming Azure Blob storage has a similar functionality, that would allow delta.rs to shunt the initial filtering of objects into the cloud provider.

**Comment by sd2k** [comment]
Azure Blob storage does have similar functionality, yep: https://docs.rs/azure_sdk_storage_blob/0.45.3/azure_sdk_storage_blob/container/requests/struct.ListBlobBuilder.html#method.with_prefix

**Comment by kevinglasson** [comment]
Seems like this is the way to go. Should the table name be included as part of the filter in the event that there are multiple tables.

**Comment by houqp** [comment]
We are already using prefix to restrict directory listing to `table_path/_delta_log` folder. It's a bit harder to filter with prefix for objects within that directory since we don't know what the prefix should be for individual commit log entries.

@kevinglasson table name is part of `table_path`, so this should have already been covered for both s3 and azure blob storage.

**Comment by houqp** [comment]
closing this ticket since I believe we are already leveraging prefix listing as efficient as we could.
