### ISSUE TITLE
S3 storage backend should take the region as a parameter

### ISSUE THREAD

**Issue by rtyler** [delta-io/delta-rs#42]
Right now us-east-2 is hard-coded. Not sure what the right API will be here, but the region should be user-defined in some fashion

**Comment by houqp** [comment]
Based on the look up order in https://docs.rs/rusoto_credential/0.45.0/src/rusoto_credential/lib.rs.html#368-373, we can try to first read the region from `AWS_REGION` env var, if not found use https://docs.rs/rusoto_credential/0.45.0/rusoto_credential/struct.ProfileProvider.html#method.region_from_profile to load it from profile. And lastly throw an error if region cannot be resolved.

**Comment by houqp** [comment]
I think this could be a useful feature to add to upstream trait: https://docs.rs/rusoto_credential/0.45.0/rusoto_credential/trait.ProvideAwsCredentials.html

**Comment by rtyler** [comment]
@houqp I was referring to [this line](https://github.com/delta-io/delta.rs/blob/main/rust/src/storage/s3.rs#L32) which I don't fully understand how the credentials interacts with that setting on the `S3Client`

**Comment by houqp** [comment]
it uses https://docs.rs/rusoto_credential/0.45.0/rusoto_credential/struct.DefaultCredentialsProvider.html, which is basically chained provider. there is also a method that lets you override what provider to use: https://rusoto.github.io/rusoto/rusoto_s3/struct.S3Client.html

**Comment by kevinglasson** [comment]
Should it just mimic the [S3Client API](https://rusoto.github.io/rusoto/rusoto_s3/struct.S3Client.html) API and have:

pub fn new(region: Region) -> S3Client

pub fn new_with<P, D>(
    request_dispatcher: D,
    credentials_provider: P,
    region: Region
) -> S3Client

?

**Comment by houqp** [comment]
@kevinglasson the code you pasted still requires users to manually specify a region and it is what we are using at the moment: https://github.com/delta-io/delta-rs/blob/main/rust/src/storage/s3.rs#L32.

The issue here is implementing a way to automatically resolve the region based on credential chain so it works just like other tools using AWS sdks.

**Comment by kevinglasson** [comment]
@houqp ahh I think I misunderstood, sorry.

I personally think it makes sense for the user to have to specify the region when creating a storage backend, seeing as the bucket they're supposedly targeting should already exist.

However, if we wanted a default we could use [this](https://rusoto.github.io/rusoto/rusoto_core/region/enum.Region.html). It looks like the default implementation for `Region` will do what we want, here is the relevant info:

```text
Region implements the Default trait. Calling Region::default() will attempt to
read the AWS_DEFAULT_REGION or AWS_REGION environment variable. If it is
malformed, it will fall back to Region::UsEast1. If it is not present it will
fallback on the value associated with the current profile in ~/.aws/config or
the file specified by the AWS_CONFIG_FILE environment variable. If that is
malformed of absent it will fall back on Region::UsEast1
```

Meaning we could have:

```rust
impl S3StorageBackend {
    pub fn new(region: Region) -> Self {
        let client = S3Client::new(region);
        Self { client }
    }
}

impl Default for S3StorageBackend {
    fn default() -> Self {
        Self::new(Region::default())
    }
}
```

**Comment by houqp** [comment]
good call @kevinglasson , i was not aware of that `Region::default()` magic :D This is exactly what we need. Since you already wrote the patch in markdown, do you mind converting it to a PR? Just don't forget to also update `get_backend_for_uri` ;)

**Comment by kevinglasson** [comment]
Sure thing, thanks for the tip!

**Comment by kevinglasson** [comment]
So I looked in to updating `get_backend_for_uri`

According to [AWS' docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html) in the **Accessing a bucket** section it states that the `s3://...` style URI does not contain the region so we can't actually extract a specific region from the URI to create an `S3Client` with.

It's also important to note that s3 bucket names are **globally unique** and so creating the client with the region doesn't seem to be necessary when using the `s3://...` style URI.

So I think the solution is to just change to using `Region::default()` in new and to remove the `Default impl`.

ADLSGen2Backend probably doesn't need the `Default impl` either (it just calls new) and File doesn't have one.
