### ISSUE TITLE
Optimize remove action apply with early iteration exit

### ISSUE THREAD

**Issue by houqp** [delta-io/delta-rs#424]
# Description

**Use Case**

Right now, we use `Iterator::retain` to remove files from active file list when applying remove actions from the transaction log: https://github.com/delta-io/delta-rs/blob/0a05cb45ace7a75ae87bbd4acb3b919653e09233/rust/src/delta.rs#L1484

This can be further optimized by performing an early exit of the iteration when we reach the file that needs to be removed. There is no point going through the remaining of the file list and compare paths since file paths should be unique.

**Related Issue(s)**

**Comment by akshay26031996** [comment]
Hey, can I have this issue? I am thinking of the following approach.

First find the position of the file to remove.
```rust
state.files.iter().position(|a| *a.path == v.path)
```
[It will stop processing as soon as it finds a true.](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.position)

Then we can just use the index from above to remove the element from files.
```rust
let index = { state.files.iter().position(|a| *a.path == v.path) };
if let Some(index) = index {
    state.files.remove(index);
}
```

**Comment by houqp** [comment]
Looks good to me, @akshay26031996 assigned the issue to you.
