### ISSUE TITLE
Datafusion integration assumes table's data files are local

### ISSUE THREAD

**Issue by sd2k** [delta-io/delta-rs#43]
The Datafusion integration passes a list of file paths representing a table's actual data to Datafusion's ParquetExec, but if the Delta table's StorageBackend is anything other than the FileStorageBackend then this fails because the files aren't local.

I'm not sure where this should be handled though - it feels like this should be part of Datafusion or an extension crate?

**Comment by houqp** [comment]
Yeah, unfortunately, datafusion uses arrow parquet readers, which only supports local file at the moment: https://github.com/apache/arrow/blob/master/rust/datafusion/src/physical_plan/parquet.rs#L181. I think this is best handled by the rust parquet reader with minor adjustments to datafusion's execution plan after that.

@nevi-me has plans to add S3 support to the parquet reader. If you are interested in extending the reader to support S3 or other cloud storages, I would recommend collaborating with him :)

**Comment by sd2k** [comment]
> I think this is best handled by the rust parquet reader with minor adjustments to datafusion's execution plan after that.

Makes sense to me!

> @nevi-me has plans to add S3 support to the parquet reader. If you are interested in extending the reader to support S3 or other cloud storages, I would recommend collaborating with him :)

Sounds good, I'll keep an eye on it and try and contribute an Azure reader when the time comes.

**Comment by nevi-me** [comment]
What could work in the interim is to use DataFusion's in-memory datasource (https://docs.rs/datafusion/2.0.0/datafusion/datasource/memory/index.html). When we have async-support on Parquet, then we can change to the relevant methods.

**Comment by meastham** [comment]
@nevi-me is there a bug anywhere to track S3 support? I took a brief look in the Arrow and Datafusion repos and didn't find anything. If you're open to it it's something that we could potentially look in to contributing.

**Comment by houqp** [comment]
@meastham feel free to start a discussion for s3 support in the upstream datafusion github repo or in the arrow dev mailing list.

**Comment by roeap** [comment]
With the adoption of `object_store`, the datafusion integration now supports all storage backends - there are integration tests as well :). 

https://github.com/delta-io/delta-rs/blob/main/rust/tests/integration_datafusion.rs
