### ISSUE TITLE
Java binding for `delta-rs`

### ISSUE THREAD

**Issue by dungdm93** [delta-io/delta-rs#469]
Hello Delta community, thanks for create a great table format.

It's just a random idea, but it's nice, I think.
Current [`delta`](https://github.com/delta-io/delta) implementation depends on to Spark, which means there are a lots of others use-cases as Kafka Sink Connect, Flink, Trino/Presto,... which requires both read and write into delta table are now impossible.
In the other hand, `delta-rs` project now provide bindings for `python` and `ruby`.

So, the idea here is why don't we create `java` binding from `delta-rs`, then Flink, Trino/Presto will benefit greatly from this.

**Comment by houqp** [comment]
@scottsand-db is working on write support for the native java implementation at https://github.com/delta-io/connectors/tree/master/standalone/src. So it's better to focus on that effort instead.
