### ISSUE TITLE
GCS support not working properly for Python binding

### ISSUE THREAD

**Issue by kelvins** [delta-io/delta-rs#470]
# Environment

- **OS**: Ubuntu 16.04.7 LTS
- **Binding**: Python
- **Python Version**: 3.8.5
- **deltalake**: 0.5.3
- **pyarrow**: 5.0.0

***
# Bug

**What happened**:

GCS support was recently included to `delta-rs` but when trying to read a delta table directly from GCS, using Python bindings, I'm getting the following error:

```python
>>> from deltalake import DeltaTable
>>> dt = DeltaTable('gs://my-bucket/my-table')
---------------------------------------------------------------------------
PyDeltaTableError                         Traceback (most recent call last)
----> 1 dt = DeltaTable('gs://my-bucket/my-table')

/usr/local/lib/python3.8/site-packages/deltalake/table.py in __init__(self, table_uri, version)
     77         :param version: version of the DeltaTable
     78         """
---> 79         self._table = RawDeltaTable(table_uri, version=version)
     80         self._metadata = Metadata(self._table)
     81 

PyDeltaTableError: Failed to read delta log object: Invalid object URI
```

To be honest, I'm not sure if the Python bindings v0.5.3 is already supporting GCS backend as I couldn't find a documentation about that.

I have also tried to build the Python wheel from source, following this documentation:

https://github.com/delta-io/delta-rs/tree/main/python#build-manylinux-wheels

But I got the same error.

**What you expected to happen**:

I expected the delta table could be read successfully from a GCS bucket, using the Python bindings.

**How to reproduce it**:

Using Python 3.8.5 install `deltalake` from PyPI: `pip install deltalake==0.5.3`

Change the following path to point to a valid GCS bucket containing a delta table and run the code:

```python
from deltalake import DeltaTable
dt = DeltaTable('gs://my-bucket/my-table')
```

**More details**:

The discussion about this issue started at `delta-rs` channel from Delta Users Slack workspace ([link](https://delta-users.slack.com/archives/C013LCAEB98/p1634667728082600)).

**Comment by houqp** [comment]
@kelvins could you try this development build step instead? https://github.com/delta-io/delta-rs/tree/main/python#ready-to-develop-with-maturin. When you build it from source, make sure you are passing in `--features=gcs` argument.
