### ISSUE TITLE
Create Golang bindings for Delta Rust API

### ISSUE THREAD

**Issue by dennyglee** [delta-io/delta-rs#481]
# Description
Just like the Python and Ruby bindings, it would be great if we could have Golang bindings.

**Use Case**
Allow clients use Golang to connect to Delta tables 

**Related Issue(s)**

**Comment by rtyler** [comment]
There are a couple other concurrent projects implementing native Golang libraries

**Comment by xrn** [comment]
@rtyler do you have any links to them?

**Comment by rtyler** [comment]
* https://github.com/cmackenzie1/deltalake-go
* https://github.com/csimplestring/delta-go
* https://github.com/delta-golang/delta-go

There's also another one which I am aware of t hat is private
