### ISSUE TITLE
High-level writer API

### ISSUE THREAD

**Issue by roeap** [delta-io/delta-rs#509]
# Description

Recently I have been trying to understand the current state of writer implementations for `delta-rs` and what could be the desired state for a high level writer API. All of it in the hopes to contribute to this effort. Looking into this it seems to me there can be a wide range of complexity for a potential implementation - from complex to very complex :D.

This may be already a too simplistic/naive view, but it seems to me on a lower level all operations would boil down to a number of add/remove actions to update the log and associated data that may contain new data or represent existing data with some records removed or updated. The files to be removed would depend on the specifics of a higher level operation. Based on what I understand right now, the files to be added would "only" depend on the partitioning of the table and the desired max file size for files written to the table.

If I understood the current implementations from this crate and `kafka-delta-ingest` correctly, they are mostly based on json messages to be written, which are distributed to several buckets based on partitioning of the table. On the arrow record batch level we already seem to assume individual batches contain data belonging to exactly one partition. Trying to find a way to generically implement partitioning for record batches it already seemed to me it may be worthwhile to consider using a higher level crate for this rather then re-implementing this using the arrow compute kernels.

Making the question a bit more specific, I see some options to move forward with this.

1) Minimal only

The writer API would expect pre-partitioned data (and panic otherwise) along with remove actions, write the record batches and wrap everything in a transaction. Current implementations for json data could be retained.

2) Automatic partitioning

The writer API can take generic record batches and remove actions. Partitioning would be implemented using arrow kernels. This approach could (I think) already support the `write` operations (add / overwrite) as they are implemented in the delta reference implementation. 

3) Full featured using external query engine

The writer API could support all higher level operations like `update`, `merge`, `delete` etc, but depend on an external crate like datafusion or polars to implement scanning individual files and passed data.

I assume each level could build on lower levels, but might look different based on how far we want to take this within this crate. Also hoping my thinking with regards to this topic did not go off in an entirely wrong direction and I did not miss somethting obvious. 

Any feedback on this is greatly appreciated.

**Comment by houqp** [comment]
I think you are spot on with your analysis @roeap :) I don't have much to add. In step 3, we can also include `optimize`. I also think it would be a good idea to use arrow record batches as the input serialization format.

**Comment by houqp** [comment]
> on how far we want to take this within this crate.

I want to take it very far, to the point where we can use it to process delta tables in a distributed setup using systems like ballista ;)

**Comment by roeap** [comment]
I think this Issue has served its purpose :).
