### ISSUE TITLE
Cannot create a new delta table with nested structures like lists and maps in the schema

### ISSUE THREAD

**Issue by andrei-ionescu** [delta-io/delta-rs#513]
# Environment

**Delta-rs version**:
Latest from git as dependency is defined as a git url. Current git commit is: https://github.com/delta-io/delta-rs/commit/52d20984dd6c59c6559dbec010c2d9aa49a78877.

**Binding**: 

**Environment**:
- **Cloud provider**: N/A
- **OS**: macOS Monterey
- **Other**: -

***
# Bug

**What happened**:

Unable to create a new delta table with nested structures like lists and maps in the schema. For example I cannot create a list type field or a map type field because all type's fields are private.

For example, this is one of the compile errors returned:
```
error[E0451]: field `r#type` of struct `SchemaTypeArray` is private

r#type: String::from("array"),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ private field
```

**What you expected to happen**:

To be able to create schemas with lists and maps.

**How to reproduce it**:

Try creating a `SchemaTypeArray`:

```
let array = SchemaTypeArray {
    r#type: String::from("array"),
    elementType: Box::new(...),
    containsNull: false,
};
```

All three `r#type`, `elementType`, `containsNull` properties will fail the compile process due to their visibility. 

**More details**:

The issue is because neither of `SchemaTypeArray` nor `SchemaTypeMap` have a `new` method similar to  `SchemaTypeStruct`.

**Comment by houqp** [comment]
good catch @andrei-ionescu , do you mind sending a PR to implement what you suggested?

**Comment by andrei-ionescu** [comment]
@houqp The PR is created and ready for review. Thanks for the opportunity.
