### ISSUE TITLE
Retry every S3 request on 5xx server errors

### ISSUE THREAD

**Issue by mosyp** [delta-io/delta-rs#514]
The 5xx server errors for s3 have to be retried, however rusoto has no such feature. See discussion https://github.com/delta-io/delta-rs/pull/510#issuecomment-981887975 for more details.

**Comment by viirya** [comment]
I think this can be closed now?

**Comment by houqp** [comment]
@viirya i think this issue tracks the work to make the retry more robust. Right now the current retry logic is a busy loop without sleep and exponential backoff. We might want to apply the retry more generally to other S3 api calls as well.

**Comment by ion-elgreco** [comment]
I don't believe this is relevant anymore to the official AWS rust crates, we can open a new issue if it was still relevant
