### ISSUE TITLE
Improve DataCatalog documentation

### ISSUE THREAD

**Issue by matthewmturner** [delta-io/delta-rs#522]
# Description
I would like better documentation / user guides on how to use `DataCatalog`, in particular from AWS / Glue, in both Rust and Python

**Use Case**
I am already using AWS Glue / Athena and i am starting to explore if datafusion / deltalake can be used instead.

**Related Issue(s)**

**Comment by fvaleye** [comment]
Hello @matthewmturner,

Thanks for submitting your issue!

Did you already see this [documentation page](https://delta-io.github.io/delta-rs/python/usage.html#deltatable) for the Python binding? (Create a DeltaTable using a Data Catalog)

How could we improve this based on your usage?

**Comment by matthewmturner** [comment]
@fvaleye thanks for quick response!  yes, i saw that.

being new to deltalake, and wanting to set it up (i.e. not using an existing deltalake), for me the part that was missing was general context of the relation between the DataCatalog and deltalake and how they can be used together (i.e. is anything in particular needed in the db / table glue metadata).

i had naively tried using my existing glue db / table and of course it didnt work as it wasnt a deltatable yet.  so i was hoping for directions how to convert existing glue db / tables to deltatables.

thinking on it now maybe thats broader than adding to docs here though.  what do you think?

**Comment by matthewmturner** [comment]
Im going to look for documentation elsewhere on AWS Glue / Data Catalog and how it works with Delta Lake.  But if you think its relevant im happy to add some details here as well.

**Comment by fvaleye** [comment]
Let me try to find an example of how we can load a `DeltaTable` using delta-rs with the AWS Glue Data Catalog using [OSS Delta Lake](https://github.com/delta-io/delta).

**First:**
Before writing a `DeltaTable` as a table in the Hive Metastore with Spark, you need to specify AWS Glue Data Catalog as the Metastore for your cluster:
[OSS Delta Lake documentation](https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-hive-metastore-glue.html) 
[Databricks Delta Lake documentation](https://docs.databricks.com/data/metastores/aws-glue-metastore.html)

**Then:**
You could use this method in Spark for creating the Delta Table in AWS S3 (or a SQL one):

> data_frame.format("delta")
>         .option("delta.compatibility.symlinkFormatManifest.enabled", "true")
>         .option("path", path)
>         .saveAsTable(f"{database_name}.{table_name}")
> 
[OSS Delta Lake documentation](https://docs.delta.io/1.0.0/delta-batch.html#create-a-table)
[Databricks Delta Lake documentation](https://docs.databricks.com/delta/quick-start.html#create-a-table)

**Result:**
At this step, you have a `DeltaTable` written in AWS at`s3://{path}` registered in the AWS Glue Data Catalog with a `database_name` and `table_name` entries.

_The only requirement is to use AWS credentials that have permissions to access this S3 bucket and the AWS Glue Data Catalog._

Using delta-rs with the Python binding, you could [read this `DeltaTable`]( https://delta-io.github.io/delta-rs/python/usage.html#deltatable) by only using the `database_name` and `table_name` with AWS Data Catalog.

**Comment by matthewmturner** [comment]
@fvaleye thanks much for providing this information!  I'll review and close this for now.
