### ISSUE TITLE
Programmatic authentication for Azure

### ISSUE THREAD

**Issue by alexeiakimov** [delta-io/delta-rs#527]
# Description
It would be nice to provide API which allows to specify the Azure credentials in the code. Currently the Azure storage implementation only relies on the environment variables, which makes it difficult to access two independent storages in the same program. In case of AWS S3 the problem does not exists because the API allows to use a custom rusoto S3 client with a static credentials provider.

**Use Case**
A program needs to access two delta tables stored in Azure using two independent access credentials.  

**Related Issue(s)**

**Comment by thovoll** [comment]
This sounds like a good use case. Note that the auth is currently in flux as we are [in the process of adopting the ADLS Gen2 API](https://github.com/delta-io/delta-rs/pull/499).

**Comment by alexeiakimov** [comment]
Many thanks for implementing this. When will it be released? If the release date has not been fixed yet, which revision of main could you suggest as a stable enough? Thank you.

**Comment by houqp** [comment]
@alexeiakimov the main branch is usually quite stable from a bug's point of view, so you can just consume it using git.
