### ISSUE TITLE
Can't read Delta Lake table from GCS

### ISSUE THREAD

**Issue by oneextrafact** [delta-io/delta-rs#530]
# Environment

**Delta-rs version**: 0.5.4

**Binding**:  python

**Environment**:
- **Cloud provider**: GCP
- **OS**: Linux
- **Other**:

***
# Bug

**What happened**:
Getting the following stack trace when trying to read a Delta Lake table from GCS (code is executing from Jupyter notebook):

----> 1 dt = DeltaTable("gs://valid/path", version=0)

~/Source/evms_analysis/evms_analysis/lib/python3.8/site-packages/deltalake/table.py in __init__(self, table_uri, version)
     77         :param version: version of the DeltaTable
     78         """
---> 79         self._table = RawDeltaTable(table_uri, version=version)
     80         self._metadata = Metadata(self._table)
     81 

PyDeltaTableError: Failed to read delta log object: GCS error: IO error: No such file or directory (os error 2)

**What you expected to happen**:

Expected to be able to read the table and work with it.

**How to reproduce it**:

**More details**:

I can access the table using PySpark running locally. The tables were created using DataProc.

**Comment by viirya** [comment]
What happens if you don't specify version but load from latest version? Seems it cannot load from the log of version 0?

**Comment by oneextrafact** [comment]
I've tried without the version argument as well, doesn't work.

**Comment by viirya** [comment]
Hmm, I can see we have s3 and azure tests, but I don't find gcs test. I suppose that the gcs storage module works. Maybe I can create a free trial gcs bucket to test it...

**Comment by viirya** [comment]
Okay. I just spent some time setting up a trial gcs bucket to test it.

Do you set `SERVICE_ACCOUNT` environment variable to the path of gcs credentials with permission to read from the bucket?

If `SERVICE_ACCOUNT` is not correctly set, there will be the error `"No such file or directory"`. The error is very confusing as it actually means the path to gcs credentials cannot be found...

**Comment by oneextrafact** [comment]
Yes, that was it! I thought SERVICE_ACCOUNT was asking for the account name, not the path to the file. It's working now. Thanks!

**Comment by rodrigotheia** [comment]
Does anyone have an example of this configuration, please?
