### ISSUE TITLE
PyDeltaTableError: Invalid action record found in log: Invalid action field: Unexpected field name for add action: partitionValues_parsed

### ISSUE THREAD

**Issue by GBBBAS** [delta-io/delta-rs#54]
I'm getting the below error when trying to read a delta table from ADLS Gen 2:
`PyDeltaTableError: Invalid action record found in log: Invalid action field: Unexpected field name for add action: partitionValues_parsed`

When I try and read the delta table using spark sql, I have no issues. Any ideas what could be causing this?

**Comment by rtyler** [comment]
Thanks for trying the python bindings out @GBBBAS! 

For whoever takes a look at this, delta-rs might not be parsing the [checkpoint format](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#checkpoint-format) properly.


@GBBBAS how was the delta table generated?  I wonder if there is some Delta functionality that's being used in the generation which our test cases currently do not cover.

**Comment by GBBBAS** [comment]
@rtyler The table was created using pyspark on a v7.4 Databricks Runtime Cluster

**Comment by houqp** [comment]
looks like write stats as struct is new and added to the spec 4 months ago. the test data are prepared way before that.

but it should be pretty straight forward to add support for it.
