### ISSUE TITLE
running the  example of `read_delta_table` reports an error

### ISSUE THREAD

**Issue by xudong963** [delta-io/delta-rs#543]
# Environment

**Delta-rs version**:
master

**Binding**: 

**Environment**:
- **Cloud provider**:
- **OS**: macos
- **Other**:

***
# Bug

**What happened**:
`Error: Not a Delta table: No snapshot or version 0 found, perhaps ./tests/data/delta-0.8.0 is an empty dir?`

**What you expected to happen**:
No error
**How to reproduce it**:
run the example
```rust
extern crate anyhow;
extern crate deltalake;

#[tokio::main(flavor = "current_thread")]
async fn main() -> anyhow::Result<()> {
    let table_path = "./tests/data/delta-0.8.0";
    let table = deltalake::open_table(table_path).await?;
    println!("{}", table);
    Ok(())
}

```

**More details**:

**Comment by fvaleye** [comment]
Hello @xudong963!

Could you please share with us the command line (and the path where you launched it) used for running the example?

**Comment by xudong963** [comment]
Oh, I just run use the button of Clion.
![image](https://user-images.githubusercontent.com/41979257/149480575-77279643-bf08-4405-b0fd-765bdde8c497.png)
I believe it's because clion's execution position isn't at `delta-rs/rust`.

When I run ` cargo run --color=always --example read_delta_table --manifest-path Cargo.toml` at `delta-rs/rust`, it's ok.

**Comment by fvaleye** [comment]
Thanks @xudong963 

Yes, you're right - I think it's because we use a relative path `./tests/data/delta-0.8.0`. We are launching the example command line from the `delta-rs/rust` folder.

**Comment by xudong963** [comment]
Thanks @fvaleye ,  closed
