### ISSUE TITLE
Error loading DeltaTable on AWS with default values

### ISSUE THREAD

**Issue by bossenti** [delta-io/delta-rs#559]
# Environment

**Delta-rs version**: 0.5.5, 0.5.6

**Binding**:  Python

**Environment**:
- **Cloud provider**: AWS
- **OS**: MacOS/Ubuntu

***
# Bug

**What happened**:
Reading a delta table with `DeltaTable(table_uri=path_to_table)` yields to the following error:

```
deltalake.PyDeltaTableError: Failed to load checkpoint: Failed to read checkpoint content: Failed to read S3 object content: Request ID: None Body: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Endpoint>[<bucket-name>.s3.eu-central-1.amazonaws.com](http://<bucket-name>.s3.eu-central-1.amazonaws.com/)</Endpoint><Bucket>[bucket-name]</Bucket><RequestId>4A4K1CE8ZS50FC</RequestId><HostId>9iwNTLiqZaA3tnveLsUle93LvONolukcSMltIG84ovk2TpPjLw8g124yodY43a5numlsut5po=</HostId></Error>

```
**What you expected to happen**:
Read delta table successfully

**How to reproduce it**:
see **what happened** 

**More details**:
Passing the default AWS endpoint URL via `storage_options` fixes the error and the delta table can be read:
```
DeltaTable(
            table_uri=self.path_to_table,
            storage_options={"AWS_REGION": aws_region, "AWS_ENDPOINT_URL": f"s3.{aws_region}.amazonaws.com"},
        )
```
So this issue might be caused by the default values for `storage_options`.

**Comment by nbonnotte** [comment]
I had the same issue with the `eu-west-1` region
```PyDeltaTableError: Failed to load checkpoint: Failed to read checkpoint content: Failed to read S3 object content: Request ID: None Body: <?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>PermanentRedirect</Code>
    <Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message>
    <Endpoint>my-bucket.s3-eu-west-1.amazonaws.com</Endpoint>
    ...
</Error>
```
If I follow the error message instruction and set
```
storage_options["AWS_ENDPOINT_URL"] = f"{bucket_name}.s3-{aws_region}.amazonaws.com"
```
I then get the error
```
PyDeltaTableError: Not a Delta table: No snapshot or version 0 found, perhaps s3://my-bucket/my_table is an empty dir?
```
But @bossenti's solution worked! Thanks :heart: 
```
storage_options["AWS_ENDPOINT_URL"] = f"s3.{aws_region}.amazonaws.com"
```

**Comment by tommydangerous** [comment]
I struggled with this forever... The fix for me was to set the environment variable `AWS_DEFAULT_REGION` to the buck’s region.

**Comment by wjones127** [comment]
Sorry for the struggle! We should eventually support resolving the region automatically. Tracking upstream here: https://github.com/apache/arrow-rs/issues/3213

**Comment by patrick-muller** [comment]
this works for me
storage_options = {"AWS_DEFAULT_REGION": "us-east-1", 'AWS_S3_ALLOW_UNSAFE_RENAME':'true'}
write_deltalake(new_path, df, mode='append',storage_options=storage_options)
