### ISSUE TITLE
DeltaTable support for GCS

### ISSUE THREAD

**Issue by dineshvelmuruga** [delta-io/delta-rs#56]
Can I read DeltaTable that resides in GCS like below

dt = DeltaTable("gs://<path>")

**Comment by houqp** [comment]
GCS is not supported at the moment, but it should be pretty straight forward to add this feature. You can check out the code that implements s3 and azure backends: https://github.com/delta-io/delta-rs/blob/main/rust/src/storage/s3.rs, https://github.com/delta-io/delta-rs/blob/main/rust/src/storage/azure.rs

**Comment by dineshvelmuruga** [comment]
Any enhancement planned for GCS? Because it would be quite good to have

**Comment by nevi-me** [comment]
What crate do you use to access GCS object storage?

**Comment by fvaleye** [comment]
I didn't find any crate available for interacting with GCS... do you have something in mind @houqp?

**Comment by houqp** [comment]
Maybe this one? https://docs.rs/google-storage1/1.0.14+20200623/google_storage1/index.html.
