### ISSUE TITLE
Python usage docs still reference abfss

### ISSUE THREAD

**Issue by thovoll** [delta-io/delta-rs#561]
# Environment

**Delta-rs version**: 0.5.6

**Binding**: python

**Environment**: any
- **Cloud provider**: any
- **OS**: any
- **Other**: n/a

***
# Bug

**More details**: Usage docs should say adls2 instead of abfss

**Comment by dgcaron** [comment]
this is being addressed in #560

**Comment by wjones127** [comment]
@houqp FYI I think this could be closed given #560 has been merged.

**Comment by houqp** [comment]
Thanks @wjones127 for helping with the issue clean up :)
