### ISSUE TITLE
Python: Finish filesystem bindings

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#570]
# Description

The PyArrow filesystem bindings are only partially implemented: https://github.com/delta-io/delta-rs/blob/main/python/deltalake/fs.py

**Use Case**

We will need the rest of the methods implemented for the PyArrow writer (`write_deltalake()`) to work.

**Related Issue(s)**

Blocks: #542

**Comment by wjones127** [comment]
In addition, it probably makes sense to also add in support for Windows and "older" Linux. See https://github.com/delta-io/delta-rs/blob/d54e952026c83fd15c4d5a8b6c07339405751d48/rust/src/storage/file/rename.rs#L96-L114

**Comment by wjones127** [comment]
I am working on this one.

**Comment by wjones127** [comment]
Update: current plan is to use object-store-rs (soon to be moved into arrow-rs) and then wrap that as a PyArrow filesystem for the writer.

So blocked on #610 for now.

**Comment by wjones127** [comment]
We can now pass ObjectStores into PyArrow writer. But we need to be able to provide PyArrow / fsspec filesystems into `DeltaTable`.

```python
fs = S3Filesystem()
dt = DeltaTable("s3://path/to/table", filesystem=fs)
dt.to_pyarrow_table() # Should use fs
write_deltalake(dt, pa.table({'x': [1,2,3]})) # should use fs
write_deltalake("s3://path/to/table", pa.table({'x': [1,2,3]}), filesystem=fs)  # should use fs
```

**Comment by Lundez** [comment]
Is there any ETA until this is done?

**Comment by ion-elgreco** [comment]
@wjones127 can you clarify what is still needed for this? I can work on it if it's still relevant

**Comment by bjornandre** [comment]
I am also waiting for this to be implemented:
https://github.com/delta-io/delta-rs/blob/d98a0c22efb98368c429610e89acf9bd1e45e299/python/deltalake/writer.py#L184

**Comment by wjones127** [comment]
We aren't working on this, and might never implement this. Copying from another discussion where I explained why we didn't peruse this:

> We don't write the log files with PyArrow, and that's the really important part to get right. If you mess that up, you mess up atomicity of transactions. The particular operation we need is an atomic replace if not exist or copy if not exist. That is how we write the log file to commit a transaction. ObjectStore has those, but I don't think fsspec has them.
>
> I had considered just having two filesystems, letting the user pass a PyArrow / fsspec one for the data files and keep using object store for the log files. But then you have to keep the configuration of the two in sync. That seemed like more trouble than it was worth.
