### ISSUE TITLE
Python: allow metadata for write_deltalake

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#576]
# Description

Currently, `write_deltalake()` doesn't support passing in a table name or description, or additional custom config values. 

**Related Issue(s)**
Umbrella issue: #542

**Comment by PadenZach** [comment]
Worked on some of this. Just need to finish some tests. New to rust however, getting a too many arguments warning from clippy since I just added the name description and configuration map as extra optional arguments. Should I just override it or refactor some of it into a struct?

**Comment by wjones127** [comment]
Either seems fine. I'd lean towards overriding for now.
