### ISSUE TITLE
When table is created with name, register it in data catalog

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#588]
# Description

#587 allows providing a name for a Delta table. However, it won't immediately work for users since we don't register it. We should provide a way to automatically register tables when they are created in a catalog. There may be other changes, like schema changes or deleting tables that will also require an update to the catalog.

I'm not very familiar with how data catalogs work, so I'd welcome assistance from someone who is more familiar. 😄 

**Use Case**

**Related Issue(s)**

**Comment by edmondo1984** [comment]
@wjones127 can you give me a feedback on https://github.com/edmondo1984/delta-rs/commit/b524f66322a388fecb9670a95676329fe9df567c as a starting point? I am a little confused since I found that the call to the catalog was actually within the Python folder and not something shared by all bindings

**Comment by houqp** [comment]
+1 on @wjones127 's explicit table registration proposal :) The separation of concerns here also avoids unnecessary overhead in table creation when users don't need to register it in the catalog.

**Comment by ion-elgreco** [comment]
I can look into this for the databricks unity catalog. It's one of the use cases I need to touch at work in a couple months.

@houqp @wjones127 is this still a desired feature?
