### ISSUE TITLE
Expected layout and structure of Azure storage accounts should be documented

### ISSUE THREAD

**Issue by rtyler** [delta-io/delta-rs#60]
In order to use Delta Lake and Azure, the library expects the storage account to be configured with Azure Delta Lake Service Gen2 enabled, which is a non-default setting.

Some README or user-guide type documentation on how a Delta Table(s) should look in Azure, including the Azure configuration, would be beneficial for us to include!

**Comment by drahnreb** [comment]
Highly appreciated if this is documented. I haven't looked into the Rust code, but from a python perspective this is very opaque.

**Comment by roeap** [comment]
With the adoption of `object_store`, we now use the blob api throughout, which is supported by Gen1 and Gen2 accounts. We do retain the if_not_exists functionality of course :).
