### ISSUE TITLE
Support CDC

### ISSUE THREAD

**Issue by houqp** [delta-io/delta-rs#604]
# Description

See design doc at: https://docs.google.com/document/d/1FQSl0S0Irckim331YvcAKyxxGBhdLiJcJH6v3fEyiC0/edit#. This will make non-append only table usable as a streaming source!

**Comment by kietay** [comment]
I could take this on as would be useful in current project

**Comment by roeap** [comment]
We welcome all contributions, large and small - my assumption this would fall well in the former category 🙂.

I only skimmed the design docs, but it seems we will have to work in the datafusion / query integration quite a bit for all to work...

**Comment by houqp** [comment]
Yes, reading should be pretty straight forward to implement and will help unlock a lot of the streaming use-cases.

**Comment by kietay** [comment]
@roeap I'm sorry I missed this notification - let me do some digging into this to understand the problem and then propose a change to see what you think
