### ISSUE TITLE
Support For Azure Blob Storage - Muli-Protocol Access

### ISSUE THREAD

**Issue by reynoldspravindev** [delta-io/delta-rs#608]
Hi, this is more of an inquiry than an issue. As the documentation states that the support is available for ADLS Gen 2, just checking to see if azure blob storage is supported or if there is a plan to support this in future, especially considering when Azure supports Multi-protocol access now for their storage services. FYI, I used a WASBS URI to check if it works and I got an error "deltalake.PyDeltaTableError: Failed to read delta log object: Invalid object URI".

**Comment by roeap** [comment]
Hi @reynoldspravindev - right now delta-rs only supports ADLSGen2 - preferably with hierarchical namespaces enabled. Main reason for this decision is that delta has certain requirements in terms of atomicity of certain file system operations. Specifically we need rename without replace. The Gen2 API supports that behavior natively, while the blob apis don't. For S3 this is solved with a spearate lock client based on dynamo DB. I actually once had look into implementing something similar based on cosmos DB, but there the consistency guarantees are somewhat of a challenge.

This is really only an issue in multi writer scenarios, but a compliant implementation hat to make these guarantees nonetheless. That being said, we may support blob storage in the future - maybe as a "use at your own risk" option for singe writer scenarios.

However there is no timeline for that yet.
