### ISSUE TITLE
Cannot read Delta Lake created with write_deltalake (Python bindings)

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#617]
# Environment

**Delta-rs version**: 0.5.7

**Binding**: Python

**Environment**:
- **Cloud provider**: N/A (using localhost)
- **OS**: MacOS

***
# Bug

**What happened**: I created a Delta Lake using delta-rs with `write_deltalake` and was unable to read the Delta Lake using delta-rs

**What you expected to happen**: I expected the read operation to work

**How to reproduce it**: 
 
```python
import pandas as pd
from deltalake.writer import write_deltalake

# create Delta Lake
df = pd.DataFrame({"x": [1, 2, 3]})
write_deltalake("./tmp/delta-table", df)

# read Delta Lake
from deltalake import DeltaTable
dt = DeltaTable("./tmp/delta-table")
dt.to_pandas()
```

Here's the error message: 

```
File ~/opt/miniconda3/envs/mr-delta-rs/lib/python3.9/site-packages/deltalake/fs.py:149, in DeltaStorageHandler.open_input_file(self, path)
    142 def open_input_file(self, path: str) -> pa.NativeFile:
    143     """
    144     Open an input file for random access reading.
    145 
    146     :param source: The source to open for reading.
    147     :return:  NativeFile
    148     """
--> 149     raw = self._storage.get_obj(path)
    150     return pa.BufferReader(pa.py_buffer(raw))

PyDeltaTableError: Object not found
```

**More details**: You can easily reproduce this by creating [this conda environment](https://github.com/MrPowers/delta-examples/blob/master/envs/mr-delta-rs.yml) and running [this Jupyter notebook](https://github.com/MrPowers/delta-examples/blob/master/notebooks/delta-rs/01_overview.ipynb).  

Other operations like `dt.files()` and `dt.version()` work as expected.  I am able to read Delta Tables created by [delta-io/delta](https://github.com/delta-io/delta) without any issue.

**Comment by wjones127** [comment]
Thanks for reporting this @MrPowers. Looks like we only tested with absolute paths so far, so didn't catch this yet.

But it's made me realize we are writing the paths in the delta log incorrectly; they should be relative to the table's root, but we've been writing absolute paths.
