### ISSUE TITLE
Is delta-rs properly handling partition folder naming?

### ISSUE THREAD

**Issue by roeap** [delta-io/delta-rs#619]
# Description
The protocols specifies to serialize empty partition values as 'null', however internally we use a constant value `__HIVE_DEFAULT_PARTITION__`  

https://github.com/delta-io/delta/blob/master/PROTOCOL.md#partition-value-serialization

Are we doing the right thing when writing partition folders? 

@houqp @wjones127

**Comment by wjones127** [comment]
Thanks for pointing this out, @roeap! I found I wasn't handling this correctly while I was writing integration tests with PySpark ([PR](https://github.com/delta-io/delta-rs/pull/625)). It seems that we should be writing directories as `part_col=__HIVE_DEFAULT_PARTITION__`, but within the add actions we need to specify `{"partitionValues": {"part_col": null } }`. (In the PyArrow writer, I was filling in the add action with the string `"__HIVE_DEFAULT_PARTITION__"` 🤦 .)

There's an example table that demonstrates this in the repo at `rust/tests/data/delta-0.8.0-null-partition`.

**Comment by houqp** [comment]
@roeap @wjones127 i think we can close this issue now?

**Comment by roeap** [comment]
Fixed in #625
