### ISSUE TITLE
Expose optimize in Python bindings

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#622]
# Description

#607 added optimize implementation using datafusion in rust. If we enable the `datafusion` option in the Python package, we can expose this in Python. We'll likely want this feature anyways to support writer protocol version 2 (see #592).

**Use Case**

**Related Issue(s)**

**Comment by a-m-w** [comment]
Is there an approximate timeline when optimization will be supported via Python? Thanks in advance!

**Comment by wjones127** [comment]
I don't believe anyone has volunteered to work on this yet, so no timeline for now. PRs for this are welcome though! 😄

**Comment by loleek** [comment]
Maybe I can contribute this. I've already implement it today but without doc and unit-tests.This is my first PR, it maybe take sometime.

**Comment by roeap** [comment]
@loleek - that would be awesome! 

We are always happy to help you along with reviews and guidance if needed.

**Comment by ion-elgreco** [comment]
@wjones127 this can be closed now, right?

**Comment by wjones127** [comment]
Yes, thanks for reminding me!
