### ISSUE TITLE
Allow users to bypass retention duration check when running vacuum

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#635]
The `retention_period=0` setting yields a “PyDeltaTableError: Invalid retention period, retention for Vacuum must be greater than 1 week (168 hours)” error to protect users from accidentally vacuuming new files that they don’t actually want to delete.  You can overcome this restriction with normal Delta Lake by setting `config("spark.databricks.delta.retentionDurationCheck.enabled", "false")` when creating the SparkSession.

@wjones127 suggested adding an `enforce_retention_duration=True` parameter in `DeltaTable.vacuum()`, so end users have a way to bypass this error.

We may want to add this parameter as `retention_duration_check_enabled=True`, so we're consistent with the Delta Lake wording.

**Comment by houqp** [comment]
Support for this has been added in the latest python release :)
