### ISSUE TITLE
dates statistics are not saved in the delta log

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#655]
# Environment

**Delta-rs version**: 0.5.8

**Binding**: Python

**Environment**: 
- **Cloud provider**:  NA
- **OS**: Windows 
- **Other**:

***
# Bug

**What happened**: Date statistics are not saved in the log file

**What you expected to happen**: expect the statistics to be working

**How to reproduce it**:
```
import duckdb 
from deltalake.writer import write_deltalake
con = duckdb.connect()
df =con.execute('''
INSTALL 'httpfs';
LOAD 'httpfs';
SELECT countries_and_territories, date_rep,year(date_rep) as year,sum(deaths) as total FROM 
read_parquet('https://pandemicdatalake.blob.core.windows.net/public/curated/covid-19/ecdc_cases/latest/ecdc_cases.parquet')
group by all
order by total desc
''').fetch_arrow_table()

write_deltalake('C:/covid', df,mode='overwrite',partition_by=['year'])
```

**More details**:

this is literally the first time, I used Delta, I hope it is a supported feature

**Comment by wjones127** [comment]
Yes, we don't yet support writing [date32 and decimals in stats](https://github.com/delta-io/delta-rs/blob/27c0cbb6ad404a4176e0e13f8d30914430f9dc53/python/tests/test_writer.py#L336-L338). There was a limitation in the underlying library PyArrow that made it difficult to implement, but we [got that fixed](https://issues.apache.org/jira/browse/ARROW-7350) in PyArrow 8.0.0 so we should be able to get it working now.
