### ISSUE TITLE
GCP : write_dataset() got an unexpected keyword argument 'max_open_files'

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#660]
# Environment

**Delta-rs version**: 0.5.8

**Environment**:
- **Cloud provider**: GCP Colab
- **OS**: Linux
- **Other**:

***
# Bug

I a trying to write delta file on Google cloud

`write_deltalake('gs://xxxxx/covid', df,mode='append')`

I get this error

```
 220         max_rows_per_file=max_rows_per_file,
    221         min_rows_per_group=min_rows_per_group,
--> 222         max_rows_per_group=max_rows_per_group,
    223     )
    224 

TypeError: write_dataset() got an unexpected keyword argument 'max_open_files'
```

**Comment by wjones127** [comment]
First off, want to flag we don't yet test support for non-local filesystems on `write_deltalake` right now, and I'm pretty sure it won't work yet for GCS in particular. We have a bit of work to do before that's enabled.

But this error is unexpected. What version of PyArrow do you have here? (`import pyarrow; print(pyarrow.__version__)`)

**Comment by djouallah** [comment]
Thanks, I updated pyarrow to 8, and now I get this error

ArrowNotImplementedError: Got GCS URI but Arrow compiled without GCS support

**Comment by wjones127** [comment]
Out of curiosity, could you share what version of Python and PyArrow you were using when you got the original error? I am unable to reproduce.

**Comment by djouallah** [comment]
6.0.1
3.7.13

**Comment by djouallah** [comment]
no more relevant with the new 0.6.2 release
