### ISSUE TITLE
vacuum isn't actually deleting files

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#663]
# Environment

**Delta-rs version**: 0.5.8

**Binding**: Python

**Environment**: localhost

***
# Bug

**What happened**: Ran `dt.vacuum(retention_hours=0, enforce_retention_duration=False, dry_run=False)` and files didn't actually get deleted.

**What you expected to happen**: I thought the stale files would actually get deleted.

**How to reproduce it**: Here's [the notebook to reproduce this](https://github.com/MrPowers/delta-examples/blob/master/notebooks/delta-rs/intro-to-delta-rs.ipynb).

**More details**: `enforce_retention_duration` was added recently and that's successfully letting me bypass the retention duration error I was facing before.  Let me know if I'm missing something here and there's a way to get the files vacuumed with the existing code.

**Comment by wjones127** [comment]
From what I can tell, the bug is that if you provide a *relative* path to `DeltaTable()` constructor, then vacuum doesn't delete any files. But it works if you pass an *absolute* path. It seems like we've probably only tested with the latter.

I'll look at fixing this soon.

**Comment by MrPowers** [comment]
@wjones127 - looks like you added a fix already, awesome ;)

I verified in the notebook that `vacuum` does work as anticipated with absolute paths and this is a relative path bug, like you expected.  Thanks for the rapid response time!!
