### ISSUE TITLE
Test vacuum deletes correct files on object_stores

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#667]
# Description

I don't believe we actually test this; we only test with `dry_run = true`.

**Use Case**

**Related Issue(s)**

**Comment by mrk-its** [comment]
vacuum definitely needs more tests (even with dry_run=true only). After short play with it I found number of issues not covered by tests:

* files not referenced by delta log at all (so not included on `DeltaTableState.files()` and `DeltaTableState.all_tombstones()` lists) are completely ignored and not vacuumed (this can easily happen if vacuum is not running regular way and old log entries are cleaned up by delta itself)

* while testing I noticed that for local `file` storage vacuum doesn't work for files nested in subdirectories. It looks like `FileStorageBackend.list_objs` returns only top-level files / dirs

I have a patch for first issue from above list, are you interested in PR?

**Comment by mrk-its** [comment]
The good thing is `delta-rs` vacuum implementation is blazingly fast ;) comparing to official java VACUUM impl (at least for S3 backend). I did tests on real, production S3 dataset (in dry-run mode) and single-threaded delta-rs vacuum completed in ~7minutes while official java VACUUM running on multi-node EMR cluster didn't complete in 24h (https://github.com/delta-io/delta/issues/1248). 

The reason of such big difference is numer of S3 LIST requests issued by each implementation needed to fetch list of all files in dataset (java impl executes separate S3 LIST for each directory ending with over 1mln of requests for test dataset, delta-rs does that optimal way and needs ~1000 requests to list all the files).

**Comment by wjones127** [comment]
> I have a patch for first issue from above list, are you interested in PR?
A PR would be very welcome!

And good to know our performance is good. I think once we get good tests in place we should release a blog post with some performance comparisons.

**Comment by houqp** [comment]
Very cool to hear about that as well! Like you mentioned, we haven't even started any optimization work yet :D First obvious step is to parallelizing it with multiple threads. After that, we could leverage datafusion and ballista, to further spread the load on top multiple nodes.

**Comment by wjones127** [comment]
Resolved by #669
