### ISSUE TITLE
Add Support for writing to ADSL 

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#678]
I managed to read from from azure storage, thanks a lot for that, now I am trying to write, and I get this error

pyarrow.lib.ArrowInvalid: Unrecognized filesystem type in URI: adls2://xxxxxxx/test/test

is it supported ? if not can we have it please.

**Comment by wjones127** [comment]
For the PyArrow writer, we currently only support local file systems. We will add ADLS (and GCS and S3) support later this year after we refactor our object store interaction.

I'm going to close this, since we are already tracking this work in #570.
