### ISSUE TITLE
Python: Automatically convert Pandas types to valid Delta Lake types in write_deltalake()

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#686]
# Description

Many Pandas types aren't automatically converted into valid Delta Lake types when converted into Arrow tables. For example, Pandas Timestamps are converted into timestamps with nanosecond precision by default, but Delta Lake only supports microsecond precision. This makes `write_deltalake()` difficult to use for Pandas users.

We should write a test that validates all Pandas types can be written with `write_deltalake()` without manual conversion.

I'm not sure yet how to configure the conversion here:

https://github.com/delta-io/delta-rs/blob/431d0ea47700bb3b388a5679ce8d906fa84bb1c6/python/deltalake/writer.py#L128-L129

It's possible that we can pass in an adjusted schema to the schema parameter of `pyarrow.Table.from_pandas()` and that will make the correct conversion. 

**Use Case**

**Related Issue(s)**

Based on #685

**Comment by blaze225** [comment]
Would appreciate if this can be prioritized. Right now this is forcing us to use spark over delta-rs.

**Comment by ion-elgreco** [comment]
This also happens when you write delta from Polars with columns with nano precision datetime. However it's slightly more easy to circumvent you just have to do the casting first to micro precision.

**Comment by ion-elgreco** [comment]
> Would appreciate if this can be prioritized. Right now this is forcing us to use spark over delta-rs.

You can also switch to polars, which casts the dtypes correctly to a delta compatible schema: https://github.com/pola-rs/polars/pull/10165/files#diff-843e4fa7334b1cfcdf4ebe039377c0d724d0abb51bcde68c9aaae1b93868e20b

**Comment by thehappycheese** [comment]
I made this as a stopgap solution. Its a dumb solution but it helped me actually get it to write and test out the library.

```python
import deltalake as dl
from deltalake import DeltaTable
from typing import Union

def strip_categorical(df:pd.DataFrame):
    """convert categorical columns back into integer types,
    and return a dataframe of the categories
    
    Example:

    ```python
    (original_df, categories) = strip_categorical(df)
    ```"""
    categories = {}
    df=df.copy()
    for col in df.columns:
        if pd.api.types.is_categorical_dtype(df[col]):
            print(f"Converting categorical column to integer: '{col}' - {dict(enumerate(df[col].cat.categories))}")
            categories[col] = df[col].cat.categories
            df[col] = df[col].cat.codes
    return df, pd.DataFrame(categories)

def strip_duration_to_int(df:pd.DataFrame, to_int_unit:Union[str,dict[str,str]]="ms"):
    """convert Timedelta columns to integer types with the given unit
    to_int_unit should be a string or a dictionary of column names to units
    
    Example:
    
    ```python
    df, time_delta_cols = strip_duration_to_int(df, to_int_unit="ms")
    ```"""
    df=df.copy()
    time_delta_cols = {}
    for col in df.columns:
        if pd.api.types.is_timedelta64_dtype(df[col].dtype):
            col_to_int_unit = to_int_unit
            if isinstance(to_int_unit, dict):
                col_to_int_unit = to_int_unit[col]
            print(f"Converting Timedelta column to integer using units '{col_to_int_unit}': '{col}'")
            time_delta_cols[col] = col_to_int_unit
            df[col] = df[col] // pd.Timedelta(1, unit=col_to_int_unit)
    return df, time_delta_cols

def write_delta(path, data, timedelta_to_int_unit:Union[str,dict[str,str]]="ms", **kwargs):
    data, categories = strip_categorical(data)
    data, time_delta_cols = strip_duration_to_int(data, timedelta_to_int_unit)
    dl.write_deltalake(path, data, **kwargs)
    if len(categories) > 0:
        dl.write_deltalake(path+"_categories", categories,**kwargs)
    if len(time_delta_cols) > 0:
        dl.write_deltalake(path+"_time_delta_cols", time_delta_cols,**kwargs)
```

**Comment by kangshung** [comment]
Are there any plans to implement this?

**Comment by ion-elgreco** [comment]
> Are there any plans to implement this?

You can use polars.io.delta import _convert_pa_schema_to_delta

**Comment by ion-elgreco** [comment]
> > > > > Are there any plans to implement this?
> > > > 
> > > > 
> > > > You can use polars.io.delta import _convert_pa_schema_to_delta
> > > 
> > > 
> > > What about the `_check_for_unsupported_types()` method that lists Categorical as an unsupported type? Why would it work without polars if it doesn't with polars?
> > 
> > I don't see any categorical primitive types in here: https://github.com/delta-io/delta/blob/master/PROTOCOL.md#primitive-types
> 
> And that's the issue. Delta returns deltalake.PyDeltaTableError: Schema error: Invalid data type for Delta Lake: Dictionary(Int8, Utf8) for Categorical fields.
> 
> Here you have a method that raises an exception on Categorical fields in polars: https://github.com/pola-rs/polars/blob/main/py-polars/polars/io/delta.py#L323-L329

I see, we could possibly port these things from Polars into delta-rs, I'll check with the polars contributors. Not super familiar with licenses and all

**Comment by felipewhitaker** [comment]
I believe I might have found an issue. While `write_deltalake` works well when creating a new `DeltaTable` from `pd.DataFrame`, `DeltaTable.create` fails due to `pd.TimeStamp` coerced data type.

```python
import pandas as pd
import pyarrow as pa

from deltalake import DeltaTable

df = pd.DataFrame({"timestamp": [pd.Timestamp.now()]})
table = pa.Table.from_pandas(df)

dtable_path = "dtable"

DeltaTable.create(dtable_path, table.schema)
# Out:
---------------------------------------------------------------------------
SchemaMismatchError     Traceback (most recent call last)
      [7] table = pa.Table.from_pandas(df)
      [9] dtable_path = "dtable"
---> [11] DeltaTable.create(dtable_path, table.schema)

File c:\PythonScripting\Applications\Mambaforge\envs\azfunc\lib\site-packages\deltalake\table.py:522, in DeltaTable.create(cls, table_uri, schema, mode, partition_by, name, description, configuration, storage_options, custom_metadata, raise_if_key_not_exists)
    [519] (deltalake/table.py:519) if isinstance(table_uri, Path):
    [520] (deltalake/table.py:520)     table_uri = str(table_uri)
--> [522] (deltalake/table.py:522) _create_deltalake(
    [523] (deltalake/table.py:523)     table_uri,
    [524] (deltalake/table.py:524)     schema,
    [525] (deltalake/table.py:525)     partition_by or [],
    [526] (deltalake/table.py:526)     mode,
    [527] (deltalake/table.py:527)     raise_if_key_not_exists,
    [528] (deltalake/table.py:528)     name,
    [529] (deltalake/table.py:529)     description,
    [530] (deltalake/table.py:530)     configuration,
    [531] (deltalake/table.py:531)     storage_options,
    [532] (deltalake/table.py:532)     custom_metadata,
    [533] (deltalake/table.py:533) )
    [535] (deltalake/table.py:535) return cls(table_uri=table_uri, storage_options=storage_options)

SchemaMismatchError: Invalid data type for Delta Lake: Timestamp(Nanosecond, None)
```

However, `write_deltalake` works fine.

```python
from deltalake import write_deltalake

write_deltalake(dtable_path, table)  # correctly creates `dtable`
```

**Comment by FrankPortman** [comment]
I believe I have found another issue - but I cannot tell if it is related. When a column is considered "null" by Pandas (because empirically all the data is null), then it will not be coerced to anything upon write. We have to manually say its a "String" or "int" when doing inserts for that batch. This feels like another thing that could happen automatically but maybe I am missing an edge case preventing safe automatic coercion.

**Comment by felipewhitaker** [comment]
Do you have a minimal example?

What I noticed it that, if a partition column contains `null` values, they are put in a folder following this format: `column=__HIVE_DEFAULT_PARTITION__ `.

**Comment by ion-elgreco** [comment]
> I believe I have found another issue - but I cannot tell if it is related. When a column is considered "null" by Pandas (because empirically all the data is null), then it will not be coerced to anything upon write. We have to manually say its a "String" or "int" when doing inserts for that batch. This feels like another thing that could happen automatically but maybe I am missing an edge case preventing safe automatic coercion.

This is a pandas thing.

How should we know what a null column should actually coerce to?

**Comment by FrankPortman** [comment]
> > I believe I have found another issue - but I cannot tell if it is related. When a column is considered "null" by Pandas (because empirically all the data is null), then it will not be coerced to anything upon write. We have to manually say its a "String" or "int" when doing inserts for that batch. This feels like another thing that could happen automatically but maybe I am missing an edge case preventing safe automatic coercion.
> 
> This is a pandas thing.
> 
> How should we know what a null column should actually coerce to? 

By looking at the type of the column in the DeltaTable being written to. Is there an edge case with that?

**Comment by ion-elgreco** [comment]
> > > I believe I have found another issue - but I cannot tell if it is related. When a column is considered "null" by Pandas (because empirically all the data is null), then it will not be coerced to anything upon write. We have to manually say its a "String" or "int" when doing inserts for that batch. This feels like another thing that could happen automatically but maybe I am missing an edge case preventing safe automatic coercion.
> > 
> > 
> > This is a pandas thing.
> > How should we know what a null column should actually coerce to?
> 
> By looking at the type of the column in the DeltaTable being written to. Is there an edge case with that?

Ah you meant during writing, yeah I think that is possible in theory but requires some changes in our casting module

**Comment by FrankPortman** [comment]
Do you think it's a reasonable request? I can open a ticket if so.

**Comment by ion-elgreco** [comment]
@FrankPortman it's reasonable yeah, but we need someone to implement it then :)
