### ISSUE TITLE
Call to DeltaTable from Python

### ISSUE THREAD

**Issue by fvaleye** [delta-io/delta-rs#69]
Hello guys,

I am using `delta-rs` from Python and it seems that calling `DeltaTable()` blocks after calling it once.
I tested with DeltaTable on AWS S3.

**Context information:**
```
deltalake="==0.2.0" and deltalake="==0.1.4" installed via pip 20.3.3
Python 3.7.8
```

**Scenario:**
```
table_list = ["s3://bucket-test/delta_table1",  "s3://bucket-test/delta_table2"]
for table in table_list:
    delta_table = DeltaTable(table)
    print(delta_table.files())
```

The first call to `DeltaTable()` with `files()` worked and the files are printed. But on the second call, it blocks my application.
I tried to use it without the loop, with sequential calls, but it is the same.

Is it normal?

Thank you for your help :)

**Comment by rtyler** [comment]
I was able to quickly reproduce this, it has nothing to do with multiple tables, doing an iteration across a list with the same bucket hangs on the second iteration as well.

```
>>> table_list = ['s3://deltars/simple', 's3://deltars/simple']
>>> for table in table_list:
...     print('hello')
...     t = deltalake.DeltaTable(table)
...     print(t.files())
```


@houqp  I have a feeling that there is something that's not being properly deallocated here. I would write a proper integration test, but I cannot get pyo3 to build on my local (openSUSE) machine :unamused:

**Comment by rtyler** [comment]
My hunch is that the tokio runtime that's being created per DeltaTable object is not being dropped properly in the iteration.
