### ISSUE TITLE
Slack invitation revoked

### ISSUE THREAD

**Issue by jojayaro** [delta-io/delta-rs#706]
Hi there! Awesome work!

I was trying to join the Slack group and it says that my invitation has been revoked but I don’t remember trying to join the group before.

**Comment by wjones127** [comment]
https://join.slack.com/t/delta-users/shared_invite/zt-1cwse5g8y-q9Jt9wkC3uzDQfV69hsBNA

I think the link just expires after X days. Where did you get the invite link? I've put a temporary one above.

**Comment by jojayaro** [comment]
Thanks! 

I clicked the link in the Repo.

https://github.com/delta-io/delta-rs#get-involved

**Comment by chinmaychandak** [comment]
Hi @wjones127, facing a similar issue here. I'm trying to join the Slack group but could not find a link that hasn't expired. Can you please help?
