### ISSUE TITLE
DeltaTable.history() returns empty list for any table in ADLS2

### ISSUE THREAD

**Issue by george-zubrienko** [delta-io/delta-rs#723]
# Environment

**Delta-rs version**: 0.5.8

**Binding**: Python (3.9.12)

**Environment**:
- **Cloud provider**: Azure
- **OS**: ubuntu 20.04
- **Other**:

***
# Bug

**What happened**:
Calling 
```
d = DeltaTable('adls2://account/container/some/table')
d.history()
```
Returns

```
[2022-08-05T20:23:30Z ERROR azure_core::policies::retry_policies::retry_policy] server returned error status which will not be retried: 404 Not Found
[]
```

**What you expected to happen**:

This worked in 0.5.6 with output matching `describe history ...` on the same table when run through Spark.

**How to reproduce it**:

I'm not sure this is related to Azure - but might be. So try loading any DeltaTable in ADLS2 and calling history on it.

**More details**: Getting current version works alright:
```
>>> d.version()
2986
```

**Comment by houqp** [comment]
@george-zubrienko could you try download the table to local filesystem and load it with delta-rs to see if you can reproduce the same error? This should help us figure out whether it's azure specific or not.

**Comment by george-zubrienko** [comment]
@houqp it works w/o issues on local delta table:

```
>>> delta_table = DeltaTable(test_data_path)
>>> delta_table.history()
[{'timestamp': 1657791883326, 'userId': '1955071889815830', 'userName': 'jjas@ecco.com', 'operation': 'CREATE OR REPLACE TABLE AS SELECT', 'operationParameters': {'isManaged': 'true', 'description': 'Defines the schedule for replenishment orders calculations.', 'partitionBy': '[]', 'properties': '{}'}, 'job': {'jobId': '121785611736814', 'jobName': 'assortment_replenishment_schedule', 'runId': '3788217', 'jobOwnerId': '1955071889815830', 'triggerType': 'manual'}, 'notebook': {'notebookId': '3595887358471898'}, 'clusterId': '0714-094235-u7hbtl12', 'readVersion': 2931, 'isolationLevel': 'WriteSerializable', 'isBlindAppend': False, 'operationMetrics': {'numFiles': '1', 'numOutputRows': '9', 'numOutputBytes': '2921'}, 'engineInfo': 'Databricks-Runtime/10.4.x-scala2.12', 'txnId': '570ad11a-947a-4b23-a08e-d703ac254ea8'}, ...
```

**Comment by roeap** [comment]
I need to run some integration tests with azure anyhow, so I can check what's going on with history there...

**Comment by george-zubrienko** [comment]
After upgrading to 0.6.0 history is back again!

**Comment by roeap** [comment]
great news @george-zubrienko, does that also mean we can close this issue?

**Comment by roeap** [comment]
btw. we changed how uris are being used. the old way `adls2://account/container/some/table` should still work as before, but having the account in the uri is different from how all others are doing it. WE now recommend using the fsspec formats (e.g. `az://container/some/table` and set `AZURE_STORAGE_ACCOUNT_NAME` either via the environment or as option when loading the table.

**Comment by george-zubrienko** [comment]
We use `az` protocol now and `storage_options` instead of env vars, which is huge for us since we work across several storage accounts and switching env vars is bit inconvenient.

Overall, really nice release and yes, issue can be closed!
