### ISSUE TITLE
Publish to conda

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#735]
delta-rs is currently [uploaded to PyPi](https://pypi.org/project/deltalake/), so users can `pip install deltalake`.

Lots of Python data projects are also uploaded to Conda, which is more popular in the data community.  Here's how to install `deltalake` in a Conda environment file:

```
name: mr-delta-rs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - pip
  - pip:
    - deltalake==0.5.8
```

It's possible, but it'd be nice if this was also uploaded to `conda-forge`.  Thoughts?

**Comment by houqp** [comment]
Yes, this would be a good thing to have. We could perform the release using github action too.

**Comment by craustin** [comment]
Created a forge-side request here:
https://github.com/conda-forge/staged-recipes/issues/21102

**Comment by MrPowers** [comment]
@craustin - awesome, so exciting!  Anything you need from our end to help you move this forward?  Or will conda-forge take it from here?

**Comment by kukushking** [comment]
Hi folks, this is precisely our case -- AWS SDK for pandas added support for deltalake in the latest release and we are publishing both to pypi and conda. Would be great to have this

https://github.com/aws/aws-sdk-pandas/issues/873
https://github.com/delta-io/delta-rs/issues/870

**Comment by mlguruz** [comment]
Hi guys - just curious where we're on publishing to conda? 
Our org uses conda/mamba (not pip) for pkg management so would be great to have it on conda.

**Comment by craustin** [comment]
I started a `conda-forge` PR here:
https://github.com/conda-forge/staged-recipes/pull/22162/checks

It's currently failing on some deprecation errors, looks like:
> error: use of deprecated type alias `object_store::prefix::PrefixObjectStore`: Use PrefixStore

I haven't had a chance to look into those yet. Maybe just need to ignore them...?

**Comment by roeap** [comment]
> I haven't had a chance to look into those yet. Maybe just need to ignore them...?

I think we already updated this on main. Not sure how the conda builds work, but I guess with the next release this should be fixed. Then the conda build would pick it up?

**Comment by craustin** [comment]
Yes, I think that's right. Once `deltalake` v0.9.0+ is published to pip, the conda-forge recipe build should succeed then.

**Comment by nkarpov** [comment]
also just FYI once this is passing you need to be quite persistent to get it in 😬 ... it took me many bumps before it was addressed when publishing delta-spark (https://github.com/conda-forge/staged-recipes/pull/21556)

**Comment by CTCC1** [comment]
Glad to find out that this is now resolved! https://github.com/conda-forge/staged-recipes/pull/23386

**Comment by roeap** [comment]
That's excellent news! Will close this then ...
