### ISSUE TITLE
Provide a way to install Master branch binary release using Pip

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#754]
I don't know how to install deltalake master using code, and there are some new bug reports that were fixed in master, can we have something like pip install deltalke -- pre, DuckDB do the same and it is extremely convenient.

**Comment by wjones127** [comment]
Oh interesting. Looks like we could just do that by publishing to PyPI every time there is a new set of Python changes to master. We should look into this; it does seem like we would get a good amount of usage around that, especially while we have experimental functionality we are working on.

For reference, here is how DuckDB tags their master/dev releases: https://pypi.org/project/duckdb/#history

**Comment by houqp** [comment]
Yeah, pushing pre-releases to pypi sounds like a good idea :+1:
