### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#763]
reading this parquet file using duckdb
`import duckdb
con = duckdb.connect()
results =con.execute('''
                    select SETTLEMENTDATE ,DUID, Technology,Region, MWH as SCADAVALUE , day as Date from 'data.parquet' 
                     ''').arrow()`
I get this
`pyarrow.Table
SETTLEMENTDATE: timestamp[us]
DUID: string
Technology: string
Region: string
SCADAVALUE: double
Date: date32[day]`

there are some null values in the field Region
when I try to create a delta table
`
from deltalake.writer import write_deltalake
write_deltalake("C:/delta1", results,mode='append',partition_by=['Date'])`

I get  a lot of errors like this one 

`TypeError: '<' not supported between instances of 'NoneType' and 'str'`

**Comment by wjones127** [comment]
Thanks for reporting this. This occurs only in cases where an entire row group is all-null for one of the columns. I have a PR ready to fix this.
