### ISSUE TITLE
DuckDB ignore the log and scan the whole table 

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#764]
Not sure if it is a DuckDB issue or a delta lake issue or maybe I don't understand how this thing should works, I have this Table

```
from deltalake import DeltaTable
lineitem = DeltaTable("gs://test_delta1/delta2").to_pyarrow_dataset()

```

when I run this Query
```
import duckdb
con = duckdb.connect()
df = con.execute('''
SELECT
    max (year)
FROM
    lineitem
               ''').df()
```

DuckDB take 26 second, basically it is scanning the whole table, I thought somehow, this information is saved in the log and does not require a full scan ?

**Comment by wjones127** [comment]
How it works under the hood is that Delta Lake creates a PyArrow Dataset made up of Fragments. Each Fragment gets a `partition_expression` that describes the partition info and stats. So for file in the partition folder `/year=2022/`, the expression would be `year == 2022`. You can see these expressions by first getting the fragments from a dataset with `.get_fragments()` and then accessing the `.partition_expression` attribute on them.

DuckDB doesn't access that info, but I'm not sure yet if it passes down the `max(year)` computation as a projection into PyArrow. If it does, then maybe there is some possibility that this could happen in the PyArrow layer. https://github.com/duckdb/duckdb/blob/76a8cbc383646ee4cbf5fa981fbbd7b4de6b218c/tools/pythonpkg/src/arrow_array_stream.cpp#L24

I'll look more into this later.

**Comment by djouallah** [comment]
DuckDB actually knows about partition if I do

```
ELECT
    max (year) where year = 1998
FROM
    lineitem
```

then DuckDB scan only one file ?

**Comment by djouallah** [comment]
Closed as this a DuckDB problem not delta
