### ISSUE TITLE
Missing required package typing_extensions under Python 3.10

### ISSUE THREAD

**Issue by tschager** [delta-io/delta-rs#768]
# Environment

**Delta-rs version**:

**Binding**: python 3.10

**Environment**:
- **Cloud provider**: -
- **OS**: Ubuntu 22.04
- **Other**: - 

***
# Bug

**What happened**: 
After installing the python package under python 3.10.6 in a new venv, the package cannot be imported:

```{python
import deltalake
> ...deltalake\writer.py line 29, in <module>
>   from typing_extensions import Literal
> ModuleNotFoundError: No module named 'typing_extensions'
```

**What you expected to happen**:
Import should work also under Python 3.10

**How to reproduce it**:
1. create a new venv using python 3.10
2. pip install deltalake
3. python -c 'import deltalake'

**More details**:
After installing typing-extensions, the package deltalake can be imported without errors.

**Comment by roeap** [comment]
Thanks for the repost! AFAIK, this dependency should not be needed in 3.10, so we should probably fix the fact that it is :)
