### ISSUE TITLE
Remove cargo.patch for `object_store` crate

### ISSUE THREAD

**Issue by roeap** [delta-io/delta-rs#781]
# Description

Currently we patch the version of the `object_store` crate to take advantage of the removed S3 and azure SDKs, once the new version is published (apache/arrow-rs#2620), we need to remember to remove the patch from Cargo.,toml

**Use Case**

**Related Issue(s)**

**Comment by kesavkolla** [comment]
The `object_store` got updated to 0.5 version which removes the requirement of patch version.
