### ISSUE TITLE
BlobNotFound on to_pandas() or to_pyarrow_table() using Azure (ADLS gen 2)

### ISSUE THREAD

**Issue by dyrx** [delta-io/delta-rs#786]
# Environment

**Delta-rs version**: 0.6.0

**Binding**: Python

**Environment**:
- **OS**: Windows

***
# Bug

When using ADLS Gen 2 storage, the `to_pandas()` and `to_pyarrow_table()` methods produce a BlobNotFound error.
This is true for all suggested address formats in the [usage docs](https://github.com/delta-io/delta-rs/blob/main/python/docs/source/usage.rst):

> az://\<container\>/\<path\>
> adl://\<container\>/\<path\>
> abfs://\<container\>/\<path\>

```python
from deltalake import DeltaTable

storage_options = {}
storage_options["AZURE_STORAGE_ACCOUNT_NAME "] = "XXXXXXXX"
storage_options["AZURE_STORAGE_ACCOUNT_KEY "] = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
container = "my_container"
path_to_delta = "path/to/my/delta/table"

dt = DeltaTable(f"az://{container}/{path_to_delta}", storage_options=storage_options) # Succeeds
dt.schema() # Succeeds
dt.history() # Succeeds
df = dt.to_pandas() # Fails
```

**What happened**:

The .to_pandas() method seems to produce a malformed address:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\<MY USER>\AppData\Local\pypoetry\Cache\virtualenvs\sandbox-oS5I-KK--py3.10\lib\site-packages\deltalake\table.py", line 347, in to_pandas
>     return self.to_pyarrow_table(
>   File "C:\Users\DYEREX\AppData\Local\pypoetry\Cache\virtualenvs\sandbox-oS5I-KK--py3.10\lib\site-packages\deltalake\table.py", line 329, in to_pyarrow_table
>     return self.to_pyarrow_dataset(
>   File "pyarrow\_dataset.pyx", line 331, in pyarrow._dataset.Dataset.to_table
>   File "pyarrow\_dataset.pyx", line 2577, in pyarrow._dataset.Scanner.to_table
>   File "pyarrow\error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
>   File "pyarrow\_fs.pyx", line 1544, in pyarrow._fs._cb_open_input_file
>   File "C:\Users\<MY USER>\AppData\Local\pypoetry\Cache\virtualenvs\sandbox-oS5I-KK--py3.10\lib\site-packages\deltalake\fs.py", line 151, in open_input_file
>     raw = self._storage.get_obj(path)
> deltalake.PyDeltaTableError: Object at location az:/<my container>/<path_to_my_delta_directory>/part-00000-tid-6544020586825720068-1f4700fe-5039-4cad-beaa-6ae7c7f141d7-2009-1-c000.snappy.parquet not found: response error "<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
> RequestId:5fa973e4-401e-0097-4adb-c07f1a000000
> Time:2022-09-05T03:54:24.0666054Z</Message></Error>", after 0 retries: HTTP status client error (404 Not Found) for url (**https://<my_adls_account_name>.blob.core.windows.net/<my_container>/az:/<my_container>/<path_to_my_delta_directory>/part-00000-tid-6544020586825720068-1f4700fe-5039-4cad-beaa-6ae7c7f141d7-2009-1-c000.snappy.parquet**)
>

**Comment by roeap** [comment]
@dyrx - we just released `0.6.1`, could you check if this gets resolved?

**Comment by dyrx** [comment]
Thanks, confirming all of these are working in `0.6.1`

```python
df = DeltaTable(f"az://{container}/{delta_path}", storage_options=storage_options).to_pandas()
df = DeltaTable(f"adl://{container}/{delta_path}", storage_options=storage_options).to_pandas()
df = DeltaTable(f"abfs://{container}/{delta_path}", storage_options=storage_options).to_pandas()
df = DeltaTable(f"abfss://{container}@{azure_storage_account_name}.dfs.core.windows.net/{delta_path}", storage_options=storage_options).to_pandas()
```

**Comment by 0xdarkman** [comment]
delta-rs v0.6.3
["pyarrow==9.0.0", "pandas==1.3.5", "deltalake==0.6.3"]


```
import pandas as pd
import pyarrow.dataset as ds

from typing import List
from deltalake.table import DeltaTable

input_table_path = "abfss://CONTAINER@SA.dfs.core.windows.net/1d"

storage_options = {
        "AZURE_STORAGE_ACCOUNT_NAME": account_name,
        "AZURE_STORAGE_ACCOUNT_KEY": account_key,
    }

delta_table: DeltaTable = DeltaTable(input_table_path, storage_options=storage_options)
dataset = delta_table.to_pyarrow_dataset()
df = dataset.to_table().to_pandas()
print(df.head(10))
df = dataset.to_table(filter=ds.field("date") == f"{date}").to_pandas()
print(df.head(10))
```


`deltalake.PyDeltaTableError: Generic MicrosoftAzure error: Error performing get request 1d/date=2022-11-02/part-00054-60efecf3-c5f3-4faa-a8f5-01b3fa94f9d3.c000.snappy.parquet: response error "request error", after 0 retries: error sending request for url (https://SA.blob.core.windows.net/CONTIANER/1d/date=2022-11-02/part-00054-60efecf3-c5f3-4faa-a8f5-01b3fa94f9d3.c000.snappy.parquet): dispatch task is gone: runtime dropped the dispatch task`
