### ISSUE TITLE
Better authentication for GCP 

### ISSUE THREAD

**Issue by djouallah** [delta-io/delta-rs#797]
currently to connect to gcp, delta table require an environment variable something like this

```
import os
os.environ["SERVICE_ACCOUNT"] ='secret_API.json'
```
which is fine when using a notebook for example, but when I tried to deploy it to Google cloud function, it does not works and complain about authentification, error, currently I am just using arrow dataset as it works out of the box , but would love that delta has the same behavior

**Comment by sa-** [comment]
Allowing access to cloud storage via fsspec should fix most connection/auth issues but I have no idea how much effort it would be to implement this

**Comment by Renzmeister** [comment]
Arrow by default follows [Application Default Credentials](https://google.aip.dev/auth/4110) to authenticate the user. It would be great if `deltalake` supports this as well! Using service account keys is no longer the preferred method for authentication in GCP. We should be able to use workload identity federation.

**Comment by houqp** [comment]
This is something that we need to add to https://github.com/apache/arrow-rs/tree/master/object_store first. PRs welcome!
