### ISSUE TITLE
Using delta-rs on databricks

### ISSUE THREAD

**Issue by sa-** [delta-io/delta-rs#798]
# Environment

**Delta-rs version**: 0.6.1

**Binding**: python

**Environment**:
- **Cloud provider**: AWS
- **OS**: ubuntu
- **Other**: Databricks runtime 11.2

***
# Bug

**What happened**: My databricks cluster on AWS uses an IAM role to access s3 buckets. I don't have access to the aws access key and secret key, but spark can read some delta tables and deltalake cannot

**What you expected to happen**: Both pyspark and deltalake can read the same folder from s3

**How to reproduce it**:
```
%pip install deltalake
import pandas as pd
from deltalake import DeltaTable

DELTA_PATH = "s3://..."
# spark is able to write and read from the data source because of how databricks authenticates with IAM
spark.createDataFrame(pd.DataFrame({"a": [1,2,3]})).write.format("delta").save(DELTA_PATH) 

# this is where the error happens
dt = DeltaTable(DELTA_PATH)
```

**More details**:
Error log
```
PyDeltaTableError: Failed to load checkpoint: Invalid JSON in checkpoint: expected value at line 1 column 1
```
This error doesn't seem related to auth but I have a strong feeling that it is an auth issue

Sort of related to #797, because if the `deltalake` package supported fsspec (like pyarrow does), then the `delta-rs` wouldn't have to worry about building out cloud support. At least for python

**Comment by sa-** [comment]
Looks like databricks authenticates via Instance Profile and I'm not sure how to pass that information to the `deltalake` package

**Comment by sa-** [comment]
Okay, looks like it's not an auth issue but something is broken for sure.

Here is an updated snippet showing that the creds are not the problem
```

%pip install deltalake
import pandas as pd
from deltalake import DeltaTable
import requests
import json

ROLE_NAME = "" # fill this out
token = requests.put("http://169.254.169.254/latest/api/token", headers={"X-aws-ec2-metadata-token-ttl-seconds": "21600"}).content.decode("utf-8")
creds = json.loads(requests.get(f"http://169.254.169.254/latest/meta-data/iam/security-credentials/{ROLE_NAME}", headers={"X-aws-ec2-metadata-token": token}).content)
storage_options = {"AWS_ACCESS_KEY_ID": creds["AccessKeyId"], "AWS_SECRET_ACCESS_KEY": creds["SecretAccessKey"]}

DELTA_PATH = "s3://..."
# spark is able to write and read from the data source because of how databricks authenticates with IAM
spark.createDataFrame(pd.DataFrame({"a": [1,2,3]})).write.format("delta").save(DELTA_PATH) 

# this is where the error happens
dt = DeltaTable(DELTA_PATH, storage_options=storage_options)
```

The error still occurs, and it occurs as long as it's an s3 path and it doesn't happen if it's a local path

**Comment by houqp** [comment]
It might be caused by something else because we use IAM role based cred in kafka-delta-ingest as well in production.

Just to reconfirm, if you type in nonsensical s3 paths, you still get the same checkpoint json parsing error?

**Comment by sa-** [comment]
Yes it's the same error

**Comment by houqp** [comment]
I wonder if this has something to do with the newer object store implementation not returning an error for 403 resulting in us parsing the S3 XML error response as JSON?

**Comment by houqp** [comment]
@sa- if you are comfortable with Rust, you can try adding a print/logging for `data` before the following line to see what's going on exactly: https://github.com/delta-io/delta-rs/blob/0fdaeed734b036d2bd7734eb3c4b3e56680dffff/rust/src/delta.rs#L511

**Comment by yourssvk** [comment]
facing this issue, how can we get more debug logs to this issue? It works from local file system, but not from s3

**Comment by houqp** [comment]
This is caused by a bug in the upstream object store crate it looks like: https://github.com/apache/arrow-rs/issues/2802. You can try downgrade to 0.5.x until we have this fixed upstream and pull in the change in a newer release.

**Comment by houqp** [comment]
This issue has been fixed upstream, we should bump objectstore-rs with a new release :D

**Comment by dmoore247** [comment]
I can independently confirm the error, I have nearly identical setup.
Python 3.9, DeltaLake 0.6.1, AWS, IAM ROLE, Databricks Runtime 11.3 (beta)

Also errors with DeltaLake==0.5.8 and 0.6.0 and 0.5.0
with 0.5.x the error message is: `PyDeltaTableError: Failed to load checkpoint: Failed to read checkpoint content: Failed to read S3 object content: Couldn't find AWS credentials in environment, credentials file, or IAM role.`

**Comment by dmoore247** [comment]
Also a problem with Databricks Runtime 10.4LTS

**Comment by sa-** [comment]
@dmoore247 cool to see someone that works at databricks on this thread :)
I wasn't able to get my rust toolchain working for some reason, but could you try and follow @houqp 's suggestion in this comment? https://github.com/delta-io/delta-rs/issues/798#issuecomment-1256865348

**Comment by sa-** [comment]
Just had a look again with 0.6.3 and the error message is different, should I create a new issue or modify the current one?

The new error message is
`Failed to load checkpoint: Failed to read checkpoint content: Generic S3 error: Error performing get request tmp/delta-test/_delta_log/_last_checkpoint: response error "Received redirect without LOCATION, this normally indicates an incorrectly configured region", after 0 retries`

**Comment by houqp** [comment]
@sa- i think that's a good UX improvement we could add to the upstream objectstore-rs crate. Ideally, even if the region is not part of the s3 endpoint url, the client should be able to figure out the region by probing the instance metadata endpoint.

**Comment by sa-** [comment]
It might be easier to support `s3fs` or `fsspec`, this way the delta-rs project is decoupled from the cloud auth logic

**Comment by wjones127** [comment]
It sounds like this is working, besides the bucket resolution annoyance. We'll track that in https://github.com/delta-io/delta-rs/issues/1095

> It might be easier to support s3fs or fsspec, this way the delta-rs project is decoupled from the cloud auth logic

This is being worked on in:

https://github.com/delta-io/delta-rs/pull/900

**Comment by dmoore247** [comment]
Is there a way to get rid of the weird error when the bucket region property is missing?
`PyDeltaTableError: Failed to load checkpoint: Invalid JSON in checkpoint: expected value at line 1 column 1`

**Comment by dmoore247** [comment]
@sa- We at Databricks are super excited about this great community. I read about this path to Pandas / Arrow. I wanted to experiment with this and Polars too. My only compute is Databricks :)
