### ISSUE TITLE
Table history timestamp missing timezone information

### ISSUE THREAD

**Issue by boonware** [delta-io/delta-rs#833]
# Environment

**Delta-rs version**:
See below.

**Binding**: 
Python - `delta-spark = '1.2.1' `

***
# Bug

**What happened**:
Retrieving the last commit timestamp from table history returns a value in the format `2022-09-21 13:45:08.100000`. This timestamp contains no timezone information. Am I to assume this is UTC?

**What you expected to happen**:
Timestamp will include timezone information.

**How to reproduce it**:
```
from delta import DeltaTable

table = DeltaTable.forPath(spark_context, backend_url)
timestamp = table.history(depth).first()['timestamp']
```

**More details**:

**Comment by wjones127** [comment]
This repo is for the Rust-based implementation (`deltalake`). For the Spark-based one (`delta-spark`), you can report here: https://github.com/delta-io/delta/issues
