### ISSUE TITLE
Can  create a deltalakeTable based on S3 Alibaba Cloud OSS?

### ISSUE THREAD

**Issue by zhangxuefei3** [delta-io/delta-rs#835]
# Description
I want to access deltalake on Alibaba Cloud OSS, but the current configuration items for accessing S3 cannot meet the requirements

Here is Python code to access Alibaba Cloud OSS through boot3
```python
import boto3
from botocore.config import Config
endpoint = 'https://oss-cn-hangzhou.aliyuncs.com'
access_key_id = 'OSS_AccessKeyId'
secret_access_key = 'OSS_AccessKeySecret'

s3 = boto3.client(
    's3',
    aws_access_key_id=access_key_id,
    aws_secret_access_key=secret_access_key,
    endpoint_url=endpoint,
    config=Config(s3={"addressing_style": "virtual", "signature_version": 's3v4'}))
```
You may need to add the last line of configuration in storage_options to successfully create an instance of s3

**Use Case**
```python
from deltalake.writer import write_deltalake
from deltalake import DeltaTable


if __name__ == "__main__":
    storage_options = {
        "AWS_ACCESS_KEY_ID": "LxA45tAGp4dBaYzvuRqr3PjA",
        "AWS_SECRET_ACCESS_KEY": "77SCSIviXxFiDGubedDYbFbDHauR40",
        "AWS_ENDPOINT_URL": "https://oss-cn-beijing.aliyuncs.com",
        "AWS_REGION": "oss-cn-beijing" 
        # "addressing_style": "virtual",
        # "signature_version": "s3v4"
    }
    dt = DeltaTable(
        "oss://automatic-driving-prd/delta/",
        storage_options=storage_options,
    )
```
**Related Issue(s)**

**Comment by wjones127** [comment]
Thanks for the suggestion. I've created an issue in the upstream repo for adding support to the object store crate we use.

In the next release, we will have support on the `write_deltalake()` function to pass in your own filesystem, which can be a PyArrowFilesystem (or a fsspec one such as s3fs if you wrap it in [FSSpecHandler](https://arrow.apache.org/docs/python/generated/pyarrow.fs.FSSpecHandler.html)). Perhaps we can do the same on `DeltaTable`. Do you know if the [s3fs](https://docs.aws.amazon.com/AmazonS3/latest/API/bucket-policy-s3-sigv4-conditions.html) package supports this?

**Comment by Qiuzhuang** [comment]
Still get following error:

File ~/miniconda3/lib/python3.8/site-packages/deltalake/table.py:95, in DeltaTable.__init__(self, table_uri, version, storage_options, without_files)
     82 """
     83 Create the Delta Table from a path with an optional version.
     84 Multiple StorageBackends are currently supported: AWS S3, Azure Data Lake Storage Gen2, Google Cloud Storage (GCS) and local URI.
   (...)
     92                       DeltaTable will be loaded with a significant memory reduction.
     93 """
     94 self._storage_options = storage_options
---> 95 self._table = RawDeltaTable(
     96     table_uri,
     97     version=version,
     98     storage_options=storage_options,
     99     without_files=without_files,
    100 )
    101 self._metadata = Metadata(self._table)

PanicException: not yet implemented
