### ISSUE TITLE
Implement restore command

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#837]
# Description

This is another easy to implement command that shouldn't require writing data files. It makes the history command much more useful!

See docs: https://docs.databricks.com/delta/delta-utility.html#restore-delta-table

**Use Case**

**Related Issue(s)**

**Comment by Bernolt** [comment]
Hello,
I will start working on this.
I will use a similar approach as for Vacuum implementation.

**Comment by roeap** [comment]
Hi @Bernolt - there is a PR open (#852) which will intorduce some changes to the operations APIs. It is similar to the way how vacuum is implemented right now, but leverages the `IntoFuture` trait stabilized in 1.64. Not sure how far along you are, but if still feasible maybe consider this :).

**Comment by loleek** [comment]
Is this issue still available?

**Comment by wjones127** [comment]
Yes, we haven't gotten a PR for this yet, but would be happy to review one. I haven't heard from Bernolt recently.

**Comment by loleek** [comment]
OK.I will look into it and try to file a PR.

**Comment by loleek** [comment]
Been busy with other things lately, now back to this feature. I've already read delta's implement, and will try to file recent days.

**Comment by ion-elgreco** [comment]
@wjones127 it's available in rust and python now, so we can close it :)
