### ISSUE TITLE
Cannot open a deltatable in S3 using role-based credentials in a Fargate cluster.

### ISSUE THREAD

**Issue by mdespriee** [delta-io/delta-rs#854]
# Environment

**Delta-rs version**: python-v0.6.1

**Binding**: python

**Environment**:
- **Cloud provider**: AWS
- **OS**: debian
- **Other**: in an ECS/Fargate cluster

***
# Bug

**What happened**: 
While opening an deltatable, we got this error:
```
deltalake.PyDeltaTableError: Failed to load checkpoint: Failed to read checkpoint content: 
Generic S3 error: response error "request error", after 0 retries: error sending request for url 
(http://169.254.169.254/latest/api/token): error trying to connect: tcp connect error: Invalid argument (os error 22)
```
The url `http://169.254.169.254` is to get instance metadata from AWS EC2, but not in fargate clusters.

According to the [doc](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html), the url should be `169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`. 

I don't know if this is purely an issue of the storage backend implementation, or some option that is not mapped in delta-rs to allow it ?

**Comment by wjones127** [comment]
Thanks for the bug report, @mdespriee! This is indeed an issue in the upstream implementation, but should be easy to fix.

As a workaround, I believe you should be able to call

```bash
curl 169.254.170.2$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
```

from Python and pass these options into storage options:

```python
storage_options = {
    "AWS_ACCESS_KEY_ID": "ACCESS_KEY_ID", 
    "AWS_SECRET_ACCESS_KEY":"SECRET_ACCESS_KEY",
    "AWS_SESSION_TOKEN": "SECURITY_TOKEN_STRING",
}

dt = DeltaTable("path/to/table", storage_options=storage_options)
```

**Comment by dudzicp** [comment]
I am getting the similar error when I try to :
```
OSError: Generic S3 error: response error "request error", after 0 retries: error sending request for url (http://**xxxxxxx**/v2/credentials/**xxxxxx**/latest/api/token): error trying to connect: tcp connect error: Invalid argument (os error 22)
```

**Comment by TheKnightCoder** [comment]
Also cannot access via aws lambda, same issue
