### ISSUE TITLE
without_files flag for RawDeltaTable

### ISSUE THREAD

**Issue by MykhailoHevak** [delta-io/delta-rs#860]
There is the method _without_files_ in the DeltaTableBuilder
https://github.com/delta-io/delta-rs/blob/c13804d1e2919abb98f3f5263e771589387e8974/rust/src/builder/mod.rs#L156
The method sets _require_files_ flag in **DeltaTableLoadOptions**. And this flag is very useful cause it can load DeltaTable with significant memory reduction.

But python's class **RawDeltaTable** doesn't have the flag! And it is impossibly to handle tracking files :( 
https://github.com/delta-io/delta-rs/blob/c13804d1e2919abb98f3f5263e771589387e8974/python/src/lib.rs#L105

So, it's impossible to load big DeltaTable if python's library is used :(

**Comment by wjones127** [comment]
Yes I think we could add a new flag to the `DeltaTable` constructor for that. Would you be willing to make a PR?

BTW, `DeltaTable` is the public class. `RawDeltaTable` is meant to be internal.

**Comment by MykhailoHevak** [comment]
Sure, I will do PR

**Comment by roeap** [comment]
closed by https://github.com/delta-io/delta-rs/pull/866, feel free to re-open if needed.
