### ISSUE TITLE
Make load_version return DeltaTable object

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#868]
# Description

The Python `load_version` method returns `None`, so you can't do this: 

```python
dt = DeltaTable("tmp/some_delta_lake")
dt.load_version(0).to_pandas()
```

You have to do this:

```python
dt = DeltaTable("tmp/some_delta_lake")
dt.load_version(0)
dt.to_pandas()
```

Would it be alright to update the API to allow for the fluent style of programming?

**Comment by ion-elgreco** [comment]
Closing it as per short discussion with Will in the above mentioned pr
