### ISSUE TITLE
Thoughts on adding read_delta to pandas

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#869]
There is an open pandas issue on [Delta Lake file format support](https://github.com/pandas-dev/pandas/issues/40573).

@houqp made this suggestion in the thread:

> Perhaps we could add https://pypi.org/project/deltalake/ as an optional extra dependency to pandas itself to make deltalake support work out of the box for pandas users?

pandas already has `read_csv`, `read_excel`, `read_parquet`, etc., so `read_delta` would be a natural fit.

Some thoughts to brainstorm as a team:

* would adding `read_delta` to pandas be a good idea?  I certainly think so, but interested if there are any objections
* Is `read_delta` a good method name or perhaps `read_deltalake`?
* What method signature would we need?  We'd at least need an optional `version` keyword argument for time travel 😎

**Comment by fvaleye** [comment]
A [Pull Request](https://github.com/pandas-dev/pandas/pull/49692) has been submitted to integrate directly `deltalake` in the code base as an optional external dependency.

**Comment by fvaleye** [comment]
Closing this, based on the response from pandas core devs in https://github.com/pandas-dev/pandas/pull/49692
