### ISSUE TITLE
Integrating with aws-sdk-pandas

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#870]
[aws-sdk-pandas](https://github.com/aws/aws-sdk-pandas) (formerly known as aws-wrangler) is an awesome library for integrating with a bunch of AWS services in AWS Lambda (it might be more generic than lambda, but that's what I've used it for in the past).

It packages up dependencies in a Lambda Layer, so you can easily access Python libraries in your Lambda function.  Building your own Lamba Layers is really hard unless you're running Linux (if you're running a Mac, the C dependencies don't get compiled correctly).

A [user was asking to integrate delta-rs in aws-sdk-pandas](https://github.com/aws/aws-sdk-pandas/issues/873).  I think this would be a great addition.  I've seen lots of users asking how they can read/write to Delta Lakes in Lambda functions.  This should make a lot of users happy.

**Comment by dennyglee** [comment]
Before we close this, let's create a PR to update the read-the-docs for `aws-pandas-sdk` to include how to use `deltalake`.

**Comment by MrPowers** [comment]
@nkarpov - can we close this one?

**Comment by nkarpovdb** [comment]
yeah I think we can close this - the changes had to (were) made in aws-pandas-sdk
