### ISSUE TITLE
Support `CREATE EXTERNAL TABLE dt STORED AS DELTATABLE` syntax with datafusion

### ISSUE THREAD

**Issue by avantgardnerio** [delta-io/delta-rs#891]
# Description

In datafusion, SQL users can use the `create external table xyz stored as csv` option to register CSV, JSON, and parquet data. It would be nice (essential in my company's case) to allow users to register deltalake tables in the same manner.

**Comment by MrPowers** [comment]
@avantgardnerio - this is awesome.  Can't wait to have Datafusion support!  I will definitely help update the docs / write blog posts when this functionality is added.

**Comment by avantgardnerio** [comment]
Thanks! Related datafusion PR if you'd like to follow along: https://github.com/apache/arrow-datafusion/pull/3907 . I've definitely seen it work in Datafusion, so I don't think support is far away for that. Ballista will be some more work as we'll need to do serde on the physical plan, and re-register the object store on the executors.
