### ISSUE TITLE
Adding R bindings to this library

### ISSUE THREAD

**Issue by MrPowers** [delta-io/delta-rs#908]
There is a large number of R DataFrame library users, many of whom would certainly enjoy being able to read Delta tables.  Would it be feasible to add R bindings to this library?

There is a [zero323/dlt library](https://github.com/zero323/dlt), which is a Delta Lake interface for SparkR, but that has a Spark dependency.

There is also a [Delta Sharing R Connector](https://github.com/zacdav-db/delta-sharing-r), but that requires a Delta Sharing server.

It'd be awesome if we could provide R users with a "dependency free" way of loading Delta tables into R DataFrames.

**Comment by comicfans** [comment]
This should be very useful, I'd like to see delta-rs provide R binding

**Comment by wjones127** [comment]
Duplicate of #537.

I think the best path forward is to first implement ADBC in delta-rs (see #830). Then we can create R and other bindings more easily, without having to write as much custom code for each implementation. (If we had to do for R what we've done so far for Python, it would take a while.)

**Comment by MrPowers** [comment]
Closing cause this is a duplicate, thank you @wjones127
