### ISSUE TITLE
Handle the decimal data type in the arrow format conversion

### ISSUE THREAD

**Issue by fvaleye** [delta-io/delta-rs#91]
When the delta table has a `decimal(_,_)` column type, it is not handled by the ArrowSchema conversion (https://github.com/delta-io/delta-rs/blob/main/rust/src/delta_arrow.rs#L42). We could use pattern matching for extracting precision and scale for generating an `ArrowDataType::Decimal(_,_)` value.

**Comment by houqp** [comment]
Yep, that's a good idea :+1:

**Comment by fvaleye** [comment]
It is resolved by #92, I close the issue!
