### ISSUE TITLE
PyDeltaTableError: Failed to read delta log object: Generic DeltaS3ObjectStore error: Atomic rename requires a LockClient for S3 backends.

### ISSUE THREAD

**Issue by akashd11** [delta-io/delta-rs#911]
# Environment
USING PYTHON BINDING OF DELTA RS 0.6.2 with s3

**Delta-rs version**: 0.6.2

**Binding**: 

**Environment**:
- **Cloud provider**: S3 storage
- **OS**: MacOSX
- **Other**: Using python binding for delta rs

***
# Bug
PyDeltaTableError: Failed to read delta log object: Generic DeltaS3ObjectStore error: Atomic rename requires a LockClient for S3 backends
Getting this error while using write_deltalake from deltalake.write passed the following in filesystem
raw_fs, normalized_path = fs.FileSystem.from_uri(table_uri)
filesystem = fs.SubTreeFileSystem(normalized_path, raw_fs)
also tried with passing storage_options with correct aws_region and aws_endpoint

**What happened**: .json.tmp is being created in _delta_log but not able to write to the correct json file and update version
Also no checkpoints being created after 10 commits when trying locally

**What you expected to happen**:
Expecting to get version update after each commit. Is it an issue in the python binding.

**Comment by wjones127** [comment]
This is being fixed in #893.

**Comment by wjones127** [comment]
I'll need to check on the checkpoint creation though; I'm not sure we have a test for that yet, but we should.
