### ISSUE TITLE
Create Checkpoints based on table config when writing data

### ISSUE THREAD

**Issue by roeap** [delta-io/delta-rs#913]
# Description

Delta allows configuring at which commit intervals a new checkpoint should be created (default 10). We should honor this config.

**Use Case**

Checkpoints are an important performance optimization in the delta log.

**Related Issue(s)**

**Comment by ion-elgreco** [comment]
@roeap I guess this requires a small check after each operation to see the if the current commit is greater than then the interval + last checkpoint commit. 

Do we store somewhere this checkpoint version on the table as an attribute? When I do dt.metadata() I always get no results.

**Comment by ion-elgreco** [comment]
Never mind, found how to write the table properties during write :)

**Comment by roeap** [comment]
> Do we store somewhere this checkpoint version on the table as an attribute? When I do dt.metadata() I don't see this info.

This information is not tracked, and I think we also should not :) - i.e. other writers are not adding this metadata, so we could not rely on it.

IMO, we could just do a quick check if `_last_checkpoint` is present, and if not, revert to `version % 10 == 0`.

**Comment by ion-elgreco** [comment]
@ldacey from the table configuration. You can grab it from the metadata of the table

**Comment by roeap** [comment]
@ldacey, as @ion-elgreco points out, there is a configuration for delta-tables, namely `delta.checkpointInterval` which controls at which interval checkpoints should be created. delta-rs does not honour that yet.

In your scenario - assuming accounts means independent writers - I recommend having a dedicated job to create checkpoints. Checkpoint creation in the current spec does suffer from potential race conditions if multiple writers try to create teh same checkpoint. This will be mitigated once we have v2 checkpoints implemented, which is currently ongoing work...
