### ISSUE TITLE
Use Chrono without default  features

### ISSUE THREAD

**Issue by hntd187** [delta-io/delta-rs#914]
Chrono currently (version 0.4.22) by default enables the "oldtime" feature, which is for compatibility. It also introduces this rustsec issue, https://rustsec.org/advisories/RUSTSEC-2020-0071

To the best of my understanding chrono does not need this feature enabled, would it be possible to do this? I am happy to put in a PR if maintainers are onboard with the change.

**Comment by wjones127** [comment]
I'm in favor of this. Feel free to open a PR and I am happy to review. 👍
