### ISSUE TITLE
Switch back the toolchain to "stable" in the build and test CI jobs

### ISSUE THREAD

**Issue by fvaleye** [delta-io/delta-rs#926]
# Description
A workaround has been created by freezing the version of rust in the CI jobs to `v0.16.4` to unblock the Windows CI job failure with the latest Rust versions.
When the `v0.17.0` version of [Rust](https://github.com/rust-lang/rust) is published, we should switch back to `"stable"` in the toolchain setting.

**Lines:**
- https://github.com/delta-io/delta-rs/pull/923/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R42
- https://github.com/delta-io/delta-rs/pull/923/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R67

**Related Issue(s)**
- #923

**Comment by roeap** [comment]
we switched back to stable as part of #1097
