### ISSUE TITLE
Select * from partitioned table failed by datafusion

### ISSUE THREAD

**Issue by doki23** [delta-io/delta-rs#937]
***
# Bug

**What happened**:
`select * from table` by datafusion doesn't work when table is partitioned.

**What you expected to happen**:
It can work as `pyspark` -- can select partitioned columns.

**How to reproduce it**:
First, creating a table with meta like below:
```rust
/// table_schema = (c0 string, c1 boolean, c2 integer)
let metadata = DeltaTableMetaData::new(
            Some("my_table".into()),
            Some("for test".into()),
            None,
            table_schema,
            vec!["c2".into()],
            HashMap::new(),
        );
```
Second, inserting some data like ("a", true, 0).
Finally, execute `select * from my_table` or `select * from my_table where c2 = 0` by `datafusion`.

**Comment by doki23** [comment]
It seems because datafusion can only process utf8 partitioned columns.

**Comment by roeap** [comment]
Thanks for the report. This is in fact (or has been) a limitation in datafusion an with that delta-rs. AS we have more specific schema information available, wecan make these conversions though. This has been bothering me as well an I hope to get around fixing this soonishly.

**Comment by doki23** [comment]
I'm working on this and already have a pr to datafusion. When the pr gets merged, we just need upgrade the datafusion version. Of course, there's still some work to do then.

**Comment by ion-elgreco** [comment]
I think this is resolved by now
