### ISSUE TITLE
Create and bind Delta Schema structures with pyo3 for Python.

### ISSUE THREAD

**Issue by fvaleye** [delta-io/delta-rs#95]
Currently, we use a `JSON` string for binding Rust and Python for reading the Delta table schema. The improvement is to create and use pyo3 structure in Rust for binding the Schema.

**Comment by houqp** [comment]
I am thinking of releasing a new version of the python binding, @fvaleye do you want me to wait for this before doing the release?

**Comment by fvaleye** [comment]
It's a good idea to release a new version 👍 I will take some time in the next weeks to work on it. In the mean time, the bindings for the schema will be available.

**Comment by roeap** [comment]
@fvaleye, @houqp - this is done here, so we can close this, right?

https://github.com/delta-io/delta-rs/blob/5b2a09c59e1fa18f38c275475e41c2148ae02b5e/python/src/lib.rs#L74

**Comment by houqp** [comment]
@roeap I think that's something separate. We are currently still using passing the schema from rust to python through string ser/de, see https://github.com/delta-io/delta-rs/blob/5b2a09c59e1fa18f38c275475e41c2148ae02b5e/python/deltalake/schema.py#L153
