### ISSUE TITLE
MacOS arm64 wheels are generated incorrectly

### ISSUE THREAD

**Issue by hsheth2** [delta-io/delta-rs#972]
# Environment

**Binding**: Python

**Environment**:
- **OS**: MacOS 13 (M1 / arm64)
- Python 3.10.8
- Pip 22.3.1

***

# Bug

**What happened**:

On the PyPI releases page (https://pypi.org/project/deltalake/0.6.4/#files), the arm64 wheel file is published as `
deltalake-0.6.4-cp37-abi3-macosx_10_9_arm64.whl`. However, it should be `macosx_11_0_arm64.whl`. This causes pip to not install from source instead of using the pre-built wheel.

**What you expected to happen**: Pip should install from wheel.

**More details**:

Note that `pip -v debug` does not contain `macosx_10_9_arm64` but does contain `macosx_11_0_arm64`. As such, `macosx_10_9_arm64` is never a compatible ABI tag. I believe the actions release workflow is not generating the correct ABI tag.

Release log: https://github.com/delta-io/delta-rs/actions/runs/3567491762/jobs/5995258547#step:3:668

Possible fixes
1. build universal2 wheels on mac (not sure if this is actually possible for delta-rs)
2. increase the min macosx version to 11_0 for the arm64 wheel.

**Comment by fvaleye** [comment]
Thank you @hsheth2 for reporting this issue 👍 

I added a dedicated GitHub Action to release `universal2` wheel on Mac!
