### ISSUE TITLE
Support LIMIT pushdown in scans

### ISSUE THREAD

**Issue by wjones127** [delta-io/delta-rs#982]
# Description

Similar optimization to: https://github.com/delta-io/delta/commit/1a94a585

**Use Case**

**Related Issue(s)**

**Comment by dominikpeter** [comment]
Is there any news about implementing this?

**Comment by wjones127** [comment]
This issue was intended for the Rust DataFusion-based scanner, which will come later. For the PyArrow-based scanner, see my comment in https://github.com/pola-rs/polars/issues/7337.

**Comment by ion-elgreco** [comment]
Resolved in Polars in terms of head scans
